"""Canonical enforcement catalog row constants.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from typing import Final


class FlextConstantsEnforcementCatalogRows:
    """Table-driven rows used to build the canonical enforcement catalog."""

    INFRA_DETECTOR_ROWS: Final[
        tuple[tuple[str, str, str, str, tuple[str, ...], bool, str], ...]
    ] = (
        (
            "ENFORCE-001",
            "HIGH",
            "loose_objects",
            "2-architecture-law",
            ("flext-mro-namespace-rules",),
            False,
            "Loose object detected at module level — every public symbol must be nested inside its facade family.",
        ),
        (
            "ENFORCE-002",
            "HIGH",
            "import_violations",
            "",
            ("flext-import-rules",),
            False,
            "Import alias source is wrong — alias imported from a non-canonical module.",
        ),
        (
            "ENFORCE-003",
            "HIGH",
            "namespace_source_violations",
            "",
            ("flext-import-rules", "flext-mro-namespace-rules"),
            False,
            "Namespace source violation — canonical alias imported from a project that does not own that slot.",
        ),
        (
            "ENFORCE-004",
            "MEDIUM",
            "internal_import_violations",
            "",
            ("flext-import-rules",),
            False,
            "Internal (private) module import reaches outside its owning package boundary.",
        ),
        (
            "ENFORCE-005",
            "MEDIUM",
            "manual_protocol_violations",
            "",
            ("flext-patterns",),
            False,
            "Manual Protocol class declared outside protocols.py / _protocols/ tree.",
        ),
        (
            "ENFORCE-006",
            "CRITICAL",
            "cyclic_imports",
            "",
            ("flext-import-rules",),
            False,
            "Cyclic import detected between modules.",
        ),
        (
            "ENFORCE-007",
            "HIGH",
            "runtime_alias_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "Runtime alias (c/p/t/m/u/r/s/x/d/e/h) rebound in a module that should not own it.",
        ),
        (
            "ENFORCE-008",
            "MEDIUM",
            "future_violations",
            "",
            ("rules-examples",),
            False,
            "Python module missing `from __future__ import annotations`.",
        ),
        (
            "ENFORCE-009",
            "MEDIUM",
            "manual_typing_violations",
            "",
            ("flext-type-system",),
            False,
            "Manual typing alias declared outside typings.py / _typings/ tree.",
        ),
        (
            "ENFORCE-010",
            "LOW",
            "compatibility_alias_violations",
            "",
            ("flext-refactoring-workflow",),
            False,
            "Backwards-compatibility alias retained after refactor — should be removed.",
        ),
        (
            "ENFORCE-011",
            "HIGH",
            "class_placement_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "Class placed in the wrong facade layer (e.g. Protocol in models.py).",
        ),
        (
            "ENFORCE-012",
            "CRITICAL",
            "mro_completeness_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "MRO composition incomplete — facade does not compose all its domain mixin trees.",
        ),
        (
            "ENFORCE-013",
            "HIGH",
            "parse_failures",
            "",
            (),
            False,
            "Source file failed to parse during enforcement.",
        ),
        (
            "ENFORCE-014",
            "CRITICAL",
            "facade_statuses",
            "",
            ("flext-mro-namespace-rules",),
            True,
            "Canonical facade family is missing (no constants.py / models.py / typings.py / protocols.py / utilities.py).",
        ),
    )

    SKILL_POINTER_ROWS: Final[
        tuple[tuple[str, str, str, str, str, tuple[str, ...], str], ...]
    ] = (
        (
            "ENFORCE-034",
            "HIGH",
            "flext-patterns",
            "no-accessor-methods",
            "3-code-law",
            ("flext-patterns",),
            "Accessor method (get_*, set_*) forbidden — expose as field or @u.computed_field (AGENTS.md §3.1).",
        ),
        (
            "ENFORCE-035",
            "HIGH",
            "lib-pydantic-settings",
            "settings-baseline",
            "2-architecture-law",
            ("lib-pydantic-settings",),
            "Settings models must inherit FlextSettings, not BaseModel or BaseSettings (AGENTS.md §2.6).",
        ),
        (
            "ENFORCE-036",
            "MEDIUM",
            "pydantic-v2-governance",
            "",
            "0-quick-reference-must-read",
            ("pydantic-v2-governance",),
            "Never call `model_rebuild()` as a fix strategy — resolve forward refs via proper imports/annotations.",
        ),
        (
            "ENFORCE-037",
            "HIGH",
            "lib-pydantic-settings",
            "",
            "0-quick-reference-must-read",
            ("lib-pydantic-settings", "flext-constants-discipline"),
            "No `os.environ` / `os.getenv` in src/ — use settings + constants contracts.",
        ),
        (
            "ENFORCE-038",
            "HIGH",
            "flext-mro-namespace-rules",
            "",
            "0-quick-reference-must-read",
            ("flext-mro-namespace-rules",),
            "Never flatten organic namespace paths — preserve `m.TargetOracle.ExecuteResult` etc., don't rebind to `m.ExecuteResult`.",
        ),
        (
            "ENFORCE-056",
            "HIGH",
            "flext-mro-namespace-rules",
            "facade-purity",
            "2-5-services-pattern",
            ("flext-mro-namespace-rules", "flext-strict-refactoring"),
            "api.py must contain exactly one ClassDef whose body is Pass-only and exactly one eager alias assignment. Logic in api.py or module-level mutable instance (e.g., `api = FlextApi()`) violates AGENTS.md §2.5 (Services Pattern facade purity).",
        ),
        (
            "ENFORCE-057",
            "HIGH",
            "flext-mro-namespace-rules",
            "service-mixin-inheritance",
            "2-5-services-pattern",
            ("flext-mro-namespace-rules", "flext-patterns"),
            "Classes in services/*.py must end MRO at the project's Flext<X>ServiceBase (which itself ends at FlextService/s[T]). Plain classes lacking the canonical service base violate AGENTS.md §2.5 (Services Pattern services/* shape).",
        ),
        (
            "ENFORCE-058",
            "HIGH",
            "pydantic-v2-governance",
            "models-have-no-helpers",
            "3-1-supreme-law",
            ("pydantic-v2-governance", "pydantic-v2-patterns"),
            "Pydantic 2 data models must contain only fields, model_config, field_validator/model_validator/computed_field, and essential dunders. Methods named get_*/to_*/from_*/is_*/with_* on data models violate AGENTS.md §3.1 (Pydantic v2 Mastery) — relocate to a service mixin or @computed_field. Carve-out: infrastructure base classes (FlextSettingsBase, FlextService, Flext<X>ServiceBase) may expose singleton/clone/factory kernel methods. Extends ENFORCE-034 (get_/set_) to to_/from_/is_/with_ family.",
        ),
        (
            "ENFORCE-059",
            "HIGH",
            "pydantic-v2-governance",
            "data-boundaries-are-models",
            "3-1-supreme-law",
            ("pydantic-v2-governance", "flext-patterns"),
            "Public method parameters and return types in services/*.py and api.py must be Pydantic 2 models, p.* Protocols, r[T] of those, or PEP 604 unions thereof. Bare `dict`, `list[primitive]`, `tuple[primitive...]`, `set`, `TypedDict`, `Mapping[str, Any]`, `Sequence[primitive]` are loose data crossings and violate AGENTS.md §3.1.",
        ),
        (
            "ENFORCE-060",
            "HIGH",
            "pydantic-v2-patterns",
            "no-round-trip-validation",
            "3-1-supreme-law",
            ("pydantic-v2-patterns",),
            "Sequence `model_dump()` -> dict ops -> `model_validate(...)` in the same scope is round-trip validation and violates AGENTS.md §3.1. Use `model_copy(update={...})` directly. JSON roundtrips: use `model_dump(mode='json')` / `model_dump_json()` / `model_validate_json()` — never `json.loads(model.model_dump_json())`.",
        ),
        (
            "ENFORCE-061",
            "MEDIUM",
            "flext-strict-typing",
            "override-decorator-required",
            "3-1-supreme-law",
            ("flext-strict-typing",),
            "Methods overriding a parent method must carry `@typing.override` (PEP 698). Missing decorator weakens static refactoring guarantees and violates AGENTS.md §3.1 (Python 3.13 idioms).",
        ),
        (
            "ENFORCE-062",
            "HIGH",
            "flext-strict-typing",
            "match-exhaustiveness-assert-never",
            "3-1-supreme-law",
            ("flext-strict-typing", "pydantic-v2-patterns"),
            "`match value:` over a discriminated union or finite type set must include `case _: assert_never(value)` as default. Missing exhaustiveness guard violates AGENTS.md §3.1 (Python 3.13 idioms — typing.assert_never).",
        ),
        (
            "ENFORCE-063",
            "HIGH",
            "flext-mro-namespace-rules",
            "constants-chain-inheritance",
            "2-3-mro-inheritance-namespace-composition",
            ("flext-mro-namespace-rules", "flext-architecture-layers"),
            "Flext<X>{Constants,Models,Protocols,Utilities} must extend the immediately-preceding project's facade in the dependency chain (flext-core -> flext-cli -> flext-infra -> flext-{ldap,ldif,...} -> flext-{tap,target,dbt}-* -> end-user), not skip to FlextX root when an intermediate parent project is depended on. Violates AGENTS.md §2.3 (MRO Cascade) by redeclaring symbols already inheritable.",
        ),
    )

    RUFF_ROWS: Final[tuple[tuple[str, str, str, tuple[str, ...], str], ...]] = (
        (
            "ENFORCE-023",
            "HIGH",
            "ANN401",
            ("flext-strict-typing",),
            "Dynamic Any usage (ruff ANN401) — enforced at lint time by `make lint`; listed here for cross-reference.",
        ),
        (
            "ENFORCE-024",
            "MEDIUM",
            "PGH003",
            ("flext-strict-typing",),
            "Missing specific rule code on pyright/pygrep suppressions (ruff PGH003).",
        ),
        (
            "ENFORCE-025",
            "MEDIUM",
            "TID252",
            ("flext-import-rules",),
            "Relative import (ruff TID252) — prefer absolute imports.",
        ),
    )

    TESTS_VALIDATOR_ROWS: Final[
        tuple[tuple[str, str, str, tuple[str, ...], tuple[str, ...], str], ...]
    ] = (
        (
            "ENFORCE-015",
            "HIGH",
            "imports",
            (
                "IMPORT-001",
                "IMPORT-002",
                "IMPORT-003",
                "IMPORT-004",
                "IMPORT-006",
            ),
            ("flext-import-rules",),
            "Import discipline violation — lazy imports, TYPE_CHECKING misuse, sys.path manipulation, or non-root flext-* imports.",
        ),
        (
            "ENFORCE-016",
            "HIGH",
            "types",
            ("TYPE-001", "TYPE-002", "TYPE-003"),
            ("flext-strict-typing", "flext-type-system"),
            "Type-system violation — Any/object/legacy typing or type: ignore bypass.",
        ),
        (
            "ENFORCE-017",
            "HIGH",
            "bypass",
            ("BYPASS-001", "BYPASS-002", "BYPASS-003"),
            ("flext-patterns",),
            "Bypass pattern — noqa, pragma: no cover (unapproved), or exception swallowing.",
        ),
        (
            "ENFORCE-018",
            "CRITICAL",
            "layer",
            ("LAYER-001",),
            ("flext-architecture-layers",),
            "Layer violation — lower layer importing an upper layer.",
        ),
        (
            "ENFORCE-019",
            "MEDIUM",
            "tests",
            ("TEST-001", "TEST-002", "TEST-003"),
            ("testing-patterns",),
            "Test pattern violation — monkeypatch, Mock/MagicMock, or @patch usage.",
        ),
        (
            "ENFORCE-020",
            "HIGH",
            "validate_config",
            ("CONFIG-001", "CONFIG-003", "CONFIG-004", "CONFIG-005"),
            ("flext-development-workflow",),
            "pyproject.toml deviation — mypy ignore_errors, unapproved ruff ignores, or incomplete type strictness.",
        ),
        (
            "ENFORCE-021",
            "MEDIUM",
            "markdown",
            ("MD-001", "MD-002", "MD-003", "MD-004"),
            ("testing-patterns",),
            "Markdown code block validation — syntax, forbidden typings, missing future annotations, object as type.",
        ),
    )

    AST_GREP_ROWS: Final[tuple[tuple[str, str, str, str, str], ...]] = (
        (
            "ENFORCE-026",
            "HIGH",
            "flext-patterns",
            "ban-bare-except",
            "Bare `except:` clause swallows all exceptions including SystemExit.",
        ),
        (
            "ENFORCE-027",
            "MEDIUM",
            "flext-patterns",
            "ban-print-in-src",
            "`print()` call in source code — use structured logging.",
        ),
        (
            "ENFORCE-028",
            "HIGH",
            "flext-patterns",
            "no-breakpoint",
            "`breakpoint()` / pdb left in code.",
        ),
        (
            "ENFORCE-029",
            "MEDIUM",
            "flext-patterns",
            "ban-open-no-encoding",
            "`open()` without explicit encoding.",
        ),
        (
            "ENFORCE-030",
            "HIGH",
            "flext-strict-typing",
            "ban-dict-type-annotation",
            "`dict` in type annotation — prefer Mapping / MutableMapping / TypedDict.",
        ),
        (
            "ENFORCE-031",
            "HIGH",
            "flext-strict-typing",
            "ban-typing-dict-attribute",
            "`typing.Dict` attribute usage — use collections.abc.Mapping family.",
        ),
        (
            "ENFORCE-032",
            "HIGH",
            "flext-strict-typing",
            "ban-typing-dict-import",
            "`from typing import Dict` — banned in favor of dict / Mapping.",
        ),
        (
            "ENFORCE-033",
            "HIGH",
            "flext-patterns",
            "no-hardcoded-version-string",
            "Hardcoded `__version__` string — use importlib.metadata.",
        ),
    )

    BEARTYPE_ROWS: Final[
        tuple[tuple[str, str, str, str, tuple[str, ...], str], ...]
    ] = (
        (
            "ENFORCE-039",
            "HIGH",
            "cast_outside_core",
            "3-2-types-and-contracts",
            ("flext-strict-typing", "flext-patterns"),
            "cast() call outside flext-core result internals violates AGENTS.md §3.2 (Strict Types).",
        ),
        (
            "ENFORCE-041",
            "HIGH",
            "model_rebuild_call",
            "3-4-tools-and-modules",
            ("flext-patterns",),
            "model_rebuild() call indicates unresolved forward refs and violates AGENTS.md §3.4 (Tools/Modules/Env).",
        ),
        (
            "ENFORCE-042",
            "HIGH",
            "settings_inheritance",
            "2-6-settings-law",
            ("flext-patterns", "lib-pydantic-settings"),
            "Settings class missing FlextSettings base or wrong env_prefix violates AGENTS.md §2.6 (Settings Law). Reuses the existing check_settings_inheritance hook — no new detection code per SSOT/DRY.",
        ),
        (
            "ENFORCE-043",
            "MEDIUM",
            "pass_through_wrapper",
            "3-5-integrity",
            ("flext-refactoring-workflow",),
            "Pass-through wrapper (single-statement return delegating to another callable with identical args) violates AGENTS.md §3.5.",
        ),
        (
            "ENFORCE-044",
            "HIGH",
            "private_attr_probe",
            "3-6-test-standardization",
            ("flext-strict-typing", "flext-patterns"),
            "hasattr/getattr/setattr probing of private attributes (single-underscore names) violates AGENTS.md §3.6.",
        ),
        (
            "ENFORCE-045",
            "HIGH",
            "no_pydantic_consumer_import",
            "2-7-library-abstraction-boundaries",
            ("flext-import-rules", "pydantic-v2-patterns"),
            "Direct 'from pydantic import ...' in a consumer project (outside its own '_' base pyramid) violates AGENTS.md §2.7 (Library Abstraction Boundaries) + §3.1 (Pydantic v2 Mastery — facade-only access).",
        ),
        (
            "ENFORCE-046",
            "HIGH",
            "no_concrete_namespace_import",
            "4-import-law",
            ("flext-import-rules", "flext-mro-namespace-rules"),
            "Canonical facade files (constants/models/protocols/typings/utilities) must import only c/m/p/t/u aliases from parent — never bare FlextXxx concrete classes (unless Pattern-B peer). Violates AGENTS.md §4 (Import Law).",
        ),
        (
            "ENFORCE-047",
            "HIGH",
            "facade_base_is_alias_or_peer",
            "2-2-facades-namespaces-naming-patterns",
            ("flext-mro-namespace-rules", "flext-import-rules"),
            "Facade-class first base must be an alias (c/m/p/t/u) or a Pattern-B peer FlextXxx — never an arbitrary Flext* concrete class. Violates AGENTS.md §2.2 (One Facade Rule + Pattern-A/B).",
        ),
        (
            "ENFORCE-048",
            "MEDIUM",
            "no_redundant_inner_namespace",
            "2-3-mro-inheritance-namespace-composition",
            ("flext-mro-namespace-rules",),
            "Inner namespace class with empty body that re-inherits from outer (e.g. 'class Cli(FlextCliTypes): pass') is redundant — parent already exposes the namespace. Violates AGENTS.md §2.3 (Single Root Nested Namespace).",
        ),
        (
            "ENFORCE-049",
            "HIGH",
            "alias_first_multi_parent",
            "2-2-facades-namespaces-naming-patterns",
            ("flext-mro-namespace-rules",),
            "Multi-parent facade class must list canonical alias (c/m/p/t/u) as FIRST base — required for C3 MRO linearization. Violates AGENTS.md §2.2 (Pattern-B facade ordering).",
        ),
        (
            "ENFORCE-050",
            "MEDIUM",
            "alias_rebound_at_module_end",
            "4-import-law",
            ("flext-import-rules", "flext-mro-namespace-rules"),
            "Canonical facade module must rebind its alias at end-of-file (e.g. 't = FlextXxxTypes') — establishes the public contract surface. Violates AGENTS.md §4 (Aliases — assigned once at module bottom).",
        ),
        (
            "ENFORCE-051",
            "HIGH",
            "no_self_root_import_in_core_files",
            "4-import-law",
            ("flext-import-rules",),
            "Canonical facade files must NOT import c/m/p/t/u from their own package — must import from the parent MRO package to avoid lazy-load circular initialization. Violates AGENTS.md §4 (No Same-Project Cross-Facade Runtime Imports).",
        ),
        (
            "ENFORCE-052",
            "HIGH",
            "sibling_models_type_checking",
            "4-import-law",
            ("flext-import-rules",),
            "Sibling _models/* imports referenced only in annotations must live under 'if TYPE_CHECKING:' to avoid circular runtime imports. Violates AGENTS.md §4 (Circular Import Resolution — TYPE_CHECKING for annotation-only siblings).",
        ),
        (
            "ENFORCE-053",
            "HIGH",
            "utilities_explicit_class_when_self_ref",
            "2-3-mro-inheritance-namespace-composition",
            ("flext-mro-namespace-rules",),
            "Multi-parent utilities.py facade must list explicit PARENT class as first base (not alias 'u') to allow pyrefly to resolve the MRO when 'u' is rebound to the local class. Violates AGENTS.md §2.3 (MRO Cascade).",
        ),
        (
            "ENFORCE-054",
            "HIGH",
            "no_core_tests_namespace",
            "0-quick-reference-must-read",
            ("flext-mro-namespace-rules", "flext-import-rules"),
            "Deprecated test namespace path '.Core.Tests' is forbidden in tests/examples/scripts. Use flat c/p/t/m/u.Tests.* access only.",
        ),
        (
            "ENFORCE-055",
            "HIGH",
            "no_wrapper_root_alias_import",
            "0-quick-reference-must-read",
            ("flext-import-rules", "flext-mro-namespace-rules", "rules-scripts"),
            "Wrapper alias imports in tests/examples/scripts must come from wrapper root package (`from tests|examples|scripts import ...`). Submodule alias imports are forbidden outside `__init__.py`.",
        ),
    )
