from ...shared_test_domain import (
    ComplexValueObject as ComplexValueObject,
    ConcreteValueObject as ConcreteValueObject,
    TestDomainFactory as TestDomainFactory,
)

EXPECTED_BULK_SIZE: int

class TestFlextValueObjectEquality:
    def test_equality_same_values(self) -> None: ...
    def test_equality_different_values(self) -> None: ...
    def test_equality_with_different_types(self) -> None: ...
    def test_equality_with_different_value_object_types(self) -> None: ...
    def test_equality_with_optional_fields(self) -> None: ...

class TestFlextValueObjectHashing:
    def test_hash_consistency_same_values(self) -> None: ...
    def test_hash_different_values(self) -> None: ...
    def test_hash_with_complex_types(self) -> None: ...
    def test_hash_stability(self) -> None: ...
    def test_hash_in_collections(self) -> None: ...

class TestFlextValueObjectStringRepresentation:
    def test_str_representation_simple(self) -> None: ...
    def test_str_representation_with_many_fields(self) -> None: ...
    def test_str_representation_complex_types(self) -> None: ...

class TestFlextValueObjectDomainValidation:
    def test_domain_rules_validation_called(self) -> None: ...
    def test_domain_rules_validation_negative_amount(self) -> None: ...
    def test_domain_rules_validation_invalid_currency_length(self) -> None: ...
    def test_domain_rules_validation_lowercase_currency(self) -> None: ...
    def test_domain_rules_validation_empty_name(self) -> None: ...
    def test_domain_rules_validation_whitespace_name(self) -> None: ...

class TestFlextValueObjectPydanticIntegration:
    def test_pydantic_validation_required_fields(self) -> None: ...
    def test_pydantic_validation_field_types(self) -> None: ...
    def test_pydantic_model_dump(self) -> None: ...
    def test_pydantic_immutability(self) -> None: ...
    def test_pydantic_default_values(self) -> None: ...
    def test_pydantic_string_stripping(self) -> None: ...
    def test_pydantic_extra_fields_forbidden(self) -> None: ...

class TestFlextValueObjectEdgeCases:
    def test_empty_complex_collections(self) -> None: ...
    def test_nested_complex_data_equality(self) -> None: ...
    def test_large_data_structures(self) -> None: ...
    def test_special_characters_in_strings(self) -> None: ...
    def test_decimal_precision_equality(self) -> None: ...
    def test_model_dump_with_complex_types(self) -> None: ...

class TestFlextValueObjectInheritance:
    def test_single_inheritance(self) -> None: ...
    def test_multiple_inheritance_behavior(self) -> None: ...
    def test_polymorphic_equality(self) -> None: ...
