from ...shared_test_domain import (
    ConcreteFlextEntity as ConcreteFlextEntity,
    TestDomainFactory as TestDomainFactory,
    TestUserStatus as TestUserStatus,
)

EXPECTED_BULK_SIZE: int

class TestFlextEntityFieldValidators:
    def test_validate_entity_id_empty_string(self) -> None: ...
    def test_validate_entity_id_whitespace_only(self) -> None: ...
    def test_validate_entity_id_valid_with_whitespace(self) -> None: ...
    def test_validate_entity_version_zero(self) -> None: ...
    def test_validate_entity_version_negative(self) -> None: ...
    def test_validate_entity_version_valid(self) -> None: ...

class TestFlextEntityEquality:
    def test_equality_with_non_entity(self) -> None: ...
    def test_equality_with_different_entity_types(self) -> None: ...

class TestFlextEntityVersioning:
    def test_with_version_valid_increment(self) -> None: ...
    def test_with_version_large_increment(self) -> None: ...
    def test_with_version_same_version(self) -> None: ...
    def test_with_version_lower_version(self) -> None: ...
    def test_with_version_preserves_all_fields(self) -> None: ...
    def test_with_version_maintains_type(self) -> None: ...

class TestFlextEntityEdgeCases:
    def test_entity_id_type_preservation(self) -> None: ...
    def test_entity_creation_with_all_optional_fields(self) -> None: ...
    def test_entity_hash_stability(self) -> None: ...
    def test_entity_string_representations(self) -> None: ...
    def test_entity_model_dump_excludes_private_fields(self) -> None: ...

class TestFlextEntityValidation:
    def test_domain_rules_validation_called(self) -> None: ...
    def test_pydantic_field_validation_integration(self) -> None: ...
