from collections.abc import Callable as Callable
from datetime import datetime

import pytest
from _typeshed import Incomplete
from pydantic import BaseModel

from flext_core import FlextAggregateRoot, FlextEntity, FlextResult, FlextValueObject

EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

def create_test_entity(entity_class: type, **kwargs: object) -> object: ...

class SampleDomainEvent(BaseModel):
    model_config: Incomplete
    aggregate_id: str
    event_type: str
    event_id: str
    timestamp: datetime
    version: int
    action: str
    details: dict[str, object]
    @classmethod
    def validate_aggregate_id(cls, v: str) -> str: ...
    @classmethod
    def validate_event_type(cls, v: str) -> str: ...

class SampleEntity(FlextEntity):
    name: str
    status: str
    def validate_domain_rules(self) -> FlextResult[None]: ...

class SampleValueObject(FlextValueObject):
    amount: int
    currency: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class SampleAggregateRoot(FlextAggregateRoot):
    title: str
    description: str
    def validate_domain_rules(self) -> FlextResult[None]: ...
    def perform_action(self, action: str) -> None: ...

class TestFlextEntity:
    def test_entity_creation_with_auto_id(self) -> None: ...
    def test_entity_creation_with_custom_id(self) -> None: ...
    def test_entity_creation_with_timestamps(self) -> None: ...
    def test_entity_mutability(self) -> None: ...
    def test_entity_equality_by_id(self) -> None: ...
    def test_entity_hash_consistency(self) -> None: ...
    def test_entity_string_representation(self) -> None: ...
    def test_entity_model_dump(self) -> None: ...
    def test_entity_validation_error(self) -> None: ...

class TestFlextValueObject:
    def test_value_object_creation(self) -> None: ...
    def test_value_object_with_defaults(self) -> None: ...
    def test_value_object_immutability(self) -> None: ...
    def test_value_object_equality_by_value(self) -> None: ...
    def test_value_object_hash_consistency(self) -> None: ...
    def test_value_object_model_dump(self) -> None: ...

class TestFlextDomainEvent:
    def test_domain_event_creation(self) -> None: ...
    def test_domain_event_with_custom_values(self) -> None: ...
    def test_domain_event_immutability(self) -> None: ...
    def test_domain_event_validation(self) -> None: ...
    def test_domain_event_ordering(self) -> None: ...
    def test_domain_event_model_dump(self) -> None: ...

class TestFlextAggregateRoot:
    def test_aggregate_root_creation(self) -> None: ...
    def test_aggregate_root_with_custom_version(self) -> None: ...
    def test_aggregate_root_raise_event(self) -> None: ...
    def test_aggregate_root_multiple_events(self) -> None: ...
    def test_aggregate_root_clear_events(self) -> None: ...
    def test_aggregate_root_immutability(self) -> None: ...
    def test_aggregate_root_inheritance_from_entity(self) -> None: ...
    def test_aggregate_root_model_dump(self) -> None: ...
    def test_aggregate_root_with_entity_id_parameter(self) -> None: ...
    def test_aggregate_root_with_created_at_datetime(self) -> None: ...
    def test_add_domain_event_failure_handling(self) -> None: ...
    def test_add_domain_event_exception_handling(self) -> None: ...
    def test_add_event_object_method(self) -> None: ...
    def test_has_domain_events_method(self) -> None: ...

class TestEntitiesIntegration:
    def test_entity_value_object_composition(self) -> None: ...
    @pytest.mark.ddd
    @pytest.mark.architecture
    def test_aggregate_event_sourcing_pattern(self) -> None: ...
    def test_polymorphic_entity_behavior(self) -> None: ...
    def test_entity_types_consistency(self, entity_class: type) -> None: ...
