from collections.abc import Callable as Callable

class TestFlextValidation:
    def test_validation_utilities_exist(self) -> None: ...
    def test_is_non_empty_string_valid(self) -> None: ...
    def test_is_non_empty_string_invalid(self) -> None: ...
    def test_is_callable_valid(self) -> None: ...
    def test_is_callable_invalid(self) -> None: ...
    def test_is_list_valid(self) -> None: ...
    def test_is_list_invalid(self) -> None: ...
    def test_is_dict_valid(self) -> None: ...
    def test_is_dict_invalid(self) -> None: ...
    def test_is_none_valid(self) -> None: ...
    def test_is_none_invalid(self) -> None: ...
    def test_is_not_none_valid(self) -> None: ...
    def test_is_not_none_invalid(self) -> None: ...
    def test_is_email_placeholder(self) -> None: ...
    def test_is_uuid_placeholder(self) -> None: ...
    def test_is_url_placeholder(self) -> None: ...

class TestFlextResultValidation:
    def test_success_result_creation(self) -> None: ...
    def test_failure_result_creation(self) -> None: ...
    def test_validation_with_flext_result(self) -> None: ...

class TestValidationIntegration:
    def test_complex_validation_scenario(self) -> None: ...
    def test_validation_chaining(self) -> None: ...
