from flext_core import FlextCommands, FlextResult

FlextCommandId = str
FlextCommandType = str
EXPECTED_BULK_SIZE: int
FlextCommand = FlextCommands.Command
FlextCommandHandler = FlextCommands.Handler
FlextCommandBus = FlextCommands.Bus
FlextCommandResult = FlextCommands.Result

class CreateUserCommand(FlextCommands.Command):
    username: str
    email: str
    def get_payload(self) -> dict[str, object]: ...
    def validate_command(self) -> FlextResult[None]: ...

class UpdateUserCommand(FlextCommands.Command):
    user_id: str
    updates: dict[str, object]
    def get_payload(self) -> dict[str, object]: ...
    def validate_command(self) -> FlextResult[None]: ...

class FailingCommand(FlextCommands.Command):
    def get_payload(self) -> dict[str, object]: ...
    def validate_command(self) -> FlextResult[None]: ...

class CreateUserCommandHandler(
    FlextCommandHandler[CreateUserCommand, dict[str, object]]
):
    created_users: list[dict[str, object]]
    def __init__(self) -> None: ...
    def get_command_type(self) -> FlextCommandType: ...
    def can_handle(self, command: object) -> bool: ...
    def handle(self, command: CreateUserCommand) -> FlextResult[dict[str, object]]: ...
    def handle_command(
        self, command: CreateUserCommand
    ) -> FlextResult[dict[str, object]]: ...

class UpdateUserCommandHandler(
    FlextCommandHandler[UpdateUserCommand, dict[str, object]]
):
    updated_users: dict[str, dict[str, object]]
    def __init__(self) -> None: ...
    def get_command_type(self) -> FlextCommandType: ...
    def can_handle(self, command: object) -> bool: ...
    def handle(self, command: UpdateUserCommand) -> FlextResult[dict[str, object]]: ...
    def handle_command(
        self, command: UpdateUserCommand
    ) -> FlextResult[dict[str, object]]: ...

class FailingCommandHandler(FlextCommandHandler[FailingCommand, None]):
    def get_command_type(self) -> FlextCommandType: ...
    def can_handle(self, command: object) -> bool: ...
    def handle(self, command: FailingCommand) -> FlextResult[None]: ...
    def handle_command(self, command: FailingCommand) -> FlextResult[None]: ...

class TestFlextCommand:
    def test_command_creation_with_auto_id(self) -> None: ...
    def test_command_creation_with_custom_id(self) -> None: ...
    def test_get_payload(self) -> None: ...
    def test_validate_command_success(self) -> None: ...
    def test_validate_command_failure_no_username(self) -> None: ...
    def test_validate_command_failure_no_email(self) -> None: ...
    def test_validate_command_failure_invalid_email(self) -> None: ...
    def test_get_command_metadata(self) -> None: ...

class TestFlextCommandHandler:
    def test_handler_creation(self) -> None: ...
    def test_can_handle_correct_command_type(self) -> None: ...
    def test_can_handle_wrong_command_type(self) -> None: ...
    def test_can_handle_non_command_object(self) -> None: ...
    def test_handle_command_success(self) -> None: ...
    def test_process_command_success(self) -> None: ...
    def test_process_command_validation_failure(self) -> None: ...
    def test_process_command_cannot_handle(self) -> None: ...
    def test_process_command_handling_failure(self) -> None: ...

class TestFlextCommandBus:
    def test_command_bus_creation(self) -> None: ...
    def test_register_handler_success(self) -> None: ...
    def test_register_invalid_handler(self) -> None: ...
    def test_execute_command_success(self) -> None: ...
    def test_execute_command_no_handler(self) -> None: ...
    def test_execute_command_validation_failure(self) -> None: ...
    def test_find_handler_for_command(self) -> None: ...
    def test_find_handler_not_found(self) -> None: ...
    def test_get_all_handlers(self) -> None: ...

class TestFlextCommandResult:
    def test_success_result_creation(self) -> None: ...
    def test_failure_result_creation(self) -> None: ...
    def test_result_metadata(self) -> None: ...

class TestCommandPatternIntegration:
    def test_complete_command_flow(self) -> None: ...
    def test_multiple_command_types(self) -> None: ...
    def test_command_validation_and_processing_chain(self) -> None: ...
    def test_error_handling_throughout_command_flow(self) -> None: ...
    def test_command_bus_handler_management(self) -> None: ...
