EXPECTED_BULK_SIZE: int

class TestFlextFieldsFactory:
    def test_create_integer_field_minimal(self) -> None: ...
    def test_create_integer_field_with_constraints(self) -> None: ...
    def test_create_integer_field_with_description(self) -> None: ...
    def test_integer_field_validate_value_success(self) -> None: ...
    def test_integer_field_validate_value_failure(self) -> None: ...
    def test_integer_field_get_field_schema(self) -> None: ...
    def test_create_boolean_field_minimal(self) -> None: ...
    def test_create_boolean_field_with_description(self) -> None: ...
    def test_boolean_field_validate_value_success(self) -> None: ...
    def test_boolean_field_validate_value_failure(self) -> None: ...
    def test_create_string_field_minimal(self) -> None: ...
    def test_create_string_field_with_pattern(self) -> None: ...

class TestFlextFieldRegistry:
    def test_registry_creation(self) -> None: ...
    def test_register_field(self) -> None: ...
    def test_get_field_existing(self) -> None: ...
    def test_get_field_non_existing(self) -> None: ...
    def test_list_field_names(self) -> None: ...
    def test_list_field_ids(self) -> None: ...
    def test_clear_registry(self) -> None: ...
    def test_remove_field(self) -> None: ...
