import pytest

from flext_core import FlextLogContext as FlextLogContext

EXPECTED_BULK_SIZE: int

class TestFlextLogContext:
    def test_context_creation_empty(self) -> None: ...
    def test_context_creation_with_values(self) -> None: ...
    def test_context_optional_fields(self) -> None: ...
    def test_context_enterprise_fields(self) -> None: ...
    def test_context_performance_fields(self) -> None: ...
    def test_context_error_fields(self) -> None: ...

class TestFlextLogLevel:
    def test_log_level_values(self) -> None: ...
    def test_log_level_membership(self) -> None: ...

class TestFlextLogger:
    def test_logger_auto_configuration(self) -> None: ...
    def test_get_logger_creates_instance(self) -> None: ...
    def test_get_logger_caches_instances(self) -> None: ...
    def test_logger_methods_exist(self) -> None: ...
    def test_configure_with_defaults(self) -> None: ...
    def test_configure_with_custom_settings(self) -> None: ...
    def test_configure_idempotent(self) -> None: ...
    def test_get_base_logger(self) -> None: ...
    def test_get_base_logger_with_level(self) -> None: ...
    def test_bind_context(self) -> None: ...
    def test_clear_context(self) -> None: ...
    def test_with_performance_tracking(self) -> None: ...
    def test_backward_compatibility_function(self) -> None: ...
    def test_module_level_function(self) -> None: ...

class TestFlextLoggerUsage:
    def test_basic_logging(self) -> None: ...
    def test_logging_with_context(self) -> None: ...
    def test_bound_logger_usage(self) -> None: ...
    def test_context_manager_style(self) -> None: ...
    @pytest.mark.performance
    def test_performance_logging(self) -> None: ...
    def test_logger_factory_called(self) -> None: ...

class TestFlextLoggerIntegration:
    def test_multiple_loggers(self) -> None: ...
    def test_logging_hierarchy(self) -> None: ...
    def test_complex_logging_scenario(self) -> None: ...
    def test_error_logging_with_context(self) -> None: ...
    @pytest.mark.performance
    def test_performance_logging_integration(self) -> None: ...
