from flext_core import FlextFieldCore, FlextResult

EXPECTED_BULK_SIZE: int

class TestFlextFieldCoreInteger:
    def test_integer_field_creation_minimal(self) -> None: ...
    def test_integer_field_creation_with_constraints(self) -> None: ...
    def test_integer_field_validate_value_success(self) -> None: ...
    def test_integer_field_validate_value_success_case(self) -> None: ...
    def test_integer_field_validate_none_value(self) -> None: ...
    def test_integer_field_validate_non_integer_type(self) -> None: ...
    def test_integer_field_serialize_value(self) -> None: ...
    def test_metadata_creation_with_defaults(self) -> None: ...
    def test_metadata_creation_with_values(self) -> None: ...
    def test_metadata_to_dict(self) -> None: ...
    def test_metadata_from_dict(self) -> None: ...
    def test_metadata_from_dict_with_defaults(self) -> None: ...
    def test_metadata_round_trip(self) -> None: ...

class ConcreteFlextFieldCore(FlextFieldCore):
    def validate_value(self, value: object) -> FlextResult[object]: ...
    def serialize_value(self, value: object) -> str: ...
    def deserialize_value(self, value: object) -> str: ...

class TestFlextFieldCoreBase:
    def test_field_creation_minimal(self) -> None: ...
    def test_field_creation_full(self) -> None: ...
    def test_field_get_default_value(self) -> None: ...
    def test_field_get_default_value_none(self) -> None: ...
    def test_field_is_required(self) -> None: ...
    def test_field_is_deprecated(self) -> None: ...
    def test_field_is_sensitive(self) -> None: ...
    def test_field_get_field_info(self) -> None: ...
    def test_field_get_field_info_no_validator(self) -> None: ...
    def test_field_validate_value_required_success(self) -> None: ...
    def test_field_validate_value_required_failure(self) -> None: ...
    def test_field_serialize_value(self) -> None: ...
    def test_field_deserialize_value(self) -> None: ...

class TestFlextFieldCoreString:
    def test_string_field_creation_minimal(self) -> None: ...
    def test_string_field_creation_with_constraints(self) -> None: ...
    def test_string_field_creation_with_custom_metadata(self) -> None: ...
    def test_string_field_validate_value_success(self) -> None: ...
    def test_string_field_validate_value_success_case(self) -> None: ...
    def test_string_field_serialize_value(self) -> None: ...
    def test_string_field_deserialize_value(self) -> None: ...
    def test_string_field_deserialize_non_string(self) -> None: ...
    def test_string_field_validate_none_value(self) -> None: ...
    def test_string_field_validate_non_string_type(self) -> None: ...
    def test_string_field_with_all_parameters(self) -> None: ...

class TestFlextFieldCoreBoolean:
    def test_boolean_field_creation_minimal(self) -> None: ...
    def test_boolean_field_validate_value_success(self) -> None: ...
    def test_boolean_field_validate_value_success_case(self) -> None: ...
    def test_boolean_field_validate_non_boolean_type(self) -> None: ...
    def test_boolean_field_serialize_value(self) -> None: ...
    def test_boolean_field_deserialize_existing_boolean(self) -> None: ...
    def test_boolean_field_deserialize_string_values(self) -> None: ...
    def test_boolean_field_deserialize_integer(self) -> None: ...
    def test_boolean_field_deserialize_non_convertible(self) -> None: ...

class TestFlextFieldCoreRegistry:
    def test_registry_creation(self) -> None: ...
    def test_register_field(self) -> None: ...
    def test_get_field_existing(self) -> None: ...
    def test_get_field_non_existent(self) -> None: ...
    def test_get_all_fields_empty(self) -> None: ...
    def test_get_all_fields_with_fields(self) -> None: ...
    def test_get_fields_by_type_with_matches(self) -> None: ...
    def test_validate_all_fields_success(self) -> None: ...
    def test_validate_all_fields_required_missing(self) -> None: ...
    def test_validate_all_fields_validation_error(self) -> None: ...
