# AUTO-GENERATED FILE — Regenerate with: make gen
"""Lazy-import manifest — single source of truth for flext_core._models.__init__.py.

Generated by ``make gen``. The package initializer consumes only this module for
lazy (PEP 562) import access; sibling ``__all__`` discovery is the upstream source.
"""

from __future__ import annotations

LAZY_MODULES: dict[str, tuple[str, ...]] = {
    ".base": ("FlextModelsBase",),
    ".builder": ("FlextModelsBuilder",),
    ".collections": ("FlextModelsCollections",),
    ".config": ("FlextModelsConfig",),
    ".container": ("FlextModelsContainer",),
    ".containers": (
        "FlextModelsContainers",
        "mc",
    ),
    ".context": ("FlextModelsContext",),
    ".cqrs": ("FlextModelsCqrs",),
    ".dispatcher": ("FlextModelsDispatcher",),
    ".domain_event": ("FlextModelsDomainEvent",),
    ".enforcement": ("FlextModelsEnforcement",),
    ".entity": ("FlextModelsEntity",),
    ".errors": ("FlextModelsErrors",),
    ".exception_params": ("FlextModelsExceptionParams",),
    ".handler": ("FlextModelsHandler",),
    ".namespace": ("FlextModelsNamespace",),
    ".project_metadata": ("FlextModelsProjectMetadata",),
    ".pydantic": ("FlextModelsPydantic",),
    ".registry": ("FlextModelsRegistry",),
    ".service": ("FlextModelsService",),
    ".settings": ("FlextModelsSettings",),
}


LAZY_ALIAS_GROUPS: dict[str, tuple[tuple[str, str], ...]] = {}


CHILD_MODULE_PATHS: tuple[str, ...] = (
    "._base_parts",
    "._container_parts",
    "._context",
    "._cqrs_parts",
    "._enforcement",
    "._exception_params_parts",
    "._handler_parts",
)


EXCLUDED_LAZY_NAMES: tuple[str, ...] = ()


PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextModelsBase",
    "FlextModelsBuilder",
    "FlextModelsCollections",
    "FlextModelsConfig",
    "FlextModelsContainer",
    "FlextModelsContainers",
    "FlextModelsContext",
    "FlextModelsCqrs",
    "FlextModelsDispatcher",
    "FlextModelsDomainEvent",
    "FlextModelsEnforcement",
    "FlextModelsEntity",
    "FlextModelsErrors",
    "FlextModelsExceptionParams",
    "FlextModelsHandler",
    "FlextModelsNamespace",
    "FlextModelsProjectMetadata",
    "FlextModelsPydantic",
    "FlextModelsRegistry",
    "FlextModelsService",
    "FlextModelsSettings",
    "_base_parts",
    "_container_parts",
    "_context",
    "_cqrs_parts",
    "_enforcement",
    "_exception_params_parts",
    "_handler_parts",
    "mc",
)
