"""Lightweight test doubles for github test modules.

Replaces generic mock objects with typed, configurable stub classes
that satisfy flext_infra protocol contracts.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

from pydantic import Field

from flext_core import FlextModels, r


class StubCommandOutput(FlextModels.ArbitraryTypesModel):
    """Stub command output matching p.Infra.CommandOutput protocol."""

    exit_code: int = Field(default=0, description="Command exit code")
    stdout: str = Field(default="", description="Captured stdout")
    stderr: str = Field(default="", description="Captured stderr")


class StubRunner:
    """Configurable stub for p.Infra.CommandRunner protocol."""

    def __init__(
        self,
        run_returns: Sequence[object] | None = None,
        capture_returns: Sequence[object] | None = None,
        run_checked_returns: Sequence[object] | None = None,
        run_to_file_returns: Sequence[object] | None = None,
    ) -> None:
        self._run_returns = list(run_returns or [])
        self._capture_returns = list(capture_returns or [])
        self._run_checked_returns = list(run_checked_returns or [])
        self._run_to_file_returns = list(run_to_file_returns or [])
        self.run_calls: list[list[str]] = []
        self.capture_calls: list[list[str]] = []
        self.run_checked_calls: list[list[str]] = []
        self.run_to_file_calls: list[list[str]] = []

    def _pop(self, returns: list[object]) -> object:
        if not returns:
            return r[bool].fail("no return value configured")
        return returns[0] if len(returns) == 1 else returns.pop(0)

    def run(
        self,
        cmd: Sequence[str],
        cwd: Path | None = None,
        timeout: int | None = None,
        env: Mapping[str, str] | None = None,
    ) -> object:
        self.run_calls.append(list(cmd))
        return self._pop(self._run_returns)

    def capture(
        self,
        cmd: Sequence[str],
        cwd: Path | None = None,
        timeout: int | None = None,
        env: Mapping[str, str] | None = None,
    ) -> object:
        self.capture_calls.append(list(cmd))
        return self._pop(self._capture_returns)

    def run_checked(
        self,
        cmd: Sequence[str],
        cwd: Path | None = None,
        timeout: int | None = None,
        env: Mapping[str, str] | None = None,
    ) -> object:
        self.run_checked_calls.append(list(cmd))
        return self._pop(self._run_checked_returns)

    def run_to_file(
        self,
        cmd: Sequence[str],
        output_file: Path,
        cwd: Path | None = None,
        timeout: int | None = None,
        env: Mapping[str, str] | None = None,
    ) -> object:
        self.run_to_file_calls.append(list(cmd))
        return self._pop(self._run_to_file_returns)

    def run_raw(
        self,
        cmd: Sequence[str],
        cwd: Path | None = None,
        timeout: int | None = None,
        env: Mapping[str, str] | None = None,
    ) -> object:
        return self.run(cmd, cwd=cwd, timeout=timeout, env=env)


class StubJsonIo:
    """Stub for FlextInfraUtilitiesIo (json_io dependency)."""

    def __init__(self, write_returns: r[bool] | None = None) -> None:
        self.write_json_returns = write_returns or r[bool].ok(True)
        self.write_json_calls: list[tuple[Path, object]] = []

    def write_json(self, path: Path, data: object, **kwargs: object) -> r[bool]:
        self.write_json_calls.append((path, data))
        return self.write_json_returns


class StubVersioning:
    """Stub for FlextInfraUtilitiesVersioning."""

    def __init__(self, release_tag_returns: r[str] | None = None) -> None:
        self._release_tag_returns = release_tag_returns or r[str].fail("no tag")

    def release_tag_from_branch(self, branch: str) -> r[str]:
        return self._release_tag_returns


class StubSelector:
    """Stub for FlextInfraUtilitiesSelection."""

    def __init__(self, resolve_returns: object | None = None) -> None:
        self._resolve_returns = (
            resolve_returns if resolve_returns is not None else r[list[object]].ok([])
        )

    def resolve_projects(self, *args: object, **kwargs: object) -> object:
        return self._resolve_returns


class StubReporting:
    """Stub for FlextInfraUtilitiesReporting."""

    def __init__(self, report_dir: Path | None = None) -> None:
        self._report_dir = report_dir or Path("/tmp/reports")

    def get_report_dir(self, *_args: object, **_kwargs: object) -> Path:
        return self._report_dir


class StubTemplates:
    """Stub for FlextInfraUtilitiesTemplates."""

    GENERATED_SHELL_HEADER: str = "# GENERATED by {source}\n"


class StubProjectInfo:
    """Stub for p.Infra.ProjectInfo protocol."""

    def __init__(self, name: str = "test-project", path: Path | None = None) -> None:
        self.name = name
        self.path = path or Path("/tmp/test-project")


class StubPrManager:
    """Stub for FlextInfraPrManager used in CLI tests."""

    def __init__(
        self,
        status_returns: Sequence[object] | None = None,
        create_returns: Sequence[object] | None = None,
        view_returns: Sequence[object] | None = None,
        checks_returns: Sequence[object] | None = None,
        merge_returns: Sequence[object] | None = None,
        close_returns: Sequence[object] | None = None,
    ) -> None:
        self._status = list(status_returns or [])
        self._create = list(create_returns or [])
        self._view = list(view_returns or [])
        self._checks = list(checks_returns or [])
        self._merge = list(merge_returns or [])
        self._close = list(close_returns or [])

    def _pop(self, returns: list[object]) -> object:
        if not returns:
            return r[bool].fail("no return configured")
        return returns[0] if len(returns) == 1 else returns.pop(0)

    def status(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._status)

    def create(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._create)

    def view(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._view)

    def checks(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._checks)

    def merge(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._merge)

    def close(self, *_a: object, **_kw: object) -> object:
        return self._pop(self._close)


class StubSyncer:
    """Stub for FlextInfraWorkflowSyncer used in CLI tests."""

    def __init__(self, sync_returns: object | None = None) -> None:
        self._sync_returns = (
            sync_returns if sync_returns is not None else r[list[object]].ok([])
        )
        self.sync_workspace_calls: list[dict[str, object]] = []

    def sync_workspace(self, **kwargs: object) -> object:
        self.sync_workspace_calls.append(kwargs)
        return self._sync_returns


class StubLinter:
    """Stub for FlextInfraWorkflowLinter used in CLI tests."""

    def __init__(self, lint_returns: object | None = None) -> None:
        self._lint_returns = (
            lint_returns if lint_returns is not None else r[bool].ok(True)
        )
        self.lint_calls: list[dict[str, object]] = []

    def lint(self, **kwargs: object) -> object:
        self.lint_calls.append(kwargs)
        return self._lint_returns


class StubWorkspaceManager:
    """Stub for FlextInfraPrWorkspaceManager used in CLI tests."""

    def __init__(self, orchestrate_returns: object | None = None) -> None:
        self._orchestrate_returns = (
            orchestrate_returns if orchestrate_returns is not None else r[bool].ok(True)
        )
        self.orchestrate_calls: list[dict[str, object]] = []

    def orchestrate(self, **kwargs: object) -> object:
        self.orchestrate_calls.append(kwargs)
        return self._orchestrate_returns


class StubUtilities:
    """Stub for u (FlextInfraUtilities) used in CLI tests."""

    class Infra:
        """Stub for u.Infra namespace."""

        _git_branch_returns: object = None

        @classmethod
        def git_current_branch(cls, *_a: object, **_kw: object) -> object:
            return cls._git_branch_returns or r[str].ok("feature")

        @classmethod
        def git_has_changes(cls, *_a: object, **_kw: object) -> object:
            return r[bool].ok(True)

        @classmethod
        def git_checkout(cls, *_a: object, **_kw: object) -> object:
            return r[bool].ok(True)

        @classmethod
        def git_add(cls, *_a: object, **_kw: object) -> object:
            return r[bool].ok(True)

        @classmethod
        def git_commit(cls, *_a: object, **_kw: object) -> object:
            return r[bool].ok(True)


__all__ = [
    "StubCommandOutput",
    "StubJsonIo",
    "StubLinter",
    "StubPrManager",
    "StubProjectInfo",
    "StubReporting",
    "StubRunner",
    "StubSelector",
    "StubSyncer",
    "StubTemplates",
    "StubUtilities",
    "StubVersioning",
    "StubWorkspaceManager",
]
