# AUTO-GENERATED FILE — Regenerate with: make gen
"""Root Typing Parts package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import build_lazy_import_map, install_lazy_exports

if TYPE_CHECKING:
    from flext_core._root_typing_parts.contracts import (
        FlextProtocolsBase as FlextProtocolsBase,
        FlextProtocolsContainer as FlextProtocolsContainer,
        FlextProtocolsContext as FlextProtocolsContext,
        FlextProtocolsHandler as FlextProtocolsHandler,
        FlextProtocolsLogging as FlextProtocolsLogging,
        FlextProtocolsPydantic as FlextProtocolsPydantic,
        FlextProtocolsRegistry as FlextProtocolsRegistry,
        FlextProtocolsResult as FlextProtocolsResult,
        FlextProtocolsService as FlextProtocolsService,
        FlextProtocolsSettings as FlextProtocolsSettings,
        FlextTypesAnnotateds as FlextTypesAnnotateds,
        FlextTypesCore as FlextTypesCore,
        FlextTypesPydantic as FlextTypesPydantic,
        FlextTypesServices as FlextTypesServices,
        FlextTypesTypeAdapters as FlextTypesTypeAdapters,
        FlextTypingBase as FlextTypingBase,
        FlextTypingContainers as FlextTypingContainers,
        FlextTypingProjectMetadata as FlextTypingProjectMetadata,
    )
    from flext_core._root_typing_parts.core import (
        FlextConstantsBase as FlextConstantsBase,
        FlextConstantsCqrs as FlextConstantsCqrs,
        FlextConstantsEnforcement as FlextConstantsEnforcement,
        FlextConstantsEnvironment as FlextConstantsEnvironment,
        FlextConstantsErrors as FlextConstantsErrors,
        FlextConstantsFile as FlextConstantsFile,
        FlextConstantsGuards as FlextConstantsGuards,
        FlextConstantsInfrastructure as FlextConstantsInfrastructure,
        FlextConstantsLogging as FlextConstantsLogging,
        FlextConstantsMixins as FlextConstantsMixins,
        FlextConstantsProjectMetadata as FlextConstantsProjectMetadata,
        FlextConstantsPydantic as FlextConstantsPydantic,
        FlextConstantsRegex as FlextConstantsRegex,
        FlextConstantsSerialization as FlextConstantsSerialization,
        FlextConstantsSettings as FlextConstantsSettings,
        FlextConstantsStatus as FlextConstantsStatus,
        FlextConstantsTimeout as FlextConstantsTimeout,
        FlextConstantsValidation as FlextConstantsValidation,
        FlextExceptionsBase as FlextExceptionsBase,
        FlextExceptionsFactories as FlextExceptionsFactories,
        FlextExceptionsHelpers as FlextExceptionsHelpers,
        FlextExceptionsMetrics as FlextExceptionsMetrics,
        FlextExceptionsTemplate as FlextExceptionsTemplate,
        FlextExceptionsTypes as FlextExceptionsTypes,
        FlextMroViolation as FlextMroViolation,
        FlextSettingsBase as FlextSettingsBase,
        FlextSettingsContext as FlextSettingsContext,
        FlextSettingsCore as FlextSettingsCore,
        FlextSettingsDatabase as FlextSettingsDatabase,
        FlextSettingsDI as FlextSettingsDI,
        FlextSettingsDispatcher as FlextSettingsDispatcher,
        FlextSettingsInfrastructure as FlextSettingsInfrastructure,
        FlextSettingsRegistry as FlextSettingsRegistry,
        FlextSmellViolation as FlextSmellViolation,
    )
    from flext_core._root_typing_parts.facades import (
        FlextConstants as FlextConstants,
        FlextContainer as FlextContainer,
        FlextContext as FlextContext,
        FlextDecorators as FlextDecorators,
        FlextDispatcher as FlextDispatcher,
        FlextExceptions as FlextExceptions,
        FlextHandlers as FlextHandlers,
        FlextLazy as FlextLazy,
        FlextLogger as FlextLogger,
        FlextMixins as FlextMixins,
        FlextModels as FlextModels,
        FlextProtocols as FlextProtocols,
        FlextRegistry as FlextRegistry,
        FlextResult as FlextResult,
        FlextRuntime as FlextRuntime,
        FlextService as FlextService,
        FlextSettings as FlextSettings,
        FlextTypes as FlextTypes,
        FlextUtilities as FlextUtilities,
        build_lazy_import_map as build_lazy_import_map,
        c as c,
        d as d,
        e as e,
        h as h,
        lazy as lazy,
        m as m,
        normalize_lazy_imports as normalize_lazy_imports,
        p as p,
        r as r,
        s as s,
        t as t,
        u as u,
        x as x,
    )
    from flext_core._root_typing_parts.models import (
        FlextModelsBase as FlextModelsBase,
        FlextModelsBuilder as FlextModelsBuilder,
        FlextModelsCollections as FlextModelsCollections,
        FlextModelsContainer as FlextModelsContainer,
        FlextModelsContainers as FlextModelsContainers,
        FlextModelsContext as FlextModelsContext,
        FlextModelsCqrs as FlextModelsCqrs,
        FlextModelsDispatcher as FlextModelsDispatcher,
        FlextModelsDomainEvent as FlextModelsDomainEvent,
        FlextModelsEnforcement as FlextModelsEnforcement,
        FlextModelsEntity as FlextModelsEntity,
        FlextModelsErrors as FlextModelsErrors,
        FlextModelsExceptionParams as FlextModelsExceptionParams,
        FlextModelsHandler as FlextModelsHandler,
        FlextModelsNamespace as FlextModelsNamespace,
        FlextModelsProjectMetadata as FlextModelsProjectMetadata,
        FlextModelsPydantic as FlextModelsPydantic,
        FlextModelsRegistry as FlextModelsRegistry,
        FlextModelsService as FlextModelsService,
        FlextModelsSettings as FlextModelsSettings,
        mc as mc,
    )
    from flext_core._root_typing_parts.utilities_part_01 import (
        FlextUtilitiesArgs as FlextUtilitiesArgs,
        FlextUtilitiesBeartypeAttrVisitor as FlextUtilitiesBeartypeAttrVisitor,
        FlextUtilitiesBeartypeClassVisitor as FlextUtilitiesBeartypeClassVisitor,
        FlextUtilitiesBeartypeConf as FlextUtilitiesBeartypeConf,
        FlextUtilitiesBeartypeDeprecatedVisitor as FlextUtilitiesBeartypeDeprecatedVisitor,
        FlextUtilitiesBeartypeEngine as FlextUtilitiesBeartypeEngine,
        FlextUtilitiesBeartypeFieldVisitor as FlextUtilitiesBeartypeFieldVisitor,
        FlextUtilitiesBeartypeHelpers as FlextUtilitiesBeartypeHelpers,
        FlextUtilitiesBeartypeImportVisitor as FlextUtilitiesBeartypeImportVisitor,
        FlextUtilitiesBeartypeMethodVisitor as FlextUtilitiesBeartypeMethodVisitor,
        FlextUtilitiesBeartypeModuleVisitor as FlextUtilitiesBeartypeModuleVisitor,
        FlextUtilitiesBeartypeTypingExtPatch as FlextUtilitiesBeartypeTypingExtPatch,
        FlextUtilitiesChecker as FlextUtilitiesChecker,
        FlextUtilitiesCollection as FlextUtilitiesCollection,
        FlextUtilitiesCollectionIter as FlextUtilitiesCollectionIter,
        FlextUtilitiesCollectionMerge as FlextUtilitiesCollectionMerge,
        FlextUtilitiesContext as FlextUtilitiesContext,
        FlextUtilitiesContextCrud as FlextUtilitiesContextCrud,
    )
    from flext_core._root_typing_parts.utilities_part_02 import (
        FlextUtilitiesContextLifecycle as FlextUtilitiesContextLifecycle,
        FlextUtilitiesContextState as FlextUtilitiesContextState,
        FlextUtilitiesConversion as FlextUtilitiesConversion,
        FlextUtilitiesDiscovery as FlextUtilitiesDiscovery,
        FlextUtilitiesDomain as FlextUtilitiesDomain,
        FlextUtilitiesEnforcement as FlextUtilitiesEnforcement,
        FlextUtilitiesEnforcementCollect as FlextUtilitiesEnforcementCollect,
        FlextUtilitiesEnforcementEmit as FlextUtilitiesEnforcementEmit,
        FlextUtilitiesEnum as FlextUtilitiesEnum,
        FlextUtilitiesGenerators as FlextUtilitiesGenerators,
        FlextUtilitiesGuards as FlextUtilitiesGuards,
        FlextUtilitiesGuardsTypeCore as FlextUtilitiesGuardsTypeCore,
        FlextUtilitiesGuardsTypeModel as FlextUtilitiesGuardsTypeModel,
        FlextUtilitiesGuardsTypeProtocol as FlextUtilitiesGuardsTypeProtocol,
        FlextUtilitiesHandler as FlextUtilitiesHandler,
        FlextUtilitiesLoggingConfig as FlextUtilitiesLoggingConfig,
        FlextUtilitiesLoggingContext as FlextUtilitiesLoggingContext,
        FlextUtilitiesMapper as FlextUtilitiesMapper,
    )
    from flext_core._root_typing_parts.utilities_part_03 import (
        FlextUtilitiesMapperAccess as FlextUtilitiesMapperAccess,
        FlextUtilitiesMapperExtract as FlextUtilitiesMapperExtract,
        FlextUtilitiesModel as FlextUtilitiesModel,
        FlextUtilitiesModelOptions as FlextUtilitiesModelOptions,
        FlextUtilitiesModelRuntime as FlextUtilitiesModelRuntime,
        FlextUtilitiesParser as FlextUtilitiesParser,
        FlextUtilitiesParserCoerce as FlextUtilitiesParserCoerce,
        FlextUtilitiesParserTargets as FlextUtilitiesParserTargets,
        FlextUtilitiesProjectMetadata as FlextUtilitiesProjectMetadata,
        FlextUtilitiesPydantic as FlextUtilitiesPydantic,
        FlextUtilitiesReliability as FlextUtilitiesReliability,
        FlextUtilitiesRuntimeViolationRegistry as FlextUtilitiesRuntimeViolationRegistry,
        FlextUtilitiesSettings as FlextUtilitiesSettings,
        FlextUtilitiesText as FlextUtilitiesText,
        execute_dispatcher_handler as execute_dispatcher_handler,
        ube as ube,
    )
_LAZY_IMPORTS = build_lazy_import_map(
    {
        ".contracts": (
            "FlextProtocolsBase",
            "FlextProtocolsContainer",
            "FlextProtocolsContext",
            "FlextProtocolsHandler",
            "FlextProtocolsLogging",
            "FlextProtocolsPydantic",
            "FlextProtocolsRegistry",
            "FlextProtocolsResult",
            "FlextProtocolsService",
            "FlextProtocolsSettings",
            "FlextTypesAnnotateds",
            "FlextTypesCore",
            "FlextTypesPydantic",
            "FlextTypesServices",
            "FlextTypesTypeAdapters",
            "FlextTypingBase",
            "FlextTypingContainers",
            "FlextTypingProjectMetadata",
        ),
        ".core": (
            "FlextConstantsBase",
            "FlextConstantsCqrs",
            "FlextConstantsEnforcement",
            "FlextConstantsEnvironment",
            "FlextConstantsErrors",
            "FlextConstantsFile",
            "FlextConstantsGuards",
            "FlextConstantsInfrastructure",
            "FlextConstantsLogging",
            "FlextConstantsMixins",
            "FlextConstantsProjectMetadata",
            "FlextConstantsPydantic",
            "FlextConstantsRegex",
            "FlextConstantsSerialization",
            "FlextConstantsSettings",
            "FlextConstantsStatus",
            "FlextConstantsTimeout",
            "FlextConstantsValidation",
            "FlextExceptionsBase",
            "FlextExceptionsFactories",
            "FlextExceptionsHelpers",
            "FlextExceptionsMetrics",
            "FlextExceptionsTemplate",
            "FlextExceptionsTypes",
            "FlextMroViolation",
            "FlextSettingsBase",
            "FlextSettingsContext",
            "FlextSettingsCore",
            "FlextSettingsDI",
            "FlextSettingsDatabase",
            "FlextSettingsDispatcher",
            "FlextSettingsInfrastructure",
            "FlextSettingsRegistry",
            "FlextSmellViolation",
        ),
        ".facades": (
            "FlextConstants",
            "FlextContainer",
            "FlextContext",
            "FlextDecorators",
            "FlextDispatcher",
            "FlextExceptions",
            "FlextHandlers",
            "FlextLazy",
            "FlextLogger",
            "FlextMixins",
            "FlextModels",
            "FlextProtocols",
            "FlextRegistry",
            "FlextResult",
            "FlextRuntime",
            "FlextService",
            "FlextSettings",
            "FlextTypes",
            "FlextUtilities",
            "build_lazy_import_map",
            "c",
            "d",
            "e",
            "h",
            "lazy",
            "m",
            "normalize_lazy_imports",
            "p",
            "r",
            "s",
            "t",
            "u",
            "x",
        ),
        ".models": (
            "FlextModelsBase",
            "FlextModelsBuilder",
            "FlextModelsCollections",
            "FlextModelsContainer",
            "FlextModelsContainers",
            "FlextModelsContext",
            "FlextModelsCqrs",
            "FlextModelsDispatcher",
            "FlextModelsDomainEvent",
            "FlextModelsEnforcement",
            "FlextModelsEntity",
            "FlextModelsErrors",
            "FlextModelsExceptionParams",
            "FlextModelsHandler",
            "FlextModelsNamespace",
            "FlextModelsProjectMetadata",
            "FlextModelsPydantic",
            "FlextModelsRegistry",
            "FlextModelsService",
            "FlextModelsSettings",
            "mc",
        ),
        ".utilities_part_01": (
            "FlextUtilitiesArgs",
            "FlextUtilitiesBeartypeAttrVisitor",
            "FlextUtilitiesBeartypeClassVisitor",
            "FlextUtilitiesBeartypeConf",
            "FlextUtilitiesBeartypeDeprecatedVisitor",
            "FlextUtilitiesBeartypeEngine",
            "FlextUtilitiesBeartypeFieldVisitor",
            "FlextUtilitiesBeartypeHelpers",
            "FlextUtilitiesBeartypeImportVisitor",
            "FlextUtilitiesBeartypeMethodVisitor",
            "FlextUtilitiesBeartypeModuleVisitor",
            "FlextUtilitiesBeartypeTypingExtPatch",
            "FlextUtilitiesChecker",
            "FlextUtilitiesCollection",
            "FlextUtilitiesCollectionIter",
            "FlextUtilitiesCollectionMerge",
            "FlextUtilitiesContext",
            "FlextUtilitiesContextCrud",
        ),
        ".utilities_part_02": (
            "FlextUtilitiesContextLifecycle",
            "FlextUtilitiesContextState",
            "FlextUtilitiesConversion",
            "FlextUtilitiesDiscovery",
            "FlextUtilitiesDomain",
            "FlextUtilitiesEnforcement",
            "FlextUtilitiesEnforcementCollect",
            "FlextUtilitiesEnforcementEmit",
            "FlextUtilitiesEnum",
            "FlextUtilitiesGenerators",
            "FlextUtilitiesGuards",
            "FlextUtilitiesGuardsTypeCore",
            "FlextUtilitiesGuardsTypeModel",
            "FlextUtilitiesGuardsTypeProtocol",
            "FlextUtilitiesHandler",
            "FlextUtilitiesLoggingConfig",
            "FlextUtilitiesLoggingContext",
            "FlextUtilitiesMapper",
        ),
        ".utilities_part_03": (
            "FlextUtilitiesMapperAccess",
            "FlextUtilitiesMapperExtract",
            "FlextUtilitiesModel",
            "FlextUtilitiesModelOptions",
            "FlextUtilitiesModelRuntime",
            "FlextUtilitiesParser",
            "FlextUtilitiesParserCoerce",
            "FlextUtilitiesParserTargets",
            "FlextUtilitiesProjectMetadata",
            "FlextUtilitiesPydantic",
            "FlextUtilitiesReliability",
            "FlextUtilitiesRuntimeViolationRegistry",
            "FlextUtilitiesSettings",
            "FlextUtilitiesText",
            "execute_dispatcher_handler",
            "ube",
        ),
    },
)


install_lazy_exports(
    __name__,
    globals(),
    _LAZY_IMPORTS,
    publish_all=False,
)
