# =============================================================================
# flext-core - Enterprise Foundation Framework - Modern Python 3.13 + Clean Architecture
# =============================================================================
# @generated by: flext_infra workspace sync
# Run 'make sync' from workspace root to update this section.
# Edit below # --- FLEXT:custom-targets --- only.
# =============================================================================

PROJECT_NAME := flext-core
PYTHON_VERSION ?= 3.13
SRC_DIR ?= src
TESTS_DIR ?= tests
ifneq ("$(wildcard ../base.mk)", "")
include ../base.mk
else
# =============================================================================
# STANDALONE BOOTSTRAP — auto-generates base.mk via flext-infra
# =============================================================================
# GNU Make auto-rebuild: if base.mk is missing, Make builds this target first,
# then restarts with base.mk loaded. All standard verbs become available.
# =============================================================================

PYTHON_VERSION ?= 3.13
PYTHON_CMD := $(firstword $(shell command -v python$(PYTHON_VERSION) python3 python 2>/dev/null))
BOOTSTRAP_VENV := .venv
BOOTSTRAP_PIP := $(BOOTSTRAP_VENV)/bin/pip
BOOTSTRAP_PYTHON := $(BOOTSTRAP_VENV)/bin/python

-include base.mk

base.mk: Makefile
	@echo "==> Resolving base.mk for $(PROJECT_NAME)..."
	@if [ -d "$(BOOTSTRAP_VENV)" ] && $(BOOTSTRAP_PYTHON) -c 'import flext_infra' 2>/dev/null; then \
		$(BOOTSTRAP_PYTHON) -m flext_infra basemk generate \
			--project-name $(PROJECT_NAME) --output $@; \
	elif $(PYTHON_CMD) -c 'import flext_infra' 2>/dev/null; then \
		$(PYTHON_CMD) -m flext_infra basemk generate \
			--project-name $(PROJECT_NAME) --output $@; \
	else \
		echo "==> flext-infra not found. Bootstrapping standalone environment..."; \
		$(MAKE) _bootstrap-venv; \
		$(BOOTSTRAP_PIP) install -q flext-infra; \
		$(BOOTSTRAP_PYTHON) -m flext_infra basemk generate \
			--project-name $(PROJECT_NAME) --output $@; \
	fi
	@test -s $@ || { echo "ERROR: base.mk generation failed"; rm -f $@; exit 1; }
	@echo "==> base.mk generated. Restarting make..."

.PHONY: _bootstrap-venv venv setup help

_bootstrap-venv:
	@if [ ! -d "$(BOOTSTRAP_VENV)" ]; then \
		echo "==> Creating virtual environment with $(PYTHON_CMD)..."; \
		if [ -z "$(PYTHON_CMD)" ]; then \
			echo "ERROR: Python $(PYTHON_VERSION) not found. Install it first."; \
			exit 1; \
		fi; \
		$(PYTHON_CMD) -m venv $(BOOTSTRAP_VENV); \
		$(BOOTSTRAP_PIP) install -q -U pip; \
	fi

venv: _bootstrap-venv ## Create standalone virtual environment
	@$(BOOTSTRAP_PIP) install -q -U pip poetry
	@echo "Virtual environment ready at $(BOOTSTRAP_VENV)"

setup: venv ## Full standalone setup (venv + dependencies + base.mk)
	@echo "==> Installing project dependencies..."
	@$(BOOTSTRAP_PIP) install -q flext-infra
	@$(BOOTSTRAP_PYTHON) -m flext_infra deps internal-sync \
		--project-root "$(CURDIR)" 2>/dev/null || true
	@$(BOOTSTRAP_VENV)/bin/poetry lock
	@$(BOOTSTRAP_VENV)/bin/poetry install --all-extras --all-groups
	@if git rev-parse --git-dir >/dev/null 2>&1; then \
		$(BOOTSTRAP_VENV)/bin/poetry run pre-commit install 2>/dev/null || true; \
	fi
	@$(BOOTSTRAP_PYTHON) -m flext_infra basemk generate \
		--project-name $(PROJECT_NAME) --output base.mk
	@echo "==> Setup complete. All 'make' verbs now available."

help: ## Show available commands
	@echo "================================================"
	@echo "  $(PROJECT_NAME) (standalone bootstrap)"
	@echo "================================================"
	@echo ""
	@echo "Bootstrap targets (no base.mk required):"
	@printf "  %-14s %s\n" "venv"   "Create virtual environment"
	@printf "  %-14s %s\n" "setup"  "Full standalone setup"
	@printf "  %-14s %s\n" "help"   "Show this help"
	@echo ""
	@echo "After 'make setup', all standard verbs become available:"
	@echo "  check, test, format, build, validate, clean, docs, pr"
	@echo ""
	@echo "Run 'make setup' first, then 'make help' for full verb list."
endif
# --- FLEXT:custom-targets ---
FLEXT_MODERNIZE_FLAGS ?= --skip-check

FLEXT_INFRA_PYTHON = PYTHONPATH=$(CURDIR)/src $(POETRY) run python

# -----------------------------------------------------------------------------
# Project-specific convenience targets (on top of standardized FLEXT verbs)
# -----------------------------------------------------------------------------
.PHONY: docs-serve diagnose doctor deps-update deps-show validate-typings precommit quick-check ci ci-fast activate tooling-sync setup-project

docs-serve: ## Serve MkDocs locally
	$(Q)$(POETRY) run mkdocs serve

diagnose: ## Show local runtime and Poetry diagnostics
	$(Q)echo "Project: $(PROJECT_NAME)"
	$(Q)echo "Python: $$($(POETRY) run python --version)"
	$(Q)echo "Poetry: $$($(POETRY) --version)"
	$(Q)$(POETRY) env info

activate: ## Pre-activate environment for flext-infra automations
	$(Q)$(POETRY) install --all-extras --all-groups
	$(Q)if git rev-parse --git-dir >/dev/null 2>&1; then \
		$(POETRY) run pre-commit install; \
	else \
		echo "INFO: skipping pre-commit install (no git repository)"; \
	fi

tooling-sync: ## Regenerate pyproject/base.mk through flext-infra generators
	$(Q)$(FLEXT_INFRA_PYTHON) -m flext_infra deps modernize $(FLEXT_MODERNIZE_FLAGS)
	$(Q)$(FLEXT_INFRA_PYTHON) -m flext_infra basemk generate --project-name $(PROJECT_NAME) --output base.mk

setup-project: ## Recommended setup: activate env + generate files + internal sync
	$(Q)$(MAKE) activate
	$(Q)$(MAKE) tooling-sync
	$(Q)$(FLEXT_INFRA_PYTHON) -m flext_infra deps internal-sync --project-root "$(CURDIR)"
	$(Q)$(POETRY) lock
	$(Q)$(POETRY) install --all-extras --all-groups

precommit: ## Run all pre-commit hooks
	$(Q)$(POETRY) run pre-commit run --all-files

quick-check: ## Fast gates for local development loop
	$(Q)$(MAKE) check CHECK_GATES=lint,format,pyrefly,mypy,pyright

ci-fast: ## CI-style check without docs generation
	$(Q)$(MAKE) check

ci: ## Full CI-style check including docs
	$(Q)$(MAKE) check
	$(Q)$(MAKE) docs DOCS_PHASE=all

# Extended health check for contributors
doctor: ## Project health check
	$(Q)$(MAKE) diagnose
	$(Q)$(MAKE) validate
	$(Q)$(MAKE) test

deps-update: ## Refresh lockfile and dependency graph
	$(Q)$(POETRY) update
	$(Q)$(POETRY) lock

deps-show: ## Show dependency tree
	$(Q)$(POETRY) show --tree

validate-typings: ## Validate TypeAlias syntax rules in typings.py
	$(Q)bash scripts/validate_typings.sh

.DEFAULT_GOAL := help
