# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Flext core package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core import _constants, _models, _protocols, _typings, _utilities
    from flext_core.__version__ import (
        __all__,
        __author__,
        __author_email__,
        __description__,
        __license__,
        __title__,
        __url__,
        __version__,
        __version_info__,
    )
    from flext_core._constants import (
        FlextConstantsBase,
        FlextConstantsCqrs,
        FlextConstantsDomain,
        FlextConstantsInfrastructure,
        FlextConstantsMixins,
        FlextConstantsPlatform,
        FlextConstantsSettings,
        FlextConstantsValidation,
    )
    from flext_core._models import (
        FlextGenericModels,
        FlextModelFoundation,
        FlextModelsCollections,
        FlextModelsConfig,
        FlextModelsContainer,
        FlextModelsContainers,
        FlextModelsContext,
        FlextModelsCqrs,
        FlextModelsDecorators,
        FlextModelsDispatcher,
        FlextModelsDomainEvent,
        FlextModelsEntity,
        FlextModelsHandler,
        FlextModelsResult,
        FlextModelsService,
    )
    from flext_core._protocols import (
        FlextProtocolsBase,
        FlextProtocolsConfig,
        FlextProtocolsContainer,
        FlextProtocolsContext,
        FlextProtocolsHandler,
        FlextProtocolsLogging,
        FlextProtocolsRegistry,
        FlextProtocolsResult,
        FlextProtocolsService,
    )
    from flext_core._typings import (
        FlextTypesCore,
        FlextTypesServices,
        FlextTypesValidation,
        FlextTypingBase,
        FlextTypingContainers,
    )
    from flext_core._utilities import (
        FlextUtilitiesArgs,
        FlextUtilitiesCache,
        FlextUtilitiesChecker,
        FlextUtilitiesCollection,
        FlextUtilitiesConfiguration,
        FlextUtilitiesContext,
        FlextUtilitiesConversion,
        FlextUtilitiesDeprecation,
        FlextUtilitiesDiscovery,
        FlextUtilitiesDomain,
        FlextUtilitiesEnum,
        FlextUtilitiesFileOps,
        FlextUtilitiesGenerators,
        FlextUtilitiesGuards,
        FlextUtilitiesGuardsEnsure,
        FlextUtilitiesGuardsType,
        FlextUtilitiesGuardsTypeCore,
        FlextUtilitiesGuardsTypeModel,
        FlextUtilitiesGuardsTypeProtocol,
        FlextUtilitiesMapper,
        FlextUtilitiesModel,
        FlextUtilitiesPagination,
        FlextUtilitiesParser,
        FlextUtilitiesReliability,
        FlextUtilitiesResultHelpers,
        FlextUtilitiesText,
    )
    from flext_core.constants import FlextConstants, FlextConstants as c
    from flext_core.container import FlextContainer
    from flext_core.context import FlextContext
    from flext_core.decorators import FlextDecorators, FlextDecorators as d
    from flext_core.dispatcher import FlextDispatcher
    from flext_core.errors import ErrorDomain, FlextError
    from flext_core.exceptions import FlextExceptions, FlextExceptions as e, Metadata
    from flext_core.handlers import FlextHandlers, FlextHandlers as h
    from flext_core.loggings import FlextLogger
    from flext_core.mixins import FlextMixins, FlextMixins as x
    from flext_core.models import FlextModels, FlextModels as m
    from flext_core.protocols import FlextProtocols, FlextProtocols as p
    from flext_core.registry import FlextRegistry
    from flext_core.result import FlextResult, FlextResult as r
    from flext_core.runtime import FlextRuntime
    from flext_core.service import FlextService, FlextService as s
    from flext_core.settings import FlextSettings
    from flext_core.typings import (
        TV,
        BaseModel,
        EnumT,
        FlextTypes,
        FlextTypes as t,
        MessageT_contra,
        P,
        R,
        ResultT,
        T,
        T_co,
        T_contra,
        T_Model,
        T_Namespace,
        T_Settings,
        TRuntime,
        TV_co,
        U,
    )
    from flext_core.utilities import FlextUtilities, FlextUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "BaseModel": ("flext_core.typings", "BaseModel"),
    "EnumT": ("flext_core.typings", "EnumT"),
    "ErrorDomain": ("flext_core.errors", "ErrorDomain"),
    "FlextConstants": ("flext_core.constants", "FlextConstants"),
    "FlextConstantsBase": ("flext_core._constants", "FlextConstantsBase"),
    "FlextConstantsCqrs": ("flext_core._constants", "FlextConstantsCqrs"),
    "FlextConstantsDomain": ("flext_core._constants", "FlextConstantsDomain"),
    "FlextConstantsInfrastructure": (
        "flext_core._constants",
        "FlextConstantsInfrastructure",
    ),
    "FlextConstantsMixins": ("flext_core._constants", "FlextConstantsMixins"),
    "FlextConstantsPlatform": ("flext_core._constants", "FlextConstantsPlatform"),
    "FlextConstantsSettings": ("flext_core._constants", "FlextConstantsSettings"),
    "FlextConstantsValidation": ("flext_core._constants", "FlextConstantsValidation"),
    "FlextContainer": ("flext_core.container", "FlextContainer"),
    "FlextContext": ("flext_core.context", "FlextContext"),
    "FlextDecorators": ("flext_core.decorators", "FlextDecorators"),
    "FlextDispatcher": ("flext_core.dispatcher", "FlextDispatcher"),
    "FlextError": ("flext_core.errors", "FlextError"),
    "FlextExceptions": ("flext_core.exceptions", "FlextExceptions"),
    "FlextGenericModels": ("flext_core._models", "FlextGenericModels"),
    "FlextHandlers": ("flext_core.handlers", "FlextHandlers"),
    "FlextLogger": ("flext_core.loggings", "FlextLogger"),
    "FlextMixins": ("flext_core.mixins", "FlextMixins"),
    "FlextModelFoundation": ("flext_core._models", "FlextModelFoundation"),
    "FlextModels": ("flext_core.models", "FlextModels"),
    "FlextModelsCollections": ("flext_core._models", "FlextModelsCollections"),
    "FlextModelsConfig": ("flext_core._models", "FlextModelsConfig"),
    "FlextModelsContainer": ("flext_core._models", "FlextModelsContainer"),
    "FlextModelsContainers": ("flext_core._models", "FlextModelsContainers"),
    "FlextModelsContext": ("flext_core._models", "FlextModelsContext"),
    "FlextModelsCqrs": ("flext_core._models", "FlextModelsCqrs"),
    "FlextModelsDecorators": ("flext_core._models", "FlextModelsDecorators"),
    "FlextModelsDispatcher": ("flext_core._models", "FlextModelsDispatcher"),
    "FlextModelsDomainEvent": ("flext_core._models", "FlextModelsDomainEvent"),
    "FlextModelsEntity": ("flext_core._models", "FlextModelsEntity"),
    "FlextModelsHandler": ("flext_core._models", "FlextModelsHandler"),
    "FlextModelsResult": ("flext_core._models", "FlextModelsResult"),
    "FlextModelsService": ("flext_core._models", "FlextModelsService"),
    "FlextProtocols": ("flext_core.protocols", "FlextProtocols"),
    "FlextProtocolsBase": ("flext_core._protocols", "FlextProtocolsBase"),
    "FlextProtocolsConfig": ("flext_core._protocols", "FlextProtocolsConfig"),
    "FlextProtocolsContainer": ("flext_core._protocols", "FlextProtocolsContainer"),
    "FlextProtocolsContext": ("flext_core._protocols", "FlextProtocolsContext"),
    "FlextProtocolsHandler": ("flext_core._protocols", "FlextProtocolsHandler"),
    "FlextProtocolsLogging": ("flext_core._protocols", "FlextProtocolsLogging"),
    "FlextProtocolsRegistry": ("flext_core._protocols", "FlextProtocolsRegistry"),
    "FlextProtocolsResult": ("flext_core._protocols", "FlextProtocolsResult"),
    "FlextProtocolsService": ("flext_core._protocols", "FlextProtocolsService"),
    "FlextRegistry": ("flext_core.registry", "FlextRegistry"),
    "FlextResult": ("flext_core.result", "FlextResult"),
    "FlextRuntime": ("flext_core.runtime", "FlextRuntime"),
    "FlextService": ("flext_core.service", "FlextService"),
    "FlextSettings": ("flext_core.settings", "FlextSettings"),
    "FlextTypes": ("flext_core.typings", "FlextTypes"),
    "FlextTypesCore": ("flext_core._typings", "FlextTypesCore"),
    "FlextTypesServices": ("flext_core._typings", "FlextTypesServices"),
    "FlextTypesValidation": ("flext_core._typings", "FlextTypesValidation"),
    "FlextTypingBase": ("flext_core._typings", "FlextTypingBase"),
    "FlextTypingContainers": ("flext_core._typings", "FlextTypingContainers"),
    "FlextUtilities": ("flext_core.utilities", "FlextUtilities"),
    "FlextUtilitiesArgs": ("flext_core._utilities", "FlextUtilitiesArgs"),
    "FlextUtilitiesCache": ("flext_core._utilities", "FlextUtilitiesCache"),
    "FlextUtilitiesChecker": ("flext_core._utilities", "FlextUtilitiesChecker"),
    "FlextUtilitiesCollection": ("flext_core._utilities", "FlextUtilitiesCollection"),
    "FlextUtilitiesConfiguration": (
        "flext_core._utilities",
        "FlextUtilitiesConfiguration",
    ),
    "FlextUtilitiesContext": ("flext_core._utilities", "FlextUtilitiesContext"),
    "FlextUtilitiesConversion": ("flext_core._utilities", "FlextUtilitiesConversion"),
    "FlextUtilitiesDeprecation": ("flext_core._utilities", "FlextUtilitiesDeprecation"),
    "FlextUtilitiesDiscovery": ("flext_core._utilities", "FlextUtilitiesDiscovery"),
    "FlextUtilitiesDomain": ("flext_core._utilities", "FlextUtilitiesDomain"),
    "FlextUtilitiesEnum": ("flext_core._utilities", "FlextUtilitiesEnum"),
    "FlextUtilitiesFileOps": ("flext_core._utilities", "FlextUtilitiesFileOps"),
    "FlextUtilitiesGenerators": ("flext_core._utilities", "FlextUtilitiesGenerators"),
    "FlextUtilitiesGuards": ("flext_core._utilities", "FlextUtilitiesGuards"),
    "FlextUtilitiesGuardsEnsure": (
        "flext_core._utilities",
        "FlextUtilitiesGuardsEnsure",
    ),
    "FlextUtilitiesGuardsType": ("flext_core._utilities", "FlextUtilitiesGuardsType"),
    "FlextUtilitiesGuardsTypeCore": (
        "flext_core._utilities",
        "FlextUtilitiesGuardsTypeCore",
    ),
    "FlextUtilitiesGuardsTypeModel": (
        "flext_core._utilities",
        "FlextUtilitiesGuardsTypeModel",
    ),
    "FlextUtilitiesGuardsTypeProtocol": (
        "flext_core._utilities",
        "FlextUtilitiesGuardsTypeProtocol",
    ),
    "FlextUtilitiesMapper": ("flext_core._utilities", "FlextUtilitiesMapper"),
    "FlextUtilitiesModel": ("flext_core._utilities", "FlextUtilitiesModel"),
    "FlextUtilitiesPagination": ("flext_core._utilities", "FlextUtilitiesPagination"),
    "FlextUtilitiesParser": ("flext_core._utilities", "FlextUtilitiesParser"),
    "FlextUtilitiesReliability": ("flext_core._utilities", "FlextUtilitiesReliability"),
    "FlextUtilitiesResultHelpers": (
        "flext_core._utilities",
        "FlextUtilitiesResultHelpers",
    ),
    "FlextUtilitiesText": ("flext_core._utilities", "FlextUtilitiesText"),
    "MessageT_contra": ("flext_core.typings", "MessageT_contra"),
    "Metadata": ("flext_core.exceptions", "Metadata"),
    "P": ("flext_core.typings", "P"),
    "R": ("flext_core.typings", "R"),
    "ResultT": ("flext_core.typings", "ResultT"),
    "T": ("flext_core.typings", "T"),
    "TRuntime": ("flext_core.typings", "TRuntime"),
    "TV": ("flext_core.typings", "TV"),
    "TV_co": ("flext_core.typings", "TV_co"),
    "T_Model": ("flext_core.typings", "T_Model"),
    "T_Namespace": ("flext_core.typings", "T_Namespace"),
    "T_Settings": ("flext_core.typings", "T_Settings"),
    "T_co": ("flext_core.typings", "T_co"),
    "T_contra": ("flext_core.typings", "T_contra"),
    "U": ("flext_core.typings", "U"),
    "__all__": ("flext_core.__version__", "__all__"),
    "__author__": ("flext_core.__version__", "__author__"),
    "__author_email__": ("flext_core.__version__", "__author_email__"),
    "__description__": ("flext_core.__version__", "__description__"),
    "__license__": ("flext_core.__version__", "__license__"),
    "__title__": ("flext_core.__version__", "__title__"),
    "__url__": ("flext_core.__version__", "__url__"),
    "__version__": ("flext_core.__version__", "__version__"),
    "__version_info__": ("flext_core.__version__", "__version_info__"),
    "_constants": ("flext_core._constants", ""),
    "_models": ("flext_core._models", ""),
    "_protocols": ("flext_core._protocols", ""),
    "_typings": ("flext_core._typings", ""),
    "_utilities": ("flext_core._utilities", ""),
    "c": ("flext_core.constants", "FlextConstants"),
    "d": ("flext_core.decorators", "FlextDecorators"),
    "e": ("flext_core.exceptions", "FlextExceptions"),
    "h": ("flext_core.handlers", "FlextHandlers"),
    "m": ("flext_core.models", "FlextModels"),
    "p": ("flext_core.protocols", "FlextProtocols"),
    "r": ("flext_core.result", "FlextResult"),
    "s": ("flext_core.service", "FlextService"),
    "t": ("flext_core.typings", "FlextTypes"),
    "u": ("flext_core.utilities", "FlextUtilities"),
    "x": ("flext_core.mixins", "FlextMixins"),
}

__all__ = [
    "TV",
    "BaseModel",
    "EnumT",
    "ErrorDomain",
    "FlextConstants",
    "FlextConstantsBase",
    "FlextConstantsCqrs",
    "FlextConstantsDomain",
    "FlextConstantsInfrastructure",
    "FlextConstantsMixins",
    "FlextConstantsPlatform",
    "FlextConstantsSettings",
    "FlextConstantsValidation",
    "FlextContainer",
    "FlextContext",
    "FlextDecorators",
    "FlextDispatcher",
    "FlextError",
    "FlextExceptions",
    "FlextGenericModels",
    "FlextHandlers",
    "FlextLogger",
    "FlextMixins",
    "FlextModelFoundation",
    "FlextModels",
    "FlextModelsCollections",
    "FlextModelsConfig",
    "FlextModelsContainer",
    "FlextModelsContainers",
    "FlextModelsContext",
    "FlextModelsCqrs",
    "FlextModelsDecorators",
    "FlextModelsDispatcher",
    "FlextModelsDomainEvent",
    "FlextModelsEntity",
    "FlextModelsHandler",
    "FlextModelsResult",
    "FlextModelsService",
    "FlextProtocols",
    "FlextProtocolsBase",
    "FlextProtocolsConfig",
    "FlextProtocolsContainer",
    "FlextProtocolsContext",
    "FlextProtocolsHandler",
    "FlextProtocolsLogging",
    "FlextProtocolsRegistry",
    "FlextProtocolsResult",
    "FlextProtocolsService",
    "FlextRegistry",
    "FlextResult",
    "FlextRuntime",
    "FlextService",
    "FlextSettings",
    "FlextTypes",
    "FlextTypesCore",
    "FlextTypesServices",
    "FlextTypesValidation",
    "FlextTypingBase",
    "FlextTypingContainers",
    "FlextUtilities",
    "FlextUtilitiesArgs",
    "FlextUtilitiesCache",
    "FlextUtilitiesChecker",
    "FlextUtilitiesCollection",
    "FlextUtilitiesConfiguration",
    "FlextUtilitiesContext",
    "FlextUtilitiesConversion",
    "FlextUtilitiesDeprecation",
    "FlextUtilitiesDiscovery",
    "FlextUtilitiesDomain",
    "FlextUtilitiesEnum",
    "FlextUtilitiesFileOps",
    "FlextUtilitiesGenerators",
    "FlextUtilitiesGuards",
    "FlextUtilitiesGuardsEnsure",
    "FlextUtilitiesGuardsType",
    "FlextUtilitiesGuardsTypeCore",
    "FlextUtilitiesGuardsTypeModel",
    "FlextUtilitiesGuardsTypeProtocol",
    "FlextUtilitiesMapper",
    "FlextUtilitiesModel",
    "FlextUtilitiesPagination",
    "FlextUtilitiesParser",
    "FlextUtilitiesReliability",
    "FlextUtilitiesResultHelpers",
    "FlextUtilitiesText",
    "MessageT_contra",
    "Metadata",
    "P",
    "R",
    "ResultT",
    "T",
    "TRuntime",
    "TV_co",
    "T_Model",
    "T_Namespace",
    "T_Settings",
    "T_co",
    "T_contra",
    "U",
    "__all__",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "_constants",
    "_models",
    "_protocols",
    "_typings",
    "_utilities",
    "c",
    "d",
    "e",
    "h",
    "m",
    "p",
    "r",
    "s",
    "t",
    "u",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
