from collections.abc import Callable

class LazyAttribute:
    def __init__(self, func: Callable[[object], object]) -> None: ...

class LazyFunction:
    def __init__(self, func: Callable[[], object]) -> None: ...

class Sequence:
    def __init__(self, func: Callable[[int], object]) -> None: ...

class Faker:
    def __init__(self, provider: str, **kwargs: object) -> None: ...

class Factory:
    class Meta:
        model: type[object]

    @classmethod
    def create(cls, **kwargs: object) -> object: ...
    @classmethod
    def create_batch(cls, size: int, **kwargs: object) -> list[object]: ...
    @classmethod
    def build(cls, **kwargs: object) -> object: ...
    @classmethod
    def build_batch(cls, size: int, **kwargs: object) -> list[object]: ...
