class Factory:
    class Meta:
        model: type[object]

    @classmethod
    def create(cls, **kwargs: object) -> object: ...
    @classmethod
    def create_batch(cls, size: int, **kwargs: object) -> list[object]: ...
    @classmethod
    def build(cls, **kwargs: object) -> object: ...
    @classmethod
    def build_batch(cls, size: int, **kwargs: object) -> list[object]: ...
