# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Tests package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

if _t.TYPE_CHECKING:
    import tests.base as _tests_base

    base = _tests_base
    import tests.benchmark as _tests_benchmark
    from tests.base import TestsFlextServiceBase

    benchmark = _tests_benchmark
    import tests.conftest as _tests_conftest
    from tests.benchmark import (
        TestContainerMemory,
        TestContainerPerformance,
        TestPerformanceBenchmarks,
        get_memory_usage,
        test_container_memory,
        test_container_performance,
        test_refactor_nesting_performance,
    )

    conftest = _tests_conftest
    import tests.constants as _tests_constants
    from tests.conftest import (
        FunctionalExternalService,
        assert_rejects,
        assert_validates,
        clean_container,
        empty_strings,
        flext_result_failure,
        flext_result_success,
        invalid_hostnames,
        invalid_port_numbers,
        invalid_uris,
        mock_external_service,
        out_of_range,
        parser_scenarios,
        reliability_scenarios,
        reset_global_container,
        sample_data,
        temp_dir,
        temp_directory,
        temp_file,
        test_context,
        valid_hostnames,
        valid_port_numbers,
        valid_ranges,
        valid_strings,
        valid_uris,
        validation_scenarios,
        whitespace_strings,
    )

    constants = _tests_constants
    import tests.helpers as _tests_helpers
    from tests.constants import FlextCoreTestConstants, FlextCoreTestConstants as c
    from tests.fixtures.namespace_validator import (
        DEFAULT_TIMEOUT,
        MAX_RETRIES,
        MAX_VALUE,
        FlextTestConstants,
        FlextTestModels,
        FlextTestTypes,
        FlextTestUtilities,
        LooseTypeAlias,
        RandomConstants,
        Rule0LooseItemsFixture,
        Rule0MultipleClassesFixture,
        Rule1LooseEnumFixture,
        Status,
        helper,
    )

    helpers = _tests_helpers
    import tests.integration as _tests_integration
    from tests.helpers import (
        FailingService,
        FailingServiceAuto,
        FailingServiceAutoFactory,
        FailingServiceFactory,
        GenericModelFactory,
        GetUserService,
        GetUserServiceAuto,
        GetUserServiceAutoFactory,
        GetUserServiceFactory,
        ParserScenario,
        ParserScenarios,
        ReliabilityScenario,
        ReliabilityScenarios,
        ServiceFactoryRegistry,
        ServiceTestCaseFactory,
        ServiceTestCases,
        TestDataGenerators,
        TestHelperFactories,
        TestHelperScenarios,
        UserFactory,
        ValidatingService,
        ValidatingServiceAuto,
        ValidatingServiceAutoFactory,
        ValidatingServiceFactory,
        ValidationScenario,
        ValidationScenarios,
        factories,
        factories_impl,
        reset_all_factories,
        scenarios,
    )

    integration = _tests_integration
    import tests.integration.patterns as _tests_integration_patterns
    from tests.integration import (
        TestAutomatedArchitecture,
        TestCompleteFlextSystemIntegration,
        TestFlextSettingsSingletonIntegration,
        TestIdempotency,
        TestInfraIntegration,
        TestLibraryIntegration,
        TestMigrationValidation,
        TestProjectLevelRefactor,
        TestRefactorPolicyMRO,
        TestService,
        TestWorkspaceLevelRefactor,
        test_architecture,
        test_class_nesting_refactor_single_file_end_to_end,
        test_config_integration,
        test_infra_integration,
        test_integration,
        test_migration_validation,
        test_refactor_nesting_file,
        test_refactor_nesting_idempotency,
        test_refactor_nesting_project,
        test_refactor_nesting_workspace,
        test_refactor_policy_mro,
        test_service,
        test_system,
    )

    patterns = _tests_integration_patterns
    import tests.models as _tests_models
    from tests.integration.patterns import (
        EXPECTED_BULK_SIZE,
        P,
        R,
        TestAdvancedPatterns,
        TestArchitecturalPatterns,
        TestFunction,
        TestPatternsCommands,
        TestPatternsLogging,
        TestPatternsTesting,
        test_advanced_patterns,
        test_architectural_patterns,
        test_patterns_commands,
        test_patterns_logging,
        test_patterns_testing,
    )

    models = _tests_models
    import tests.protocols as _tests_protocols
    from tests.models import FlextCoreTestModels, FlextCoreTestModels as m

    protocols = _tests_protocols
    import tests.test_documented_patterns as _tests_test_documented_patterns
    from tests.protocols import FlextCoreTestProtocols, FlextCoreTestProtocols as p

    test_documented_patterns = _tests_test_documented_patterns
    import tests.test_service_result_property as _tests_test_service_result_property
    from tests.test_documented_patterns import TestDocumentedPatterns

    test_service_result_property = _tests_test_service_result_property
    import tests.test_utils as _tests_test_utils
    from tests.test_service_result_property import TestServiceResultProperty

    test_utils = _tests_test_utils
    import tests.typings as _tests_typings
    from tests.test_utils import (
        FlextTestResult,
        FlextTestResultCo,
        TestUtils,
        assertion_helpers,
        fixture_factory,
        test_data_factory,
    )

    typings = _tests_typings
    import tests.unit as _tests_unit
    from tests.typings import (
        FlextCoreTestTypes,
        FlextCoreTestTypes as t,
        T,
        T_co,
        T_contra,
    )

    unit = _tests_unit
    import tests.unit.contracts as _tests_unit_contracts
    from tests.unit import (
        NORMALIZE_COMPONENT_SCENARIOS,
        AttrObject,
        BadBool,
        BadConfigForTest,
        BadMapping,
        BadString,
        CacheTestModel,
        ComplexModel,
        ConfigModelForTest,
        ExplodingLenList,
        FlextUnitTestProtocols,
        InputPayloadMap,
        InvalidModelForTest,
        NestedModel,
        NormalizeComponentScenario,
        RuntimeCloneService,
        SampleModel,
        SimpleObj,
        SingletonClassForTest,
        TestAllLayerIntegration,
        TestBaseModelCoverage,
        TestCaseMap,
        TestCheckExtraPolicy,
        TestCheckFieldDescriptions,
        TestCheckNoAny,
        TestCheckNoBareCollections,
        TestCheckNoV1Patterns,
        TestCollectionUtilitiesCoverage,
        TestConstantsEnforcement,
        TestContainerFullCoverage,
        TestContext100Coverage,
        TestCoverageContext,
        TestCoverageExceptions,
        TestCoverageLoggings,
        TestCoverageModels,
        TestDecoratorsDiscoveryFullCoverage,
        TestDecoratorsFullCoverage,
        TestDeprecationWarnings,
        TestDIIncremental,
        TestDiServicesAccess,
        TestDispatcherDI,
        TestDispatcherFullCoverage,
        TestDispatcherMinimal,
        TestDispatcherTimeoutCoverage100,
        Teste,
        TestEnforcementMode,
        TestEntityCoverageEdgeCases,
        TestEnumUtilitiesCoverage,
        TestExceptionsHypothesis,
        TestExemptions,
        TestFlextConstants,
        TestFlextContainer,
        TestFlextContext,
        TestFlextDecorators,
        TestFlextHandlers,
        TestFlextInfraNamespaceValidator,
        TestFlextMixinsNestedClasses,
        TestFlextModelsCollectionsCoverage100,
        TestFlextModelsContainer,
        TestFlextProtocols,
        TestFlextRegistry,
        TestFlextRuntime,
        TestFlextSettings,
        TestFlextSettingsCoverage,
        TestFlextTypes,
        TestFlextUtilitiesArgs,
        TestFlextUtilitiesConfiguration,
        TestFlextUtilitiesReliability,
        TestFlextVersion,
        TestHandlerDecoratorDiscovery,
        TestHandlersFullCoverage,
        TestHelperConsolidationTransformer,
        TestLoggingsErrorPaths,
        TestLoggingsStrictReturns,
        TestMixinsFullCoverage,
        TestModels,
        TestModelsBaseFullCoverage,
        TestModule,
        TestProtocolsEnforcement,
        Testr,
        TestrCoverage,
        TestResultExceptionCarrying,
        TestRuntimeCoverage100,
        TestsCore,
        TestService100Coverage,
        TestServiceBootstrap,
        TestServiceInternals,
        TestTypesEnforcement,
        TestTypingsFullCoverage,
        Testu,
        TestuCacheLogger,
        TestuCacheNormalizeComponent,
        TestuDomain,
        TestuMapperAccessors,
        TestuMapperAdvanced,
        TestuMapperConversions,
        TestuMapperExtract,
        TestuMapperUtils,
        TestUtilitiesCollectionCoverage,
        TestUtilitiesCollectionFullCoverage,
        TestUtilitiesConfigurationFullCoverage,
        TestUtilitiesContextFullCoverage,
        TestUtilitiesCoverage,
        TestUtilitiesDataMapper,
        TestUtilitiesDomainFullCoverage,
        TestUtilitiesEnforcement,
        TestUtilitiesGeneratorsFullCoverage,
        TestUtilitiesParserFullCoverage,
        TestUtilitiesTextFullCoverage,
        TestUtilitiesTypeGuardsCoverage100,
        TestuTypeChecker,
        TMessage,
        UtilitiesCacheCoverage100Namespace,
        UtilitiesMapperCoverage100Namespace,
        _BadCopyModel,
        _BrokenDumpModel,
        _Cfg,
        _DumpErrorModel,
        _ErrorsModel,
        _FakeConfig,
        _FrozenEntity,
        _GoodModel,
        _Model,
        _MsgWithCommandId,
        _MsgWithMessageId,
        _Opts,
        _PlainErrorModel,
        _SampleEntity,
        _SvcModel,
        _TargetModel,
        _ValidationLikeError,
        conftest_infra,
        create_compare_entities_cases,
        create_compare_value_objects_cases,
        create_hash_entity_cases,
        create_hash_value_object_cases,
        infra_git,
        infra_git_repo,
        infra_io,
        infra_path,
        infra_patterns,
        infra_reporting,
        infra_safe_command_output,
        infra_selection,
        infra_subprocess,
        infra_templates,
        infra_test_workspace,
        infra_toml,
        inject,
        mapper,
        pytestmark,
        reset_runtime_state,
        runtime_module,
        test_aliases_are_available,
        test_args_coverage_100,
        test_async_log_writer_paths,
        test_async_log_writer_shutdown_with_full_queue,
        test_bad_string_and_bad_bool_raise_value_error,
        test_canonical_aliases_are_available,
        test_centralize_pydantic_cli_outputs_extended_metrics,
        test_chk_exercises_missed_branches,
        test_circuit_breaker_half_open_and_rate_limiter_accessors,
        test_circuit_breaker_transitions_and_metrics,
        test_class_nesting_appends_to_existing_namespace_and_removes_pass,
        test_class_nesting_keeps_unmapped_top_level_classes,
        test_class_nesting_moves_top_level_class_into_new_namespace,
        test_clear_keys_values_items_and_validate_branches,
        test_collection_utilities_coverage_100,
        test_collections_coverage_100,
        test_command_pagination_limit,
        test_config,
        test_config_bridge_and_trace_context_and_http_validation,
        test_configuration_mapping_and_dict_negative_branches,
        test_configure_structlog_async_logging_uses_print_logger_factory,
        test_configure_structlog_edge_paths,
        test_configure_structlog_print_logger_factory_fallback,
        test_constants_new,
        test_container,
        test_container_and_service_domain_paths,
        test_container_full_coverage,
        test_context_coverage_100,
        test_context_data_metadata_normalizer_removed,
        test_context_data_normalize_and_json_checks,
        test_context_data_validate_dict_serializable_error_paths,
        test_context_data_validate_dict_serializable_none_and_mapping,
        test_context_data_validate_dict_serializable_real_dicts,
        test_context_export_serializable_and_validators,
        test_context_export_statistics_validator_and_computed_fields,
        test_context_export_validate_dict_serializable_mapping_and_models,
        test_context_export_validate_dict_serializable_valid,
        test_context_full_coverage,
        test_conversion_add_converted_and_error_metadata_append_paths,
        test_conversion_add_skipped_skip_reason_upsert_paths,
        test_conversion_add_warning_metadata_append_paths,
        test_conversion_start_and_complete_methods,
        test_coverage_context,
        test_coverage_exceptions,
        test_coverage_loggings,
        test_coverage_models,
        test_coverage_utilities,
        test_cqrs_query_resolve_deeper_and_int_pagination,
        test_create_auto_discover_and_mode_mapping,
        test_create_from_callable_and_repr,
        test_create_merges_metadata_dict_branch,
        test_create_overloads_and_auto_correlation,
        test_decorators,
        test_decorators_discovery_full_coverage,
        test_decorators_family_blocks_dispatcher_target,
        test_decorators_full_coverage,
        test_dependency_integration_and_wiring_paths,
        test_dependency_registration_duplicate_guards,
        test_deprecation_warnings,
        test_di_incremental,
        test_di_services_access,
        test_discover_project_roots_without_nested_git_dirs,
        test_dispatcher_di,
        test_dispatcher_family_blocks_models_target,
        test_dispatcher_full_coverage,
        test_dispatcher_minimal,
        test_dispatcher_reliability,
        test_dispatcher_timeout_coverage_100,
        test_enforcement,
        test_ensure_trace_context_dict_conversion_paths,
        test_entity_comparable_map_and_bulk_validation_paths,
        test_entity_coverage,
        test_enum_utilities_coverage_100,
        test_exceptions,
        test_execute_and_register_handler_failure_paths,
        test_export_paths_with_metadata_and_statistics,
        test_extract_array_index_helpers,
        test_extract_error_paths_and_prop_accessor,
        test_flext_message_type_alias_adapter,
        test_flow_through_short_circuits_on_failure,
        test_from_validation_and_to_model_paths,
        test_get_logger_auto_configures_structlog,
        test_get_logger_none_name_paths,
        test_get_plugin_and_register_metadata_and_list_items_exception,
        test_guard_in_has_empty_none_helpers,
        test_guard_instance_attribute_access_warnings,
        test_guards_bool_identity_branch_via_isinstance_fallback,
        test_guards_bool_shortcut_and_issubclass_typeerror,
        test_guards_handler_type_issubclass_typeerror_branch_direct,
        test_guards_issubclass_success_when_callable_is_patched,
        test_guards_issubclass_typeerror_when_class_not_treated_as_callable,
        test_handler_builder_fluent_methods,
        test_handler_decorator_discovery,
        test_handlers,
        test_handlers_full_coverage,
        test_helper_consolidation_is_prechecked,
        test_inactive_and_none_value_paths,
        test_init_fallback_and_lazy_returns_result_property,
        test_is_container_negative_paths_and_callable,
        test_is_type_non_empty_unknown_and_tuple_and_fallback,
        test_is_type_protocol_fallback_branches,
        test_is_valid_handles_validation_exception,
        test_lash_runtime_result_paths,
        test_loggings_error_paths_coverage,
        test_loggings_full_coverage,
        test_loggings_strict_returns,
        test_map_error_identity_and_transform,
        test_map_flat_map_and_then_paths,
        test_migrate_protocols_rewrites_references_with_p_alias,
        test_migrate_to_mro_inlines_alias_constant_into_constants_class,
        test_migrate_to_mro_moves_constant_and_rewrites_reference,
        test_migrate_to_mro_moves_manual_uppercase_assignment,
        test_migrate_to_mro_normalizes_facade_alias_to_c,
        test_migrate_to_mro_rejects_unknown_target,
        test_migrate_typings_rewrites_references_with_t_alias,
        test_mixins,
        test_mixins_full_coverage,
        test_model_helpers_remaining_paths,
        test_model_support_and_hash_compare_paths,
        test_models,
        test_models_base_full_coverage,
        test_models_container,
        test_models_context_full_coverage,
        test_models_cqrs_full_coverage,
        test_models_entity_full_coverage,
        test_models_family_blocks_utilities_target,
        test_models_generic_full_coverage,
        test_namespace_enforce_cli_fails_on_manual_protocol_violation,
        test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring,
        test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future,
        test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file,
        test_namespace_enforcer_creates_missing_facades_and_rewrites_imports,
        test_namespace_enforcer_detects_cyclic_imports_in_tests_directory,
        test_namespace_enforcer_detects_internal_private_imports,
        test_namespace_enforcer_detects_manual_protocol_outside_canonical_files,
        test_namespace_enforcer_detects_manual_typings_and_compat_aliases,
        test_namespace_enforcer_detects_missing_runtime_alias_outside_src,
        test_namespace_enforcer_does_not_rewrite_indented_import_aliases,
        test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks,
        test_namespace_validator,
        test_narrow_contextvar_exception_branch,
        test_narrow_contextvar_invalid_inputs,
        test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage,
        test_nested_class_propagation_updates_import_annotations_and_calls,
        test_non_empty_and_normalize_branches,
        test_normalization_edge_branches,
        test_normalize_to_container_alias_removal_path,
        test_normalize_to_metadata_alias_removal_path,
        test_ok_accepts_none,
        test_operation_progress_start_operation_sets_runtime_fields,
        test_protocol_and_simple_guard_helpers,
        test_protocols_new,
        test_query_resolve_pagination_wrapper_and_fallback,
        test_query_validate_pagination_dict_and_default,
        test_rate_limiter_blocks_then_recovers,
        test_rate_limiter_jitter_application,
        test_reconfigure_and_reset_state_paths,
        test_recover_tap_and_tap_error_paths,
        test_refactor_cli_models_workflow,
        test_refactor_migrate_to_class_mro,
        test_refactor_namespace_enforcer,
        test_refactor_policy_family_rules,
        test_refactor_utilities_iter_python_files_includes_examples_and_scripts,
        test_registry,
        test_registry_full_coverage,
        test_result,
        test_result_additional,
        test_result_coverage_100,
        test_result_exception_carrying,
        test_result_full_coverage,
        test_result_property_raises_on_failure,
        test_reuse_existing_runtime_coverage_branches,
        test_reuse_existing_runtime_scenarios,
        test_runtime,
        test_runtime_coverage_100,
        test_runtime_create_instance_failure_branch,
        test_runtime_family_blocks_non_runtime_target,
        test_runtime_full_coverage,
        test_runtime_integration_tracking_paths,
        test_runtime_misc_remaining_paths,
        test_runtime_module_accessors_and_metadata,
        test_runtime_result_alias_compatibility,
        test_runtime_result_all_missed_branches,
        test_runtime_result_remaining_paths,
        test_scope_data_validators_and_errors,
        test_service_additional,
        test_service_bootstrap,
        test_service_coverage_100,
        test_set_set_all_get_validation_and_error_paths,
        test_settings_coverage,
        test_statistics_and_custom_fields_validators,
        test_structlog_proxy_context_var_default_when_key_missing,
        test_structlog_proxy_context_var_get_set_reset_paths,
        test_summary_error_paths_and_bindings_failures,
        test_summary_properties_and_subclass_storage_reset,
        test_to_general_value_dict_removed,
        test_transformer_class_nesting,
        test_transformer_helper_consolidation,
        test_transformer_nested_class_propagation,
        test_type_guards_result,
        test_typings_full_coverage,
        test_typings_new,
        test_ultrawork_models_cli_runs_dry_run_copy,
        test_update_statistics_remove_hook_and_clone_false_result,
        test_utilities,
        test_utilities_cache_coverage_100,
        test_utilities_collection_coverage_100,
        test_utilities_collection_full_coverage,
        test_utilities_configuration_coverage_100,
        test_utilities_configuration_full_coverage,
        test_utilities_context_full_coverage,
        test_utilities_coverage,
        test_utilities_data_mapper,
        test_utilities_domain,
        test_utilities_domain_full_coverage,
        test_utilities_enum_full_coverage,
        test_utilities_family_allows_utilities_target,
        test_utilities_generators_full_coverage,
        test_utilities_guards_full_coverage,
        test_utilities_mapper_coverage_100,
        test_utilities_mapper_full_coverage,
        test_utilities_parser_full_coverage,
        test_utilities_reliability,
        test_utilities_text_full_coverage,
        test_utilities_type_checker_coverage_100,
        test_utilities_type_guards_coverage_100,
        test_validation_like_error_structure,
        test_version,
        test_with_resource_cleanup_runs,
    )
    from tests.unit._models import (
        TestFlextModelsBase,
        TestFlextModelsCqrs,
        TestFlextModelsEntity,
        TestFlextModelsExceptionParams,
        test_base,
        test_cqrs,
        test_entity,
        test_exception_params,
    )
    from tests.unit._utilities import (
        TestFlextUtilitiesGuards,
        TestFlextUtilitiesMapper,
        test_guards,
        test_mapper,
    )

    contracts = _tests_unit_contracts
    import tests.unit.flext_tests as _tests_unit_flext_tests
    from tests.unit.contracts import TextUtilityContract, text_contract

    flext_tests = _tests_unit_flext_tests
    import tests.utilities as _tests_utilities
    from tests.unit.flext_tests import (
        TestDocker,
        TestFlextTestsDomains,
        TestFlextTestsFiles,
        TestFlextTestsMatchers,
        TestUtilities,
        test_docker,
        test_domains,
        test_files,
        test_matchers,
    )

    utilities = _tests_utilities
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s
    from tests.utilities import FlextCoreTestUtilities, FlextCoreTestUtilities as u
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "tests.benchmark",
        "tests.helpers",
        "tests.integration",
        "tests.unit",
    ),
    {
        "DEFAULT_TIMEOUT": "tests.fixtures.namespace_validator.rule1_loose_constant",
        "FlextCoreTestConstants": "tests.constants",
        "FlextCoreTestModels": "tests.models",
        "FlextCoreTestProtocols": "tests.protocols",
        "FlextCoreTestTypes": "tests.typings",
        "FlextCoreTestUtilities": "tests.utilities",
        "FlextTestConstants": "tests.fixtures.namespace_validator.rule0_multiple_classes",
        "FlextTestModels": "tests.fixtures.namespace_validator.rule1_loose_enum",
        "FlextTestResult": "tests.test_utils",
        "FlextTestResultCo": "tests.test_utils",
        "FlextTestTypes": "tests.fixtures.namespace_validator.rule2_protocol_in_types",
        "FlextTestUtilities": "tests.fixtures.namespace_validator.rule1_magic_number",
        "FunctionalExternalService": "tests.conftest",
        "LooseTypeAlias": "tests.fixtures.namespace_validator.typings",
        "MAX_RETRIES": "tests.fixtures.namespace_validator.rule1_loose_constant",
        "MAX_VALUE": "tests.fixtures.namespace_validator.rule0_no_class",
        "RandomConstants": "tests.fixtures.namespace_validator.rule0_wrong_prefix",
        "Rule0LooseItemsFixture": "tests.fixtures.namespace_validator.rule0_loose_items",
        "Rule0MultipleClassesFixture": "tests.fixtures.namespace_validator.rule0_multiple_classes",
        "Rule1LooseEnumFixture": "tests.fixtures.namespace_validator.rule1_loose_enum",
        "Status": "tests.fixtures.namespace_validator.rule1_loose_enum",
        "T": "tests.typings",
        "T_co": "tests.typings",
        "T_contra": "tests.typings",
        "TestDocumentedPatterns": "tests.test_documented_patterns",
        "TestServiceResultProperty": "tests.test_service_result_property",
        "TestUtils": "tests.test_utils",
        "TestsFlextServiceBase": "tests.base",
        "assert_rejects": "tests.conftest",
        "assert_validates": "tests.conftest",
        "assertion_helpers": "tests.test_utils",
        "base": "tests.base",
        "benchmark": "tests.benchmark",
        "c": ("tests.constants", "FlextCoreTestConstants"),
        "clean_container": "tests.conftest",
        "conftest": "tests.conftest",
        "constants": "tests.constants",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "empty_strings": "tests.conftest",
        "fixture_factory": "tests.test_utils",
        "flext_result_failure": "tests.conftest",
        "flext_result_success": "tests.conftest",
        "h": ("flext_core.handlers", "FlextHandlers"),
        "helper": "tests.fixtures.namespace_validator.rule0_no_class",
        "helpers": "tests.helpers",
        "integration": "tests.integration",
        "invalid_hostnames": "tests.conftest",
        "invalid_port_numbers": "tests.conftest",
        "invalid_uris": "tests.conftest",
        "m": ("tests.models", "FlextCoreTestModels"),
        "mock_external_service": "tests.conftest",
        "models": "tests.models",
        "out_of_range": "tests.conftest",
        "p": ("tests.protocols", "FlextCoreTestProtocols"),
        "parser_scenarios": "tests.conftest",
        "protocols": "tests.protocols",
        "r": ("flext_core.result", "FlextResult"),
        "reliability_scenarios": "tests.conftest",
        "reset_global_container": "tests.conftest",
        "s": ("flext_core.service", "FlextService"),
        "sample_data": "tests.conftest",
        "t": ("tests.typings", "FlextCoreTestTypes"),
        "temp_dir": "tests.conftest",
        "temp_directory": "tests.conftest",
        "temp_file": "tests.conftest",
        "test_context": "tests.conftest",
        "test_data_factory": "tests.test_utils",
        "test_documented_patterns": "tests.test_documented_patterns",
        "test_service_result_property": "tests.test_service_result_property",
        "test_utils": "tests.test_utils",
        "typings": "tests.typings",
        "u": ("tests.utilities", "FlextCoreTestUtilities"),
        "unit": "tests.unit",
        "utilities": "tests.utilities",
        "valid_hostnames": "tests.conftest",
        "valid_port_numbers": "tests.conftest",
        "valid_ranges": "tests.conftest",
        "valid_strings": "tests.conftest",
        "valid_uris": "tests.conftest",
        "validation_scenarios": "tests.conftest",
        "whitespace_strings": "tests.conftest",
        "x": ("flext_core.mixins", "FlextMixins"),
    },
)

__all__ = [
    "DEFAULT_TIMEOUT",
    "EXPECTED_BULK_SIZE",
    "MAX_RETRIES",
    "MAX_VALUE",
    "NORMALIZE_COMPONENT_SCENARIOS",
    "AttrObject",
    "BadBool",
    "BadConfigForTest",
    "BadMapping",
    "BadString",
    "CacheTestModel",
    "ComplexModel",
    "ConfigModelForTest",
    "ExplodingLenList",
    "FailingService",
    "FailingServiceAuto",
    "FailingServiceAutoFactory",
    "FailingServiceFactory",
    "FlextCoreTestConstants",
    "FlextCoreTestModels",
    "FlextCoreTestProtocols",
    "FlextCoreTestTypes",
    "FlextCoreTestUtilities",
    "FlextTestConstants",
    "FlextTestModels",
    "FlextTestResult",
    "FlextTestResultCo",
    "FlextTestTypes",
    "FlextTestUtilities",
    "FlextUnitTestProtocols",
    "FunctionalExternalService",
    "GenericModelFactory",
    "GetUserService",
    "GetUserServiceAuto",
    "GetUserServiceAutoFactory",
    "GetUserServiceFactory",
    "InputPayloadMap",
    "InvalidModelForTest",
    "LooseTypeAlias",
    "NestedModel",
    "NormalizeComponentScenario",
    "P",
    "ParserScenario",
    "ParserScenarios",
    "R",
    "RandomConstants",
    "ReliabilityScenario",
    "ReliabilityScenarios",
    "Rule0LooseItemsFixture",
    "Rule0MultipleClassesFixture",
    "Rule1LooseEnumFixture",
    "RuntimeCloneService",
    "SampleModel",
    "ServiceFactoryRegistry",
    "ServiceTestCaseFactory",
    "ServiceTestCases",
    "SimpleObj",
    "SingletonClassForTest",
    "Status",
    "T",
    "TMessage",
    "T_co",
    "T_contra",
    "TestAdvancedPatterns",
    "TestAllLayerIntegration",
    "TestArchitecturalPatterns",
    "TestAutomatedArchitecture",
    "TestBaseModelCoverage",
    "TestCaseMap",
    "TestCheckExtraPolicy",
    "TestCheckFieldDescriptions",
    "TestCheckNoAny",
    "TestCheckNoBareCollections",
    "TestCheckNoV1Patterns",
    "TestCollectionUtilitiesCoverage",
    "TestCompleteFlextSystemIntegration",
    "TestConstantsEnforcement",
    "TestContainerFullCoverage",
    "TestContainerMemory",
    "TestContainerPerformance",
    "TestContext100Coverage",
    "TestCoverageContext",
    "TestCoverageExceptions",
    "TestCoverageLoggings",
    "TestCoverageModels",
    "TestDIIncremental",
    "TestDataGenerators",
    "TestDecoratorsDiscoveryFullCoverage",
    "TestDecoratorsFullCoverage",
    "TestDeprecationWarnings",
    "TestDiServicesAccess",
    "TestDispatcherDI",
    "TestDispatcherFullCoverage",
    "TestDispatcherMinimal",
    "TestDispatcherTimeoutCoverage100",
    "TestDocker",
    "TestDocumentedPatterns",
    "TestEnforcementMode",
    "TestEntityCoverageEdgeCases",
    "TestEnumUtilitiesCoverage",
    "TestExceptionsHypothesis",
    "TestExemptions",
    "TestFlextConstants",
    "TestFlextContainer",
    "TestFlextContext",
    "TestFlextDecorators",
    "TestFlextHandlers",
    "TestFlextInfraNamespaceValidator",
    "TestFlextMixinsNestedClasses",
    "TestFlextModelsBase",
    "TestFlextModelsCollectionsCoverage100",
    "TestFlextModelsContainer",
    "TestFlextModelsCqrs",
    "TestFlextModelsEntity",
    "TestFlextModelsExceptionParams",
    "TestFlextProtocols",
    "TestFlextRegistry",
    "TestFlextRuntime",
    "TestFlextSettings",
    "TestFlextSettingsCoverage",
    "TestFlextSettingsSingletonIntegration",
    "TestFlextTestsDomains",
    "TestFlextTestsFiles",
    "TestFlextTestsMatchers",
    "TestFlextTypes",
    "TestFlextUtilitiesArgs",
    "TestFlextUtilitiesConfiguration",
    "TestFlextUtilitiesGuards",
    "TestFlextUtilitiesMapper",
    "TestFlextUtilitiesReliability",
    "TestFlextVersion",
    "TestFunction",
    "TestHandlerDecoratorDiscovery",
    "TestHandlersFullCoverage",
    "TestHelperConsolidationTransformer",
    "TestHelperFactories",
    "TestHelperScenarios",
    "TestIdempotency",
    "TestInfraIntegration",
    "TestLibraryIntegration",
    "TestLoggingsErrorPaths",
    "TestLoggingsStrictReturns",
    "TestMigrationValidation",
    "TestMixinsFullCoverage",
    "TestModels",
    "TestModelsBaseFullCoverage",
    "TestModule",
    "TestPatternsCommands",
    "TestPatternsLogging",
    "TestPatternsTesting",
    "TestPerformanceBenchmarks",
    "TestProjectLevelRefactor",
    "TestProtocolsEnforcement",
    "TestRefactorPolicyMRO",
    "TestResultExceptionCarrying",
    "TestRuntimeCoverage100",
    "TestService",
    "TestService100Coverage",
    "TestServiceBootstrap",
    "TestServiceInternals",
    "TestServiceResultProperty",
    "TestTypesEnforcement",
    "TestTypingsFullCoverage",
    "TestUtilities",
    "TestUtilitiesCollectionCoverage",
    "TestUtilitiesCollectionFullCoverage",
    "TestUtilitiesConfigurationFullCoverage",
    "TestUtilitiesContextFullCoverage",
    "TestUtilitiesCoverage",
    "TestUtilitiesDataMapper",
    "TestUtilitiesDomainFullCoverage",
    "TestUtilitiesEnforcement",
    "TestUtilitiesGeneratorsFullCoverage",
    "TestUtilitiesParserFullCoverage",
    "TestUtilitiesTextFullCoverage",
    "TestUtilitiesTypeGuardsCoverage100",
    "TestUtils",
    "TestWorkspaceLevelRefactor",
    "Teste",
    "Testr",
    "TestrCoverage",
    "TestsCore",
    "TestsFlextServiceBase",
    "Testu",
    "TestuCacheLogger",
    "TestuCacheNormalizeComponent",
    "TestuDomain",
    "TestuMapperAccessors",
    "TestuMapperAdvanced",
    "TestuMapperConversions",
    "TestuMapperExtract",
    "TestuMapperUtils",
    "TestuTypeChecker",
    "TextUtilityContract",
    "UserFactory",
    "UtilitiesCacheCoverage100Namespace",
    "UtilitiesMapperCoverage100Namespace",
    "ValidatingService",
    "ValidatingServiceAuto",
    "ValidatingServiceAutoFactory",
    "ValidatingServiceFactory",
    "ValidationScenario",
    "ValidationScenarios",
    "_BadCopyModel",
    "_BrokenDumpModel",
    "_Cfg",
    "_DumpErrorModel",
    "_ErrorsModel",
    "_FakeConfig",
    "_FrozenEntity",
    "_GoodModel",
    "_Model",
    "_MsgWithCommandId",
    "_MsgWithMessageId",
    "_Opts",
    "_PlainErrorModel",
    "_SampleEntity",
    "_SvcModel",
    "_TargetModel",
    "_ValidationLikeError",
    "assert_rejects",
    "assert_validates",
    "assertion_helpers",
    "base",
    "benchmark",
    "c",
    "clean_container",
    "conftest",
    "conftest_infra",
    "constants",
    "contracts",
    "create_compare_entities_cases",
    "create_compare_value_objects_cases",
    "create_hash_entity_cases",
    "create_hash_value_object_cases",
    "d",
    "e",
    "empty_strings",
    "factories",
    "factories_impl",
    "fixture_factory",
    "flext_result_failure",
    "flext_result_success",
    "flext_tests",
    "get_memory_usage",
    "h",
    "helper",
    "helpers",
    "infra_git",
    "infra_git_repo",
    "infra_io",
    "infra_path",
    "infra_patterns",
    "infra_reporting",
    "infra_safe_command_output",
    "infra_selection",
    "infra_subprocess",
    "infra_templates",
    "infra_test_workspace",
    "infra_toml",
    "inject",
    "integration",
    "invalid_hostnames",
    "invalid_port_numbers",
    "invalid_uris",
    "m",
    "mapper",
    "mock_external_service",
    "models",
    "out_of_range",
    "p",
    "parser_scenarios",
    "patterns",
    "protocols",
    "pytestmark",
    "r",
    "reliability_scenarios",
    "reset_all_factories",
    "reset_global_container",
    "reset_runtime_state",
    "runtime_module",
    "s",
    "sample_data",
    "scenarios",
    "t",
    "temp_dir",
    "temp_directory",
    "temp_file",
    "test_advanced_patterns",
    "test_aliases_are_available",
    "test_architectural_patterns",
    "test_architecture",
    "test_args_coverage_100",
    "test_async_log_writer_paths",
    "test_async_log_writer_shutdown_with_full_queue",
    "test_bad_string_and_bad_bool_raise_value_error",
    "test_base",
    "test_canonical_aliases_are_available",
    "test_centralize_pydantic_cli_outputs_extended_metrics",
    "test_chk_exercises_missed_branches",
    "test_circuit_breaker_half_open_and_rate_limiter_accessors",
    "test_circuit_breaker_transitions_and_metrics",
    "test_class_nesting_appends_to_existing_namespace_and_removes_pass",
    "test_class_nesting_keeps_unmapped_top_level_classes",
    "test_class_nesting_moves_top_level_class_into_new_namespace",
    "test_class_nesting_refactor_single_file_end_to_end",
    "test_clear_keys_values_items_and_validate_branches",
    "test_collection_utilities_coverage_100",
    "test_collections_coverage_100",
    "test_command_pagination_limit",
    "test_config",
    "test_config_bridge_and_trace_context_and_http_validation",
    "test_config_integration",
    "test_configuration_mapping_and_dict_negative_branches",
    "test_configure_structlog_async_logging_uses_print_logger_factory",
    "test_configure_structlog_edge_paths",
    "test_configure_structlog_print_logger_factory_fallback",
    "test_constants_new",
    "test_container",
    "test_container_and_service_domain_paths",
    "test_container_full_coverage",
    "test_container_memory",
    "test_container_performance",
    "test_context",
    "test_context_coverage_100",
    "test_context_data_metadata_normalizer_removed",
    "test_context_data_normalize_and_json_checks",
    "test_context_data_validate_dict_serializable_error_paths",
    "test_context_data_validate_dict_serializable_none_and_mapping",
    "test_context_data_validate_dict_serializable_real_dicts",
    "test_context_export_serializable_and_validators",
    "test_context_export_statistics_validator_and_computed_fields",
    "test_context_export_validate_dict_serializable_mapping_and_models",
    "test_context_export_validate_dict_serializable_valid",
    "test_context_full_coverage",
    "test_conversion_add_converted_and_error_metadata_append_paths",
    "test_conversion_add_skipped_skip_reason_upsert_paths",
    "test_conversion_add_warning_metadata_append_paths",
    "test_conversion_start_and_complete_methods",
    "test_coverage_context",
    "test_coverage_exceptions",
    "test_coverage_loggings",
    "test_coverage_models",
    "test_coverage_utilities",
    "test_cqrs",
    "test_cqrs_query_resolve_deeper_and_int_pagination",
    "test_create_auto_discover_and_mode_mapping",
    "test_create_from_callable_and_repr",
    "test_create_merges_metadata_dict_branch",
    "test_create_overloads_and_auto_correlation",
    "test_data_factory",
    "test_decorators",
    "test_decorators_discovery_full_coverage",
    "test_decorators_family_blocks_dispatcher_target",
    "test_decorators_full_coverage",
    "test_dependency_integration_and_wiring_paths",
    "test_dependency_registration_duplicate_guards",
    "test_deprecation_warnings",
    "test_di_incremental",
    "test_di_services_access",
    "test_discover_project_roots_without_nested_git_dirs",
    "test_dispatcher_di",
    "test_dispatcher_family_blocks_models_target",
    "test_dispatcher_full_coverage",
    "test_dispatcher_minimal",
    "test_dispatcher_reliability",
    "test_dispatcher_timeout_coverage_100",
    "test_docker",
    "test_documented_patterns",
    "test_domains",
    "test_enforcement",
    "test_ensure_trace_context_dict_conversion_paths",
    "test_entity",
    "test_entity_comparable_map_and_bulk_validation_paths",
    "test_entity_coverage",
    "test_enum_utilities_coverage_100",
    "test_exception_params",
    "test_exceptions",
    "test_execute_and_register_handler_failure_paths",
    "test_export_paths_with_metadata_and_statistics",
    "test_extract_array_index_helpers",
    "test_extract_error_paths_and_prop_accessor",
    "test_files",
    "test_flext_message_type_alias_adapter",
    "test_flow_through_short_circuits_on_failure",
    "test_from_validation_and_to_model_paths",
    "test_get_logger_auto_configures_structlog",
    "test_get_logger_none_name_paths",
    "test_get_plugin_and_register_metadata_and_list_items_exception",
    "test_guard_in_has_empty_none_helpers",
    "test_guard_instance_attribute_access_warnings",
    "test_guards",
    "test_guards_bool_identity_branch_via_isinstance_fallback",
    "test_guards_bool_shortcut_and_issubclass_typeerror",
    "test_guards_handler_type_issubclass_typeerror_branch_direct",
    "test_guards_issubclass_success_when_callable_is_patched",
    "test_guards_issubclass_typeerror_when_class_not_treated_as_callable",
    "test_handler_builder_fluent_methods",
    "test_handler_decorator_discovery",
    "test_handlers",
    "test_handlers_full_coverage",
    "test_helper_consolidation_is_prechecked",
    "test_inactive_and_none_value_paths",
    "test_infra_integration",
    "test_init_fallback_and_lazy_returns_result_property",
    "test_integration",
    "test_is_container_negative_paths_and_callable",
    "test_is_type_non_empty_unknown_and_tuple_and_fallback",
    "test_is_type_protocol_fallback_branches",
    "test_is_valid_handles_validation_exception",
    "test_lash_runtime_result_paths",
    "test_loggings_error_paths_coverage",
    "test_loggings_full_coverage",
    "test_loggings_strict_returns",
    "test_map_error_identity_and_transform",
    "test_map_flat_map_and_then_paths",
    "test_mapper",
    "test_matchers",
    "test_migrate_protocols_rewrites_references_with_p_alias",
    "test_migrate_to_mro_inlines_alias_constant_into_constants_class",
    "test_migrate_to_mro_moves_constant_and_rewrites_reference",
    "test_migrate_to_mro_moves_manual_uppercase_assignment",
    "test_migrate_to_mro_normalizes_facade_alias_to_c",
    "test_migrate_to_mro_rejects_unknown_target",
    "test_migrate_typings_rewrites_references_with_t_alias",
    "test_migration_validation",
    "test_mixins",
    "test_mixins_full_coverage",
    "test_model_helpers_remaining_paths",
    "test_model_support_and_hash_compare_paths",
    "test_models",
    "test_models_base_full_coverage",
    "test_models_container",
    "test_models_context_full_coverage",
    "test_models_cqrs_full_coverage",
    "test_models_entity_full_coverage",
    "test_models_family_blocks_utilities_target",
    "test_models_generic_full_coverage",
    "test_namespace_enforce_cli_fails_on_manual_protocol_violation",
    "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring",
    "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future",
    "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file",
    "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports",
    "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory",
    "test_namespace_enforcer_detects_internal_private_imports",
    "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files",
    "test_namespace_enforcer_detects_manual_typings_and_compat_aliases",
    "test_namespace_enforcer_detects_missing_runtime_alias_outside_src",
    "test_namespace_enforcer_does_not_rewrite_indented_import_aliases",
    "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks",
    "test_namespace_validator",
    "test_narrow_contextvar_exception_branch",
    "test_narrow_contextvar_invalid_inputs",
    "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage",
    "test_nested_class_propagation_updates_import_annotations_and_calls",
    "test_non_empty_and_normalize_branches",
    "test_normalization_edge_branches",
    "test_normalize_to_container_alias_removal_path",
    "test_normalize_to_metadata_alias_removal_path",
    "test_ok_accepts_none",
    "test_operation_progress_start_operation_sets_runtime_fields",
    "test_patterns_commands",
    "test_patterns_logging",
    "test_patterns_testing",
    "test_protocol_and_simple_guard_helpers",
    "test_protocols_new",
    "test_query_resolve_pagination_wrapper_and_fallback",
    "test_query_validate_pagination_dict_and_default",
    "test_rate_limiter_blocks_then_recovers",
    "test_rate_limiter_jitter_application",
    "test_reconfigure_and_reset_state_paths",
    "test_recover_tap_and_tap_error_paths",
    "test_refactor_cli_models_workflow",
    "test_refactor_migrate_to_class_mro",
    "test_refactor_namespace_enforcer",
    "test_refactor_nesting_file",
    "test_refactor_nesting_idempotency",
    "test_refactor_nesting_performance",
    "test_refactor_nesting_project",
    "test_refactor_nesting_workspace",
    "test_refactor_policy_family_rules",
    "test_refactor_policy_mro",
    "test_refactor_utilities_iter_python_files_includes_examples_and_scripts",
    "test_registry",
    "test_registry_full_coverage",
    "test_result",
    "test_result_additional",
    "test_result_coverage_100",
    "test_result_exception_carrying",
    "test_result_full_coverage",
    "test_result_property_raises_on_failure",
    "test_reuse_existing_runtime_coverage_branches",
    "test_reuse_existing_runtime_scenarios",
    "test_runtime",
    "test_runtime_coverage_100",
    "test_runtime_create_instance_failure_branch",
    "test_runtime_family_blocks_non_runtime_target",
    "test_runtime_full_coverage",
    "test_runtime_integration_tracking_paths",
    "test_runtime_misc_remaining_paths",
    "test_runtime_module_accessors_and_metadata",
    "test_runtime_result_alias_compatibility",
    "test_runtime_result_all_missed_branches",
    "test_runtime_result_remaining_paths",
    "test_scope_data_validators_and_errors",
    "test_service",
    "test_service_additional",
    "test_service_bootstrap",
    "test_service_coverage_100",
    "test_service_result_property",
    "test_set_set_all_get_validation_and_error_paths",
    "test_settings_coverage",
    "test_statistics_and_custom_fields_validators",
    "test_structlog_proxy_context_var_default_when_key_missing",
    "test_structlog_proxy_context_var_get_set_reset_paths",
    "test_summary_error_paths_and_bindings_failures",
    "test_summary_properties_and_subclass_storage_reset",
    "test_system",
    "test_to_general_value_dict_removed",
    "test_transformer_class_nesting",
    "test_transformer_helper_consolidation",
    "test_transformer_nested_class_propagation",
    "test_type_guards_result",
    "test_typings_full_coverage",
    "test_typings_new",
    "test_ultrawork_models_cli_runs_dry_run_copy",
    "test_update_statistics_remove_hook_and_clone_false_result",
    "test_utilities",
    "test_utilities_cache_coverage_100",
    "test_utilities_collection_coverage_100",
    "test_utilities_collection_full_coverage",
    "test_utilities_configuration_coverage_100",
    "test_utilities_configuration_full_coverage",
    "test_utilities_context_full_coverage",
    "test_utilities_coverage",
    "test_utilities_data_mapper",
    "test_utilities_domain",
    "test_utilities_domain_full_coverage",
    "test_utilities_enum_full_coverage",
    "test_utilities_family_allows_utilities_target",
    "test_utilities_generators_full_coverage",
    "test_utilities_guards_full_coverage",
    "test_utilities_mapper_coverage_100",
    "test_utilities_mapper_full_coverage",
    "test_utilities_parser_full_coverage",
    "test_utilities_reliability",
    "test_utilities_text_full_coverage",
    "test_utilities_type_checker_coverage_100",
    "test_utilities_type_guards_coverage_100",
    "test_utils",
    "test_validation_like_error_structure",
    "test_version",
    "test_with_resource_cleanup_runs",
    "text_contract",
    "typings",
    "u",
    "unit",
    "utilities",
    "valid_hostnames",
    "valid_port_numbers",
    "valid_ranges",
    "valid_strings",
    "valid_uris",
    "validation_scenarios",
    "whitespace_strings",
    "x",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
