# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Tests package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_infra import d, e, h, r, s, x

    from flext_core.typings import FlextTypes

    from . import (
        benchmark as benchmark,
        helpers as helpers,
        integration as integration,
        unit as unit,
    )
    from .base import TestsFlextServiceBase
    from .benchmark import (
        TestContainerMemory,
        TestContainerPerformance,
        TestPerformanceBenchmarks,
        get_memory_usage,
    )
    from .conftest import (
        FunctionalExternalService,
        assert_rejects,
        assert_validates,
        clean_container,
        empty_strings,
        flext_result_failure,
        flext_result_success,
        invalid_hostnames,
        invalid_port_numbers,
        invalid_uris,
        mock_external_service,
        out_of_range,
        parser_scenarios,
        reliability_scenarios,
        reset_global_container,
        sample_data,
        temp_dir,
        temp_directory,
        temp_file,
        test_context,
        valid_hostnames,
        valid_port_numbers,
        valid_ranges,
        valid_strings,
        valid_uris,
        validation_scenarios,
        whitespace_strings,
    )
    from .constants import TestsFlextConstants, TestsFlextConstants as c
    from .helpers import (
        FailingService,
        FailingServiceAuto,
        FailingServiceAutoFactory,
        FailingServiceFactory,
        GenericModelFactory,
        GetUserService,
        GetUserServiceAuto,
        GetUserServiceAutoFactory,
        GetUserServiceFactory,
        ServiceFactoryRegistry,
        ServiceTestCase,
        ServiceTestCaseFactory,
        ServiceTestCases,
        TestDataGenerators,
        TestHelperFactories,
        TestHelperScenarios,
        User,
        UserFactory,
        ValidatingService,
        ValidatingServiceAuto,
        ValidatingServiceAutoFactory,
        ValidatingServiceFactory,
        reset_all_factories,
    )
    from .integration import (
        TestAdvancedPatterns,
        TestArchitecturalPatterns,
        TestCompleteFlextSystemIntegration,
        TestFlextSettingsSingletonIntegration,
        TestFunction,
        TestIdempotency,
        TestInfraIntegration,
        TestLibraryIntegration,
        TestMigrationValidation,
        TestPatternsCommands,
        TestPatternsLogging,
        TestPatternsTesting,
        TestProjectLevelRefactor,
        TestRefactorPolicyMRO,
        TestService,
        TestWorkspaceLevelRefactor,
        patterns,
        pytestmark,
        test_class_nesting_refactor_single_file_end_to_end,
    )
    from .models import TestsFlextModels, TestsFlextModels as m
    from .protocols import TestsFlextProtocols, TestsFlextProtocols as p
    from .test_documented_patterns import TestDocumentedPatterns
    from .test_service_result_property import TestServiceResultProperty
    from .test_utils import (
        FlextTestResult,
        FlextTestResultCo,
        TestUtils,
        assertion_helpers,
        fixture_factory,
        test_data_factory,
    )
    from .typings import T, T_co, T_contra, TestsFlextTypes, TestsFlextTypes as t
    from .unit import (
        AttrObject,
        BadBool,
        BadMapping,
        BadString,
        CircuitBreakerManager,
        ClearCacheScenario,
        ExplodingLenList,
        FlextProtocols,
        NestedClassPropagationTransformer,
        NormalizeComponentScenario,
        Provide,
        RateLimiterManager,
        RetryPolicy,
        RuntimeCloneService,
        SimpleObj,
        SortKeyScenario,
        TestAutomatedArchitecture,
        TestAutomatedExceptions,
        TestAutomatedFlextContainer,
        TestAutomatedFlextContext,
        TestAutomatedFlextDecorators,
        TestAutomatedFlextDispatcher,
        TestAutomatedFlextHandlers,
        TestAutomatedFlextLogger,
        TestAutomatedFlextMixins,
        TestAutomatedFlextRegistry,
        TestAutomatedFlextRuntime,
        TestAutomatedFlextService,
        TestAutomatedFlextSettings,
        TestAutomatedFlextUtilities,
        TestAutomatedResult,
        TestCollectionUtilitiesCoverage,
        TestConstants,
        TestContainerFullCoverage,
        TestContext100Coverage,
        TestCoverage76Lines,
        TestCoverageContext,
        TestCoverageExceptions,
        TestCoverageLoggings,
        TestCoverageModels,
        TestDecoratorsDiscoveryFullCoverage,
        TestDecoratorsFullCoverage,
        TestDeprecationWarnings,
        TestDIIncremental,
        TestDiServicesAccess,
        TestDispatcherDI,
        TestDispatcherFullCoverage,
        TestDispatcherMinimal,
        TestDispatcherTimeoutCoverage100,
        TestDocker,
        Teste,
        TestEntityCoverageEdgeCases,
        TestEnumUtilitiesCoverage,
        TestFinal75PercentPush,
        TestFlextContainer,
        TestFlextContext,
        TestFlextDecorators,
        TestFlextHandlers,
        TestFlextInfraNamespaceValidator,
        TestFlextMixinsNestedClasses,
        TestFlextModelsCollectionsCoverage100,
        TestFlextModelsContainer,
        TestFlextProtocols,
        TestFlextRegistry,
        TestFlextRuntime,
        TestFlextSettings,
        TestFlextTestsDomains,
        TestFlextTestsFiles,
        TestFlextTestsMatchers,
        TestFlextUtilitiesArgs,
        TestFlextUtilitiesConfiguration,
        TestFlextUtilitiesReliability,
        TestFlextVersion,
        TestHandlerDecoratorDiscovery,
        TestHandlersFullCoverage,
        TestHelperConsolidationTransformer,
        TestLoggingsErrorPaths,
        TestLoggingsStrictReturns,
        TestMixinsFullCoverage,
        TestModels,
        TestModels79Coverage,
        TestModelsBaseFullCoverage,
        TestModelsCollectionsFullCoverage,
        TestModule,
        TestPaginationCoverage100,
        TestPhase2CoverageFinal,
        Testr,
        TestrCoverage,
        TestResultExceptionCarrying,
        TestRuntimeCoverage100,
        TestsCore,
        TestService100Coverage,
        TestServiceBootstrap,
        TestServiceFullCoverage,
        TestTypings,
        TestTypingsFullCoverage,
        Testu,
        TestuCacheClearObjectCache,
        TestuCacheGenerateCacheKey,
        TestuCacheHasCacheAttributes,
        TestuCacheLogger,
        TestuCacheNormalizeComponent,
        TestuCacheSortDictKeys,
        TestuCacheSortKey,
        TestuDomain,
        TestuMapperAccessors,
        TestuMapperAdvanced,
        TestuMapperBuild,
        TestuMapperConversions,
        TestuMapperExtract,
        TestuMapperUtils,
        TestuStringParser,
        TestUtilities,
        TestUtilitiesCheckerFullCoverage,
        TestUtilitiesCollectionCoverage,
        TestUtilitiesCollectionFullCoverage,
        TestUtilitiesConfigurationFullCoverage,
        TestUtilitiesContextFullCoverage,
        TestUtilitiesCoverage,
        TestUtilitiesDataMapper,
        TestUtilitiesDomainFullCoverage,
        TestUtilitiesEnumFullCoverage,
        TestUtilitiesGeneratorsFullCoverage,
        TestUtilitiesParserFullCoverage,
        TestUtilitiesTextFullCoverage,
        TestUtilitiesTypeGuardsCoverage100,
        TestuTypeChecker,
        TextUtilityContract,
        TimeoutEnforcer,
        TMessage,
        UnknownHint,
        UtilitiesCacheCoverage100Namespace,
        UtilitiesMapperCoverage100Namespace,
        UtilitiesMapperFullCoverageNamespace,
        contracts,
        create_compare_entities_cases,
        create_compare_value_objects_cases,
        create_hash_entity_cases,
        create_hash_value_object_cases,
        create_validate_entity_has_id_cases,
        create_validate_value_object_immutable_cases,
        flext_tests,
        generators_module,
        handlers_module,
        infra_git,
        infra_git_repo,
        infra_io,
        infra_path,
        infra_patterns,
        infra_pr_manager,
        infra_pr_workspace_manager,
        infra_reporting,
        infra_safe_command_output,
        infra_selection,
        infra_subprocess,
        infra_templates,
        infra_test_workspace,
        infra_toml,
        infra_workflow_linter,
        infra_workflow_syncer,
        inject,
        mapper,
        reset_runtime_state,
        runtime_cov_tests,
        runtime_module,
        runtime_tests,
        test_accessor_take_pick_as_or_flat_and_agg_branches,
        test_aliases_are_available,
        test_args_get_enum_params_annotated_unwrap_branch,
        test_args_get_enum_params_branches,
        test_async_log_writer_paths,
        test_async_log_writer_shutdown_with_full_queue,
        test_at_take_and_as_branches,
        test_authentication_error_normalizes_extra_kwargs_into_context,
        test_bad_string_and_bad_bool_raise_value_error,
        test_base_error_normalize_metadata_merges_existing_metadata_model,
        test_basic_imports_work,
        test_build_apply_transform_and_process_error_paths,
        test_canonical_aliases_are_available,
        test_centralize_pydantic_cli_outputs_extended_metrics,
        test_centralizer_converts_typed_dict_factory_to_model,
        test_centralizer_does_not_touch_settings_module,
        test_centralizer_moves_dict_alias_in_typings_without_keyword_name,
        test_centralizer_moves_manual_type_aliases_to_models_file,
        test_chk_exercises_missed_branches,
        test_circuit_breaker_transitions_and_metrics,
        test_class_nesting_appends_to_existing_namespace_and_removes_pass,
        test_class_nesting_keeps_unmapped_top_level_classes,
        test_class_nesting_moves_top_level_class_into_new_namespace,
        test_clear_keys_values_items_and_validate_branches,
        test_command_pagination_limit,
        test_config_bridge_and_trace_context_and_http_validation,
        test_configuration_mapping_and_dict_negative_branches,
        test_configure_structlog_edge_paths,
        test_configure_structlog_print_logger_factory_fallback,
        test_constants_auto_enum_and_bimapping_paths,
        test_construct_transform_and_deep_eq_branches,
        test_container_and_service_domain_paths,
        test_container_resource_registration_metadata_normalized,
        test_context_data_metadata_normalizer_removed,
        test_context_data_normalize_and_json_checks,
        test_context_data_validate_dict_serializable_error_paths,
        test_context_data_validate_dict_serializable_none_and_mapping,
        test_context_data_validate_dict_serializable_real_dicts,
        test_context_export_serializable_and_validators,
        test_context_export_statistics_validator_and_computed_fields,
        test_context_export_validate_dict_serializable_mapping_and_models,
        test_context_export_validate_dict_serializable_valid,
        test_conversion_add_converted_and_error_metadata_append_paths,
        test_conversion_add_skipped_skip_reason_upsert_paths,
        test_conversion_add_warning_metadata_append_paths,
        test_conversion_and_extract_success_branches,
        test_conversion_start_and_complete_methods,
        test_conversion_string_and_join_paths,
        test_convert_default_fallback_matrix,
        test_convert_sequence_branch_returns_tuple,
        test_cqrs_query_resolve_deeper_and_int_pagination,
        test_create_auto_discover_and_mode_mapping,
        test_create_from_callable_and_repr,
        test_create_merges_metadata_dict_branch,
        test_create_overloads_and_auto_correlation,
        test_decorators_family_blocks_dispatcher_target,
        test_dependency_integration_and_wiring_paths,
        test_dependency_registration_duplicate_guards,
        test_deprecated_class_noop_init_branch,
        test_discover_project_roots_without_nested_git_dirs,
        test_dispatcher_family_blocks_models_target,
        test_dispatcher_reliability_branch_paths,
        test_ensure_and_extract_array_index_helpers,
        test_ensure_trace_context_dict_conversion_paths,
        test_ensure_utc_datetime_adds_tzinfo_when_naive,
        test_ensure_utc_datetime_preserves_aware,
        test_ensure_utc_datetime_returns_none_on_none,
        test_entity_comparable_map_and_bulk_validation_paths,
        test_exceptions_uncovered_metadata_paths,
        test_execute_and_register_handler_failure_paths,
        test_export_paths_with_metadata_and_statistics,
        test_extract_error_paths_and_prop_accessor,
        test_extract_field_value_and_ensure_variants,
        test_extract_mapping_or_none_branches,
        test_facade_binding_is_correct,
        test_field_and_fields_multi_branches,
        test_filter_map_normalize_convert_helpers,
        test_flext_message_type_alias_adapter,
        test_flow_through_short_circuits_on_failure,
        test_from_validation_and_to_model_paths,
        test_general_value_helpers_and_logger,
        test_get_logger_none_name_paths,
        test_get_plugin_and_register_metadata_and_list_items_exception,
        test_get_service_info,
        test_group_sort_unique_slice_chunk_branches,
        test_guard_in_has_empty_none_helpers,
        test_guard_instance_attribute_access_warnings,
        test_guards_bool_identity_branch_via_isinstance_fallback,
        test_guards_bool_shortcut_and_issubclass_typeerror,
        test_guards_handler_type_issubclass_typeerror_branch_direct,
        test_guards_issubclass_success_when_callable_is_patched,
        test_guards_issubclass_typeerror_when_class_not_treated_as_callable,
        test_handler_builder_fluent_methods,
        test_helper_consolidation_is_prechecked,
        test_inactive_and_none_value_paths,
        test_init_fallback_and_lazy_returns_result_property,
        test_invert_and_json_conversion_branches,
        test_is_container_negative_paths_and_callable,
        test_is_flexible_value_covers_all_branches,
        test_is_handler_type_branches,
        test_is_type_non_empty_unknown_and_tuple_and_fallback,
        test_is_type_protocol_fallback_branches,
        test_is_valid_handles_validation_exception,
        test_lash_runtime_result_paths,
        test_map_error_identity_and_transform,
        test_map_flags_collect_and_invert_branches,
        test_map_flat_map_and_then_paths,
        test_merge_defaults_and_dump_paths,
        test_merge_metadata_context_paths,
        test_migrate_protocols_rewrites_references_with_p_alias,
        test_migrate_to_mro_inlines_alias_constant_into_constants_class,
        test_migrate_to_mro_moves_constant_and_rewrites_reference,
        test_migrate_to_mro_moves_manual_uppercase_assignment,
        test_migrate_to_mro_normalizes_facade_alias_to_c,
        test_migrate_to_mro_rejects_unknown_target,
        test_migrate_typings_rewrites_references_with_t_alias,
        test_model_helpers_remaining_paths,
        test_model_support_and_hash_compare_paths,
        test_models_family_blocks_utilities_target,
        test_models_handler_branches,
        test_models_handler_uncovered_mode_and_reset_paths,
        test_models_settings_branch_paths,
        test_models_settings_context_validator_and_non_standard_status_input,
        test_mro_scanner_includes_constants_variants_in_all_scopes,
        test_namespace_enforce_cli_fails_on_manual_protocol_violation,
        test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring,
        test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future,
        test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file,
        test_namespace_enforcer_creates_missing_facades_and_rewrites_imports,
        test_namespace_enforcer_detects_cyclic_imports_in_tests_directory,
        test_namespace_enforcer_detects_internal_private_imports,
        test_namespace_enforcer_detects_manual_protocol_outside_canonical_files,
        test_namespace_enforcer_detects_manual_typings_and_compat_aliases,
        test_namespace_enforcer_detects_missing_runtime_alias_outside_src,
        test_namespace_enforcer_does_not_rewrite_indented_import_aliases,
        test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks,
        test_narrow_contextvar_exception_branch,
        test_narrow_contextvar_invalid_inputs,
        test_narrow_to_string_keyed_dict_and_mapping_paths,
        test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage,
        test_nested_class_propagation_updates_import_annotations_and_calls,
        test_non_empty_and_normalize_branches,
        test_normalization_edge_branches,
        test_normalize_to_container_alias_removal_path,
        test_normalize_to_list_passes_list_through,
        test_normalize_to_list_wraps_int,
        test_normalize_to_list_wraps_scalar,
        test_normalize_to_metadata_alias_removal_path,
        test_normalize_to_pydantic_dict_and_value_branches,
        test_not_found_error_correlation_id_selection_and_extra_kwargs,
        test_ok_accepts_none,
        test_operation_progress_start_operation_sets_runtime_fields,
        test_pagination_response_string_fallbacks,
        test_process_context_data_and_related_convenience,
        test_protocol_and_simple_guard_helpers,
        test_query_resolve_pagination_wrapper_and_fallback,
        test_query_validate_pagination_dict_and_default,
        test_rate_limiter_blocks_then_recovers,
        test_rate_limiter_jitter_application,
        test_reconfigure_and_reset_state_paths,
        test_recover_tap_and_tap_error_paths,
        test_refactor_utilities_iter_python_files_includes_examples_and_scripts,
        test_remaining_build_fields_construct_and_eq_paths,
        test_remaining_uncovered_branches,
        test_result_property_raises_on_failure,
        test_retry_policy_behavior,
        test_reuse_existing_runtime_coverage_branches,
        test_reuse_existing_runtime_scenarios,
        test_runtime_create_instance_failure_branch,
        test_runtime_family_blocks_non_runtime_target,
        test_runtime_integration_tracking_paths,
        test_runtime_misc_remaining_paths,
        test_runtime_module_accessors_and_metadata,
        test_runtime_result_alias_compatibility,
        test_runtime_result_all_missed_branches,
        test_runtime_result_remaining_paths,
        test_scope_data_validators_and_errors,
        test_service_request_timeout_post_validator_messages,
        test_service_request_timeout_validator_branches,
        test_set_set_all_get_validation_and_error_paths,
        test_settings_materialize_and_context_overrides,
        test_small_mapper_convenience_methods,
        test_statistics_and_custom_fields_validators,
        test_strip_whitespace_preserves_clean,
        test_strip_whitespace_returns_empty_on_spaces,
        test_strip_whitespace_trims_leading_trailing,
        test_structlog_proxy_context_var_default_when_key_missing,
        test_structlog_proxy_context_var_get_set_reset_paths,
        test_summary_error_paths_and_bindings_failures,
        test_summary_properties_and_subclass_storage_reset,
        test_to_general_value_dict_removed,
        test_transform_option_extract_and_step_helpers,
        test_type_guards_and_narrowing_failures,
        test_type_guards_result,
        test_ultrawork_models_cli_runs_dry_run_copy,
        test_update_exception_path,
        test_update_statistics_remove_hook_and_clone_false_result,
        test_update_success_path_returns_ok_result,
        test_utilities_family_allows_utilities_target,
        test_utilities_reliability_branches,
        test_utilities_reliability_compose_returns_non_result_directly,
        test_utilities_reliability_uncovered_retry_compose_and_sequence_paths,
        test_validate_config_dict_normalizes_dict,
        test_validate_tags_list_from_string,
        test_validate_tags_list_normalizes,
        test_validation_like_error_structure,
        test_with_resource_cleanup_runs,
    )
    from .utilities import FlextCoreTestUtilities, FlextCoreTestUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "AttrObject": ("tests.unit", "AttrObject"),
    "BadBool": ("tests.unit", "BadBool"),
    "BadMapping": ("tests.unit", "BadMapping"),
    "BadString": ("tests.unit", "BadString"),
    "CircuitBreakerManager": ("tests.unit", "CircuitBreakerManager"),
    "ClearCacheScenario": ("tests.unit", "ClearCacheScenario"),
    "ExplodingLenList": ("tests.unit", "ExplodingLenList"),
    "FailingService": ("tests.helpers", "FailingService"),
    "FailingServiceAuto": ("tests.helpers", "FailingServiceAuto"),
    "FailingServiceAutoFactory": ("tests.helpers", "FailingServiceAutoFactory"),
    "FailingServiceFactory": ("tests.helpers", "FailingServiceFactory"),
    "FlextCoreTestUtilities": ("tests.utilities", "FlextCoreTestUtilities"),
    "FlextProtocols": ("tests.unit", "FlextProtocols"),
    "FlextTestResult": ("tests.test_utils", "FlextTestResult"),
    "FlextTestResultCo": ("tests.test_utils", "FlextTestResultCo"),
    "FunctionalExternalService": ("tests.conftest", "FunctionalExternalService"),
    "GenericModelFactory": ("tests.helpers", "GenericModelFactory"),
    "GetUserService": ("tests.helpers", "GetUserService"),
    "GetUserServiceAuto": ("tests.helpers", "GetUserServiceAuto"),
    "GetUserServiceAutoFactory": ("tests.helpers", "GetUserServiceAutoFactory"),
    "GetUserServiceFactory": ("tests.helpers", "GetUserServiceFactory"),
    "NestedClassPropagationTransformer": (
        "tests.unit",
        "NestedClassPropagationTransformer",
    ),
    "NormalizeComponentScenario": ("tests.unit", "NormalizeComponentScenario"),
    "Provide": ("tests.unit", "Provide"),
    "RateLimiterManager": ("tests.unit", "RateLimiterManager"),
    "RetryPolicy": ("tests.unit", "RetryPolicy"),
    "RuntimeCloneService": ("tests.unit", "RuntimeCloneService"),
    "ServiceFactoryRegistry": ("tests.helpers", "ServiceFactoryRegistry"),
    "ServiceTestCase": ("tests.helpers", "ServiceTestCase"),
    "ServiceTestCaseFactory": ("tests.helpers", "ServiceTestCaseFactory"),
    "ServiceTestCases": ("tests.helpers", "ServiceTestCases"),
    "SimpleObj": ("tests.unit", "SimpleObj"),
    "SortKeyScenario": ("tests.unit", "SortKeyScenario"),
    "T": ("tests.typings", "T"),
    "TMessage": ("tests.unit", "TMessage"),
    "T_co": ("tests.typings", "T_co"),
    "T_contra": ("tests.typings", "T_contra"),
    "TestAdvancedPatterns": ("tests.integration", "TestAdvancedPatterns"),
    "TestArchitecturalPatterns": ("tests.integration", "TestArchitecturalPatterns"),
    "TestAutomatedArchitecture": ("tests.unit", "TestAutomatedArchitecture"),
    "TestAutomatedExceptions": ("tests.unit", "TestAutomatedExceptions"),
    "TestAutomatedFlextContainer": ("tests.unit", "TestAutomatedFlextContainer"),
    "TestAutomatedFlextContext": ("tests.unit", "TestAutomatedFlextContext"),
    "TestAutomatedFlextDecorators": ("tests.unit", "TestAutomatedFlextDecorators"),
    "TestAutomatedFlextDispatcher": ("tests.unit", "TestAutomatedFlextDispatcher"),
    "TestAutomatedFlextHandlers": ("tests.unit", "TestAutomatedFlextHandlers"),
    "TestAutomatedFlextLogger": ("tests.unit", "TestAutomatedFlextLogger"),
    "TestAutomatedFlextMixins": ("tests.unit", "TestAutomatedFlextMixins"),
    "TestAutomatedFlextRegistry": ("tests.unit", "TestAutomatedFlextRegistry"),
    "TestAutomatedFlextRuntime": ("tests.unit", "TestAutomatedFlextRuntime"),
    "TestAutomatedFlextService": ("tests.unit", "TestAutomatedFlextService"),
    "TestAutomatedFlextSettings": ("tests.unit", "TestAutomatedFlextSettings"),
    "TestAutomatedFlextUtilities": ("tests.unit", "TestAutomatedFlextUtilities"),
    "TestAutomatedResult": ("tests.unit", "TestAutomatedResult"),
    "TestCollectionUtilitiesCoverage": (
        "tests.unit",
        "TestCollectionUtilitiesCoverage",
    ),
    "TestCompleteFlextSystemIntegration": (
        "tests.integration",
        "TestCompleteFlextSystemIntegration",
    ),
    "TestConstants": ("tests.unit", "TestConstants"),
    "TestContainerFullCoverage": ("tests.unit", "TestContainerFullCoverage"),
    "TestContainerMemory": ("tests.benchmark", "TestContainerMemory"),
    "TestContainerPerformance": ("tests.benchmark", "TestContainerPerformance"),
    "TestContext100Coverage": ("tests.unit", "TestContext100Coverage"),
    "TestCoverage76Lines": ("tests.unit", "TestCoverage76Lines"),
    "TestCoverageContext": ("tests.unit", "TestCoverageContext"),
    "TestCoverageExceptions": ("tests.unit", "TestCoverageExceptions"),
    "TestCoverageLoggings": ("tests.unit", "TestCoverageLoggings"),
    "TestCoverageModels": ("tests.unit", "TestCoverageModels"),
    "TestDIIncremental": ("tests.unit", "TestDIIncremental"),
    "TestDataGenerators": ("tests.helpers", "TestDataGenerators"),
    "TestDecoratorsDiscoveryFullCoverage": (
        "tests.unit",
        "TestDecoratorsDiscoveryFullCoverage",
    ),
    "TestDecoratorsFullCoverage": ("tests.unit", "TestDecoratorsFullCoverage"),
    "TestDeprecationWarnings": ("tests.unit", "TestDeprecationWarnings"),
    "TestDiServicesAccess": ("tests.unit", "TestDiServicesAccess"),
    "TestDispatcherDI": ("tests.unit", "TestDispatcherDI"),
    "TestDispatcherFullCoverage": ("tests.unit", "TestDispatcherFullCoverage"),
    "TestDispatcherMinimal": ("tests.unit", "TestDispatcherMinimal"),
    "TestDispatcherTimeoutCoverage100": (
        "tests.unit",
        "TestDispatcherTimeoutCoverage100",
    ),
    "TestDocker": ("tests.unit", "TestDocker"),
    "TestDocumentedPatterns": (
        "tests.test_documented_patterns",
        "TestDocumentedPatterns",
    ),
    "TestEntityCoverageEdgeCases": ("tests.unit", "TestEntityCoverageEdgeCases"),
    "TestEnumUtilitiesCoverage": ("tests.unit", "TestEnumUtilitiesCoverage"),
    "TestFinal75PercentPush": ("tests.unit", "TestFinal75PercentPush"),
    "TestFlextContainer": ("tests.unit", "TestFlextContainer"),
    "TestFlextContext": ("tests.unit", "TestFlextContext"),
    "TestFlextDecorators": ("tests.unit", "TestFlextDecorators"),
    "TestFlextHandlers": ("tests.unit", "TestFlextHandlers"),
    "TestFlextInfraNamespaceValidator": (
        "tests.unit",
        "TestFlextInfraNamespaceValidator",
    ),
    "TestFlextMixinsNestedClasses": ("tests.unit", "TestFlextMixinsNestedClasses"),
    "TestFlextModelsCollectionsCoverage100": (
        "tests.unit",
        "TestFlextModelsCollectionsCoverage100",
    ),
    "TestFlextModelsContainer": ("tests.unit", "TestFlextModelsContainer"),
    "TestFlextProtocols": ("tests.unit", "TestFlextProtocols"),
    "TestFlextRegistry": ("tests.unit", "TestFlextRegistry"),
    "TestFlextRuntime": ("tests.unit", "TestFlextRuntime"),
    "TestFlextSettings": ("tests.unit", "TestFlextSettings"),
    "TestFlextSettingsSingletonIntegration": (
        "tests.integration",
        "TestFlextSettingsSingletonIntegration",
    ),
    "TestFlextTestsDomains": ("tests.unit", "TestFlextTestsDomains"),
    "TestFlextTestsFiles": ("tests.unit", "TestFlextTestsFiles"),
    "TestFlextTestsMatchers": ("tests.unit", "TestFlextTestsMatchers"),
    "TestFlextUtilitiesArgs": ("tests.unit", "TestFlextUtilitiesArgs"),
    "TestFlextUtilitiesConfiguration": (
        "tests.unit",
        "TestFlextUtilitiesConfiguration",
    ),
    "TestFlextUtilitiesReliability": ("tests.unit", "TestFlextUtilitiesReliability"),
    "TestFlextVersion": ("tests.unit", "TestFlextVersion"),
    "TestFunction": ("tests.integration", "TestFunction"),
    "TestHandlerDecoratorDiscovery": ("tests.unit", "TestHandlerDecoratorDiscovery"),
    "TestHandlersFullCoverage": ("tests.unit", "TestHandlersFullCoverage"),
    "TestHelperConsolidationTransformer": (
        "tests.unit",
        "TestHelperConsolidationTransformer",
    ),
    "TestHelperFactories": ("tests.helpers", "TestHelperFactories"),
    "TestHelperScenarios": ("tests.helpers", "TestHelperScenarios"),
    "TestIdempotency": ("tests.integration", "TestIdempotency"),
    "TestInfraIntegration": ("tests.integration", "TestInfraIntegration"),
    "TestLibraryIntegration": ("tests.integration", "TestLibraryIntegration"),
    "TestLoggingsErrorPaths": ("tests.unit", "TestLoggingsErrorPaths"),
    "TestLoggingsStrictReturns": ("tests.unit", "TestLoggingsStrictReturns"),
    "TestMigrationValidation": ("tests.integration", "TestMigrationValidation"),
    "TestMixinsFullCoverage": ("tests.unit", "TestMixinsFullCoverage"),
    "TestModels": ("tests.unit", "TestModels"),
    "TestModels79Coverage": ("tests.unit", "TestModels79Coverage"),
    "TestModelsBaseFullCoverage": ("tests.unit", "TestModelsBaseFullCoverage"),
    "TestModelsCollectionsFullCoverage": (
        "tests.unit",
        "TestModelsCollectionsFullCoverage",
    ),
    "TestModule": ("tests.unit", "TestModule"),
    "TestPaginationCoverage100": ("tests.unit", "TestPaginationCoverage100"),
    "TestPatternsCommands": ("tests.integration", "TestPatternsCommands"),
    "TestPatternsLogging": ("tests.integration", "TestPatternsLogging"),
    "TestPatternsTesting": ("tests.integration", "TestPatternsTesting"),
    "TestPerformanceBenchmarks": ("tests.benchmark", "TestPerformanceBenchmarks"),
    "TestPhase2CoverageFinal": ("tests.unit", "TestPhase2CoverageFinal"),
    "TestProjectLevelRefactor": ("tests.integration", "TestProjectLevelRefactor"),
    "TestRefactorPolicyMRO": ("tests.integration", "TestRefactorPolicyMRO"),
    "TestResultExceptionCarrying": ("tests.unit", "TestResultExceptionCarrying"),
    "TestRuntimeCoverage100": ("tests.unit", "TestRuntimeCoverage100"),
    "TestService": ("tests.integration", "TestService"),
    "TestService100Coverage": ("tests.unit", "TestService100Coverage"),
    "TestServiceBootstrap": ("tests.unit", "TestServiceBootstrap"),
    "TestServiceFullCoverage": ("tests.unit", "TestServiceFullCoverage"),
    "TestServiceResultProperty": (
        "tests.test_service_result_property",
        "TestServiceResultProperty",
    ),
    "TestTypings": ("tests.unit", "TestTypings"),
    "TestTypingsFullCoverage": ("tests.unit", "TestTypingsFullCoverage"),
    "TestUtilities": ("tests.unit", "TestUtilities"),
    "TestUtilitiesCheckerFullCoverage": (
        "tests.unit",
        "TestUtilitiesCheckerFullCoverage",
    ),
    "TestUtilitiesCollectionCoverage": (
        "tests.unit",
        "TestUtilitiesCollectionCoverage",
    ),
    "TestUtilitiesCollectionFullCoverage": (
        "tests.unit",
        "TestUtilitiesCollectionFullCoverage",
    ),
    "TestUtilitiesConfigurationFullCoverage": (
        "tests.unit",
        "TestUtilitiesConfigurationFullCoverage",
    ),
    "TestUtilitiesContextFullCoverage": (
        "tests.unit",
        "TestUtilitiesContextFullCoverage",
    ),
    "TestUtilitiesCoverage": ("tests.unit", "TestUtilitiesCoverage"),
    "TestUtilitiesDataMapper": ("tests.unit", "TestUtilitiesDataMapper"),
    "TestUtilitiesDomainFullCoverage": (
        "tests.unit",
        "TestUtilitiesDomainFullCoverage",
    ),
    "TestUtilitiesEnumFullCoverage": ("tests.unit", "TestUtilitiesEnumFullCoverage"),
    "TestUtilitiesGeneratorsFullCoverage": (
        "tests.unit",
        "TestUtilitiesGeneratorsFullCoverage",
    ),
    "TestUtilitiesParserFullCoverage": (
        "tests.unit",
        "TestUtilitiesParserFullCoverage",
    ),
    "TestUtilitiesTextFullCoverage": ("tests.unit", "TestUtilitiesTextFullCoverage"),
    "TestUtilitiesTypeGuardsCoverage100": (
        "tests.unit",
        "TestUtilitiesTypeGuardsCoverage100",
    ),
    "TestUtils": ("tests.test_utils", "TestUtils"),
    "TestWorkspaceLevelRefactor": ("tests.integration", "TestWorkspaceLevelRefactor"),
    "Teste": ("tests.unit", "Teste"),
    "Testr": ("tests.unit", "Testr"),
    "TestrCoverage": ("tests.unit", "TestrCoverage"),
    "TestsCore": ("tests.unit", "TestsCore"),
    "TestsFlextConstants": ("tests.constants", "TestsFlextConstants"),
    "TestsFlextModels": ("tests.models", "TestsFlextModels"),
    "TestsFlextProtocols": ("tests.protocols", "TestsFlextProtocols"),
    "TestsFlextServiceBase": ("tests.base", "TestsFlextServiceBase"),
    "TestsFlextTypes": ("tests.typings", "TestsFlextTypes"),
    "Testu": ("tests.unit", "Testu"),
    "TestuCacheClearObjectCache": ("tests.unit", "TestuCacheClearObjectCache"),
    "TestuCacheGenerateCacheKey": ("tests.unit", "TestuCacheGenerateCacheKey"),
    "TestuCacheHasCacheAttributes": ("tests.unit", "TestuCacheHasCacheAttributes"),
    "TestuCacheLogger": ("tests.unit", "TestuCacheLogger"),
    "TestuCacheNormalizeComponent": ("tests.unit", "TestuCacheNormalizeComponent"),
    "TestuCacheSortDictKeys": ("tests.unit", "TestuCacheSortDictKeys"),
    "TestuCacheSortKey": ("tests.unit", "TestuCacheSortKey"),
    "TestuDomain": ("tests.unit", "TestuDomain"),
    "TestuMapperAccessors": ("tests.unit", "TestuMapperAccessors"),
    "TestuMapperAdvanced": ("tests.unit", "TestuMapperAdvanced"),
    "TestuMapperBuild": ("tests.unit", "TestuMapperBuild"),
    "TestuMapperConversions": ("tests.unit", "TestuMapperConversions"),
    "TestuMapperExtract": ("tests.unit", "TestuMapperExtract"),
    "TestuMapperUtils": ("tests.unit", "TestuMapperUtils"),
    "TestuStringParser": ("tests.unit", "TestuStringParser"),
    "TestuTypeChecker": ("tests.unit", "TestuTypeChecker"),
    "TextUtilityContract": ("tests.unit", "TextUtilityContract"),
    "TimeoutEnforcer": ("tests.unit", "TimeoutEnforcer"),
    "UnknownHint": ("tests.unit", "UnknownHint"),
    "User": ("tests.helpers", "User"),
    "UserFactory": ("tests.helpers", "UserFactory"),
    "UtilitiesCacheCoverage100Namespace": (
        "tests.unit",
        "UtilitiesCacheCoverage100Namespace",
    ),
    "UtilitiesMapperCoverage100Namespace": (
        "tests.unit",
        "UtilitiesMapperCoverage100Namespace",
    ),
    "UtilitiesMapperFullCoverageNamespace": (
        "tests.unit",
        "UtilitiesMapperFullCoverageNamespace",
    ),
    "ValidatingService": ("tests.helpers", "ValidatingService"),
    "ValidatingServiceAuto": ("tests.helpers", "ValidatingServiceAuto"),
    "ValidatingServiceAutoFactory": ("tests.helpers", "ValidatingServiceAutoFactory"),
    "ValidatingServiceFactory": ("tests.helpers", "ValidatingServiceFactory"),
    "assert_rejects": ("tests.conftest", "assert_rejects"),
    "assert_validates": ("tests.conftest", "assert_validates"),
    "assertion_helpers": ("tests.test_utils", "assertion_helpers"),
    "benchmark": ("tests.benchmark", ""),
    "c": ("tests.constants", "TestsFlextConstants"),
    "clean_container": ("tests.conftest", "clean_container"),
    "contracts": ("tests.unit", "contracts"),
    "create_compare_entities_cases": ("tests.unit", "create_compare_entities_cases"),
    "create_compare_value_objects_cases": (
        "tests.unit",
        "create_compare_value_objects_cases",
    ),
    "create_hash_entity_cases": ("tests.unit", "create_hash_entity_cases"),
    "create_hash_value_object_cases": ("tests.unit", "create_hash_value_object_cases"),
    "create_validate_entity_has_id_cases": (
        "tests.unit",
        "create_validate_entity_has_id_cases",
    ),
    "create_validate_value_object_immutable_cases": (
        "tests.unit",
        "create_validate_value_object_immutable_cases",
    ),
    "d": ("flext_infra", "d"),
    "e": ("flext_infra", "e"),
    "empty_strings": ("tests.conftest", "empty_strings"),
    "fixture_factory": ("tests.test_utils", "fixture_factory"),
    "flext_result_failure": ("tests.conftest", "flext_result_failure"),
    "flext_result_success": ("tests.conftest", "flext_result_success"),
    "flext_tests": ("tests.unit", "flext_tests"),
    "generators_module": ("tests.unit", "generators_module"),
    "get_memory_usage": ("tests.benchmark", "get_memory_usage"),
    "h": ("flext_infra", "h"),
    "handlers_module": ("tests.unit", "handlers_module"),
    "helpers": ("tests.helpers", ""),
    "infra_git": ("tests.unit", "infra_git"),
    "infra_git_repo": ("tests.unit", "infra_git_repo"),
    "infra_io": ("tests.unit", "infra_io"),
    "infra_path": ("tests.unit", "infra_path"),
    "infra_patterns": ("tests.unit", "infra_patterns"),
    "infra_pr_manager": ("tests.unit", "infra_pr_manager"),
    "infra_pr_workspace_manager": ("tests.unit", "infra_pr_workspace_manager"),
    "infra_reporting": ("tests.unit", "infra_reporting"),
    "infra_safe_command_output": ("tests.unit", "infra_safe_command_output"),
    "infra_selection": ("tests.unit", "infra_selection"),
    "infra_subprocess": ("tests.unit", "infra_subprocess"),
    "infra_templates": ("tests.unit", "infra_templates"),
    "infra_test_workspace": ("tests.unit", "infra_test_workspace"),
    "infra_toml": ("tests.unit", "infra_toml"),
    "infra_workflow_linter": ("tests.unit", "infra_workflow_linter"),
    "infra_workflow_syncer": ("tests.unit", "infra_workflow_syncer"),
    "inject": ("tests.unit", "inject"),
    "integration": ("tests.integration", ""),
    "invalid_hostnames": ("tests.conftest", "invalid_hostnames"),
    "invalid_port_numbers": ("tests.conftest", "invalid_port_numbers"),
    "invalid_uris": ("tests.conftest", "invalid_uris"),
    "m": ("tests.models", "TestsFlextModels"),
    "mapper": ("tests.unit", "mapper"),
    "mock_external_service": ("tests.conftest", "mock_external_service"),
    "out_of_range": ("tests.conftest", "out_of_range"),
    "p": ("tests.protocols", "TestsFlextProtocols"),
    "parser_scenarios": ("tests.conftest", "parser_scenarios"),
    "patterns": ("tests.integration", "patterns"),
    "pytestmark": ("tests.integration", "pytestmark"),
    "r": ("flext_infra", "r"),
    "reliability_scenarios": ("tests.conftest", "reliability_scenarios"),
    "reset_all_factories": ("tests.helpers", "reset_all_factories"),
    "reset_global_container": ("tests.conftest", "reset_global_container"),
    "reset_runtime_state": ("tests.unit", "reset_runtime_state"),
    "runtime_cov_tests": ("tests.unit", "runtime_cov_tests"),
    "runtime_module": ("tests.unit", "runtime_module"),
    "runtime_tests": ("tests.unit", "runtime_tests"),
    "s": ("flext_infra", "s"),
    "sample_data": ("tests.conftest", "sample_data"),
    "t": ("tests.typings", "TestsFlextTypes"),
    "temp_dir": ("tests.conftest", "temp_dir"),
    "temp_directory": ("tests.conftest", "temp_directory"),
    "temp_file": ("tests.conftest", "temp_file"),
    "test_accessor_take_pick_as_or_flat_and_agg_branches": (
        "tests.unit",
        "test_accessor_take_pick_as_or_flat_and_agg_branches",
    ),
    "test_aliases_are_available": ("tests.unit", "test_aliases_are_available"),
    "test_args_get_enum_params_annotated_unwrap_branch": (
        "tests.unit",
        "test_args_get_enum_params_annotated_unwrap_branch",
    ),
    "test_args_get_enum_params_branches": (
        "tests.unit",
        "test_args_get_enum_params_branches",
    ),
    "test_async_log_writer_paths": ("tests.unit", "test_async_log_writer_paths"),
    "test_async_log_writer_shutdown_with_full_queue": (
        "tests.unit",
        "test_async_log_writer_shutdown_with_full_queue",
    ),
    "test_at_take_and_as_branches": ("tests.unit", "test_at_take_and_as_branches"),
    "test_authentication_error_normalizes_extra_kwargs_into_context": (
        "tests.unit",
        "test_authentication_error_normalizes_extra_kwargs_into_context",
    ),
    "test_bad_string_and_bad_bool_raise_value_error": (
        "tests.unit",
        "test_bad_string_and_bad_bool_raise_value_error",
    ),
    "test_base_error_normalize_metadata_merges_existing_metadata_model": (
        "tests.unit",
        "test_base_error_normalize_metadata_merges_existing_metadata_model",
    ),
    "test_basic_imports_work": ("tests.unit", "test_basic_imports_work"),
    "test_build_apply_transform_and_process_error_paths": (
        "tests.unit",
        "test_build_apply_transform_and_process_error_paths",
    ),
    "test_canonical_aliases_are_available": (
        "tests.unit",
        "test_canonical_aliases_are_available",
    ),
    "test_centralize_pydantic_cli_outputs_extended_metrics": (
        "tests.unit",
        "test_centralize_pydantic_cli_outputs_extended_metrics",
    ),
    "test_centralizer_converts_typed_dict_factory_to_model": (
        "tests.unit",
        "test_centralizer_converts_typed_dict_factory_to_model",
    ),
    "test_centralizer_does_not_touch_settings_module": (
        "tests.unit",
        "test_centralizer_does_not_touch_settings_module",
    ),
    "test_centralizer_moves_dict_alias_in_typings_without_keyword_name": (
        "tests.unit",
        "test_centralizer_moves_dict_alias_in_typings_without_keyword_name",
    ),
    "test_centralizer_moves_manual_type_aliases_to_models_file": (
        "tests.unit",
        "test_centralizer_moves_manual_type_aliases_to_models_file",
    ),
    "test_chk_exercises_missed_branches": (
        "tests.unit",
        "test_chk_exercises_missed_branches",
    ),
    "test_circuit_breaker_transitions_and_metrics": (
        "tests.unit",
        "test_circuit_breaker_transitions_and_metrics",
    ),
    "test_class_nesting_appends_to_existing_namespace_and_removes_pass": (
        "tests.unit",
        "test_class_nesting_appends_to_existing_namespace_and_removes_pass",
    ),
    "test_class_nesting_keeps_unmapped_top_level_classes": (
        "tests.unit",
        "test_class_nesting_keeps_unmapped_top_level_classes",
    ),
    "test_class_nesting_moves_top_level_class_into_new_namespace": (
        "tests.unit",
        "test_class_nesting_moves_top_level_class_into_new_namespace",
    ),
    "test_class_nesting_refactor_single_file_end_to_end": (
        "tests.integration",
        "test_class_nesting_refactor_single_file_end_to_end",
    ),
    "test_clear_keys_values_items_and_validate_branches": (
        "tests.unit",
        "test_clear_keys_values_items_and_validate_branches",
    ),
    "test_command_pagination_limit": ("tests.unit", "test_command_pagination_limit"),
    "test_config_bridge_and_trace_context_and_http_validation": (
        "tests.unit",
        "test_config_bridge_and_trace_context_and_http_validation",
    ),
    "test_configuration_mapping_and_dict_negative_branches": (
        "tests.unit",
        "test_configuration_mapping_and_dict_negative_branches",
    ),
    "test_configure_structlog_edge_paths": (
        "tests.unit",
        "test_configure_structlog_edge_paths",
    ),
    "test_configure_structlog_print_logger_factory_fallback": (
        "tests.unit",
        "test_configure_structlog_print_logger_factory_fallback",
    ),
    "test_constants_auto_enum_and_bimapping_paths": (
        "tests.unit",
        "test_constants_auto_enum_and_bimapping_paths",
    ),
    "test_construct_transform_and_deep_eq_branches": (
        "tests.unit",
        "test_construct_transform_and_deep_eq_branches",
    ),
    "test_container_and_service_domain_paths": (
        "tests.unit",
        "test_container_and_service_domain_paths",
    ),
    "test_container_resource_registration_metadata_normalized": (
        "tests.unit",
        "test_container_resource_registration_metadata_normalized",
    ),
    "test_context": ("tests.conftest", "test_context"),
    "test_context_data_metadata_normalizer_removed": (
        "tests.unit",
        "test_context_data_metadata_normalizer_removed",
    ),
    "test_context_data_normalize_and_json_checks": (
        "tests.unit",
        "test_context_data_normalize_and_json_checks",
    ),
    "test_context_data_validate_dict_serializable_error_paths": (
        "tests.unit",
        "test_context_data_validate_dict_serializable_error_paths",
    ),
    "test_context_data_validate_dict_serializable_none_and_mapping": (
        "tests.unit",
        "test_context_data_validate_dict_serializable_none_and_mapping",
    ),
    "test_context_data_validate_dict_serializable_real_dicts": (
        "tests.unit",
        "test_context_data_validate_dict_serializable_real_dicts",
    ),
    "test_context_export_serializable_and_validators": (
        "tests.unit",
        "test_context_export_serializable_and_validators",
    ),
    "test_context_export_statistics_validator_and_computed_fields": (
        "tests.unit",
        "test_context_export_statistics_validator_and_computed_fields",
    ),
    "test_context_export_validate_dict_serializable_mapping_and_models": (
        "tests.unit",
        "test_context_export_validate_dict_serializable_mapping_and_models",
    ),
    "test_context_export_validate_dict_serializable_valid": (
        "tests.unit",
        "test_context_export_validate_dict_serializable_valid",
    ),
    "test_conversion_add_converted_and_error_metadata_append_paths": (
        "tests.unit",
        "test_conversion_add_converted_and_error_metadata_append_paths",
    ),
    "test_conversion_add_skipped_skip_reason_upsert_paths": (
        "tests.unit",
        "test_conversion_add_skipped_skip_reason_upsert_paths",
    ),
    "test_conversion_add_warning_metadata_append_paths": (
        "tests.unit",
        "test_conversion_add_warning_metadata_append_paths",
    ),
    "test_conversion_and_extract_success_branches": (
        "tests.unit",
        "test_conversion_and_extract_success_branches",
    ),
    "test_conversion_start_and_complete_methods": (
        "tests.unit",
        "test_conversion_start_and_complete_methods",
    ),
    "test_conversion_string_and_join_paths": (
        "tests.unit",
        "test_conversion_string_and_join_paths",
    ),
    "test_convert_default_fallback_matrix": (
        "tests.unit",
        "test_convert_default_fallback_matrix",
    ),
    "test_convert_sequence_branch_returns_tuple": (
        "tests.unit",
        "test_convert_sequence_branch_returns_tuple",
    ),
    "test_cqrs_query_resolve_deeper_and_int_pagination": (
        "tests.unit",
        "test_cqrs_query_resolve_deeper_and_int_pagination",
    ),
    "test_create_auto_discover_and_mode_mapping": (
        "tests.unit",
        "test_create_auto_discover_and_mode_mapping",
    ),
    "test_create_from_callable_and_repr": (
        "tests.unit",
        "test_create_from_callable_and_repr",
    ),
    "test_create_merges_metadata_dict_branch": (
        "tests.unit",
        "test_create_merges_metadata_dict_branch",
    ),
    "test_create_overloads_and_auto_correlation": (
        "tests.unit",
        "test_create_overloads_and_auto_correlation",
    ),
    "test_data_factory": ("tests.test_utils", "test_data_factory"),
    "test_decorators_family_blocks_dispatcher_target": (
        "tests.unit",
        "test_decorators_family_blocks_dispatcher_target",
    ),
    "test_dependency_integration_and_wiring_paths": (
        "tests.unit",
        "test_dependency_integration_and_wiring_paths",
    ),
    "test_dependency_registration_duplicate_guards": (
        "tests.unit",
        "test_dependency_registration_duplicate_guards",
    ),
    "test_deprecated_class_noop_init_branch": (
        "tests.unit",
        "test_deprecated_class_noop_init_branch",
    ),
    "test_discover_project_roots_without_nested_git_dirs": (
        "tests.unit",
        "test_discover_project_roots_without_nested_git_dirs",
    ),
    "test_dispatcher_family_blocks_models_target": (
        "tests.unit",
        "test_dispatcher_family_blocks_models_target",
    ),
    "test_dispatcher_reliability_branch_paths": (
        "tests.unit",
        "test_dispatcher_reliability_branch_paths",
    ),
    "test_ensure_and_extract_array_index_helpers": (
        "tests.unit",
        "test_ensure_and_extract_array_index_helpers",
    ),
    "test_ensure_trace_context_dict_conversion_paths": (
        "tests.unit",
        "test_ensure_trace_context_dict_conversion_paths",
    ),
    "test_ensure_utc_datetime_adds_tzinfo_when_naive": (
        "tests.unit",
        "test_ensure_utc_datetime_adds_tzinfo_when_naive",
    ),
    "test_ensure_utc_datetime_preserves_aware": (
        "tests.unit",
        "test_ensure_utc_datetime_preserves_aware",
    ),
    "test_ensure_utc_datetime_returns_none_on_none": (
        "tests.unit",
        "test_ensure_utc_datetime_returns_none_on_none",
    ),
    "test_entity_comparable_map_and_bulk_validation_paths": (
        "tests.unit",
        "test_entity_comparable_map_and_bulk_validation_paths",
    ),
    "test_exceptions_uncovered_metadata_paths": (
        "tests.unit",
        "test_exceptions_uncovered_metadata_paths",
    ),
    "test_execute_and_register_handler_failure_paths": (
        "tests.unit",
        "test_execute_and_register_handler_failure_paths",
    ),
    "test_export_paths_with_metadata_and_statistics": (
        "tests.unit",
        "test_export_paths_with_metadata_and_statistics",
    ),
    "test_extract_error_paths_and_prop_accessor": (
        "tests.unit",
        "test_extract_error_paths_and_prop_accessor",
    ),
    "test_extract_field_value_and_ensure_variants": (
        "tests.unit",
        "test_extract_field_value_and_ensure_variants",
    ),
    "test_extract_mapping_or_none_branches": (
        "tests.unit",
        "test_extract_mapping_or_none_branches",
    ),
    "test_facade_binding_is_correct": ("tests.unit", "test_facade_binding_is_correct"),
    "test_field_and_fields_multi_branches": (
        "tests.unit",
        "test_field_and_fields_multi_branches",
    ),
    "test_filter_map_normalize_convert_helpers": (
        "tests.unit",
        "test_filter_map_normalize_convert_helpers",
    ),
    "test_flext_message_type_alias_adapter": (
        "tests.unit",
        "test_flext_message_type_alias_adapter",
    ),
    "test_flow_through_short_circuits_on_failure": (
        "tests.unit",
        "test_flow_through_short_circuits_on_failure",
    ),
    "test_from_validation_and_to_model_paths": (
        "tests.unit",
        "test_from_validation_and_to_model_paths",
    ),
    "test_general_value_helpers_and_logger": (
        "tests.unit",
        "test_general_value_helpers_and_logger",
    ),
    "test_get_logger_none_name_paths": (
        "tests.unit",
        "test_get_logger_none_name_paths",
    ),
    "test_get_plugin_and_register_metadata_and_list_items_exception": (
        "tests.unit",
        "test_get_plugin_and_register_metadata_and_list_items_exception",
    ),
    "test_get_service_info": ("tests.unit", "test_get_service_info"),
    "test_group_sort_unique_slice_chunk_branches": (
        "tests.unit",
        "test_group_sort_unique_slice_chunk_branches",
    ),
    "test_guard_in_has_empty_none_helpers": (
        "tests.unit",
        "test_guard_in_has_empty_none_helpers",
    ),
    "test_guard_instance_attribute_access_warnings": (
        "tests.unit",
        "test_guard_instance_attribute_access_warnings",
    ),
    "test_guards_bool_identity_branch_via_isinstance_fallback": (
        "tests.unit",
        "test_guards_bool_identity_branch_via_isinstance_fallback",
    ),
    "test_guards_bool_shortcut_and_issubclass_typeerror": (
        "tests.unit",
        "test_guards_bool_shortcut_and_issubclass_typeerror",
    ),
    "test_guards_handler_type_issubclass_typeerror_branch_direct": (
        "tests.unit",
        "test_guards_handler_type_issubclass_typeerror_branch_direct",
    ),
    "test_guards_issubclass_success_when_callable_is_patched": (
        "tests.unit",
        "test_guards_issubclass_success_when_callable_is_patched",
    ),
    "test_guards_issubclass_typeerror_when_class_not_treated_as_callable": (
        "tests.unit",
        "test_guards_issubclass_typeerror_when_class_not_treated_as_callable",
    ),
    "test_handler_builder_fluent_methods": (
        "tests.unit",
        "test_handler_builder_fluent_methods",
    ),
    "test_helper_consolidation_is_prechecked": (
        "tests.unit",
        "test_helper_consolidation_is_prechecked",
    ),
    "test_inactive_and_none_value_paths": (
        "tests.unit",
        "test_inactive_and_none_value_paths",
    ),
    "test_init_fallback_and_lazy_returns_result_property": (
        "tests.unit",
        "test_init_fallback_and_lazy_returns_result_property",
    ),
    "test_invert_and_json_conversion_branches": (
        "tests.unit",
        "test_invert_and_json_conversion_branches",
    ),
    "test_is_container_negative_paths_and_callable": (
        "tests.unit",
        "test_is_container_negative_paths_and_callable",
    ),
    "test_is_flexible_value_covers_all_branches": (
        "tests.unit",
        "test_is_flexible_value_covers_all_branches",
    ),
    "test_is_handler_type_branches": ("tests.unit", "test_is_handler_type_branches"),
    "test_is_type_non_empty_unknown_and_tuple_and_fallback": (
        "tests.unit",
        "test_is_type_non_empty_unknown_and_tuple_and_fallback",
    ),
    "test_is_type_protocol_fallback_branches": (
        "tests.unit",
        "test_is_type_protocol_fallback_branches",
    ),
    "test_is_valid_handles_validation_exception": (
        "tests.unit",
        "test_is_valid_handles_validation_exception",
    ),
    "test_lash_runtime_result_paths": ("tests.unit", "test_lash_runtime_result_paths"),
    "test_map_error_identity_and_transform": (
        "tests.unit",
        "test_map_error_identity_and_transform",
    ),
    "test_map_flags_collect_and_invert_branches": (
        "tests.unit",
        "test_map_flags_collect_and_invert_branches",
    ),
    "test_map_flat_map_and_then_paths": (
        "tests.unit",
        "test_map_flat_map_and_then_paths",
    ),
    "test_merge_defaults_and_dump_paths": (
        "tests.unit",
        "test_merge_defaults_and_dump_paths",
    ),
    "test_merge_metadata_context_paths": (
        "tests.unit",
        "test_merge_metadata_context_paths",
    ),
    "test_migrate_protocols_rewrites_references_with_p_alias": (
        "tests.unit",
        "test_migrate_protocols_rewrites_references_with_p_alias",
    ),
    "test_migrate_to_mro_inlines_alias_constant_into_constants_class": (
        "tests.unit",
        "test_migrate_to_mro_inlines_alias_constant_into_constants_class",
    ),
    "test_migrate_to_mro_moves_constant_and_rewrites_reference": (
        "tests.unit",
        "test_migrate_to_mro_moves_constant_and_rewrites_reference",
    ),
    "test_migrate_to_mro_moves_manual_uppercase_assignment": (
        "tests.unit",
        "test_migrate_to_mro_moves_manual_uppercase_assignment",
    ),
    "test_migrate_to_mro_normalizes_facade_alias_to_c": (
        "tests.unit",
        "test_migrate_to_mro_normalizes_facade_alias_to_c",
    ),
    "test_migrate_to_mro_rejects_unknown_target": (
        "tests.unit",
        "test_migrate_to_mro_rejects_unknown_target",
    ),
    "test_migrate_typings_rewrites_references_with_t_alias": (
        "tests.unit",
        "test_migrate_typings_rewrites_references_with_t_alias",
    ),
    "test_model_helpers_remaining_paths": (
        "tests.unit",
        "test_model_helpers_remaining_paths",
    ),
    "test_model_support_and_hash_compare_paths": (
        "tests.unit",
        "test_model_support_and_hash_compare_paths",
    ),
    "test_models_family_blocks_utilities_target": (
        "tests.unit",
        "test_models_family_blocks_utilities_target",
    ),
    "test_models_handler_branches": ("tests.unit", "test_models_handler_branches"),
    "test_models_handler_uncovered_mode_and_reset_paths": (
        "tests.unit",
        "test_models_handler_uncovered_mode_and_reset_paths",
    ),
    "test_models_settings_branch_paths": (
        "tests.unit",
        "test_models_settings_branch_paths",
    ),
    "test_models_settings_context_validator_and_non_standard_status_input": (
        "tests.unit",
        "test_models_settings_context_validator_and_non_standard_status_input",
    ),
    "test_mro_scanner_includes_constants_variants_in_all_scopes": (
        "tests.unit",
        "test_mro_scanner_includes_constants_variants_in_all_scopes",
    ),
    "test_namespace_enforce_cli_fails_on_manual_protocol_violation": (
        "tests.unit",
        "test_namespace_enforce_cli_fails_on_manual_protocol_violation",
    ),
    "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring": (
        "tests.unit",
        "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring",
    ),
    "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future": (
        "tests.unit",
        "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future",
    ),
    "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file": (
        "tests.unit",
        "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file",
    ),
    "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports": (
        "tests.unit",
        "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports",
    ),
    "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory": (
        "tests.unit",
        "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory",
    ),
    "test_namespace_enforcer_detects_internal_private_imports": (
        "tests.unit",
        "test_namespace_enforcer_detects_internal_private_imports",
    ),
    "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files": (
        "tests.unit",
        "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files",
    ),
    "test_namespace_enforcer_detects_manual_typings_and_compat_aliases": (
        "tests.unit",
        "test_namespace_enforcer_detects_manual_typings_and_compat_aliases",
    ),
    "test_namespace_enforcer_detects_missing_runtime_alias_outside_src": (
        "tests.unit",
        "test_namespace_enforcer_detects_missing_runtime_alias_outside_src",
    ),
    "test_namespace_enforcer_does_not_rewrite_indented_import_aliases": (
        "tests.unit",
        "test_namespace_enforcer_does_not_rewrite_indented_import_aliases",
    ),
    "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks": (
        "tests.unit",
        "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks",
    ),
    "test_narrow_contextvar_exception_branch": (
        "tests.unit",
        "test_narrow_contextvar_exception_branch",
    ),
    "test_narrow_contextvar_invalid_inputs": (
        "tests.unit",
        "test_narrow_contextvar_invalid_inputs",
    ),
    "test_narrow_to_string_keyed_dict_and_mapping_paths": (
        "tests.unit",
        "test_narrow_to_string_keyed_dict_and_mapping_paths",
    ),
    "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage": (
        "tests.unit",
        "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage",
    ),
    "test_nested_class_propagation_updates_import_annotations_and_calls": (
        "tests.unit",
        "test_nested_class_propagation_updates_import_annotations_and_calls",
    ),
    "test_non_empty_and_normalize_branches": (
        "tests.unit",
        "test_non_empty_and_normalize_branches",
    ),
    "test_normalization_edge_branches": (
        "tests.unit",
        "test_normalization_edge_branches",
    ),
    "test_normalize_to_container_alias_removal_path": (
        "tests.unit",
        "test_normalize_to_container_alias_removal_path",
    ),
    "test_normalize_to_list_passes_list_through": (
        "tests.unit",
        "test_normalize_to_list_passes_list_through",
    ),
    "test_normalize_to_list_wraps_int": (
        "tests.unit",
        "test_normalize_to_list_wraps_int",
    ),
    "test_normalize_to_list_wraps_scalar": (
        "tests.unit",
        "test_normalize_to_list_wraps_scalar",
    ),
    "test_normalize_to_metadata_alias_removal_path": (
        "tests.unit",
        "test_normalize_to_metadata_alias_removal_path",
    ),
    "test_normalize_to_pydantic_dict_and_value_branches": (
        "tests.unit",
        "test_normalize_to_pydantic_dict_and_value_branches",
    ),
    "test_not_found_error_correlation_id_selection_and_extra_kwargs": (
        "tests.unit",
        "test_not_found_error_correlation_id_selection_and_extra_kwargs",
    ),
    "test_ok_accepts_none": ("tests.unit", "test_ok_accepts_none"),
    "test_operation_progress_start_operation_sets_runtime_fields": (
        "tests.unit",
        "test_operation_progress_start_operation_sets_runtime_fields",
    ),
    "test_pagination_response_string_fallbacks": (
        "tests.unit",
        "test_pagination_response_string_fallbacks",
    ),
    "test_process_context_data_and_related_convenience": (
        "tests.unit",
        "test_process_context_data_and_related_convenience",
    ),
    "test_protocol_and_simple_guard_helpers": (
        "tests.unit",
        "test_protocol_and_simple_guard_helpers",
    ),
    "test_query_resolve_pagination_wrapper_and_fallback": (
        "tests.unit",
        "test_query_resolve_pagination_wrapper_and_fallback",
    ),
    "test_query_validate_pagination_dict_and_default": (
        "tests.unit",
        "test_query_validate_pagination_dict_and_default",
    ),
    "test_rate_limiter_blocks_then_recovers": (
        "tests.unit",
        "test_rate_limiter_blocks_then_recovers",
    ),
    "test_rate_limiter_jitter_application": (
        "tests.unit",
        "test_rate_limiter_jitter_application",
    ),
    "test_reconfigure_and_reset_state_paths": (
        "tests.unit",
        "test_reconfigure_and_reset_state_paths",
    ),
    "test_recover_tap_and_tap_error_paths": (
        "tests.unit",
        "test_recover_tap_and_tap_error_paths",
    ),
    "test_refactor_utilities_iter_python_files_includes_examples_and_scripts": (
        "tests.unit",
        "test_refactor_utilities_iter_python_files_includes_examples_and_scripts",
    ),
    "test_remaining_build_fields_construct_and_eq_paths": (
        "tests.unit",
        "test_remaining_build_fields_construct_and_eq_paths",
    ),
    "test_remaining_uncovered_branches": (
        "tests.unit",
        "test_remaining_uncovered_branches",
    ),
    "test_result_property_raises_on_failure": (
        "tests.unit",
        "test_result_property_raises_on_failure",
    ),
    "test_retry_policy_behavior": ("tests.unit", "test_retry_policy_behavior"),
    "test_reuse_existing_runtime_coverage_branches": (
        "tests.unit",
        "test_reuse_existing_runtime_coverage_branches",
    ),
    "test_reuse_existing_runtime_scenarios": (
        "tests.unit",
        "test_reuse_existing_runtime_scenarios",
    ),
    "test_runtime_create_instance_failure_branch": (
        "tests.unit",
        "test_runtime_create_instance_failure_branch",
    ),
    "test_runtime_family_blocks_non_runtime_target": (
        "tests.unit",
        "test_runtime_family_blocks_non_runtime_target",
    ),
    "test_runtime_integration_tracking_paths": (
        "tests.unit",
        "test_runtime_integration_tracking_paths",
    ),
    "test_runtime_misc_remaining_paths": (
        "tests.unit",
        "test_runtime_misc_remaining_paths",
    ),
    "test_runtime_module_accessors_and_metadata": (
        "tests.unit",
        "test_runtime_module_accessors_and_metadata",
    ),
    "test_runtime_result_alias_compatibility": (
        "tests.unit",
        "test_runtime_result_alias_compatibility",
    ),
    "test_runtime_result_all_missed_branches": (
        "tests.unit",
        "test_runtime_result_all_missed_branches",
    ),
    "test_runtime_result_remaining_paths": (
        "tests.unit",
        "test_runtime_result_remaining_paths",
    ),
    "test_scope_data_validators_and_errors": (
        "tests.unit",
        "test_scope_data_validators_and_errors",
    ),
    "test_service_request_timeout_post_validator_messages": (
        "tests.unit",
        "test_service_request_timeout_post_validator_messages",
    ),
    "test_service_request_timeout_validator_branches": (
        "tests.unit",
        "test_service_request_timeout_validator_branches",
    ),
    "test_set_set_all_get_validation_and_error_paths": (
        "tests.unit",
        "test_set_set_all_get_validation_and_error_paths",
    ),
    "test_settings_materialize_and_context_overrides": (
        "tests.unit",
        "test_settings_materialize_and_context_overrides",
    ),
    "test_small_mapper_convenience_methods": (
        "tests.unit",
        "test_small_mapper_convenience_methods",
    ),
    "test_statistics_and_custom_fields_validators": (
        "tests.unit",
        "test_statistics_and_custom_fields_validators",
    ),
    "test_strip_whitespace_preserves_clean": (
        "tests.unit",
        "test_strip_whitespace_preserves_clean",
    ),
    "test_strip_whitespace_returns_empty_on_spaces": (
        "tests.unit",
        "test_strip_whitespace_returns_empty_on_spaces",
    ),
    "test_strip_whitespace_trims_leading_trailing": (
        "tests.unit",
        "test_strip_whitespace_trims_leading_trailing",
    ),
    "test_structlog_proxy_context_var_default_when_key_missing": (
        "tests.unit",
        "test_structlog_proxy_context_var_default_when_key_missing",
    ),
    "test_structlog_proxy_context_var_get_set_reset_paths": (
        "tests.unit",
        "test_structlog_proxy_context_var_get_set_reset_paths",
    ),
    "test_summary_error_paths_and_bindings_failures": (
        "tests.unit",
        "test_summary_error_paths_and_bindings_failures",
    ),
    "test_summary_properties_and_subclass_storage_reset": (
        "tests.unit",
        "test_summary_properties_and_subclass_storage_reset",
    ),
    "test_to_general_value_dict_removed": (
        "tests.unit",
        "test_to_general_value_dict_removed",
    ),
    "test_transform_option_extract_and_step_helpers": (
        "tests.unit",
        "test_transform_option_extract_and_step_helpers",
    ),
    "test_type_guards_and_narrowing_failures": (
        "tests.unit",
        "test_type_guards_and_narrowing_failures",
    ),
    "test_type_guards_result": ("tests.unit", "test_type_guards_result"),
    "test_ultrawork_models_cli_runs_dry_run_copy": (
        "tests.unit",
        "test_ultrawork_models_cli_runs_dry_run_copy",
    ),
    "test_update_exception_path": ("tests.unit", "test_update_exception_path"),
    "test_update_statistics_remove_hook_and_clone_false_result": (
        "tests.unit",
        "test_update_statistics_remove_hook_and_clone_false_result",
    ),
    "test_update_success_path_returns_ok_result": (
        "tests.unit",
        "test_update_success_path_returns_ok_result",
    ),
    "test_utilities_family_allows_utilities_target": (
        "tests.unit",
        "test_utilities_family_allows_utilities_target",
    ),
    "test_utilities_reliability_branches": (
        "tests.unit",
        "test_utilities_reliability_branches",
    ),
    "test_utilities_reliability_compose_returns_non_result_directly": (
        "tests.unit",
        "test_utilities_reliability_compose_returns_non_result_directly",
    ),
    "test_utilities_reliability_uncovered_retry_compose_and_sequence_paths": (
        "tests.unit",
        "test_utilities_reliability_uncovered_retry_compose_and_sequence_paths",
    ),
    "test_validate_config_dict_normalizes_dict": (
        "tests.unit",
        "test_validate_config_dict_normalizes_dict",
    ),
    "test_validate_tags_list_from_string": (
        "tests.unit",
        "test_validate_tags_list_from_string",
    ),
    "test_validate_tags_list_normalizes": (
        "tests.unit",
        "test_validate_tags_list_normalizes",
    ),
    "test_validation_like_error_structure": (
        "tests.unit",
        "test_validation_like_error_structure",
    ),
    "test_with_resource_cleanup_runs": (
        "tests.unit",
        "test_with_resource_cleanup_runs",
    ),
    "u": ("tests.utilities", "FlextCoreTestUtilities"),
    "unit": ("tests.unit", ""),
    "valid_hostnames": ("tests.conftest", "valid_hostnames"),
    "valid_port_numbers": ("tests.conftest", "valid_port_numbers"),
    "valid_ranges": ("tests.conftest", "valid_ranges"),
    "valid_strings": ("tests.conftest", "valid_strings"),
    "valid_uris": ("tests.conftest", "valid_uris"),
    "validation_scenarios": ("tests.conftest", "validation_scenarios"),
    "whitespace_strings": ("tests.conftest", "whitespace_strings"),
    "x": ("flext_infra", "x"),
}

__all__ = [
    "AttrObject",
    "BadBool",
    "BadMapping",
    "BadString",
    "CircuitBreakerManager",
    "ClearCacheScenario",
    "ExplodingLenList",
    "FailingService",
    "FailingServiceAuto",
    "FailingServiceAutoFactory",
    "FailingServiceFactory",
    "FlextCoreTestUtilities",
    "FlextProtocols",
    "FlextTestResult",
    "FlextTestResultCo",
    "FunctionalExternalService",
    "GenericModelFactory",
    "GetUserService",
    "GetUserServiceAuto",
    "GetUserServiceAutoFactory",
    "GetUserServiceFactory",
    "NestedClassPropagationTransformer",
    "NormalizeComponentScenario",
    "Provide",
    "RateLimiterManager",
    "RetryPolicy",
    "RuntimeCloneService",
    "ServiceFactoryRegistry",
    "ServiceTestCase",
    "ServiceTestCaseFactory",
    "ServiceTestCases",
    "SimpleObj",
    "SortKeyScenario",
    "T",
    "TMessage",
    "T_co",
    "T_contra",
    "TestAdvancedPatterns",
    "TestArchitecturalPatterns",
    "TestAutomatedArchitecture",
    "TestAutomatedExceptions",
    "TestAutomatedFlextContainer",
    "TestAutomatedFlextContext",
    "TestAutomatedFlextDecorators",
    "TestAutomatedFlextDispatcher",
    "TestAutomatedFlextHandlers",
    "TestAutomatedFlextLogger",
    "TestAutomatedFlextMixins",
    "TestAutomatedFlextRegistry",
    "TestAutomatedFlextRuntime",
    "TestAutomatedFlextService",
    "TestAutomatedFlextSettings",
    "TestAutomatedFlextUtilities",
    "TestAutomatedResult",
    "TestCollectionUtilitiesCoverage",
    "TestCompleteFlextSystemIntegration",
    "TestConstants",
    "TestContainerFullCoverage",
    "TestContainerMemory",
    "TestContainerPerformance",
    "TestContext100Coverage",
    "TestCoverage76Lines",
    "TestCoverageContext",
    "TestCoverageExceptions",
    "TestCoverageLoggings",
    "TestCoverageModels",
    "TestDIIncremental",
    "TestDataGenerators",
    "TestDecoratorsDiscoveryFullCoverage",
    "TestDecoratorsFullCoverage",
    "TestDeprecationWarnings",
    "TestDiServicesAccess",
    "TestDispatcherDI",
    "TestDispatcherFullCoverage",
    "TestDispatcherMinimal",
    "TestDispatcherTimeoutCoverage100",
    "TestDocker",
    "TestDocumentedPatterns",
    "TestEntityCoverageEdgeCases",
    "TestEnumUtilitiesCoverage",
    "TestFinal75PercentPush",
    "TestFlextContainer",
    "TestFlextContext",
    "TestFlextDecorators",
    "TestFlextHandlers",
    "TestFlextInfraNamespaceValidator",
    "TestFlextMixinsNestedClasses",
    "TestFlextModelsCollectionsCoverage100",
    "TestFlextModelsContainer",
    "TestFlextProtocols",
    "TestFlextRegistry",
    "TestFlextRuntime",
    "TestFlextSettings",
    "TestFlextSettingsSingletonIntegration",
    "TestFlextTestsDomains",
    "TestFlextTestsFiles",
    "TestFlextTestsMatchers",
    "TestFlextUtilitiesArgs",
    "TestFlextUtilitiesConfiguration",
    "TestFlextUtilitiesReliability",
    "TestFlextVersion",
    "TestFunction",
    "TestHandlerDecoratorDiscovery",
    "TestHandlersFullCoverage",
    "TestHelperConsolidationTransformer",
    "TestHelperFactories",
    "TestHelperScenarios",
    "TestIdempotency",
    "TestInfraIntegration",
    "TestLibraryIntegration",
    "TestLoggingsErrorPaths",
    "TestLoggingsStrictReturns",
    "TestMigrationValidation",
    "TestMixinsFullCoverage",
    "TestModels",
    "TestModels79Coverage",
    "TestModelsBaseFullCoverage",
    "TestModelsCollectionsFullCoverage",
    "TestModule",
    "TestPaginationCoverage100",
    "TestPatternsCommands",
    "TestPatternsLogging",
    "TestPatternsTesting",
    "TestPerformanceBenchmarks",
    "TestPhase2CoverageFinal",
    "TestProjectLevelRefactor",
    "TestRefactorPolicyMRO",
    "TestResultExceptionCarrying",
    "TestRuntimeCoverage100",
    "TestService",
    "TestService100Coverage",
    "TestServiceBootstrap",
    "TestServiceFullCoverage",
    "TestServiceResultProperty",
    "TestTypings",
    "TestTypingsFullCoverage",
    "TestUtilities",
    "TestUtilitiesCheckerFullCoverage",
    "TestUtilitiesCollectionCoverage",
    "TestUtilitiesCollectionFullCoverage",
    "TestUtilitiesConfigurationFullCoverage",
    "TestUtilitiesContextFullCoverage",
    "TestUtilitiesCoverage",
    "TestUtilitiesDataMapper",
    "TestUtilitiesDomainFullCoverage",
    "TestUtilitiesEnumFullCoverage",
    "TestUtilitiesGeneratorsFullCoverage",
    "TestUtilitiesParserFullCoverage",
    "TestUtilitiesTextFullCoverage",
    "TestUtilitiesTypeGuardsCoverage100",
    "TestUtils",
    "TestWorkspaceLevelRefactor",
    "Teste",
    "Testr",
    "TestrCoverage",
    "TestsCore",
    "TestsFlextConstants",
    "TestsFlextModels",
    "TestsFlextProtocols",
    "TestsFlextServiceBase",
    "TestsFlextTypes",
    "Testu",
    "TestuCacheClearObjectCache",
    "TestuCacheGenerateCacheKey",
    "TestuCacheHasCacheAttributes",
    "TestuCacheLogger",
    "TestuCacheNormalizeComponent",
    "TestuCacheSortDictKeys",
    "TestuCacheSortKey",
    "TestuDomain",
    "TestuMapperAccessors",
    "TestuMapperAdvanced",
    "TestuMapperBuild",
    "TestuMapperConversions",
    "TestuMapperExtract",
    "TestuMapperUtils",
    "TestuStringParser",
    "TestuTypeChecker",
    "TextUtilityContract",
    "TimeoutEnforcer",
    "UnknownHint",
    "User",
    "UserFactory",
    "UtilitiesCacheCoverage100Namespace",
    "UtilitiesMapperCoverage100Namespace",
    "UtilitiesMapperFullCoverageNamespace",
    "ValidatingService",
    "ValidatingServiceAuto",
    "ValidatingServiceAutoFactory",
    "ValidatingServiceFactory",
    "assert_rejects",
    "assert_validates",
    "assertion_helpers",
    "benchmark",
    "c",
    "clean_container",
    "contracts",
    "create_compare_entities_cases",
    "create_compare_value_objects_cases",
    "create_hash_entity_cases",
    "create_hash_value_object_cases",
    "create_validate_entity_has_id_cases",
    "create_validate_value_object_immutable_cases",
    "d",
    "e",
    "empty_strings",
    "fixture_factory",
    "flext_result_failure",
    "flext_result_success",
    "flext_tests",
    "generators_module",
    "get_memory_usage",
    "h",
    "handlers_module",
    "helpers",
    "infra_git",
    "infra_git_repo",
    "infra_io",
    "infra_path",
    "infra_patterns",
    "infra_pr_manager",
    "infra_pr_workspace_manager",
    "infra_reporting",
    "infra_safe_command_output",
    "infra_selection",
    "infra_subprocess",
    "infra_templates",
    "infra_test_workspace",
    "infra_toml",
    "infra_workflow_linter",
    "infra_workflow_syncer",
    "inject",
    "integration",
    "invalid_hostnames",
    "invalid_port_numbers",
    "invalid_uris",
    "m",
    "mapper",
    "mock_external_service",
    "out_of_range",
    "p",
    "parser_scenarios",
    "patterns",
    "pytestmark",
    "r",
    "reliability_scenarios",
    "reset_all_factories",
    "reset_global_container",
    "reset_runtime_state",
    "runtime_cov_tests",
    "runtime_module",
    "runtime_tests",
    "s",
    "sample_data",
    "t",
    "temp_dir",
    "temp_directory",
    "temp_file",
    "test_accessor_take_pick_as_or_flat_and_agg_branches",
    "test_aliases_are_available",
    "test_args_get_enum_params_annotated_unwrap_branch",
    "test_args_get_enum_params_branches",
    "test_async_log_writer_paths",
    "test_async_log_writer_shutdown_with_full_queue",
    "test_at_take_and_as_branches",
    "test_authentication_error_normalizes_extra_kwargs_into_context",
    "test_bad_string_and_bad_bool_raise_value_error",
    "test_base_error_normalize_metadata_merges_existing_metadata_model",
    "test_basic_imports_work",
    "test_build_apply_transform_and_process_error_paths",
    "test_canonical_aliases_are_available",
    "test_centralize_pydantic_cli_outputs_extended_metrics",
    "test_centralizer_converts_typed_dict_factory_to_model",
    "test_centralizer_does_not_touch_settings_module",
    "test_centralizer_moves_dict_alias_in_typings_without_keyword_name",
    "test_centralizer_moves_manual_type_aliases_to_models_file",
    "test_chk_exercises_missed_branches",
    "test_circuit_breaker_transitions_and_metrics",
    "test_class_nesting_appends_to_existing_namespace_and_removes_pass",
    "test_class_nesting_keeps_unmapped_top_level_classes",
    "test_class_nesting_moves_top_level_class_into_new_namespace",
    "test_class_nesting_refactor_single_file_end_to_end",
    "test_clear_keys_values_items_and_validate_branches",
    "test_command_pagination_limit",
    "test_config_bridge_and_trace_context_and_http_validation",
    "test_configuration_mapping_and_dict_negative_branches",
    "test_configure_structlog_edge_paths",
    "test_configure_structlog_print_logger_factory_fallback",
    "test_constants_auto_enum_and_bimapping_paths",
    "test_construct_transform_and_deep_eq_branches",
    "test_container_and_service_domain_paths",
    "test_container_resource_registration_metadata_normalized",
    "test_context",
    "test_context_data_metadata_normalizer_removed",
    "test_context_data_normalize_and_json_checks",
    "test_context_data_validate_dict_serializable_error_paths",
    "test_context_data_validate_dict_serializable_none_and_mapping",
    "test_context_data_validate_dict_serializable_real_dicts",
    "test_context_export_serializable_and_validators",
    "test_context_export_statistics_validator_and_computed_fields",
    "test_context_export_validate_dict_serializable_mapping_and_models",
    "test_context_export_validate_dict_serializable_valid",
    "test_conversion_add_converted_and_error_metadata_append_paths",
    "test_conversion_add_skipped_skip_reason_upsert_paths",
    "test_conversion_add_warning_metadata_append_paths",
    "test_conversion_and_extract_success_branches",
    "test_conversion_start_and_complete_methods",
    "test_conversion_string_and_join_paths",
    "test_convert_default_fallback_matrix",
    "test_convert_sequence_branch_returns_tuple",
    "test_cqrs_query_resolve_deeper_and_int_pagination",
    "test_create_auto_discover_and_mode_mapping",
    "test_create_from_callable_and_repr",
    "test_create_merges_metadata_dict_branch",
    "test_create_overloads_and_auto_correlation",
    "test_data_factory",
    "test_decorators_family_blocks_dispatcher_target",
    "test_dependency_integration_and_wiring_paths",
    "test_dependency_registration_duplicate_guards",
    "test_deprecated_class_noop_init_branch",
    "test_discover_project_roots_without_nested_git_dirs",
    "test_dispatcher_family_blocks_models_target",
    "test_dispatcher_reliability_branch_paths",
    "test_ensure_and_extract_array_index_helpers",
    "test_ensure_trace_context_dict_conversion_paths",
    "test_ensure_utc_datetime_adds_tzinfo_when_naive",
    "test_ensure_utc_datetime_preserves_aware",
    "test_ensure_utc_datetime_returns_none_on_none",
    "test_entity_comparable_map_and_bulk_validation_paths",
    "test_exceptions_uncovered_metadata_paths",
    "test_execute_and_register_handler_failure_paths",
    "test_export_paths_with_metadata_and_statistics",
    "test_extract_error_paths_and_prop_accessor",
    "test_extract_field_value_and_ensure_variants",
    "test_extract_mapping_or_none_branches",
    "test_facade_binding_is_correct",
    "test_field_and_fields_multi_branches",
    "test_filter_map_normalize_convert_helpers",
    "test_flext_message_type_alias_adapter",
    "test_flow_through_short_circuits_on_failure",
    "test_from_validation_and_to_model_paths",
    "test_general_value_helpers_and_logger",
    "test_get_logger_none_name_paths",
    "test_get_plugin_and_register_metadata_and_list_items_exception",
    "test_get_service_info",
    "test_group_sort_unique_slice_chunk_branches",
    "test_guard_in_has_empty_none_helpers",
    "test_guard_instance_attribute_access_warnings",
    "test_guards_bool_identity_branch_via_isinstance_fallback",
    "test_guards_bool_shortcut_and_issubclass_typeerror",
    "test_guards_handler_type_issubclass_typeerror_branch_direct",
    "test_guards_issubclass_success_when_callable_is_patched",
    "test_guards_issubclass_typeerror_when_class_not_treated_as_callable",
    "test_handler_builder_fluent_methods",
    "test_helper_consolidation_is_prechecked",
    "test_inactive_and_none_value_paths",
    "test_init_fallback_and_lazy_returns_result_property",
    "test_invert_and_json_conversion_branches",
    "test_is_container_negative_paths_and_callable",
    "test_is_flexible_value_covers_all_branches",
    "test_is_handler_type_branches",
    "test_is_type_non_empty_unknown_and_tuple_and_fallback",
    "test_is_type_protocol_fallback_branches",
    "test_is_valid_handles_validation_exception",
    "test_lash_runtime_result_paths",
    "test_map_error_identity_and_transform",
    "test_map_flags_collect_and_invert_branches",
    "test_map_flat_map_and_then_paths",
    "test_merge_defaults_and_dump_paths",
    "test_merge_metadata_context_paths",
    "test_migrate_protocols_rewrites_references_with_p_alias",
    "test_migrate_to_mro_inlines_alias_constant_into_constants_class",
    "test_migrate_to_mro_moves_constant_and_rewrites_reference",
    "test_migrate_to_mro_moves_manual_uppercase_assignment",
    "test_migrate_to_mro_normalizes_facade_alias_to_c",
    "test_migrate_to_mro_rejects_unknown_target",
    "test_migrate_typings_rewrites_references_with_t_alias",
    "test_model_helpers_remaining_paths",
    "test_model_support_and_hash_compare_paths",
    "test_models_family_blocks_utilities_target",
    "test_models_handler_branches",
    "test_models_handler_uncovered_mode_and_reset_paths",
    "test_models_settings_branch_paths",
    "test_models_settings_context_validator_and_non_standard_status_input",
    "test_mro_scanner_includes_constants_variants_in_all_scopes",
    "test_namespace_enforce_cli_fails_on_manual_protocol_violation",
    "test_namespace_enforcer_apply_inserts_future_after_single_line_module_docstring",
    "test_namespace_enforcer_apply_keeps_script_shebang_when_adding_future",
    "test_namespace_enforcer_apply_moves_manual_protocol_to_protocols_file",
    "test_namespace_enforcer_creates_missing_facades_and_rewrites_imports",
    "test_namespace_enforcer_detects_cyclic_imports_in_tests_directory",
    "test_namespace_enforcer_detects_internal_private_imports",
    "test_namespace_enforcer_detects_manual_protocol_outside_canonical_files",
    "test_namespace_enforcer_detects_manual_typings_and_compat_aliases",
    "test_namespace_enforcer_detects_missing_runtime_alias_outside_src",
    "test_namespace_enforcer_does_not_rewrite_indented_import_aliases",
    "test_namespace_enforcer_does_not_rewrite_multiline_import_alias_blocks",
    "test_narrow_contextvar_exception_branch",
    "test_narrow_contextvar_invalid_inputs",
    "test_narrow_to_string_keyed_dict_and_mapping_paths",
    "test_nested_class_propagation_preserves_asname_and_rewrites_alias_usage",
    "test_nested_class_propagation_updates_import_annotations_and_calls",
    "test_non_empty_and_normalize_branches",
    "test_normalization_edge_branches",
    "test_normalize_to_container_alias_removal_path",
    "test_normalize_to_list_passes_list_through",
    "test_normalize_to_list_wraps_int",
    "test_normalize_to_list_wraps_scalar",
    "test_normalize_to_metadata_alias_removal_path",
    "test_normalize_to_pydantic_dict_and_value_branches",
    "test_not_found_error_correlation_id_selection_and_extra_kwargs",
    "test_ok_accepts_none",
    "test_operation_progress_start_operation_sets_runtime_fields",
    "test_pagination_response_string_fallbacks",
    "test_process_context_data_and_related_convenience",
    "test_protocol_and_simple_guard_helpers",
    "test_query_resolve_pagination_wrapper_and_fallback",
    "test_query_validate_pagination_dict_and_default",
    "test_rate_limiter_blocks_then_recovers",
    "test_rate_limiter_jitter_application",
    "test_reconfigure_and_reset_state_paths",
    "test_recover_tap_and_tap_error_paths",
    "test_refactor_utilities_iter_python_files_includes_examples_and_scripts",
    "test_remaining_build_fields_construct_and_eq_paths",
    "test_remaining_uncovered_branches",
    "test_result_property_raises_on_failure",
    "test_retry_policy_behavior",
    "test_reuse_existing_runtime_coverage_branches",
    "test_reuse_existing_runtime_scenarios",
    "test_runtime_create_instance_failure_branch",
    "test_runtime_family_blocks_non_runtime_target",
    "test_runtime_integration_tracking_paths",
    "test_runtime_misc_remaining_paths",
    "test_runtime_module_accessors_and_metadata",
    "test_runtime_result_alias_compatibility",
    "test_runtime_result_all_missed_branches",
    "test_runtime_result_remaining_paths",
    "test_scope_data_validators_and_errors",
    "test_service_request_timeout_post_validator_messages",
    "test_service_request_timeout_validator_branches",
    "test_set_set_all_get_validation_and_error_paths",
    "test_settings_materialize_and_context_overrides",
    "test_small_mapper_convenience_methods",
    "test_statistics_and_custom_fields_validators",
    "test_strip_whitespace_preserves_clean",
    "test_strip_whitespace_returns_empty_on_spaces",
    "test_strip_whitespace_trims_leading_trailing",
    "test_structlog_proxy_context_var_default_when_key_missing",
    "test_structlog_proxy_context_var_get_set_reset_paths",
    "test_summary_error_paths_and_bindings_failures",
    "test_summary_properties_and_subclass_storage_reset",
    "test_to_general_value_dict_removed",
    "test_transform_option_extract_and_step_helpers",
    "test_type_guards_and_narrowing_failures",
    "test_type_guards_result",
    "test_ultrawork_models_cli_runs_dry_run_copy",
    "test_update_exception_path",
    "test_update_statistics_remove_hook_and_clone_false_result",
    "test_update_success_path_returns_ok_result",
    "test_utilities_family_allows_utilities_target",
    "test_utilities_reliability_branches",
    "test_utilities_reliability_compose_returns_non_result_directly",
    "test_utilities_reliability_uncovered_retry_compose_and_sequence_paths",
    "test_validate_config_dict_normalizes_dict",
    "test_validate_tags_list_from_string",
    "test_validate_tags_list_normalizes",
    "test_validation_like_error_structure",
    "test_with_resource_cleanup_runs",
    "u",
    "unit",
    "valid_hostnames",
    "valid_port_numbers",
    "valid_ranges",
    "valid_strings",
    "valid_uris",
    "validation_scenarios",
    "whitespace_strings",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
