from _typeshed import Incomplete

pytestmark: Incomplete

class TestFlextSemanticModel:
    def test_foundation_get_base_config(self) -> None: ...
    def test_namespace_classes_exist(self) -> None: ...
    def test_factory_create_model_with_defaults(self) -> None: ...
    def test_factory_validate_with_business_rules_valid(self) -> None: ...
    def test_factory_validate_with_business_rules_failure(self) -> None: ...
    def test_factory_validate_with_business_rules_no_method(self) -> None: ...
    def test_factory_validate_with_business_rules_non_result(self) -> None: ...

class TestFlextSemanticObservability:
    def test_logger_protocol_compliance(self) -> None: ...
    def test_span_protocol_compliance(self) -> None: ...
    def test_tracer_protocol_compliance(self) -> None: ...
    def test_metrics_protocol_compliance(self) -> None: ...
    def test_observability_protocol_compliance(self) -> None: ...
    def test_factory_get_minimal_observability(self) -> None: ...
    def test_factory_configure_observability_default(self) -> None: ...
    def test_factory_configure_observability_custom_level(self) -> None: ...

class TestFlextSemanticError:
    def test_flext_error_creation(self) -> None: ...
    def test_flext_error_defaults(self) -> None: ...
    def test_flext_business_error(self) -> None: ...
    def test_flext_technical_error(self) -> None: ...
    def test_flext_validation_error(self) -> None: ...
    def test_flext_security_error(self) -> None: ...
    def test_namespace_classes_exist(self) -> None: ...
    def test_factory_create_business_error(self) -> None: ...
    def test_factory_create_validation_error(self) -> None: ...
    def test_factory_from_exception_known_type(self) -> None: ...
    def test_factory_from_exception_unknown_type(self) -> None: ...

class TestFlextSemantic:
    def test_flext_semantic_class_exists(self) -> None: ...
    def test_semantic_components_accessible(self) -> None: ...

class TestSemanticIntegration:
    def test_error_uses_constants(self) -> None: ...
    def test_model_factory_uses_constants(self) -> None: ...
    def test_observability_uses_constants(self) -> None: ...
