from collections.abc import Generator
from typing import ClassVar

import pytest
from _typeshed import Incomplete

from flext_core import (
    FlextConfig,
    FlextConfigDefaults,
    FlextConfigOps,
    FlextConfigValidation,
    FlextSettings,
)
from flext_core.result import FlextResult
from flext_core.typings import TAnyDict as TAnyDict

pytestmark: Incomplete

class FailingConfigOps(FlextConfigOps):
    @classmethod
    def safe_load_from_dict(
        cls, config: dict[str, object]
    ) -> FlextResult[dict[str, object]]: ...
    @classmethod
    def safe_load_json_file(cls, file_path: str) -> FlextResult[dict[str, object]]: ...

class FailingConfigDefaults(FlextConfigDefaults):
    @classmethod
    def apply_defaults(
        cls, config: dict[str, object], defaults: dict[str, object] | None = None
    ) -> FlextResult[dict[str, object]]: ...

class FailingConfigValidation(FlextConfigValidation):
    @classmethod
    def validate_config(cls, config: dict[str, object]) -> FlextResult[None]: ...
    @classmethod
    def validate_required_keys(
        cls, config: dict[str, object], required_keys: list[str]
    ) -> FlextResult[None]: ...

class TestFlextConfig(FlextConfig):
    @classmethod
    def create_complete_config(
        cls,
        config_data: dict[str, object],
        defaults: dict[str, object] | None = None,
        *,
        apply_defaults: bool = True,
    ) -> FlextResult[dict[str, object]]: ...

class TestFlextSettings(FlextSettings):
    model_config: ClassVar[Incomplete]
    test_var: str | None
    from_env: str | None

@pytest.fixture
def sample_config() -> TAnyDict: ...
@pytest.fixture
def sample_defaults() -> TAnyDict: ...
@pytest.fixture
def invalid_json_file() -> Generator[str]: ...

class TestFlextConfigClass:
    def test_create_complete_config_success(self, sample_config: TAnyDict) -> None: ...
    def test_create_complete_config_no_defaults(
        self, sample_config: TAnyDict
    ) -> None: ...
    def test_create_complete_config_with_custom_defaults(
        self, sample_config: TAnyDict, sample_defaults: TAnyDict
    ) -> None: ...
    def test_create_complete_config_empty_data(self) -> None: ...
    def test_create_complete_config_no_validation(
        self, sample_config: TAnyDict
    ) -> None: ...
    def test_create_complete_config_load_failure(self) -> None: ...
    def test_create_complete_config_defaults_failure(self) -> None: ...
    def test_create_complete_config_exception_handling(self) -> None: ...
    def test_load_and_validate_from_file_success(self, temp_json_file: str) -> None: ...
    def test_load_and_validate_from_file_no_required_keys(
        self, temp_json_file: str
    ) -> None: ...
    def test_load_and_validate_from_file_missing_required_key(
        self, temp_json_file: str
    ) -> None: ...
    def test_load_and_validate_from_file_none_value(self) -> None: ...
    def test_load_and_validate_from_file_load_failure(self) -> None: ...
    def test_load_and_validate_from_file_validation_failure(self) -> None: ...
    def test_load_and_validate_from_file_nonexistent(self) -> None: ...
    def test_load_and_validate_from_file_invalid_json(
        self, invalid_json_file: str
    ) -> None: ...
    def test_load_and_validate_from_file_access_denied(self) -> None: ...

class TestFlextConfigOps:
    def test_safe_load_from_dict_success(self, sample_config: TAnyDict) -> None: ...
    def test_safe_load_from_dict_empty(self) -> None: ...
    def test_safe_load_from_dict_nested(self) -> None: ...
    def test_safe_load_json_file_success(self, temp_json_file: str) -> None: ...
    def test_safe_load_json_file_nonexistent(self) -> None: ...
    def test_safe_load_json_file_invalid_json(self, invalid_json_file: str) -> None: ...
    def test_safe_get_env_var_existing(self) -> None: ...
    def test_safe_get_env_var_missing_with_default(self) -> None: ...
    def test_safe_get_env_var_missing_no_default(self) -> None: ...
    def test_safe_get_env_var_empty_string(self) -> None: ...
    def test_merge_configs_success(self) -> None: ...
    def test_merge_configs_empty_base(self) -> None: ...
    def test_merge_configs_empty_override(self) -> None: ...
    def test_merge_configs_both_empty(self) -> None: ...
    def test_merge_configs_deep_nesting(self) -> None: ...

class TestFlextConfigDefaults:
    def test_apply_defaults_with_custom_defaults(
        self, sample_defaults: TAnyDict
    ) -> None: ...
    def test_apply_defaults_no_custom_defaults(self) -> None: ...
    def test_apply_defaults_empty_config(self, sample_defaults: TAnyDict) -> None: ...
    def test_get_default_config(self) -> None: ...

class TestFlextConfigValidation:
    def test_validate_config_success(self, sample_config: TAnyDict) -> None: ...
    def test_validate_config_empty(self) -> None: ...
    def test_validate_config_with_none_values(self) -> None: ...
    def test_validate_required_keys_all_present(self) -> None: ...
    def test_validate_required_keys_missing_key(self) -> None: ...
    def test_validate_required_keys_empty_config(self) -> None: ...
    def test_validate_required_keys_empty_required(self) -> None: ...
    def test_validate_type_compatibility_success(self) -> None: ...
    def test_validate_type_compatibility_mixed_types(self) -> None: ...

class TestFlextConfigFactory:
    def test_create_from_dict_success(self, sample_config: TAnyDict) -> None: ...
    def test_create_from_dict_with_defaults(
        self, sample_config: TAnyDict, sample_defaults: TAnyDict
    ) -> None: ...
    def test_create_from_file_success(self, temp_json_file: str) -> None: ...
    def test_create_from_file_with_required_keys(self, temp_json_file: str) -> None: ...
    def test_create_from_file_missing_required(self, temp_json_file: str) -> None: ...
    def test_create_from_env_success(self) -> None: ...
    def test_create_from_env_with_prefix(self) -> None: ...
    def test_create_from_multiple_sources(
        self, temp_json_file: str, sample_defaults: TAnyDict
    ) -> None: ...

class TestFlextSettingsClass:
    def test_settings_from_env(self) -> None: ...
    def test_settings_defaults(self) -> None: ...
    def test_settings_case_insensitive(self) -> None: ...
    def test_settings_extra_allowed(self) -> None: ...
    def test_base_flext_settings(self) -> None: ...

class TestConfigIntegration:
    def test_complete_config_workflow(
        self, temp_json_file: str, sample_defaults: TAnyDict
    ) -> None: ...
    def test_factory_with_validation(self, sample_config: TAnyDict) -> None: ...
    def test_environment_override_file_config(self, temp_json_file: str) -> None: ...
    def test_config_with_complex_validation(self) -> None: ...
