from _typeshed import Incomplete

pytestmark: Incomplete

class TestFlextTypesTypeGuards:
    def test_is_instance_of_with_exception_handling(self) -> None: ...
    def test_is_callable(self) -> None: ...
    def test_is_dict_like(self) -> None: ...
    def test_is_list_like(self) -> None: ...
