from _typeshed import Incomplete

pytestmark: Incomplete

class TestFlextBaseHandler:
    def test_base_handler_initialization(self) -> None: ...
    def test_base_handler_can_handle(self) -> None: ...
    def test_base_handler_handle(self) -> None: ...
    def test_base_handler_validate_request(self) -> None: ...
    def test_base_handler_pre_process(self) -> None: ...
    def test_base_handler_process_message(self) -> None: ...
    def test_base_handler_post_process(self) -> None: ...
    def test_base_handler_get_handler_metadata(self) -> None: ...

class TestFlextValidatingHandler:
    def test_validating_handler_initialization(self) -> None: ...
    def test_validating_handler_handle(self) -> None: ...
    def test_validating_handler_can_handle(self) -> None: ...
    def test_validating_handler_validate_input(self) -> None: ...
    def test_validating_handler_validate_output(self) -> None: ...
    def test_validating_handler_get_validation_rules(self) -> None: ...
    def test_validating_handler_validate_message(self) -> None: ...
    def test_validating_handler_validate(self) -> None: ...

class TestFlextAuthorizingHandler:
    def test_authorizing_handler_initialization(self) -> None: ...
    def test_authorizing_handler_authorize(self) -> None: ...
    def test_authorizing_handler_handle_with_auth(self) -> None: ...

class TestFlextEventHandler:
    def test_event_handler_exists(self) -> None: ...

class TestFlextMetricsHandler:
    def test_metrics_handler_initialization(self) -> None: ...
    def test_metrics_handler_handle(self) -> None: ...
    def test_metrics_handler_get_metrics(self) -> None: ...

class TestFlextHandlerChain:
    def test_handler_chain_initialization(self) -> None: ...
    def test_handler_chain_add_handler(self) -> None: ...
    def test_handler_chain_handle(self) -> None: ...
    def test_handler_chain_remove_handler(self) -> None: ...

class TestFlextHandlerRegistry:
    def test_handler_registry_initialization(self) -> None: ...
    def test_handler_registry_register_handler(self) -> None: ...
    def test_handler_registry_get_handler(self) -> None: ...
    def test_handler_registry_operations(self) -> None: ...

class TestHandlerIntegration:
    def test_handler_types_work_together(self) -> None: ...
    def test_registry_with_different_handler_types(self) -> None: ...
    def test_chain_with_validation_and_metrics(self) -> None: ...
    def test_handler_metadata_consistency(self) -> None: ...
