from _typeshed import Incomplete

from flext_core import TAnyList as TAnyList, TComparable as TComparable
from flext_core.typings import (
    TBusinessCode as TBusinessCode,
    TBusinessId as TBusinessId,
    TBusinessName as TBusinessName,
    TBusinessStatus as TBusinessStatus,
    TBusinessType as TBusinessType,
    TCacheKey as TCacheKey,
    TCacheTTL as TCacheTTL,
    TCacheValue as TCacheValue,
    TConfigDict as TConfigDict,
    TConfigValue as TConfigValue,
    TConnectionString as TConnectionString,
    TCorrelationId as TCorrelationId,
    TDirectoryPath as TDirectoryPath,
    TEntityId as TEntityId,
    TFilePath as TFilePath,
    TRequestId as TRequestId,
    TUserId as TUserId,
)

FlextConfigKey = str
FlextEventType = str
FlextServiceName = str

class TestTypeProtocols:
    def test_comparable_protocol(self) -> None: ...
    def test_type_aliases_usage(self) -> None: ...
    data: Incomplete
    def test_serializable_protocol(self) -> None: ...
    def test_factory_protocol(self) -> None: ...
    def test_flext_types_usage(self) -> None: ...

class TestTypeAliases:
    def test_entity_id_basic_usage(self) -> None: ...
    def test_service_name_basic_usage(self) -> None: ...
    def test_config_key_basic_usage(self) -> None: ...
    def test_event_type_basic_usage(self) -> None: ...
    def test_payload_basic_usage(self) -> None: ...

class TestTypeGuards:
    def test_is_instance_of_type_guard(self) -> None: ...
    def test_is_callable_type_guard(self) -> None: ...
    def test_is_dict_like_type_guard(self) -> None: ...
    def test_is_list_like_type_guard(self) -> None: ...
    def test_type_guard_error_handling(self) -> None: ...

class TestProtocolDefinitions:
    value: Incomplete
    def test_comparable_protocol_interface(self) -> None: ...
    data: Incomplete
    def test_flext_serializable_protocol_interface(self) -> None: ...

class TestTypeAliasComprehensive:
    def test_entity_type_aliases(self) -> None: ...
    def test_cqrs_type_aliases(self) -> None: ...
    def test_business_type_aliases(self) -> None: ...
    def test_cache_type_aliases(self) -> None: ...
    def test_function_type_aliases(self) -> None: ...
    def test_infrastructure_type_aliases(self) -> None: ...

class TestTypesCoverageImprovements:
    def test_is_instance_exception_handling(self) -> None: ...
