from collections.abc import Callable as Callable
from unittest.mock import Mock

import pytest
from _typeshed import Incomplete

from flext_core import FlextCore, FlextServiceKey

pytestmark: Incomplete
EXPECTED_TOTAL_PAGES: int
EXPECTED_DATA_COUNT: int

@pytest.fixture
def clean_flext_core() -> FlextCore: ...
@pytest.fixture
def mock_service() -> Mock: ...
@pytest.fixture
def service_key() -> FlextServiceKey[Mock]: ...

class UserService:
    name: Incomplete
    def __init__(self, name: str = "test_user_service") -> None: ...
    def get_user(self, user_id: str) -> str: ...

class DataService:
    connection: Incomplete
    def __init__(self, connection: str = "test_db") -> None: ...
    def save_data(self, data: str) -> bool: ...

class TestFlextCoreSingleton:
    def test_singleton_instance_creation(self) -> None: ...
    def test_singleton_initialization(self) -> None: ...
    def test_singleton_reset_behavior(self) -> None: ...
    def test_singleton_thread_safety_simulation(self) -> None: ...

class TestFlextCoreContainerIntegration:
    def test_container_property_access(self, clean_flext_core: FlextCore) -> None: ...
    def test_register_service_success(
        self,
        clean_flext_core: FlextCore,
        service_key: FlextServiceKey[Mock],
        mock_service: Mock,
    ) -> None: ...
    def test_register_service_typed_keys(self, clean_flext_core: FlextCore) -> None: ...
    def test_get_service_success(
        self,
        clean_flext_core: FlextCore,
        service_key: FlextServiceKey[Mock],
        mock_service: Mock,
    ) -> None: ...
    def test_get_service_not_found(self, clean_flext_core: FlextCore) -> None: ...
    def test_multiple_services_registration(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_service_registration_failure_handling(
        self, clean_flext_core: FlextCore
    ) -> None: ...

class TestFlextCoreLogging:
    def test_get_logger_success(self, clean_flext_core: FlextCore) -> None: ...
    def test_get_logger_multiple_names(self, clean_flext_core: FlextCore) -> None: ...
    def test_get_logger_same_name_caching(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_configure_logging_default_settings(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_configure_logging_custom_level(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_configure_logging_json_output_parameter(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_logging_integration_with_services(
        self, clean_flext_core: FlextCore
    ) -> None: ...

class TestFlextCoreResultPatterns:
    def test_ok_static_method(self, clean_flext_core: FlextCore) -> None: ...
    def test_ok_with_different_types(self, clean_flext_core: FlextCore) -> None: ...
    def test_fail_static_method(self, clean_flext_core: FlextCore) -> None: ...
    def test_fail_with_different_messages(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_result_pattern_integration(self, clean_flext_core: FlextCore) -> None: ...

class TestFlextCoreRailwayProgramming:
    def test_pipe_success_pipeline(self, clean_flext_core: FlextCore) -> None: ...
    def test_pipe_failure_propagation(self, clean_flext_core: FlextCore) -> None: ...
    def test_pipe_empty_pipeline(self, clean_flext_core: FlextCore) -> None: ...
    def test_pipe_single_function(self, clean_flext_core: FlextCore) -> None: ...
    def test_compose_right_to_left(self, clean_flext_core: FlextCore) -> None: ...
    def test_when_predicate_true(self, clean_flext_core: FlextCore) -> None: ...
    def test_when_predicate_false_with_else(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_when_predicate_false_no_else(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_when_predicate_false_no_else_2(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_when_exception_handling(self, clean_flext_core: FlextCore) -> None: ...
    def test_tap_side_effect_execution(self, clean_flext_core: FlextCore) -> None: ...
    def test_tap_in_pipeline(self, clean_flext_core: FlextCore) -> None: ...
    def test_complex_railway_pattern(self, clean_flext_core: FlextCore) -> None: ...

class TestFlextCoreConfiguration:
    def test_get_settings_caching(self, clean_flext_core: FlextCore) -> None: ...
    def test_get_settings_different_classes(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_get_settings_initialization(self, clean_flext_core: FlextCore) -> None: ...
    def test_settings_cache_persistence(self, clean_flext_core: FlextCore) -> None: ...
    def test_constants_property_access(self, clean_flext_core: FlextCore) -> None: ...
    def test_constants_consistency(self, clean_flext_core: FlextCore) -> None: ...

class TestFlextCoreRepresentation:
    def test_repr_with_no_services(self, clean_flext_core: FlextCore) -> None: ...
    def test_repr_with_services(self, clean_flext_core: FlextCore) -> None: ...
    def test_repr_format_consistency(self, clean_flext_core: FlextCore) -> None: ...

class TestFlextCoreConvenienceFunction:
    def test_convenience_function_returns_singleton(self) -> None: ...
    def test_convenience_function_functional_usage(self) -> None: ...
    def test_convenience_function_service_operations(self) -> None: ...
    def test_convenience_function_logging_access(self) -> None: ...

class TestFlextCoreIntegration:
    def test_full_workflow_integration(self, clean_flext_core: FlextCore) -> None: ...
    def test_error_handling_integration(self, clean_flext_core: FlextCore) -> None: ...
    def test_settings_and_services_integration(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_constants_usage_integration(self, clean_flext_core: FlextCore) -> None: ...

class TestFlextCoreEdgeCases:
    def test_singleton_with_manual_instantiation(self) -> None: ...
    def test_container_access_consistency(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_empty_pipeline_edge_cases(self, clean_flext_core: FlextCore) -> None: ...
    def test_when_predicate_edge_cases(self, clean_flext_core: FlextCore) -> None: ...
    def test_tap_side_effect_exceptions(self, clean_flext_core: FlextCore) -> None: ...
    required_param: Incomplete
    def test_settings_with_invalid_classes(
        self, clean_flext_core: FlextCore
    ) -> None: ...
    def test_repr_edge_cases(self, clean_flext_core: FlextCore) -> None: ...
