from typing import Protocol

from _typeshed import Incomplete

class FactoryProtocol(Protocol):
    def __call__(self, *args: object, **kwargs: object) -> object: ...

class BuilderProtocol(Protocol):
    def __call__(self, *args: object, **kwargs: object) -> object: ...

EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestTypeGuards:
    def test_is_not_none(self) -> None: ...
    def test_is_list_of(self) -> None: ...
    def test_is_instance_of(self) -> None: ...
    def test_is_dict_of(self) -> None: ...

class TestValidationDecorators:
    def test_validated_decorator(self) -> None: ...
    def test_safe_decorator(self) -> None: ...
    value: Incomplete
    def test_immutable_decorator(self) -> None: ...
    def test_pure_decorator(self) -> None: ...

class TestValidatedModel:
    def test_validated_model_creation(self) -> None: ...
    def test_validated_model_validation_error(self) -> None: ...
    def test_validated_model_create_method(self) -> None: ...
    def test_validated_model_mixin_integration(self) -> None: ...
    def test_validated_model_complex_validation(self) -> None: ...

class TestFactoryHelpers:
    value: Incomplete
    name: Incomplete
    def test_make_factory(self) -> None: ...
    x: Incomplete
    y: Incomplete
    def test_make_builder(self) -> None: ...
    args: Incomplete
    kwargs: Incomplete
    def test_factory_with_complex_class(self) -> None: ...

class TestValidationUtilities:
    def test_require_not_none(self) -> None: ...
    def test_require_positive(self) -> None: ...
    def test_require_in_range(self) -> None: ...
    def test_require_non_empty(self) -> None: ...

class TestEdgeCases:
    def test_type_guards_with_none(self) -> None: ...
    def test_type_guards_with_complex_types(self) -> None: ...
    def test_validated_model_edge_cases(self) -> None: ...
    def test_factory_edge_cases(self) -> None: ...
    def test_validation_utilities_edge_cases(self) -> None: ...
    def test_error_message_consistency(self) -> None: ...

class TestIntegrationAndComposition:
    def test_validated_model_with_guards(self) -> None: ...
    value: Incomplete
    def test_factory_with_validation(self) -> None: ...
    def test_decorator_composition(self) -> None: ...
    def test_type_guard_composition(self) -> None: ...

class TestPerformanceAndScalability:
    def test_type_guard_performance(self) -> None: ...
    def test_validation_utility_performance(self) -> None: ...
    value: Incomplete
    def test_factory_performance(self) -> None: ...
