from _typeshed import Incomplete

from flext_core import (
    FlextAbstractHandler,
    FlextCommandHandler,
    FlextQueryHandler,
    FlextResult,
)

pytestmark: Incomplete

class ConcreteBaseHandler(FlextAbstractHandler[object, object]):
    @property
    def handler_name(self) -> str: ...
    def can_handle(self, _request: object) -> bool: ...
    def handle(self, request: object) -> FlextResult[object]: ...
    def validate_request(self, request: object) -> FlextResult[None]: ...

class TestFlextBaseHandler:
    def test_base_handler_initialization(self) -> None: ...
    def test_handler_name_property(self) -> None: ...
    def test_can_handle_method(self) -> None: ...
    def test_handle_method(self) -> None: ...
    def test_validate_request_method(self) -> None: ...
    def test_process_request_method(self) -> None: ...

class ConcreteCommandHandler(FlextCommandHandler[str, int]):
    @property
    def handler_name(self) -> str: ...
    def can_handle(self, message_type: object) -> bool: ...
    def handle_command(self, command: str) -> FlextResult[int]: ...
    def process_request(self, request: str) -> FlextResult[int]: ...

class TestFlextCommandHandler:
    def test_command_handler_is_abstract(self) -> None: ...
    def test_concrete_command_handler_handle_command(self) -> None: ...
    def test_command_handler_can_handle(self) -> None: ...
    def test_command_handler_process_request(self) -> None: ...
    def test_command_handler_name_property(self) -> None: ...
    def test_command_handler_failure_case(self) -> None: ...

class ConcreteQueryHandler(FlextQueryHandler[dict[str, str], str]):
    @property
    def handler_name(self) -> str: ...
    def can_handle(self, message_type: object) -> bool: ...
    def handle_query(self, query: dict[str, str]) -> FlextResult[str]: ...
    def process_request(self, request: dict[str, str]) -> FlextResult[str]: ...

class TestFlextQueryHandler:
    def test_query_handler_is_abstract(self) -> None: ...
    def test_concrete_query_handler_handle_query(self) -> None: ...
    def test_query_handler_can_handle(self) -> None: ...
    def test_query_handler_process_request(self) -> None: ...
    def test_query_handler_name_property(self) -> None: ...
    def test_query_handler_failure_case(self) -> None: ...

class TestFlextCompatibilityHandlers:
    def test_validating_handler(self) -> None: ...
    def test_authorizing_handler(self) -> None: ...
    def test_event_handler(self) -> None: ...
    def test_metrics_handler(self) -> None: ...
    def test_handler_chain(self) -> None: ...

class TestFlextHandlerRegistry:
    def test_registry_initialization(self) -> None: ...
    def test_register_handler(self) -> None: ...
    def test_register_multiple_handlers(self) -> None: ...
    def test_get_handlers(self) -> None: ...

class TestFlextLegacyAliases:
    def test_flext_handlers_alias(self) -> None: ...

class TestFlextHandlersIntegration:
    def test_handler_registry_with_different_handlers(self) -> None: ...
    def test_handler_polymorphism(self) -> None: ...
