EXPECTED_DATA_COUNT: int

class TestFlextError:
    def test_flext_error_basic_creation(self) -> None: ...
    def test_flext_error_with_error_code(self) -> None: ...
    def test_flext_error_with_context(self) -> None: ...
    def test_flext_error_with_full_context(self) -> None: ...
    def test_flext_error_context_enhancement(self) -> None: ...
    def test_flext_error_serialization(self) -> None: ...
    def test_flext_error_str_representation(self) -> None: ...
    def test_flext_error_repr_representation(self) -> None: ...
    def test_flext_error_inheritance(self) -> None: ...
    def test_flext_error_raise_and_catch(self) -> None: ...

class TestFlextValidationError:
    def test_validation_error_basic(self) -> None: ...
    def test_validation_error_with_field_details(self) -> None: ...
    def test_validation_error_multiple_fields(self) -> None: ...
    def test_validation_error_serialization(self) -> None: ...

class TestFlextTypeError:
    def test_type_error_basic(self) -> None: ...
    def test_type_error_with_type_info(self) -> None: ...
    def test_type_error_with_conversion_details(self) -> None: ...

class TestFlextOperationError:
    def test_operation_error_basic(self) -> None: ...
    def test_operation_error_with_operation_info(self) -> None: ...
    def test_operation_error_with_retry_info(self) -> None: ...

class TestSpecificErrors:
    def test_configuration_error(self) -> None: ...
    def test_connection_error(self) -> None: ...
    def test_authentication_error(self) -> None: ...
    def test_permission_error(self) -> None: ...
    def test_specific_errors_with_context(self) -> None: ...
    def test_error_code_consistency(self) -> None: ...

class TestExceptionIntegration:
    def test_exception_with_result_pattern(self) -> None: ...
    def test_exception_context_enhancement(self) -> None: ...
    def test_exception_serialization_roundtrip(self) -> None: ...
    def test_exception_chaining_patterns(self) -> None: ...

class TestErrorCodeIntegration:
    def test_error_code_enum_usage(self) -> None: ...
    def test_error_context_variations(self) -> None: ...
    def test_default_error_codes(self) -> None: ...

class TestExceptionEdgeCases:
    def test_exception_with_none_message(self) -> None: ...
    def test_exception_with_empty_context(self) -> None: ...
    def test_exception_with_complex_context(self) -> None: ...
    def test_exception_serialization_with_non_serializable_context(self) -> None: ...
    def test_exception_memory_efficiency(self) -> None: ...
    def test_exception_thread_safety_basic(self) -> None: ...

class TestAdditionalExceptions:
    def test_flext_not_found_error(self) -> None: ...
    def test_flext_already_exists_error(self) -> None: ...
    def test_flext_timeout_error(self) -> None: ...
    def test_flext_processing_error(self) -> None: ...
    def test_flext_critical_error(self) -> None: ...
    def test_flext_attribute_error(self) -> None: ...
    def test_exception_metrics(self) -> None: ...
    def test_flext_exceptions_factory(self) -> None: ...

class TestExceptionsCoverageImprovements:
    def test_context_truncation(self) -> None: ...
    def test_str_without_error_code(self) -> None: ...
    def test_str_with_error_code(self) -> None: ...
    def test_record_exception_function(self) -> None: ...
    def test_factory_config_error_with_config_key(self) -> None: ...
    def test_factory_connection_error_with_endpoint(self) -> None: ...
