from _typeshed import Incomplete

pytestmark: Incomplete

class TestProtocolInterfaces:
    def test_configurable_protocol(self) -> None: ...
    def test_validator_protocol(self) -> None: ...
    def test_protocol_runtime_checkable(self) -> None: ...
    def test_protocol_imports(self) -> None: ...
    def test_type_checking_imports(self) -> None: ...
