from collections.abc import Callable as Callable

from _typeshed import Incomplete

pytestmark: Incomplete
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class SampleMixin1:
    def __init__(self) -> None: ...
    @property
    def readonly_property(self) -> str: ...
    @property
    def writable_property(self) -> str: ...
    @writable_property.setter
    def writable_property(self, value: str) -> None: ...
    def mixin_method1(self) -> str: ...
    def mixin_method2(self, param: str) -> str: ...

class SampleMixin2:
    def __init__(self) -> None: ...
    @property
    def another_property(self) -> str: ...
    def mixin_method3(self) -> dict[str, str]: ...
    def mixin_method4(self, key: str, value: str) -> None: ...

class InitializableMixin:
    initialized: bool
    validation_initialized: bool
    timestamps_initialized: bool
    id_initialized: bool
    logging_initialized: bool
    serialization_initialized: bool
    def __init__(self) -> None: ...
    def test_method(self) -> str: ...

class FailingInitMixin:
    initialized: bool
    def __init__(self) -> None: ...
    def test_method(self) -> str: ...

class HostObject:
    host_attr: str
    def __init__(self) -> None: ...
    def host_method(self) -> str: ...

class FrozenHostObject:
    host_attr: str
    def __init__(self) -> None: ...
    def __setattr__(self, name: str, value: object) -> None: ...
    def freeze(self) -> None: ...

class TestFlextMixinDelegator:
    def test_delegator_initialization_single_mixin(self) -> None: ...
    def test_delegator_initialization_multiple_mixins(self) -> None: ...
    def test_delegator_initialization_no_mixins(self) -> None: ...
    def test_delegator_initialization_with_initializable_mixin(self) -> None: ...
    def test_delegator_initialization_with_failing_init(self) -> None: ...
    def test_delegator_initialization_with_mixin_registration_failure(self) -> None: ...
    def test_method_delegation_basic(self) -> None: ...
    def test_method_delegation_with_arguments(self) -> None: ...
    def test_method_delegation_multiple_mixins(self) -> None: ...
    def test_property_delegation_getter(self) -> None: ...
    def test_property_delegation_setter(self) -> None: ...
    def test_property_delegation_readonly(self) -> None: ...
    def test_private_methods_not_delegated(self) -> None: ...
    def test_method_delegation_error_handling(self) -> None: ...
    def test_method_signature_preservation(self) -> None: ...
    def test_frozen_host_object_delegation(self) -> None: ...
    def test_get_mixin_instance(self) -> None: ...
    def test_get_delegation_info(self) -> None: ...
    def test_delegation_validation_success(self) -> None: ...
    def test_delegation_validation_no_mixins(self) -> None: ...
    def test_delegation_validation_no_methods(self) -> None: ...
    def test_delegation_validation_with_init_failures(self) -> None: ...
    def test_mixin_registry_global(self) -> None: ...

class TestCreateMixinDelegator:
    def test_create_mixin_delegator_basic(self) -> None: ...
    def test_create_mixin_delegator_multiple_mixins(self) -> None: ...
    def test_create_mixin_delegator_no_mixins(self) -> None: ...

class TestValidateDelegationSystem:
    def test_validate_delegation_system_success(self) -> None: ...
    def test_validate_delegation_system_missing_methods(self) -> None: ...
    def test_validate_delegation_system_delegation_failure(self) -> None: ...
    def test_validate_delegation_system_type_error(self) -> None: ...
    def test_validate_delegation_system_various_exceptions(self) -> None: ...

class TestDelegationSystemEdgeCases:
    callable_attr: Callable[[str], str]
    def test_delegator_with_callable_attribute(self) -> None: ...
    def test_delegator_method_name_conflicts(self) -> None: ...
    def test_delegator_with_host_existing_methods(self) -> None: ...
    def test_delegator_initialization_with_complex_errors(self) -> None: ...
    def test_delegation_with_property_edge_cases(self) -> None: ...
    def test_mixin_registry_persistence(self) -> None: ...
    def test_delegation_info_completeness(self) -> None: ...
    def test_signature_preservation_edge_cases(self) -> None: ...
    def test_error_handling_in_method_creation(self) -> None: ...

class TestDelegationSystemIntegration:
    def test_full_delegation_workflow(self) -> None: ...
    def test_system_validation_integration(self) -> None: ...
    def test_complex_mixin_combination(self) -> None: ...
    def test_performance_with_many_mixins(self) -> None: ...
