class TestFlextConfig:
    def test_config_creation(self) -> None: ...
    def test_config_custom_values(self) -> None: ...

class TestFlextDatabaseConfig:
    def test_database_config_creation(self) -> None: ...
    def test_database_config_custom_values(self) -> None: ...
    def test_database_config_validation(self) -> None: ...
    def test_database_config_model_dump(self) -> None: ...

class TestFlextRedisConfig:
    def test_redis_config_creation(self) -> None: ...
    def test_redis_config_custom_values(self) -> None: ...
    def test_redis_config_validation(self) -> None: ...
    def test_redis_config_model_dump(self) -> None: ...

class TestFlextOracleConfig:
    def test_oracle_config_creation(self) -> None: ...
    def test_oracle_config_custom_values(self) -> None: ...

class TestFlextLDAPConfig:
    def test_ldap_config_creation(self) -> None: ...
    def test_ldap_config_ssl(self) -> None: ...

class TestConfigUtilities:
    def test_merge_configs(self) -> None: ...
    def test_validate_config(self) -> None: ...
    def test_safe_load_json_file(self) -> None: ...

class TestConfigEdgeCases:
    def test_config_with_defaults(self) -> None: ...
    def test_config_model_dump(self) -> None: ...
    def test_secret_str_handling(self) -> None: ...
    def test_config_inheritance(self) -> None: ...
    def test_config_field_validation(self) -> None: ...
    def test_complex_config_merge(self) -> None: ...

class TestFlextJWTConfig:
    def test_jwt_config_creation(self) -> None: ...
    def test_jwt_config_secret_key_validation(self) -> None: ...
    def test_jwt_config_algorithm_validation(self) -> None: ...
    def test_jwt_config_to_jwt_dict(self) -> None: ...

class TestFlextSingerConfig:
    def test_singer_config_creation(self) -> None: ...
    def test_singer_config_custom_values(self) -> None: ...
    def test_singer_config_stream_name_validation(self) -> None: ...
    def test_singer_config_to_singer_dict(self) -> None: ...

class TestFlextObservabilityConfig:
    def test_observability_config_creation(self) -> None: ...
    def test_observability_config_custom_values(self) -> None: ...
    def test_observability_config_log_level_validation(self) -> None: ...
    def test_observability_config_to_observability_dict(self) -> None: ...

class TestFlextSettings:
    def test_settings_creation(self) -> None: ...
    def test_settings_validation(self) -> None: ...
    def test_settings_create_with_validation(self) -> None: ...

class TestAdvancedConfigFeatures:
    def test_database_config_get_connection_string(self) -> None: ...
    def test_database_config_to_database_dict(self) -> None: ...
    def test_redis_config_get_connection_string(self) -> None: ...
    def test_redis_config_get_connection_string_with_password(self) -> None: ...
    def test_redis_config_to_redis_dict(self) -> None: ...
    def test_oracle_config_get_connection_string_service_name(self) -> None: ...
    def test_oracle_config_get_connection_string_sid(self) -> None: ...
    def test_oracle_config_to_oracle_dict(self) -> None: ...
    def test_ldap_config_get_connection_string(self) -> None: ...
    def test_ldap_config_get_connection_string_ssl(self) -> None: ...
    def test_ldap_config_to_ldap_dict(self) -> None: ...

class TestConfigValidation:
    def test_database_config_host_validation(self) -> None: ...
    def test_database_config_username_validation(self) -> None: ...
    def test_oracle_config_validation_no_identifier(self) -> None: ...
    def test_ldap_config_base_dn_validation_empty(self) -> None: ...
    def test_ldap_config_base_dn_validation_format(self) -> None: ...

class TestConfigFactoryFunctions:
    def test_load_config_from_env(self) -> None: ...
