from collections.abc import Generator

import pytest
from _typeshed import Incomplete

from flext_core import FlextLogContext as FlextLogContext, TAnyDict as TAnyDict

pytestmark: Incomplete
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

@pytest.fixture
def clean_log_store() -> Generator[None]: ...
@pytest.fixture
def clean_logger_cache() -> Generator[None]: ...

class TestFlextLogger:
    def test_logger_initialization(self, clean_log_store: None) -> None: ...
    def test_logger_default_level(self, clean_log_store: None) -> None: ...
    def test_should_log_method(self, clean_log_store: None) -> None: ...
    def test_should_log_with_enum_input(self, clean_log_store: None) -> None: ...
    def test_should_log_unknown_level(self, clean_log_store: None) -> None: ...
    def test_level_filtering_performance(self, clean_log_store: None) -> None: ...
    def test_set_level(self, clean_log_store: None) -> None: ...
    def test_context_management(self, clean_log_store: None) -> None: ...
    def test_with_context(self, clean_log_store: None) -> None: ...
    def test_bind_method(self, clean_log_store: None) -> None: ...
    def test_info_logging(self, clean_log_store: None) -> None: ...
    def test_debug_logging(self, clean_log_store: None) -> None: ...
    def test_warning_logging(self, clean_log_store: None) -> None: ...
    def test_error_logging(self, clean_log_store: None) -> None: ...
    def test_critical_logging(self, clean_log_store: None) -> None: ...
    def test_trace_logging_allowed(self, clean_log_store: None) -> None: ...
    def test_trace_logging_filtered(self, clean_log_store: None) -> None: ...
    def test_exception_logging(self, clean_log_store: None) -> None: ...
    def test_message_formatting_with_args(self, clean_log_store: None) -> None: ...
    def test_message_formatting_fallback(self, clean_log_store: None) -> None: ...
    def test_context_override_in_log_call(self, clean_log_store: None) -> None: ...

class TestFlextLoggerFactory:
    def test_get_logger_basic(self, clean_logger_cache: None) -> None: ...
    def test_get_logger_caching(self, clean_logger_cache: None) -> None: ...
    def test_get_logger_different_levels_no_cache(
        self, clean_logger_cache: None
    ) -> None: ...
    def test_get_logger_different_names(self, clean_logger_cache: None) -> None: ...
    def test_get_logger_validation(self, clean_logger_cache: None) -> None: ...
    def test_set_global_level(self, clean_logger_cache: None) -> None: ...
    def test_set_global_level_validation(self, clean_logger_cache: None) -> None: ...
    def test_clear_loggers(self, clean_logger_cache: None) -> None: ...
    def test_get_log_store(self, clean_log_store: None) -> None: ...
    def test_clear_log_store(self, clean_log_store: None) -> None: ...
    def test_create_context(self, clean_log_store: None) -> None: ...

class TestFlextLogContextManager:
    def test_context_manager_enter_exit(self, clean_log_store: None) -> None: ...
    def test_context_manager_with_statement(self, clean_log_store: None) -> None: ...
    def test_context_manager_exception_handling(
        self, clean_log_store: None
    ) -> None: ...
    def test_nested_context_managers(self, clean_log_store: None) -> None: ...

class TestConvenienceFunctions:
    def test_get_logger_function(self, clean_logger_cache: None) -> None: ...
    def test_create_log_context_function(self, clean_log_store: None) -> None: ...

class TestFlextLogContext:
    def test_typed_dict_usage(self) -> None: ...

class TestLoggingIntegration:
    def test_full_logging_workflow(self, clean_log_store: None) -> None: ...
    def test_multiple_loggers_isolation(
        self, clean_log_store: None, clean_logger_cache: None
    ) -> None: ...
    def test_performance_with_level_filtering(self, clean_log_store: None) -> None: ...

class TestLoggingEdgeCases:
    def test_logger_with_empty_name(
        self, clean_logger_cache: None, clean_log_store: None
    ) -> None: ...
    def test_logger_with_invalid_level(self, clean_log_store: None) -> None: ...
    def test_message_formatting_edge_cases(self, clean_log_store: None) -> None: ...
    def test_context_with_none_values(self, clean_log_store: None) -> None: ...
    def test_large_context_data(self, clean_log_store: None) -> None: ...
    def test_concurrent_logging_simulation(self, clean_log_store: None) -> None: ...
