from _typeshed import Incomplete

pytestmark: Incomplete

class TestHandlersModuleDirect:
    def test_module_imports_correctly(self) -> None: ...
    def test_base_handler_direct(self) -> None: ...
    def test_validating_handler_direct(self) -> None: ...
    def test_authorizing_handler_direct(self) -> None: ...
    def test_metrics_handler_direct(self) -> None: ...
    def test_handler_chain_direct(self) -> None: ...
    def test_handler_registry_direct(self) -> None: ...
    def test_event_handler_direct(self) -> None: ...
    def test_command_handler_direct(self) -> None: ...
    def test_query_handler_direct(self) -> None: ...
    def test_all_handler_classes_exist(self) -> None: ...
    def test_handlers_module_exports(self) -> None: ...
