from collections.abc import Callable as Callable

from _typeshed import Incomplete

from flext_core import FlextContainer

EXPECTED_BULK_SIZE: int

class SampleService:
    name: Incomplete
    def __init__(self, name: str = "test") -> None: ...
    def get_name(self) -> str: ...

class DependentService:
    test_service: Incomplete
    optional_param: Incomplete
    def __init__(
        self, test_service: SampleService, optional_param: str = "default"
    ) -> None: ...

class ComplexService:
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class TestFlextServiceRegistrar:
    def test_registrar_initialization(self) -> None: ...
    def test_service_name_validation_empty(self) -> None: ...
    def test_service_registration_replacement_warning(self) -> None: ...
    def test_factory_registration_removes_existing_service(self) -> None: ...
    def test_factory_registration_non_callable(self) -> None: ...
    def test_unregister_service_success(self) -> None: ...
    def test_unregister_factory_success(self) -> None: ...
    def test_unregister_nonexistent_service(self) -> None: ...
    def test_clear_all_services(self) -> None: ...
    def test_has_service_check(self) -> None: ...
    def test_get_service_names_combined(self) -> None: ...

class TestFlextServiceRetrivier:
    def test_retriever_initialization(self) -> None: ...
    def test_get_service_from_cache(self) -> None: ...
    def test_get_service_from_factory_with_caching(self) -> None: ...
    def test_get_service_factory_failure(self) -> None: ...
    def test_get_service_factory_various_exceptions(self) -> None: ...
    def test_get_service_not_found(self) -> None: ...
    def test_get_service_info_for_instance(self) -> None: ...
    def test_get_service_info_for_factory(self) -> None: ...
    def test_get_service_info_not_found(self) -> None: ...
    def test_list_services_mixed(self) -> None: ...

class TestFlextContainerAdvancedFeatures:
    def test_get_typed_success(self, clean_container: FlextContainer) -> None: ...
    def test_get_typed_type_mismatch(self, clean_container: FlextContainer) -> None: ...
    def test_get_typed_service_not_found(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_auto_wire_success(self, clean_container: FlextContainer) -> None: ...
    def test_auto_wire_with_custom_name(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_auto_wire_missing_dependency(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_auto_wire_registration_failure(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_get_or_create_existing_service(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_get_or_create_new_service(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_get_or_create_factory_failure(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_batch_register_success(self, clean_container: FlextContainer) -> None: ...
    def test_batch_register_failure_rollback(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_container_repr(self, clean_container: FlextContainer) -> None: ...

class TestServiceKey:
    def test_service_key_creation(self) -> None: ...
    def test_service_key_with_register_typed(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_service_key_with_get_typed(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_get_typed_service_not_found(
        self, clean_container: FlextContainer
    ) -> None: ...

class TestFlextGlobalContainerManager:
    def test_manager_initialization(self) -> None: ...
    def test_get_container_lazy_creation(self) -> None: ...
    def test_set_container(self) -> None: ...

class TestContainerEdgeCases:
    def test_container_with_none_service(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_container_with_complex_objects(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_factory_with_complex_signature(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_service_info_edge_cases(self, clean_container: FlextContainer) -> None: ...
    def test_container_validation_edge_cases(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_performance_with_many_services(
        self, clean_container: FlextContainer
    ) -> None: ...

class TestContainerValidationIntegration:
    def test_registrar_validation_integration(self) -> None: ...
    def test_retriever_validation_integration(self) -> None: ...

class TestContainerSystemIntegration:
    def test_full_lifecycle_integration(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_factory_to_service_conversion_integration(
        self, clean_container: FlextContainer
    ) -> None: ...
    def test_global_container_full_integration(self) -> None: ...
