from collections.abc import Callable as Callable, Generator
from pathlib import Path

import pytest
from _typeshed import Incomplete

from flext_core import TAnyDict as TAnyDict

pytestmark: Incomplete

@pytest.fixture
def temp_dir() -> Generator[Path]: ...

class TestBaseConfigOps:
    def test_safe_load_from_dict_valid(self) -> None: ...
    def test_safe_load_from_dict_not_dict(self) -> None: ...
    def test_safe_load_from_dict_with_required_keys_present(self) -> None: ...
    def test_safe_load_from_dict_with_required_keys_missing(self) -> None: ...
    def test_safe_load_from_dict_invalid_required_keys(self) -> None: ...
    def test_safe_load_from_dict_copy_error(self) -> None: ...
    def test_safe_get_env_var_exists(self) -> None: ...
    def test_safe_get_env_var_not_exists_with_default(self) -> None: ...
    def test_safe_get_env_var_not_exists_no_default(self) -> None: ...
    def test_safe_get_env_var_not_exists_required(self) -> None: ...
    def test_safe_get_env_var_invalid_name(self) -> None: ...
    def test_safe_get_env_var_none_name(self) -> None: ...
    def test_safe_get_env_var_whitespace_name(self) -> None: ...
    def test_safe_get_env_var_os_error(self) -> None: ...
    def test_safe_load_json_file_valid(self, temp_json_file: str) -> None: ...
    def test_safe_load_json_file_path_object(self, temp_json_file: str) -> None: ...
    def test_safe_load_json_file_not_exists(self) -> None: ...
    def test_safe_load_json_file_not_file(self, temp_dir: Path) -> None: ...
    def test_safe_load_json_file_invalid_json(self, temp_dir: Path) -> None: ...
    def test_safe_load_json_file_not_dict(self, temp_dir: Path) -> None: ...
    def test_safe_load_json_file_encoding_error(self, temp_dir: Path) -> None: ...
    def test_safe_save_json_file_valid(self, temp_dir: Path) -> None: ...
    def test_safe_save_json_file_create_dirs(self, temp_dir: Path) -> None: ...
    def test_safe_save_json_file_no_create_dirs(self, temp_dir: Path) -> None: ...
    def test_safe_save_json_file_not_dict(self, temp_dir: Path) -> None: ...
    def test_safe_save_json_file_permission_error(self, temp_dir: Path) -> None: ...

class TestBaseConfigValidation:
    def test_validate_config_value_valid(self) -> None: ...
    def test_validate_config_value_invalid(self) -> None: ...
    def test_validate_config_value_not_callable(self) -> None: ...
    def test_validate_config_value_validator_exception(self) -> None: ...
    def test_validate_config_value_default_message(self) -> None: ...
    def test_validate_config_type_correct(self) -> None: ...
    def test_validate_config_type_incorrect(self) -> None: ...
    def test_validate_config_type_default_key_name(self) -> None: ...
    def test_validate_config_type_exception(self) -> None: ...
    def test_validate_config_range_valid(self) -> None: ...
    def test_validate_config_range_no_limits(self) -> None: ...
    def test_validate_config_range_below_min(self) -> None: ...
    def test_validate_config_range_above_max(self) -> None: ...
    def test_validate_config_range_only_min(self) -> None: ...
    def test_validate_config_range_only_max(self) -> None: ...
    def test_validate_config_range_default_key_name(self) -> None: ...
    def test_validate_config_range_exception(self) -> None: ...

class TestBaseConfigDefaults:
    def test_apply_defaults_valid(self) -> None: ...
    def test_apply_defaults_empty_config(self) -> None: ...
    def test_apply_defaults_empty_defaults(self) -> None: ...
    def test_apply_defaults_config_not_dict(self) -> None: ...
    def test_apply_defaults_defaults_not_dict(self) -> None: ...
    def test_apply_defaults_copy_independence(self) -> None: ...
    def test_apply_defaults_exception(self) -> None: ...
    def test_merge_configs_single(self) -> None: ...
    def test_merge_configs_multiple(self) -> None: ...
    def test_merge_configs_empty(self) -> None: ...
    def test_merge_configs_invalid_config(self) -> None: ...
    def test_merge_configs_exception(self) -> None: ...
    def test_filter_config_keys_valid(self) -> None: ...
    def test_filter_config_keys_empty_allowed(self) -> None: ...
    def test_filter_config_keys_all_allowed(self) -> None: ...
    def test_filter_config_keys_config_not_dict(self) -> None: ...
    def test_filter_config_keys_allowed_not_list(self) -> None: ...
    def test_filter_config_keys_exception(self) -> None: ...

class TestPerformanceConfig:
    def test_performance_config_constants(self) -> None: ...
    def test_performance_config_values(self) -> None: ...

class TestObservabilityConfig:
    def test_observability_config_constants(self) -> None: ...
    def test_observability_config_values(self) -> None: ...

class TestBaseConfig:
    def test_get_model_config_defaults(self) -> None: ...
    def test_get_model_config_custom_description(self) -> None: ...
    def test_get_model_config_custom_parameters(self) -> None: ...

class TestConfigBaseIntegration:
    def test_full_config_workflow(self, temp_dir: Path) -> None: ...
    def test_config_validation_chain(self) -> None: ...
    def test_config_merging_precedence(self) -> None: ...
    def test_environment_variable_integration(self) -> None: ...
    def test_error_recovery_workflow(self) -> None: ...
