from collections.abc import Callable as Callable

from _typeshed import Incomplete

from flext_core import FlextDomainService, FlextResult

EXPECTED_BULK_SIZE: int
EXPECTED_TOTAL_PAGES: int
EXPECTED_DATA_COUNT: int
pytestmark: Incomplete

class SampleCalculationService(FlextDomainService[float]):
    value: float
    multiplier: float
    def execute(self) -> FlextResult[float]: ...
    def calculate_sum(self, a: int, b: int) -> int: ...
    def calculate_product(self, a: int, b: int) -> int: ...

class SampleValidationService(FlextDomainService[str]):
    name: str
    min_length: int
    def execute(self) -> FlextResult[str]: ...
    def validate_config(self) -> FlextResult[None]: ...
    def validate_email(self, email: str) -> bool: ...
    def validate_age(self, age: int) -> bool: ...

class SampleErrorService(FlextDomainService[None]):
    def execute(self) -> FlextResult[None]: ...
    def always_fail(self) -> FlextResult[None]: ...
    def fail_with_context(self, context: str) -> FlextResult[None]: ...

class SampleExceptionService(FlextDomainService[None]):
    def execute(self) -> FlextResult[None]: ...
    def raise_exception(self) -> None: ...
    def raise_custom_exception(self, message: str) -> None: ...

class SampleConfigErrorService(FlextDomainService[None]):
    def execute(self) -> FlextResult[None]: ...
    def validate_config(self) -> FlextResult[None]: ...

class TestFlextDomainService:
    def test_domain_service_creation_valid(self) -> None: ...
    def test_domain_service_creation_with_defaults(self) -> None: ...
    def test_domain_service_frozen_immutable(self) -> None: ...
    def test_domain_service_extra_fields_forbidden(self) -> None: ...
    def test_execute_method_is_abstract(self) -> None: ...
    def test_execute_success(self) -> None: ...
    def test_execute_business_logic_failure(self) -> None: ...
    def test_execute_validation_service_success(self) -> None: ...
    def test_execute_validation_service_failure(self) -> None: ...
    def test_validate_config_default_success(self) -> None: ...
    def test_validate_config_custom_success(self) -> None: ...
    def test_validate_config_custom_failure(self) -> None: ...
    def test_validate_config_negative_min_length(self) -> None: ...
    def test_execute_operation_success(self) -> None: ...
    def test_execute_operation_with_kwargs(self) -> None: ...
    def test_execute_operation_config_validation_failure(self) -> None: ...
    def test_execute_operation_config_validation_empty_error(self) -> None: ...
    def test_execute_operation_exception_handling(self) -> None: ...
    def test_execute_operation_type_error_handling(self) -> None: ...
    def test_execute_operation_runtime_error_handling(self) -> None: ...
    def test_get_service_info_success(self) -> None: ...
    def test_get_service_info_invalid_config(self) -> None: ...
    def test_get_service_info_validation_service(self) -> None: ...
    def test_get_service_info_invalid_validation_service(self) -> None: ...
    def test_inheritance_from_mixins(self) -> None: ...
    def test_mixin_validation_functionality(self) -> None: ...
    def test_mixin_serialization_functionality(self) -> None: ...
    def test_service_with_complex_data_types(self) -> None: ...
    def test_error_service_execution(self) -> None: ...
    def test_error_service_with_default_message(self) -> None: ...

class TestDomainServiceIntegration:
    def test_service_composition_sequential(self) -> None: ...
    def test_service_composition_with_failure(self) -> None: ...
    def test_service_chaining_with_results(self) -> None: ...
    def test_multiple_service_info_collection(self) -> None: ...
    def test_service_execute_operation_complex_workflow(self) -> None: ...

class TestDomainServiceEdgeCases:
    def test_service_with_empty_operation_name(self) -> None: ...
    def test_service_operation_with_no_args(self) -> None: ...
    def test_service_operation_returning_none(self) -> None: ...
    def test_service_operation_returning_complex_object(self) -> None: ...
    def test_service_with_zero_values(self) -> None: ...
    def test_service_with_large_values(self) -> None: ...
    def test_validation_service_boundary_conditions(self) -> None: ...
    def test_service_info_with_invalid_config_service(self) -> None: ...

class TestDomainServiceTypes:
    def test_service_type_annotations(self) -> None: ...
    def test_service_field_types(self) -> None: ...
    def test_service_validation_with_string_field(self) -> None: ...
    def test_service_model_config_attributes(self) -> None: ...

class TestDomainServiceMockIntegration:
    def test_service_with_mocked_dependencies(self) -> None: ...
    def test_service_operation_callback_pattern(self) -> None: ...
    def test_service_with_complex_validation_logic(self) -> None: ...
