from decimal import Decimal

from _typeshed import Incomplete

from flext_core import FlextResult, FlextValueObject

pytestmark: Incomplete

class SimpleValueObject(FlextValueObject):
    value: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class EmailAddress(FlextValueObject):
    address: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class MoneyAmount(FlextValueObject):
    amount: Decimal
    currency: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class ComplexValueObject(FlextValueObject):
    name: str
    metadata: dict[str, object]
    tags: list[str]
    settings: dict[str, bool]
    def validate_business_rules(self) -> FlextResult[None]: ...

class InvalidValueObject(FlextValueObject):
    data: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class SerializationTestValueObject(FlextValueObject):
    name: str
    callback: object
    def validate_business_rules(self) -> FlextResult[None]: ...

class TestFlextValueObjectBasics:
    def test_value_object_creation_success(self) -> None: ...
    def test_value_object_creation_with_validation(self) -> None: ...
    def test_value_object_immutability(self) -> None: ...
    def test_value_object_equality(self) -> None: ...
    def test_value_object_hash_consistency(self) -> None: ...
    def test_complex_value_object_hash(self) -> None: ...

class TestValueObjectValidation:
    def test_validate_business_rules_success(self) -> None: ...
    def test_validate_business_rules_failure(self) -> None: ...
    def test_validate_flext_success(self) -> None: ...
    def test_validate_flext_failure(self) -> None: ...
    def test_validate_flext_with_logging(self) -> None: ...
    def test_validate_field_with_registry(self) -> None: ...
    def test_validate_all_fields(self) -> None: ...
    def test_validate_all_fields_with_internal_fields(self) -> None: ...

class TestValueObjectFormatting:
    def test_format_dict_simple(self) -> None: ...
    def test_format_dict_complex(self) -> None: ...
    def test_str_representation(self) -> None: ...
    def test_str_representation_complex(self) -> None: ...

class TestValueObjectPayloadConversion:
    def test_to_payload_success(self) -> None: ...
    def test_to_payload_with_validation_failure(self) -> None: ...
    def test_to_payload_serialization_fallback(self) -> None: ...
    def test_to_payload_complete_failure(self) -> None: ...
    def test_extract_serializable_attributes_pydantic(self) -> None: ...
    def test_extract_serializable_attributes_manual(self) -> None: ...
    def test_extract_serializable_no_model_dump(self) -> None: ...
    def test_process_serializable_values(self) -> None: ...
    def test_should_include_attribute(self) -> None: ...
    def test_safely_get_attribute(self) -> None: ...
    def test_safely_get_attribute_with_str_method(self) -> None: ...
    def test_safely_get_attribute_exception(self) -> None: ...
    def test_get_fallback_info(self) -> None: ...

class TestValueObjectSubclassing:
    def test_init_subclass_logging(self) -> None: ...

class TestFlextValueObjectFactory:
    def test_create_value_object_factory_basic(self) -> None: ...
    def test_create_value_object_factory_with_defaults(self) -> None: ...
    def test_factory_validation_failure(self) -> None: ...
    def test_factory_creation_failure(self) -> None: ...
    def test_factory_without_defaults(self) -> None: ...

class TestValueObjectIntegration:
    def test_value_object_with_complex_validation(self) -> None: ...
    def test_value_object_equality_and_hashing(self) -> None: ...
    def test_value_object_with_nested_structures(self) -> None: ...
    def test_factory_integration_scenario(self) -> None: ...

class TestValueObjectEdgeCases:
    def test_hash_with_unhashable_nested_data(self) -> None: ...
    def test_equality_with_different_types(self) -> None: ...
    def test_serialization_with_circular_references(self) -> None: ...
    def test_field_validation_error_handling(self) -> None: ...
    def test_all_fields_validation_with_errors(self) -> None: ...
