from typing import Protocol

from _typeshed import Incomplete

from flext_core import FlextEntity
from flext_core.result import FlextResult

class EntityFactory(Protocol):
    def __call__(self, **kwargs: object) -> FlextResult[object]: ...

pytestmark: Incomplete
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class SampleUser(FlextEntity):
    name: str
    email: str
    age: int
    is_active: bool
    def get_display_name(self) -> str: ...
    def is_adult(self) -> bool: ...
    def validate_business_rules(self) -> FlextResult[None]: ...

class SampleBadUser(FlextEntity):
    name: str
    email: str
    age: int
    def validate_business_rules(self) -> FlextResult[None]: ...

class TestFlextEntity:
    def test_entity_creation_valid(self) -> None: ...
    def test_entity_id_validation_empty(self) -> None: ...
    def test_entity_id_validation_whitespace(self) -> None: ...
    def test_entity_id_validation_strips_whitespace(self) -> None: ...
    def test_entity_equality_same_id(self) -> None: ...
    def test_entity_equality_different_id(self) -> None: ...
    def test_entity_equality_with_non_entity(self) -> None: ...
    def test_entity_hash_same_id(self) -> None: ...
    def test_entity_hash_different_id(self) -> None: ...
    def test_entity_str_representation(self) -> None: ...
    def test_entity_repr_representation(self) -> None: ...
    def test_increment_version_success(self) -> None: ...
    def test_increment_version_domain_validation_failure(self) -> None: ...
    def test_increment_version_construction_error(self) -> None: ...
    def test_copy_with_success(self) -> None: ...
    def test_copy_with_explicit_version(self) -> None: ...
    def test_copy_with_no_changes(self) -> None: ...
    def test_copy_with_domain_validation_failure(self) -> None: ...
    def test_copy_with_construction_error(self) -> None: ...
    def test_add_domain_event_success(self) -> None: ...
    def test_add_domain_event_creation_failure(self) -> None: ...
    def test_clear_events(self) -> None: ...
    def test_validate_field_success_with_field_definition(self) -> None: ...
    def test_validate_field_failure_with_field_definition(self) -> None: ...
    def test_validate_field_no_field_definition(self) -> None: ...
    def test_validate_field_exception_handling(self) -> None: ...
    def test_validate_all_fields_success(self) -> None: ...
    def test_validate_all_fields_with_failures(self) -> None: ...
    def test_validate_all_fields_no_field_definitions(self) -> None: ...
    def test_with_version_success(self) -> None: ...
    def test_with_version_invalid_version(self) -> None: ...
    def test_with_version_equal_version(self) -> None: ...
    def test_with_version_domain_validation_failure(self) -> None: ...
    def test_with_version_construction_error(self) -> None: ...

class TestFlextFactory:
    def test_create_entity_factory_basic(self) -> None: ...
    def test_factory_create_entity_success(self) -> None: ...
    def test_factory_with_defaults(self) -> None: ...
    def test_factory_override_defaults(self) -> None: ...
    def test_factory_generate_id_when_not_provided(self) -> None: ...
    def test_factory_use_provided_id(self) -> None: ...
    def test_factory_handle_empty_id(self) -> None: ...
    def test_factory_set_default_version(self) -> None: ...
    def test_factory_use_provided_version(self) -> None: ...
    def test_factory_domain_validation_failure(self) -> None: ...
    def test_factory_model_validation_error(self) -> None: ...
    def test_factory_type_error_handling(self) -> None: ...
    def test_factory_import_error_handling(self) -> None: ...

class TestEntityIntegration:
    def test_entity_lifecycle_with_events(self) -> None: ...
    def test_factory_with_complex_scenario(self) -> None: ...

class TestEntityCoverageImprovements:
    def test_validate_all_fields_with_internal_fields(self) -> None: ...
