class TestCreateOudConnectionConfig:
    def test_returns_dict_with_required_keys(self) -> None: ...
    def test_default_values_are_correct(self) -> None: ...
    def test_returns_consistent_config(self) -> None: ...
    def test_all_values_are_strings(self) -> None: ...

class TestCreateLdapTestConfig:
    def test_returns_dict_with_required_keys(self) -> None: ...
    def test_default_values_are_correct(self) -> None: ...
    def test_returns_consistent_config(self) -> None: ...
    def test_port_and_timeout_are_integers(self) -> None: ...
    def test_use_ssl_is_boolean(self) -> None: ...

class TestCreateApiTestResponse:
    def test_default_success_response(self) -> None: ...
    def test_success_response_with_custom_data(self) -> None: ...
    def test_failure_response(self) -> None: ...
    def test_failure_response_structure_details(self) -> None: ...
    def test_timestamp_format(self) -> None: ...
    def test_explicit_success_true(self) -> None: ...
    def test_explicit_success_false(self) -> None: ...
    def test_none_data_handling(self) -> None: ...
    def test_custom_data_types(self) -> None: ...
    def test_kwargs_only_parameters(self) -> None: ...

class TestUtilitiesIntegration:
    def test_oud_vs_ldap_config_differences(self) -> None: ...
    def test_api_response_success_vs_failure(self) -> None: ...
    def test_all_functions_return_dicts(self) -> None: ...
    def test_no_shared_mutable_state(self) -> None: ...

class TestFlextTestMockerPatchObject:
    def test_patch_object_with_new_none(self) -> None: ...
    def test_patch_object_with_new_value(self) -> None: ...
    def test_patch_object_preserves_kwargs(self) -> None: ...
    def test_patch_object_with_spec(self) -> None: ...
    def test_patch_object_no_kwargs(self) -> None: ...
