from _typeshed import Incomplete

pytestmark: Incomplete

class TestFlextPayload:
    def test_payload_creation_basic(self) -> None: ...
    def test_payload_creation_with_metadata(self) -> None: ...
    def test_payload_create_factory(self) -> None: ...
    def test_payload_with_metadata(self) -> None: ...
    def test_payload_get_metadata(self) -> None: ...
    def test_payload_has_metadata(self) -> None: ...
    def test_payload_to_dict(self) -> None: ...
    def test_payload_from_dict(self) -> None: ...
    def test_payload_from_dict_invalid(self) -> None: ...
    def test_payload_has_data(self) -> None: ...
    def test_payload_get_data(self) -> None: ...
    def test_payload_get_data_or_default(self) -> None: ...
    def test_payload_transform_data(self) -> None: ...
    def test_payload_transform_data_none(self) -> None: ...
    def test_payload_serialization_methods(self) -> None: ...

class TestFlextMessage:
    def test_message_create_basic(self) -> None: ...
    def test_message_create_with_level(self) -> None: ...
    def test_message_create_with_source(self) -> None: ...
    def test_message_create_empty(self) -> None: ...
    def test_message_create_invalid_level(self) -> None: ...
    def test_message_properties(self) -> None: ...
    def test_message_cross_service_dict(self) -> None: ...

class TestFlextEvent:
    def test_event_create_basic(self) -> None: ...
    def test_event_create_with_aggregate(self) -> None: ...
    def test_event_create_with_version(self) -> None: ...
    def test_event_create_empty_type(self) -> None: ...
    def test_event_create_invalid_aggregate_id(self) -> None: ...
    def test_event_create_invalid_version(self) -> None: ...
    def test_event_properties(self) -> None: ...
    def test_event_cross_service_dict(self) -> None: ...

class TestEdgeCases:
    def test_payload_create_validation_error(self) -> None: ...
    def test_payload_transform_error(self) -> None: ...
    def test_message_from_cross_service_dict(self) -> None: ...
    def test_message_from_cross_service_dict_invalid(self) -> None: ...
    def test_event_from_cross_service_dict(self) -> None: ...
    def test_event_from_cross_service_dict_invalid(self) -> None: ...
    def test_payload_json_serialization_round_trip(self) -> None: ...
    def test_payload_compression(self) -> None: ...
    def test_cross_service_utilities(self) -> None: ...
