import pytest
from _typeshed import Incomplete

pytestmark: Incomplete

@pytest.fixture
def payload_test_data() -> dict[str, object]: ...

class TestFlextPayload:
    def test_payload_creation_with_various_data_types(
        self, test_data: object
    ) -> None: ...

class TestFlextEventCoverage:
    def test_create_event_invalid_event_type_empty(self) -> None: ...
    def test_create_event_invalid_event_type_none(self) -> None: ...
    def test_create_event_invalid_aggregate_id(self) -> None: ...
    def test_create_event_negative_version(self) -> None: ...
    def test_create_event_validation_error(self) -> None: ...
    def test_event_property_version_invalid(self) -> None: ...

class TestFlextMessageCoverage:
    def test_create_message_empty_string(self) -> None: ...
    def test_create_message_none(self) -> None: ...
    def test_create_message_invalid_level(self) -> None: ...
    def test_create_message_validation_error(self) -> None: ...

class TestFlextPayloadCoverage:
    def test_from_dict_invalid_metadata(self) -> None: ...
    def test_to_dict_basic_mixin_attributes_skip(self) -> None: ...
    def test_serialization_collection_handling(self) -> None: ...
    def test_payload_operations_comprehensive(
        self, payload_test_data: dict[str, object], operations: list[str]
    ) -> None: ...

class TestFlextPayloadEdgeCases:
    def test_payload_from_dict_invalid_metadata(
        self, invalid_data: dict[str, object], expected_metadata: dict[str, object]
    ) -> None: ...
    def test_payload_from_dict_with_exception_handling(self) -> None: ...
