from _typeshed import Incomplete
from pydantic import BaseModel

flext_safe_call: Incomplete
flext_cache_decorator: Incomplete
flext_safe_decorator: Incomplete
flext_timing_decorator: Incomplete
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class UserModel(BaseModel):
    name: str
    age: int
    email: str

class TestFlextDecorators:
    def test_safe_result_decorator_success(self) -> None: ...
    def test_safe_result_decorator_failure(self) -> None: ...
    def test_safe_result_decorator_with_none_return(self) -> None: ...
    def test_validated_with_result_decorator_success(self) -> None: ...
    def test_validated_with_result_decorator_validation_failure(self) -> None: ...
    def test_validated_with_result_decorator_execution_failure(self) -> None: ...
    def test_cached_with_timing_decorator(self) -> None: ...
    def test_safe_cached_decorator(self) -> None: ...
    def test_validated_cached_decorator(self) -> None: ...
    def test_complete_decorator_with_all_features(self) -> None: ...
    def test_complete_decorator_minimal(self) -> None: ...

class TestStandaloneDecorators:
    def test_flext_safe_call_success(self) -> None: ...
    def test_flext_safe_call_failure(self) -> None: ...
    def test_flext_cache_decorator(self) -> None: ...
    def test_flext_safe_decorator(self) -> None: ...
    def test_flext_timing_decorator(self) -> None: ...

class TestDecoratorComposition:
    def test_multiple_decorators_composition(self) -> None: ...
    def test_decorator_with_validation_and_caching(self) -> None: ...

class TestFlextValidationDecorators:
    def test_validation_decorator_no_input(self) -> None: ...
    def test_validation_decorator_none_output(self) -> None: ...
    def test_validation_decorator_apply_decoration_input_failure(self) -> None: ...
    def test_validation_decorator_apply_decoration_output_failure(self) -> None: ...

class TestDecoratorErrorHandling:
    def test_safe_result_with_different_exception_types(self) -> None: ...

class TestFlextDecoratorUtils:
    def test_preserve_metadata_complete(self) -> None: ...
    def test_preserve_metadata_partial(self) -> None: ...

class TestFlextErrorHandlingDecorators:
    def test_error_handler_initialization(self) -> None: ...
    def test_handle_error_method(self) -> None: ...
    def test_should_handle_error_method(self) -> None: ...
    def test_create_error_result_method(self) -> None: ...
    def test_error_handling_decorator_apply_decoration(self) -> None: ...

class TestFlextPerformanceDecorators:
    def test_performance_decorator_initialization(self) -> None: ...
    def test_start_timing_method(self) -> None: ...
    def test_stop_timing_method(self) -> None: ...
    def test_record_metrics_method(self) -> None: ...
    def test_performance_decorator_apply_decoration(self) -> None: ...
    def test_validation_decorator_error_details(self) -> None: ...

class TestDecoratorPerformance:
    def test_caching_effectiveness(self) -> None: ...
    def test_cache_size_limits(self) -> None: ...

class TestBaseDecoratorClasses:
    def test_base_decorator_utils(self) -> None: ...
    def test_base_validation_decorators(self) -> None: ...
    def test_base_error_handling_decorators(self) -> None: ...
    def test_base_performance_decorators(self) -> None: ...

class TestDecoratorCoverageImprovements:
    def test_decorator_imports_coverage(self) -> None: ...
    def test_immutability_decorators_coverage(self) -> None: ...
    def test_functional_decorators_coverage(self) -> None: ...
    def test_logging_decorator_exception_handling(self) -> None: ...
    def test_logging_decorator_type_error_handling(self) -> None: ...
    def test_logging_decorator_value_error_handling(self) -> None: ...
    def test_log_exceptions_decorator_exception_handling(self) -> None: ...
    def test_log_exceptions_decorator_multiple_exception_types(self) -> None: ...
    def test_safe_call_decorator_with_error_handler(self) -> None: ...
    def test_validate_input_decorator_validation_failure(self) -> None: ...
    def test_validate_input_decorator_with_multiple_args(self) -> None: ...
    def test_decorator_factory_methods_coverage(self) -> None: ...
    def test_error_handling_decorator_retry_method(self) -> None: ...
