from _typeshed import Incomplete

from flext_core import (
    BaseEntry,
    BaseFileWriter,
    BaseProcessor,
    FlextResult,
    FlextValueObject,
    RegexProcessor,
)

class MockEntry(FlextValueObject):
    entry_type: str
    clean_content: str
    original_content: str
    identifier: str
    def validate_business_rules(self) -> FlextResult[None]: ...

class ConcreteRegexProcessor(RegexProcessor[MockEntry]): ...
class ConcreteBaseProcessor(BaseProcessor[MockEntry]): ...

class ConcreteBaseEntry(BaseEntry):
    def validate_business_rules(self) -> FlextResult[None]: ...

class MockEntryValidator:
    is_valid_result: Incomplete
    is_whitelisted_result: Incomplete
    def __init__(
        self, *, is_valid: bool = True, is_whitelisted: bool = True
    ) -> None: ...
    def is_valid(self, entry: MockEntry) -> bool: ...
    def is_whitelisted(self, identifier: str) -> bool: ...

class MockProcessor(BaseProcessor[MockEntry]): ...

class MockFileWriter(BaseFileWriter):
    fail_write: Incomplete
    written_entries: list[object]
    def __init__(self, *, fail_write: bool = False) -> None: ...
    def write_header(self, output_file: object) -> None: ...
    def write_entry(self, output_file: object, entry: object) -> None: ...

class TestEntryType:
    def test_entry_type_enum(self) -> None: ...

class TestBaseEntry:
    def test_base_entry_creation(self) -> None: ...
    def test_base_entry_immutability(self) -> None: ...

class TestConfigAttributeValidator:
    test_attr: str
    def test_has_attribute_true(self) -> None: ...
    def test_has_attribute_false(self) -> None: ...
    rules_config: Incomplete
    def test_has_rules_config_true(self) -> None: ...
    def test_has_rules_config_false(self) -> None: ...
    attr1: str
    attr2: str
    def test_validate_required_attributes_success(self) -> None: ...
    def test_validate_required_attributes_failure(self) -> None: ...

class TestBaseConfigManager:
    def test_init(self) -> None: ...
    test_key: str
    def test_get_config_value_exists(self) -> None: ...
    def test_get_config_value_default(self) -> None: ...
    attr1: str
    attr2: str
    def test_validate_config_success(self) -> None: ...
    def test_validate_config_no_requirements(self) -> None: ...
    def test_validate_config_failure(self) -> None: ...

class TestBaseProcessor:
    def test_init_without_validator(self) -> None: ...
    def test_init_with_validator(self) -> None: ...
    def test_extract_entry_info_success(self) -> None: ...
    def test_extract_entry_info_with_prefix(self) -> None: ...
    def test_extract_entry_info_identifier_failure(self) -> None: ...
    def test_extract_entry_info_creation_failure(self) -> None: ...
    def test_extract_entry_info_validator_not_whitelisted(self) -> None: ...
    def test_extract_entry_info_validator_not_valid(self) -> None: ...
    def test_process_content_lines_success(self) -> None: ...
    def test_process_content_lines_with_empty_lines(self) -> None: ...
    def test_process_content_lines_partial_failure(self) -> None: ...
    def test_process_content_lines_all_failure(self) -> None: ...
    def test_get_extracted_entries(self) -> None: ...
    def test_clear_extracted_entries(self) -> None: ...

class TestRegexProcessor:
    def test_init(self) -> None: ...
    def test_extract_identifier_success(self) -> None: ...
    def test_extract_identifier_no_match(self) -> None: ...

class TestBaseSorter:
    def test_init_default_key_extractor(self) -> None: ...
    def test_init_custom_key_extractor(self) -> None: ...
    def test_sort_entries_success(self) -> None: ...
    def test_sort_entries_exception_handling(self) -> None: ...

class TestBaseFileWriter:
    written_data: list[str]
    def test_write_entries_success(self) -> None: ...
    def test_write_entries_failure(self) -> None: ...

class TestProcessingPipeline:
    def test_init(self) -> None: ...
    def test_add_step(self) -> None: ...
    def test_process_success(self) -> None: ...
    def test_process_failure(self) -> None: ...
    def test_process_empty_pipeline(self) -> None: ...

class TestEntryValidatorProtocol:
    def test_protocol_implementation(self) -> None: ...
