"""Generated root lazy export map: lazy_core."""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final

ROOT_LAZY_CORE: Final[Mapping[str, tuple[str, ...]]] = MappingProxyType({
    "._constants.base": ("FlextConstantsBase",),
    "._constants.cqrs": ("FlextConstantsCqrs",),
    "._constants.enforcement": (
        "FlextConstantsEnforcement",
        "FlextMroViolation",
        "FlextSmellViolation",
    ),
    "._constants.environment": ("FlextConstantsEnvironment",),
    "._constants.errors": ("FlextConstantsErrors",),
    "._constants.file": ("FlextConstantsFile",),
    "._constants.guards": ("FlextConstantsGuards",),
    "._constants.infrastructure": ("FlextConstantsInfrastructure",),
    "._constants.logging": ("FlextConstantsLogging",),
    "._constants.mixins": ("FlextConstantsMixins",),
    "._constants.project_metadata": ("FlextConstantsProjectMetadata",),
    "._constants.pydantic": ("FlextConstantsPydantic",),
    "._constants.regex": ("FlextConstantsRegex",),
    "._constants.serialization": ("FlextConstantsSerialization",),
    "._constants.settings": ("FlextConstantsSettings",),
    "._constants.status": ("FlextConstantsStatus",),
    "._constants.timeout": ("FlextConstantsTimeout",),
    "._constants.validation": ("FlextConstantsValidation",),
    "._exceptions.base": ("FlextExceptionsBase",),
    "._exceptions.factories": ("FlextExceptionsFactories",),
    "._exceptions.helpers": ("FlextExceptionsHelpers",),
    "._exceptions.metrics": ("FlextExceptionsMetrics",),
    "._exceptions.template": ("FlextExceptionsTemplate",),
    "._exceptions.types": ("FlextExceptionsTypes",),
    "._models.base": ("FlextModelsBase",),
    "._models.builder": ("FlextModelsBuilder",),
    "._models.collections": ("FlextModelsCollections",),
    "._models.container": ("FlextModelsContainer",),
    "._models.containers": ("FlextModelsContainers", "mc"),
    "._models.context": ("FlextModelsContext",),
    "._models.cqrs": ("FlextModelsCqrs",),
    "._models.dispatcher": ("FlextModelsDispatcher",),
    "._models.domain_event": ("FlextModelsDomainEvent",),
    "._models.enforcement": ("FlextModelsEnforcement",),
    "._models.entity": ("FlextModelsEntity",),
    "._models.errors": ("FlextModelsErrors",),
    "._models.exception_params": ("FlextModelsExceptionParams",),
    "._models.handler": ("FlextModelsHandler",),
    "._models.namespace": ("FlextModelsNamespace",),
    "._models.project_metadata": ("FlextModelsProjectMetadata",),
    "._models.pydantic": ("FlextModelsPydantic",),
    "._models.registry": ("FlextModelsRegistry",),
    "._models.service": ("FlextModelsService",),
    "._models.settings": ("FlextModelsSettings",),
    "._protocols.base": ("FlextProtocolsBase",),
    "._protocols.container": ("FlextProtocolsContainer",),
    "._protocols.context": ("FlextProtocolsContext",),
    "._protocols.handler": ("FlextProtocolsHandler",),
    "._protocols.logging": ("FlextProtocolsLogging",),
    "._protocols.pydantic": ("FlextProtocolsPydantic",),
    "._protocols.registry": ("FlextProtocolsRegistry",),
    "._protocols.result": ("FlextProtocolsResult",),
    "._protocols.service": ("FlextProtocolsService",),
    "._protocols.settings": ("FlextProtocolsSettings",),
    "._settings.base": ("FlextSettingsBase",),
    "._settings.context": ("FlextSettingsContext",),
    "._settings.core": ("FlextSettingsCore",),
    "._settings.database": ("FlextSettingsDatabase",),
    "._settings.di": ("FlextSettingsDI",),
    "._settings.dispatcher": ("FlextSettingsDispatcher",),
    "._settings.infrastructure": ("FlextSettingsInfrastructure",),
    "._settings.registry": ("FlextSettingsRegistry",),
    "._typings.annotateds": ("FlextTypesAnnotateds",),
    "._typings.base": ("FlextTypingBase",),
    "._typings.containers": ("FlextTypingContainers",),
    "._typings.core": ("FlextTypesCore",),
    "._typings.project_metadata": ("FlextTypingProjectMetadata",),
    "._typings.pydantic": ("FlextTypesPydantic",),
    "._typings.services": ("FlextTypesServices",),
    "._typings.typeadapters": ("FlextTypesTypeAdapters",),
})

__all__: list[str] = ["ROOT_LAZY_CORE"]
