from flext_core import TErrorMessage as TErrorMessage, TUserData as TUserData

from .validation_utilities import (
    is_email as is_email,
    is_int as is_int,
    is_non_empty_string as is_non_empty_string,
)

class DemonstrationSectionHelper:
    @staticmethod
    def print_section_header(_example_num: int, _title: str) -> None: ...
    @staticmethod
    def log_operation(operation: str, result: object) -> None: ...
    @staticmethod
    def print_separator() -> None: ...
    @staticmethod
    def log_success(message: str) -> None: ...
    @staticmethod
    def log_error(message: str) -> None: ...

class ValidationHelper:
    @staticmethod
    def validate_user_data(user_data: TUserData) -> list[TErrorMessage]: ...
    @staticmethod
    def report_validation_result(validation_errors: list[TErrorMessage]) -> None: ...
    @staticmethod
    def validate_config_data(config: dict[str, object]) -> list[TErrorMessage]: ...

class FormattingHelper:
    @staticmethod
    def format_currency(amount: float, currency: str = "USD") -> str: ...
    @staticmethod
    def format_percentage(value: float) -> str: ...
    @staticmethod
    def format_file_size(bytes_count: int) -> str: ...
