from flext_core import TEntityId as TEntityId, TUserData as TUserData

from ..shared_domain import SharedDomainFactory as SharedDomainFactory
from .complexity_helpers import (
    DemonstrationSectionHelper as DemonstrationSectionHelper,
    ValidationHelper as ValidationHelper,
)
from .domain_models import UtilityDemoUser as UtilityDemoUser
from .formatting_helpers import (
    generate_hash_id as generate_hash_id,
    generate_prefixed_id as generate_prefixed_id,
    generate_short_id as generate_short_id,
)
from .validation_utilities import calculate_discount_price as calculate_discount_price

def demonstrate_id_generation() -> None: ...
def demonstrate_timestamp_generation() -> None: ...
def demonstrate_type_checking() -> None: ...
def demonstrate_validation() -> None: ...
def demonstrate_shared_domain_usage() -> None: ...
def demonstrate_business_logic() -> None: ...
def run_all_demonstrations() -> None: ...
