from decimal import Decimal

from examples.shared_domain import Order as SharedOrder, Product as SharedProduct

from flext_core import FlextResult

from .formatting_helpers import MAX_DISCOUNT_PERCENTAGE as MAX_DISCOUNT_PERCENTAGE

def is_email(value: str) -> bool: ...
def is_url(value: str) -> bool: ...
def is_string(value: object) -> bool: ...
def is_int(value: object) -> bool: ...
def is_list(value: object) -> bool: ...
def is_dict(value: object) -> bool: ...
def is_non_empty_string(value: object) -> bool: ...
def calculate_discount_price(
    product: SharedProduct, discount_percentage: float
) -> FlextResult[Decimal]: ...
def process_shared_order(order: SharedOrder) -> FlextResult[SharedOrder]: ...
