"""Infrastructure enforcement catalog rows."""

from __future__ import annotations

from typing import Final


class FlextConstantsEnforcementCatalogInfraRows:
    """Infra detector rows for the enforcement catalog."""

    INFRA_DETECTOR_ROWS: Final[
        tuple[tuple[str, str, str, str, tuple[str, ...], bool, str], ...]
    ] = (
        (
            "ENFORCE-001",
            "HIGH",
            "loose_objects",
            "2-architecture-law",
            ("flext-mro-namespace-rules",),
            False,
            "Loose object detected at module level — every public symbol must be nested inside its facade family.",
        ),
        (
            "ENFORCE-002",
            "HIGH",
            "import_violations",
            "",
            ("flext-import-rules",),
            False,
            "Import alias source is wrong — alias imported from a non-canonical module.",
        ),
        (
            "ENFORCE-003",
            "HIGH",
            "namespace_source_violations",
            "",
            ("flext-import-rules", "flext-mro-namespace-rules"),
            False,
            "Namespace source violation — canonical alias imported from a project that does not own that slot.",
        ),
        (
            "ENFORCE-004",
            "MEDIUM",
            "internal_import_violations",
            "",
            ("flext-import-rules",),
            False,
            "Internal (private) module import reaches outside its owning package boundary.",
        ),
        (
            "ENFORCE-005",
            "MEDIUM",
            "manual_protocol_violations",
            "",
            ("flext-patterns",),
            False,
            "Manual Protocol class declared outside protocols.py / _protocols/ tree.",
        ),
        (
            "ENFORCE-006",
            "CRITICAL",
            "cyclic_imports",
            "",
            ("flext-import-rules",),
            False,
            "Cyclic import detected between modules.",
        ),
        (
            "ENFORCE-007",
            "HIGH",
            "runtime_alias_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "Runtime alias (c/p/t/m/u/r/s/x/d/e/h) rebound in a module that should not own it.",
        ),
        (
            "ENFORCE-008",
            "MEDIUM",
            "future_violations",
            "",
            ("rules-examples",),
            False,
            "Python module missing `from __future__ import annotations`.",
        ),
        (
            "ENFORCE-009",
            "MEDIUM",
            "manual_typing_violations",
            "",
            ("flext-type-system",),
            False,
            "Manual typing alias declared outside typings.py / _typings/ tree.",
        ),
        (
            "ENFORCE-010",
            "LOW",
            "compatibility_alias_violations",
            "",
            ("flext-refactoring-workflow",),
            False,
            "Backwards-compatibility alias retained after refactor — should be removed.",
        ),
        (
            "ENFORCE-080",
            "HIGH",
            "compatibility_alias_violations",
            "4-import-law",
            ("flext-import-rules", "flext-mro-namespace-rules"),
            False,
            "Canonical alias imported from flext_core when the current project re-exports the same slot locally. Use from <proj>.constants import c etc. Violates AGENTS.md §4 (Import Law).",
        ),
        (
            "ENFORCE-011",
            "HIGH",
            "class_placement_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "Class placed in the wrong facade layer (e.g. Protocol in models.py).",
        ),
        (
            "ENFORCE-012",
            "CRITICAL",
            "mro_completeness_violations",
            "",
            ("flext-mro-namespace-rules",),
            False,
            "MRO composition incomplete — facade does not compose all its domain mixin trees.",
        ),
        (
            "ENFORCE-013",
            "HIGH",
            "parse_failures",
            "",
            (),
            False,
            "Source file failed to parse during enforcement.",
        ),
        (
            "ENFORCE-014",
            "CRITICAL",
            "facade_statuses",
            "",
            ("flext-mro-namespace-rules",),
            True,
            "Canonical facade family is missing (no constants.py / models.py / typings.py / protocols.py / utilities.py).",
        ),
        (
            "ENFORCE-026",
            "HIGH",
            "bare_except_violations",
            "3-1-supreme-law",
            ("flext-patterns",),
            False,
            "Bare `except:` clause swallows all exceptions including SystemExit.",
        ),
        (
            "ENFORCE-027",
            "MEDIUM",
            "print_violations",
            "3-1-supreme-law",
            ("flext-patterns",),
            False,
            "`print()` call in source code — use structured logging.",
        ),
        (
            "ENFORCE-028",
            "HIGH",
            "breakpoint_violations",
            "3-1-supreme-law",
            ("flext-patterns",),
            False,
            "`breakpoint()` / pdb left in code.",
        ),
        (
            "ENFORCE-029",
            "MEDIUM",
            "open_encoding_violations",
            "3-1-supreme-law",
            ("flext-patterns",),
            False,
            "`open()` without explicit encoding.",
        ),
        (
            "ENFORCE-030",
            "HIGH",
            "dict_annotation_violations",
            "3-2-types-and-contracts",
            ("flext-strict-typing",),
            False,
            "`dict` in type annotation — prefer Mapping / MutableMapping / TypedDict.",
        ),
        (
            "ENFORCE-031",
            "HIGH",
            "typing_dict_attr_violations",
            "3-2-types-and-contracts",
            ("flext-strict-typing",),
            False,
            "`typing.Dict` attribute usage — use collections.abc.Mapping family.",
        ),
        (
            "ENFORCE-032",
            "HIGH",
            "typing_dict_import_violations",
            "3-2-types-and-contracts",
            ("flext-strict-typing",),
            False,
            "`from typing import Dict` — banned in favor of dict / Mapping.",
        ),
        (
            "ENFORCE-033",
            "HIGH",
            "hardcoded_version_violations",
            "3-4-tools-and-modules",
            ("flext-patterns",),
            False,
            "Hardcoded `__version__` string — use importlib.metadata.",
        ),
        (
            "ENFORCE-081",
            "HIGH",
            "inline_import_violations",
            "4-import-law",
            ("flext-import-rules", "flext-patterns"),
            False,
            "Inline or lazy import declared inside a function body or dynamic importlib.import_module call.",
        ),
        (
            "ENFORCE-082",
            "HIGH",
            "silent_failure_violations",
            "3-1-supreme-law",
            ("flext-patterns",),
            False,
            "Exception-silencing pattern (contextlib.suppress, except...: pass, broad except, unwrap_or sentinel, or sentinel return on failure branch).",
        ),
    )


__all__ = ["FlextConstantsEnforcementCatalogInfraRows"]
