# AUTO-GENERATED FILE — Regenerate with: make gen
"""Utilities package."""

from __future__ import annotations

from flext_core.lazy import (
    build_lazy_import_map,
    install_lazy_exports,
    merge_lazy_imports,
)

_LAZY_IMPORTS = merge_lazy_imports(
    ("._beartype",),
    build_lazy_import_map(
        {
            "._beartype.attr_visitor": ("FlextUtilitiesBeartypeAttrVisitor",),
            "._beartype.class_visitor": ("FlextUtilitiesBeartypeClassVisitor",),
            "._beartype.deprecated_visitor": (
                "FlextUtilitiesBeartypeDeprecatedVisitor",
            ),
            "._beartype.field_visitor": ("FlextUtilitiesBeartypeFieldVisitor",),
            "._beartype.helpers": ("FlextUtilitiesBeartypeHelpers",),
            "._beartype.import_visitor": ("FlextUtilitiesBeartypeImportVisitor",),
            "._beartype.method_visitor": ("FlextUtilitiesBeartypeMethodVisitor",),
            "._beartype.module_visitor": ("FlextUtilitiesBeartypeModuleVisitor",),
            ".args": ("FlextUtilitiesArgs",),
            ".beartype_conf": ("FlextUtilitiesBeartypeConf",),
            ".beartype_engine": (
                "FlextUtilitiesBeartypeEngine",
                "ube",
            ),
            ".checker": ("FlextUtilitiesChecker",),
            ".collection": ("FlextUtilitiesCollection",),
            ".collection_iter": ("FlextUtilitiesCollectionIter",),
            ".collection_merge": ("FlextUtilitiesCollectionMerge",),
            ".context": ("FlextUtilitiesContext",),
            ".context_crud": ("FlextUtilitiesContextCrud",),
            ".context_lifecycle": ("FlextUtilitiesContextLifecycle",),
            ".context_state": ("FlextUtilitiesContextState",),
            ".context_tracing": ("FlextUtilitiesContextTracing",),
            ".conversion": ("FlextUtilitiesConversion",),
            ".discovery": ("FlextUtilitiesDiscovery",),
            ".dispatcher_execute": ("execute_dispatcher_handler",),
            ".domain": ("FlextUtilitiesDomain",),
            ".enforcement": ("FlextUtilitiesEnforcement",),
            ".enforcement_collect": ("FlextUtilitiesEnforcementCollect",),
            ".enforcement_emit": ("FlextUtilitiesEnforcementEmit",),
            ".enum": ("FlextUtilitiesEnum",),
            ".generators": ("FlextUtilitiesGenerators",),
            ".guards": ("FlextUtilitiesGuards",),
            ".guards_type_core": ("FlextUtilitiesGuardsTypeCore",),
            ".guards_type_model": ("FlextUtilitiesGuardsTypeModel",),
            ".guards_type_protocol": ("FlextUtilitiesGuardsTypeProtocol",),
            ".handler": ("FlextUtilitiesHandler",),
            ".logging_config": ("FlextUtilitiesLoggingConfig",),
            ".logging_context": ("FlextUtilitiesLoggingContext",),
            ".mapper": ("FlextUtilitiesMapper",),
            ".mapper_access": ("FlextUtilitiesMapperAccess",),
            ".mapper_extract": ("FlextUtilitiesMapperExtract",),
            ".model": ("FlextUtilitiesModel",),
            ".model_options": ("FlextUtilitiesModelOptions",),
            ".model_runtime": ("FlextUtilitiesModelRuntime",),
            ".parser": ("FlextUtilitiesParser",),
            ".parser_coerce": ("FlextUtilitiesParserCoerce",),
            ".parser_targets": ("FlextUtilitiesParserTargets",),
            ".project_metadata": ("FlextUtilitiesProjectMetadata",),
            ".pydantic": ("FlextUtilitiesPydantic",),
            ".reliability": ("FlextUtilitiesReliability",),
            ".runtime_violation_registry": ("FlextUtilitiesRuntimeViolationRegistry",),
            ".settings": ("FlextUtilitiesSettings",),
            ".text": ("FlextUtilitiesText",),
        },
    ),
    exclude_names=(
        "cleanup_submodule_namespace",
        "install_lazy_exports",
        "lazy_getattr",
        "logger",
        "merge_lazy_imports",
        "output",
        "output_reporting",
        "pytest_addoption",
        "pytest_collect_file",
        "pytest_collection_modifyitems",
        "pytest_configure",
        "pytest_runtest_setup",
        "pytest_runtest_teardown",
        "pytest_sessionfinish",
        "pytest_sessionstart",
        "pytest_terminal_summary",
        "pytest_warning_recorded",
    ),
    module_name=__name__,
)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
