# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Examples package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

if TYPE_CHECKING:
    from examples import (
        _models as _models,
        ex_01_flext_result as ex_01_flext_result,
        ex_02_flext_settings as ex_02_flext_settings,
        ex_03_flext_logger as ex_03_flext_logger,
        ex_04_flext_dispatcher as ex_04_flext_dispatcher,
        ex_05_flext_mixins as ex_05_flext_mixins,
        ex_06_flext_context as ex_06_flext_context,
        ex_07_flext_exceptions as ex_07_flext_exceptions,
        ex_08_flext_container as ex_08_flext_container,
        ex_09_flext_decorators as ex_09_flext_decorators,
        ex_10_flext_handlers as ex_10_flext_handlers,
        ex_11_flext_service as ex_11_flext_service,
        ex_12_flext_registry as ex_12_flext_registry,
        logging_config_once_pattern as logging_config_once_pattern,
        models as models,
        shared as shared,
    )
    from examples._models import (
        ex00 as ex00,
        ex01 as ex01,
        ex02 as ex02,
        ex03 as ex03,
        ex04 as ex04,
        ex05 as ex05,
        ex07 as ex07,
        ex08 as ex08,
        ex10 as ex10,
        ex11 as ex11,
        ex12 as ex12,
        ex14 as ex14,
        exconfig as exconfig,
    )
    from examples._models.ex00 import (
        Ex00UserInput as Ex00UserInput,
        Ex00UserProfile as Ex00UserProfile,
    )
    from examples._models.ex01 import (
        Ex01DemonstrationResult as Ex01DemonstrationResult,
        Ex01InvalidPersonPayload as Ex01InvalidPersonPayload,
        Ex01RunDemonstrationCommand as Ex01RunDemonstrationCommand,
        Ex01User as Ex01User,
        Ex01ValidPersonPayload as Ex01ValidPersonPayload,
    )
    from examples._models.ex02 import (
        Ex02CacheService as Ex02CacheService,
        Ex02DatabaseService as Ex02DatabaseService,
        Ex02EmailService as Ex02EmailService,
        Ex02TestConfig as Ex02TestConfig,
    )
    from examples._models.ex03 import (
        Ex03Email as Ex03Email,
        Ex03Money as Ex03Money,
        Ex03Order as Ex03Order,
        Ex03OrderItem as Ex03OrderItem,
        Ex03User as Ex03User,
    )
    from examples._models.ex04 import (
        Ex04AutoCommand as Ex04AutoCommand,
        Ex04CreateUser as Ex04CreateUser,
        Ex04DeleteUser as Ex04DeleteUser,
        Ex04FailingDelete as Ex04FailingDelete,
        Ex04GetUser as Ex04GetUser,
        Ex04NoSubscriberEvent as Ex04NoSubscriberEvent,
        Ex04Ping as Ex04Ping,
        Ex04UnknownQuery as Ex04UnknownQuery,
        Ex04UserCreated as Ex04UserCreated,
    )
    from examples._models.ex05 import (
        Ex05BadProcessor as Ex05BadProcessor,
        Ex05GoodProcessor as Ex05GoodProcessor,
        Ex05HandlerBad as Ex05HandlerBad,
        Ex05HandlerLike as Ex05HandlerLike,
        Ex05StatusEnum as Ex05StatusEnum,
        Ex05UserModel as Ex05UserModel,
    )
    from examples._models.ex07 import (
        Ex07CreateUserCommand as Ex07CreateUserCommand,
        Ex07DemoPlugin as Ex07DemoPlugin,
        Ex07GetUserQuery as Ex07GetUserQuery,
        Ex07UserCreatedEvent as Ex07UserCreatedEvent,
    )
    from examples._models.ex08 import Ex08Order as Ex08Order, Ex08User as Ex08User
    from examples._models.ex10 import (
        Ex10CommandBusStub as Ex10CommandBusStub,
        Ex10ContextPayload as Ex10ContextPayload,
        Ex10DerivedMessage as Ex10DerivedMessage,
        Ex10Entity as Ex10Entity,
        Ex10Message as Ex10Message,
        Ex10ProcessorBad as Ex10ProcessorBad,
        Ex10ProcessorGood as Ex10ProcessorGood,
        Ex10ProtocolHandler as Ex10ProtocolHandler,
        Ex10ServiceStub as Ex10ServiceStub,
    )
    from examples._models.ex11 import (
        Ex11CommandBusStub as Ex11CommandBusStub,
        Ex11EntityStub as Ex11EntityStub,
        Ex11HandlerLike as Ex11HandlerLike,
        Ex11HandlerLikeService as Ex11HandlerLikeService,
        Ex11Payload as Ex11Payload,
        Ex11ProcessorProtocolBad as Ex11ProcessorProtocolBad,
        Ex11ProcessorProtocolGood as Ex11ProcessorProtocolGood,
    )
    from examples._models.ex12 import (
        Ex12CommandA as Ex12CommandA,
        Ex12CommandB as Ex12CommandB,
    )
    from examples._models.ex14 import (
        Ex14CreateUserCommand as Ex14CreateUserCommand,
        Ex14GetUserQuery as Ex14GetUserQuery,
        Ex14UserDTO as Ex14UserDTO,
    )
    from examples._models.exconfig import ExConfigAppConfig as ExConfigAppConfig
    from examples._models.shared import (
        SharedHandle as SharedHandle,
        SharedPerson as SharedPerson,
    )
    from examples.ex_01_flext_result import Ex01r as Ex01r
    from examples.ex_02_flext_settings import Ex02FlextSettings as Ex02FlextSettings
    from examples.ex_03_flext_logger import Ex03FlextLogger as Ex03FlextLogger
    from examples.ex_04_flext_dispatcher import (
        Ex04FlextDispatcher as Ex04FlextDispatcher,
    )
    from examples.ex_05_flext_mixins import Ex05FlextMixins as Ex05FlextMixins
    from examples.ex_06_flext_context import Ex06FlextContext as Ex06FlextContext
    from examples.ex_07_flext_exceptions import (
        Ex07FlextExceptions as Ex07FlextExceptions,
    )
    from examples.ex_08_flext_container import Ex08FlextContainer as Ex08FlextContainer
    from examples.ex_09_flext_decorators import (
        Ex09FlextDecorators as Ex09FlextDecorators,
    )
    from examples.ex_10_flext_handlers import Ex10FlextHandlers as Ex10FlextHandlers
    from examples.ex_11_flext_service import Ex11FlextService as Ex11FlextService
    from examples.ex_12_flext_registry import Ex12FlextRegistry as Ex12FlextRegistry
    from examples.logging_config_once_pattern import (
        DatabaseService as DatabaseService,
        MigrationService as MigrationService,
        main as main,
    )
    from examples.models import (
        FlextCoreExampleModels as FlextCoreExampleModels,
        FlextCoreExampleModels as m,
        UserInput as UserInput,
        UserProfile as UserProfile,
        em as em,
    )
    from examples.shared import Examples as Examples

_LAZY_IMPORTS: Mapping[str, Sequence[str]] = {
    "DatabaseService": ["examples.logging_config_once_pattern", "DatabaseService"],
    "Ex00UserInput": ["examples._models.ex00", "Ex00UserInput"],
    "Ex00UserProfile": ["examples._models.ex00", "Ex00UserProfile"],
    "Ex01DemonstrationResult": ["examples._models.ex01", "Ex01DemonstrationResult"],
    "Ex01InvalidPersonPayload": ["examples._models.ex01", "Ex01InvalidPersonPayload"],
    "Ex01RunDemonstrationCommand": [
        "examples._models.ex01",
        "Ex01RunDemonstrationCommand",
    ],
    "Ex01User": ["examples._models.ex01", "Ex01User"],
    "Ex01ValidPersonPayload": ["examples._models.ex01", "Ex01ValidPersonPayload"],
    "Ex01r": ["examples.ex_01_flext_result", "Ex01r"],
    "Ex02CacheService": ["examples._models.ex02", "Ex02CacheService"],
    "Ex02DatabaseService": ["examples._models.ex02", "Ex02DatabaseService"],
    "Ex02EmailService": ["examples._models.ex02", "Ex02EmailService"],
    "Ex02FlextSettings": ["examples.ex_02_flext_settings", "Ex02FlextSettings"],
    "Ex02TestConfig": ["examples._models.ex02", "Ex02TestConfig"],
    "Ex03Email": ["examples._models.ex03", "Ex03Email"],
    "Ex03FlextLogger": ["examples.ex_03_flext_logger", "Ex03FlextLogger"],
    "Ex03Money": ["examples._models.ex03", "Ex03Money"],
    "Ex03Order": ["examples._models.ex03", "Ex03Order"],
    "Ex03OrderItem": ["examples._models.ex03", "Ex03OrderItem"],
    "Ex03User": ["examples._models.ex03", "Ex03User"],
    "Ex04AutoCommand": ["examples._models.ex04", "Ex04AutoCommand"],
    "Ex04CreateUser": ["examples._models.ex04", "Ex04CreateUser"],
    "Ex04DeleteUser": ["examples._models.ex04", "Ex04DeleteUser"],
    "Ex04FailingDelete": ["examples._models.ex04", "Ex04FailingDelete"],
    "Ex04FlextDispatcher": ["examples.ex_04_flext_dispatcher", "Ex04FlextDispatcher"],
    "Ex04GetUser": ["examples._models.ex04", "Ex04GetUser"],
    "Ex04NoSubscriberEvent": ["examples._models.ex04", "Ex04NoSubscriberEvent"],
    "Ex04Ping": ["examples._models.ex04", "Ex04Ping"],
    "Ex04UnknownQuery": ["examples._models.ex04", "Ex04UnknownQuery"],
    "Ex04UserCreated": ["examples._models.ex04", "Ex04UserCreated"],
    "Ex05BadProcessor": ["examples._models.ex05", "Ex05BadProcessor"],
    "Ex05FlextMixins": ["examples.ex_05_flext_mixins", "Ex05FlextMixins"],
    "Ex05GoodProcessor": ["examples._models.ex05", "Ex05GoodProcessor"],
    "Ex05HandlerBad": ["examples._models.ex05", "Ex05HandlerBad"],
    "Ex05HandlerLike": ["examples._models.ex05", "Ex05HandlerLike"],
    "Ex05StatusEnum": ["examples._models.ex05", "Ex05StatusEnum"],
    "Ex05UserModel": ["examples._models.ex05", "Ex05UserModel"],
    "Ex06FlextContext": ["examples.ex_06_flext_context", "Ex06FlextContext"],
    "Ex07CreateUserCommand": ["examples._models.ex07", "Ex07CreateUserCommand"],
    "Ex07DemoPlugin": ["examples._models.ex07", "Ex07DemoPlugin"],
    "Ex07FlextExceptions": ["examples.ex_07_flext_exceptions", "Ex07FlextExceptions"],
    "Ex07GetUserQuery": ["examples._models.ex07", "Ex07GetUserQuery"],
    "Ex07UserCreatedEvent": ["examples._models.ex07", "Ex07UserCreatedEvent"],
    "Ex08FlextContainer": ["examples.ex_08_flext_container", "Ex08FlextContainer"],
    "Ex08Order": ["examples._models.ex08", "Ex08Order"],
    "Ex08User": ["examples._models.ex08", "Ex08User"],
    "Ex09FlextDecorators": ["examples.ex_09_flext_decorators", "Ex09FlextDecorators"],
    "Ex10CommandBusStub": ["examples._models.ex10", "Ex10CommandBusStub"],
    "Ex10ContextPayload": ["examples._models.ex10", "Ex10ContextPayload"],
    "Ex10DerivedMessage": ["examples._models.ex10", "Ex10DerivedMessage"],
    "Ex10Entity": ["examples._models.ex10", "Ex10Entity"],
    "Ex10FlextHandlers": ["examples.ex_10_flext_handlers", "Ex10FlextHandlers"],
    "Ex10Message": ["examples._models.ex10", "Ex10Message"],
    "Ex10ProcessorBad": ["examples._models.ex10", "Ex10ProcessorBad"],
    "Ex10ProcessorGood": ["examples._models.ex10", "Ex10ProcessorGood"],
    "Ex10ProtocolHandler": ["examples._models.ex10", "Ex10ProtocolHandler"],
    "Ex10ServiceStub": ["examples._models.ex10", "Ex10ServiceStub"],
    "Ex11CommandBusStub": ["examples._models.ex11", "Ex11CommandBusStub"],
    "Ex11EntityStub": ["examples._models.ex11", "Ex11EntityStub"],
    "Ex11FlextService": ["examples.ex_11_flext_service", "Ex11FlextService"],
    "Ex11HandlerLike": ["examples._models.ex11", "Ex11HandlerLike"],
    "Ex11HandlerLikeService": ["examples._models.ex11", "Ex11HandlerLikeService"],
    "Ex11Payload": ["examples._models.ex11", "Ex11Payload"],
    "Ex11ProcessorProtocolBad": ["examples._models.ex11", "Ex11ProcessorProtocolBad"],
    "Ex11ProcessorProtocolGood": ["examples._models.ex11", "Ex11ProcessorProtocolGood"],
    "Ex12CommandA": ["examples._models.ex12", "Ex12CommandA"],
    "Ex12CommandB": ["examples._models.ex12", "Ex12CommandB"],
    "Ex12FlextRegistry": ["examples.ex_12_flext_registry", "Ex12FlextRegistry"],
    "Ex14CreateUserCommand": ["examples._models.ex14", "Ex14CreateUserCommand"],
    "Ex14GetUserQuery": ["examples._models.ex14", "Ex14GetUserQuery"],
    "Ex14UserDTO": ["examples._models.ex14", "Ex14UserDTO"],
    "ExConfigAppConfig": ["examples._models.exconfig", "ExConfigAppConfig"],
    "Examples": ["examples.shared", "Examples"],
    "FlextCoreExampleModels": ["examples.models", "FlextCoreExampleModels"],
    "MigrationService": ["examples.logging_config_once_pattern", "MigrationService"],
    "SharedHandle": ["examples._models.shared", "SharedHandle"],
    "SharedPerson": ["examples._models.shared", "SharedPerson"],
    "UserInput": ["examples.models", "UserInput"],
    "UserProfile": ["examples.models", "UserProfile"],
    "_models": ["examples._models", ""],
    "em": ["examples.models", "em"],
    "ex00": ["examples._models.ex00", ""],
    "ex01": ["examples._models.ex01", ""],
    "ex02": ["examples._models.ex02", ""],
    "ex03": ["examples._models.ex03", ""],
    "ex04": ["examples._models.ex04", ""],
    "ex05": ["examples._models.ex05", ""],
    "ex07": ["examples._models.ex07", ""],
    "ex08": ["examples._models.ex08", ""],
    "ex10": ["examples._models.ex10", ""],
    "ex11": ["examples._models.ex11", ""],
    "ex12": ["examples._models.ex12", ""],
    "ex14": ["examples._models.ex14", ""],
    "ex_01_flext_result": ["examples.ex_01_flext_result", ""],
    "ex_02_flext_settings": ["examples.ex_02_flext_settings", ""],
    "ex_03_flext_logger": ["examples.ex_03_flext_logger", ""],
    "ex_04_flext_dispatcher": ["examples.ex_04_flext_dispatcher", ""],
    "ex_05_flext_mixins": ["examples.ex_05_flext_mixins", ""],
    "ex_06_flext_context": ["examples.ex_06_flext_context", ""],
    "ex_07_flext_exceptions": ["examples.ex_07_flext_exceptions", ""],
    "ex_08_flext_container": ["examples.ex_08_flext_container", ""],
    "ex_09_flext_decorators": ["examples.ex_09_flext_decorators", ""],
    "ex_10_flext_handlers": ["examples.ex_10_flext_handlers", ""],
    "ex_11_flext_service": ["examples.ex_11_flext_service", ""],
    "ex_12_flext_registry": ["examples.ex_12_flext_registry", ""],
    "exconfig": ["examples._models.exconfig", ""],
    "logging_config_once_pattern": ["examples.logging_config_once_pattern", ""],
    "m": ["examples.models", "FlextCoreExampleModels"],
    "main": ["examples.logging_config_once_pattern", "main"],
    "models": ["examples.models", ""],
    "shared": ["examples.shared", ""],
}

_EXPORTS: Sequence[str] = [
    "DatabaseService",
    "Ex00UserInput",
    "Ex00UserProfile",
    "Ex01DemonstrationResult",
    "Ex01InvalidPersonPayload",
    "Ex01RunDemonstrationCommand",
    "Ex01User",
    "Ex01ValidPersonPayload",
    "Ex01r",
    "Ex02CacheService",
    "Ex02DatabaseService",
    "Ex02EmailService",
    "Ex02FlextSettings",
    "Ex02TestConfig",
    "Ex03Email",
    "Ex03FlextLogger",
    "Ex03Money",
    "Ex03Order",
    "Ex03OrderItem",
    "Ex03User",
    "Ex04AutoCommand",
    "Ex04CreateUser",
    "Ex04DeleteUser",
    "Ex04FailingDelete",
    "Ex04FlextDispatcher",
    "Ex04GetUser",
    "Ex04NoSubscriberEvent",
    "Ex04Ping",
    "Ex04UnknownQuery",
    "Ex04UserCreated",
    "Ex05BadProcessor",
    "Ex05FlextMixins",
    "Ex05GoodProcessor",
    "Ex05HandlerBad",
    "Ex05HandlerLike",
    "Ex05StatusEnum",
    "Ex05UserModel",
    "Ex06FlextContext",
    "Ex07CreateUserCommand",
    "Ex07DemoPlugin",
    "Ex07FlextExceptions",
    "Ex07GetUserQuery",
    "Ex07UserCreatedEvent",
    "Ex08FlextContainer",
    "Ex08Order",
    "Ex08User",
    "Ex09FlextDecorators",
    "Ex10CommandBusStub",
    "Ex10ContextPayload",
    "Ex10DerivedMessage",
    "Ex10Entity",
    "Ex10FlextHandlers",
    "Ex10Message",
    "Ex10ProcessorBad",
    "Ex10ProcessorGood",
    "Ex10ProtocolHandler",
    "Ex10ServiceStub",
    "Ex11CommandBusStub",
    "Ex11EntityStub",
    "Ex11FlextService",
    "Ex11HandlerLike",
    "Ex11HandlerLikeService",
    "Ex11Payload",
    "Ex11ProcessorProtocolBad",
    "Ex11ProcessorProtocolGood",
    "Ex12CommandA",
    "Ex12CommandB",
    "Ex12FlextRegistry",
    "Ex14CreateUserCommand",
    "Ex14GetUserQuery",
    "Ex14UserDTO",
    "ExConfigAppConfig",
    "Examples",
    "FlextCoreExampleModels",
    "MigrationService",
    "SharedHandle",
    "SharedPerson",
    "UserInput",
    "UserProfile",
    "_models",
    "em",
    "ex00",
    "ex01",
    "ex02",
    "ex03",
    "ex04",
    "ex05",
    "ex07",
    "ex08",
    "ex10",
    "ex11",
    "ex12",
    "ex14",
    "ex_01_flext_result",
    "ex_02_flext_settings",
    "ex_03_flext_logger",
    "ex_04_flext_dispatcher",
    "ex_05_flext_mixins",
    "ex_06_flext_context",
    "ex_07_flext_exceptions",
    "ex_08_flext_container",
    "ex_09_flext_decorators",
    "ex_10_flext_handlers",
    "ex_11_flext_service",
    "ex_12_flext_registry",
    "exconfig",
    "logging_config_once_pattern",
    "m",
    "main",
    "models",
    "shared",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, _EXPORTS)
