from _typeshed import Incomplete

from flext_core import FlextResult, TEntityId as TEntityId

pytestmark: Incomplete

class MockUser:
    id: Incomplete
    name: Incomplete
    def __init__(self, user_id: TEntityId, name: str) -> None: ...

class MockDatabase:
    users: Incomplete
    def __init__(self) -> None: ...
    def get_user(self, user_id: TEntityId) -> MockUser | None: ...
    def save_user(self, user: MockUser) -> MockUser: ...

class UserService:
    database: Incomplete
    def __init__(self, database: MockDatabase) -> None: ...
    def fetch_user(self, user_id: TEntityId) -> FlextResult[MockUser]: ...
    def create_user(self, user_id: TEntityId, name: str) -> FlextResult[MockUser]: ...

class TestRealUsagePatterns:
    def test_flext_result_success_flow(self) -> None: ...
    def test_flext_result_failure_flow(self) -> None: ...
    def test_chained_operations(self) -> None: ...
    def test_error_handling_patterns(self) -> None: ...
    def test_dependency_injection_basic_usage(self) -> None: ...
    def test_global_container_usage(self) -> None: ...
    def test_entity_id_type_safety(self) -> None: ...
    def test_validation_patterns(self) -> None: ...
    def test_service_factory_pattern(self) -> None: ...
