from abc import ABC, abstractmethod
from collections.abc import Callable as Callable

from _typeshed import Incomplete

from flext_core import (
    FlextContainer,
    FlextResult,
    TAnyObject as TAnyObject,
    TConfigDict as TConfigDict,
    TEntityId as TEntityId,
    TErrorMessage as TErrorMessage,
    TUserData as TUserData,
)

from .shared_domain import (
    SharedDomainFactory as SharedDomainFactory,
    User as SharedUser,
    log_domain_operation as log_domain_operation,
)

CONNECTION_FAILURE_RATE: float

class ServiceRegistrationResult:
    success: Incomplete
    message: Incomplete
    service_name: Incomplete
    def __init__(self, *, success: bool, message: str, service_name: str) -> None: ...

class ServiceRegistrationStrategy:
    def __init__(self, container: FlextContainer) -> None: ...
    def register_service_with_validation(
        self, service_name: str, service_result: FlextResult[object]
    ) -> FlextResult[ServiceRegistrationResult]: ...

class ServiceConfiguration:
    name: Incomplete
    factory_method: Incomplete
    def __init__(
        self, name: str, factory_method: Callable[[], FlextResult[object]]
    ) -> None: ...

class ContainerSetupOrchestrator:
    def __init__(self, container: FlextContainer, configurer: object) -> None: ...
    def setup_core_services(self) -> FlextResult[None]: ...
    def setup_factories(self) -> FlextResult[None]: ...

class UserManagementServiceFactoryCreator:
    def __init__(self, configurer: object) -> None: ...
    def create_factory(self) -> Callable[[], object]: ...

class DemonstrationSection:
    number: Incomplete
    title: Incomplete
    header_text: Incomplete
    def __init__(self, number: int, title: str) -> None: ...

class PrerequisiteValidation:
    is_valid: Incomplete
    error_message: Incomplete
    def __init__(self, *, is_valid: bool, error_message: str = "") -> None: ...

class DemonstrationFormatter:
    @staticmethod
    def format_section_header(section: DemonstrationSection) -> str: ...
    @staticmethod
    def print_section_header(section: DemonstrationSection) -> None: ...

class PrerequisiteValidator:
    @staticmethod
    def validate_condition(
        *, condition: bool, error_message: str
    ) -> FlextResult[PrerequisiteValidation]: ...

class DatabaseConnection(ABC):
    @abstractmethod
    def connect(self) -> FlextResult[bool]: ...
    @abstractmethod
    def execute_query(self, query: str) -> FlextResult[list[TAnyObject]]: ...
    @abstractmethod
    def close(self) -> FlextResult[None]: ...

class EmailService(ABC):
    @abstractmethod
    def send_email(self, to: str, subject: str, body: str) -> FlextResult[str]: ...

class UserRepository(ABC):
    @abstractmethod
    def create_user(self, user_data: TUserData) -> FlextResult[TEntityId]: ...
    @abstractmethod
    def get_user(self, user_id: TEntityId) -> FlextResult[SharedUser]: ...

class NotificationService(ABC):
    @abstractmethod
    def notify_user_created(self, user: SharedUser) -> FlextResult[None]: ...

class PostgreSQLConnection(DatabaseConnection):
    host: Incomplete
    port: Incomplete
    database: Incomplete
    connected: bool
    connection_id: TEntityId
    def __init__(self, host: str, port: int, database: str) -> None: ...
    def connect(self) -> FlextResult[bool]: ...
    def execute_query(self, query: str) -> FlextResult[list[TAnyObject]]: ...
    def close(self) -> FlextResult[None]: ...

class SMTPEmailService(EmailService):
    smtp_host: Incomplete
    smtp_port: Incomplete
    service_id: TEntityId
    def __init__(self, smtp_host: str, smtp_port: int) -> None: ...
    def send_email(self, to: str, subject: str, body: str) -> FlextResult[str]: ...

class SharedDomainUserRepository(UserRepository):
    db_connection: Incomplete
    repository_id: TEntityId
    def __init__(self, db_connection: DatabaseConnection) -> None: ...
    def create_user(self, user_data: TUserData) -> FlextResult[TEntityId]: ...
    def get_user(self, user_id: TEntityId) -> FlextResult[SharedUser]: ...

class EmailNotificationService(NotificationService):
    email_service: Incomplete
    user_repository: Incomplete
    service_id: TEntityId
    def __init__(
        self, email_service: EmailService, user_repository: UserRepository
    ) -> None: ...
    def notify_user_created(self, user: SharedUser) -> FlextResult[None]: ...

class DatabaseConnectionFactory:
    @staticmethod
    def create_postgresql_connection(
        config: TConfigDict,
    ) -> FlextResult[DatabaseConnection]: ...

class EmailServiceFactory:
    @staticmethod
    def create_smtp_service(config: TConfigDict) -> FlextResult[EmailService]: ...

class UserManagementService:
    user_repository: Incomplete
    notification_service: Incomplete
    service_id: TEntityId
    def __init__(
        self, user_repository: UserRepository, notification_service: NotificationService
    ) -> None: ...
    def register_user(self, user_data: TUserData) -> FlextResult[TAnyObject]: ...

class ServiceConfigurationData:
    data: Incomplete
    def __init__(self, **config_data: object) -> None: ...
    def get(self, key: str, default: object = None) -> object: ...

class DependencyResolver:
    def __init__(self, container: FlextContainer) -> None: ...
    def resolve_single_dependency(
        self, service_name: str
    ) -> FlextResult[TAnyObject]: ...
    def resolve_multiple_dependencies(
        self, *service_names: str
    ) -> FlextResult[tuple[TAnyObject, ...]]: ...

class BaseServiceConfigurer:
    def __init__(self, container: FlextContainer) -> None: ...
    def create_database_connection(self) -> FlextResult[DatabaseConnection]: ...
    def create_email_service(self) -> FlextResult[EmailService]: ...
    def create_user_repository(self) -> FlextResult[UserRepository]: ...
    def create_notification_service(self) -> FlextResult[NotificationService]: ...
    def create_user_management_service(self) -> FlextResult[UserManagementService]: ...

class ProductionServiceConfigurer(BaseServiceConfigurer): ...

def setup_production_container() -> FlextResult[FlextContainer]: ...

class MockDatabase(DatabaseConnection):
    def connect(self) -> FlextResult[bool]: ...
    def execute_query(self, _query: str) -> FlextResult[list[TAnyObject]]: ...
    def close(self) -> FlextResult[None]: ...

class MockEmailService(EmailService):
    def send_email(self, _to: str, _subject: str, _body: str) -> FlextResult[str]: ...

class MockUserRepository(UserRepository):
    def create_user(self, _user_data: TUserData) -> FlextResult[TEntityId]: ...
    def get_user(self, user_id: TEntityId) -> FlextResult[SharedUser]: ...

class MockNotificationService(NotificationService):
    def notify_user_created(self, user: SharedUser) -> FlextResult[None]: ...

class TestServiceConfigurer:
    def __init__(self, container: FlextContainer) -> None: ...
    def register_mock_services(self) -> FlextResult[None]: ...
    def register_user_management_factory(self) -> FlextResult[None]: ...

class MockUserManagementServiceFactoryCreator:
    def __init__(self, container: FlextContainer) -> None: ...
    def create_factory(self) -> Callable[[], object]: ...

def setup_test_container() -> FlextResult[FlextContainer]: ...
def check_container_health(container: FlextContainer) -> FlextResult[TAnyObject]: ...

class DemonstrationCommand:
    def execute(self) -> FlextResult[None]: ...

class TestContainerSetupCommand(DemonstrationCommand):
    def __init__(self, demonstrator: ContainerDemonstrator) -> None: ...
    def execute(self) -> FlextResult[None]: ...

class ContainerDemonstrator:
    test_container: FlextContainer | None
    prod_container: FlextContainer | None
    def __init__(self) -> None: ...
    def run_test_container_demo(self) -> FlextResult[None]: ...
    def run_user_registration_test(self) -> FlextResult[None]: ...
    def run_health_check_demo(self) -> FlextResult[None]: ...
    def run_production_container_demo(self) -> FlextResult[None]: ...

class UserRegistrationStrategy:
    def __init__(self, container: FlextContainer, context_name: str) -> None: ...
    def register_user(self, user_data: TUserData) -> FlextResult[None]: ...

class UserRegistrationTestCommand(DemonstrationCommand):
    def __init__(
        self,
        demonstrator: ContainerDemonstrator,
        container: FlextContainer | None,
        context_name: str,
        section: DemonstrationSection,
    ) -> None: ...
    def execute(self) -> FlextResult[None]: ...

class HealthCheckDemoCommand(DemonstrationCommand):
    def __init__(
        self,
        demonstrator: ContainerDemonstrator,
        container: FlextContainer | None,
        section: DemonstrationSection,
    ) -> None: ...
    def execute(self) -> FlextResult[None]: ...

class ProductionContainerDemoCommand(DemonstrationCommand):
    def __init__(
        self, demonstrator: ContainerDemonstrator, section: DemonstrationSection
    ) -> None: ...
    def execute(self) -> FlextResult[None]: ...

def main() -> None: ...

class DemonstrationOrchestrator:
    def __init__(self) -> None: ...
    def run_complete_demonstration(self) -> None: ...
