from collections.abc import Callable as Callable

from _typeshed import Incomplete

from flext_core import (
    FlextComparableMixin,
    FlextLoggableMixin,
    FlextResult,
    TAnyObject as TAnyObject,
    TErrorMessage as TErrorMessage,
    TUserData as TUserData,
)

from .shared_domain import (
    Money as Money,
    Product as SharedProduct,
    SharedDemonstrationPattern as SharedDemonstrationPattern,
    SharedDomainFactory as SharedDomainFactory,
    User as SharedUser,
)

MIN_CUSTOMER_NAME_LENGTH: int
MAX_CUSTOMER_NAME_LENGTH: int
MIN_PRODUCT_NAME_LENGTH: int
MAX_PRODUCT_PRICE: int
MAX_AGE: int
MIN_GUARDIAN_AGE: int

class ValidationResult:
    errors: list[TErrorMessage]
    warnings: list[str]
    def __init__(self) -> None: ...
    def add_error(self, error: TErrorMessage) -> None: ...
    def add_warning(self, warning: str) -> None: ...
    def has_errors(self) -> bool: ...
    def get_combined_error(self) -> TErrorMessage: ...
    def to_flext_result(self) -> FlextResult[None]: ...

class ProductFieldValidator:
    validation_result: Incomplete
    def __init__(self, validation_result: ValidationResult) -> None: ...
    def validate_product_id(self, product_id: object) -> None: ...
    def validate_name(self, name: object) -> None: ...
    def validate_price(self, price: object) -> None: ...
    def validate_category(self, category: object) -> None: ...
    def validate_stock(self, stock: object) -> None: ...
    def validate_tags(self, tags: object) -> None: ...

class ProductValidationOrchestrator:
    product_data: Incomplete
    validation_result: Incomplete
    field_validator: Incomplete
    def __init__(self, product_data: TAnyObject) -> None: ...
    def validate_all_fields(self) -> FlextResult[None]: ...

class ValidationDemoUser(SharedUser, FlextLoggableMixin):
    def get_validation_rules(self) -> dict[str, list[str]]: ...
    def validate_business_rules(self) -> FlextResult[None]: ...

class ValidationDemoProduct(SharedProduct, FlextComparableMixin):
    def get_comparison_key(self) -> object: ...
    def get_validation_rules(self) -> dict[str, list[str]]: ...
    def validate_inventory_rules(self) -> FlextResult[None]: ...

def validate_user_business_rules(user: SharedUser) -> FlextResult[None]: ...
def demonstrate_basic_validations() -> None: ...
def demonstrate_format_validations() -> None: ...
def demonstrate_functional_predicates() -> None: ...
def demonstrate_predicate_composition() -> None: ...
def validate_customer_complete(customer_data: TUserData) -> FlextResult[SharedUser]: ...
def validate_product_complete(
    product_data: TAnyObject,
) -> FlextResult[SharedProduct]: ...
def demonstrate_customer_validation() -> None: ...
def demonstrate_product_validation() -> None: ...
def demonstrate_validation_performance() -> None: ...
def main() -> None: ...
