from collections.abc import Callable as Callable
from typing import Protocol

from _typeshed import Incomplete

from flext_core import FlextEntity, FlextResult

from .shared_domain import (
    Address as Address,
    Age as Age,
    Money as Money,
    Order as Order,
    OrderItem as OrderItem,
    User as SharedUser,
    User as User,
    UserStatus as UserStatus,
)
from .shared_example_helpers import (
    run_example_demonstration as run_example_demonstration,
)

class CustomerFactory(Protocol):
    def __call__(self, **kwargs: object) -> FlextResult[Customer]: ...

class ProductFactory(Protocol):
    def __call__(self, **kwargs: object) -> FlextResult[Product]: ...

class OrderFactory(Protocol):
    def __call__(self, **kwargs: object) -> FlextResult[Order]: ...

CURRENCY_CODE_LENGTH: int
MIN_STREET_ADDRESS_LENGTH: int
MIN_CITY_NAME_LENGTH: int
MIN_POSTAL_CODE_LENGTH: int
MIN_COUNTRY_NAME_LENGTH: int
EMAIL_PARTS_COUNT: int
MIN_NAME_LENGTH: int
MAX_CUSTOMER_NAME_LENGTH: int
MAX_COMPANY_NAME_LENGTH: int
MIN_REASON_LENGTH: int
MIN_STATUS_CHANGE_REASON_LENGTH: int
MIN_CANCELLATION_REASON_LENGTH: int
MIN_TRACKING_NUMBER_LENGTH: int
MAX_CREDIT_LIMIT: int
CURRENCY_PRECISION_TOLERANCE: float

class Customer(SharedUser):
    registration_date: str
    credit_limit: Money
    total_orders: int
    def validate_business_rules(self) -> FlextResult[None]: ...
    def validate_domain_rules(self) -> FlextResult[None]: ...
    @property
    def is_active(self) -> bool: ...
    def activate(self) -> FlextResult[User]: ...
    def deactivate(self, reason: str) -> FlextResult[Customer]: ...
    def update_address(self, new_address: Address) -> FlextResult[Customer]: ...
    def increase_credit_limit(self, amount: Money) -> FlextResult[Customer]: ...
    def increment_order_count(self) -> FlextResult[Customer]: ...

class Product(FlextEntity):
    name: str
    price: Money
    category: str
    stock_quantity: int
    is_available: bool
    minimum_stock: int
    def validate_business_rules(self) -> FlextResult[None]: ...
    def validate_domain_rules(self) -> FlextResult[None]: ...
    def is_low_stock(self) -> bool: ...
    def is_out_of_stock(self) -> bool: ...
    def update_price(self, new_price: Money) -> FlextResult[Product]: ...
    def adjust_stock(
        self, quantity_change: int, reason: str
    ) -> FlextResult[Product]: ...
    def make_unavailable(self, reason: str) -> FlextResult[Product]: ...

class CustomerRepository:
    customers: dict[str, Customer]
    def __init__(self) -> None: ...
    def save(self, customer: Customer) -> FlextResult[str]: ...
    def find_by_id(self, customer_id: str) -> FlextResult[Customer]: ...
    def find_by_email(self, email: str) -> FlextResult[Customer]: ...
    def find_active_customers(self) -> list[Customer]: ...
    def get_all(self) -> list[Customer]: ...

class ProductRepository:
    products: dict[str, Product]
    def __init__(self) -> None: ...
    def save(self, product: Product) -> FlextResult[str]: ...
    def find_by_id(self, product_id: str) -> FlextResult[Product]: ...
    def find_available_products(self) -> list[Product]: ...
    def find_low_stock_products(self) -> list[Product]: ...
    def get_all(self) -> list[Product]: ...

class OrderRepository:
    orders: dict[str, Order]
    def __init__(self) -> None: ...
    def save(self, order: Order) -> FlextResult[str]: ...
    def find_by_id(self, order_id: str) -> FlextResult[Order]: ...
    def find_by_customer(self, customer_id: str) -> list[Order]: ...
    def find_by_status(self, status: str) -> list[Order]: ...
    def get_all(self) -> list[Order]: ...

class OrderDomainService:
    customer_repo: Incomplete
    product_repo: Incomplete
    order_repo: Incomplete
    def __init__(
        self,
        customer_repo: CustomerRepository,
        product_repo: ProductRepository,
        order_repo: OrderRepository,
    ) -> None: ...
    def create_order(
        self,
        customer_id: str,
        product_orders: list[tuple[str, int]],
        shipping_address: Address,
    ) -> FlextResult[Order]: ...
    def fulfill_order(
        self, order_id: str, tracking_number: str
    ) -> FlextResult[Order]: ...

def create_customer_factory() -> CustomerFactory: ...
def create_product_factory() -> ProductFactory: ...
def create_order_factory() -> OrderFactory: ...
def demonstrate_value_objects() -> None: ...
def demonstrate_entity_lifecycle() -> None: ...
def demonstrate_aggregate_patterns() -> None: ...
def demonstrate_repository_patterns() -> None: ...
def demonstrate_version_management() -> None: ...
def demonstrate_performance_characteristics() -> None: ...
def main() -> None: ...
