from flext_core import (
    TAnyDict as TAnyDict,
    TConfigDict as TConfigDict,
    TErrorMessage as TErrorMessage,
)

from .shared_domain import (
    SharedDemonstrationPattern as SharedDemonstrationPattern,
    SharedDomainFactory as SharedDomainFactory,
    log_domain_operation as log_domain_operation,
)

def demonstrate_basic_configuration() -> None: ...
def demonstrate_environment_integration() -> None: ...
def demonstrate_configuration_merging() -> None: ...
def demonstrate_file_configuration() -> None: ...
def demonstrate_configuration_hierarchies() -> None: ...
def demonstrate_advanced_configuration_patterns() -> None: ...
def demonstrate_domain_configuration_integration() -> None: ...
def main() -> None: ...
