from collections.abc import Callable as Callable

from flext_core import TAnyObject as TAnyObject, TUserData as TUserData

from .shared_domain import (
    SharedDomainFactory as SharedDomainFactory,
    log_domain_operation as log_domain_operation,
)

MAX_RETRY_ATTEMPTS: int
MAX_REASONABLE_AGE: int

def demonstrate_validation_decorators() -> None: ...
def demonstrate_error_handling_decorators() -> None: ...
def demonstrate_performance_decorators() -> None: ...
def demonstrate_logging_decorators() -> None: ...
def demonstrate_immutability_decorators() -> None: ...
def demonstrate_functional_decorators() -> None: ...
def demonstrate_decorator_best_practices() -> None: ...
def demonstrate_domain_model_decorators() -> None: ...
def main() -> None: ...
