from flext_core import TUserData as TUserData

LOW_STOCK_THRESHOLD: int

def demonstrate_generic_payloads() -> None: ...
def demonstrate_message_payloads() -> None: ...
def demonstrate_domain_events() -> None: ...
def demonstrate_payload_serialization() -> None: ...
def demonstrate_enterprise_messaging_patterns() -> None: ...
def main() -> None: ...
