from dataclasses import dataclass

from _typeshed import Incomplete

from flext_core import (
    FlextBaseHandler,
    FlextEntity,
    FlextEventHandler,
    FlextLogger,
    FlextResult,
)

MIN_NAME_LENGTH: int
MIN_ITEMS_FOR_DISCOUNT: int

@dataclass
class User:
    id: str
    name: str
    email: str
    is_active: bool = ...

@dataclass
class Order:
    id: str
    user_id: str
    items: list[str]
    total: float
    status: str = ...

class UserEntity(FlextEntity):
    name: str
    email: str
    is_active: bool
    def validate_domain_rules(self) -> FlextResult[None]: ...
    def activate(self) -> FlextResult[UserEntity]: ...

@dataclass
class CreateUserCommand:
    name: str
    email: str
    def validate(self) -> FlextResult[None]: ...

@dataclass
class UpdateUserCommand:
    user_id: str
    name: str | None = ...
    email: str | None = ...
    def validate(self) -> FlextResult[None]: ...

@dataclass
class GetUserQuery:
    user_id: str
    include_inactive: bool = ...

@dataclass
class ListUsersQuery:
    active_only: bool = ...
    limit: int = ...
    offset: int = ...

@dataclass
class UserCreatedEvent:
    user_id: str
    name: str
    email: str
    timestamp: float

@dataclass
class UserUpdatedEvent:
    user_id: str
    changes: dict[str, object]
    timestamp: float

@dataclass
class OrderCreatedEvent:
    order_id: str
    user_id: str
    total: float
    timestamp: float

class CreateUserHandler(FlextBaseHandler):
    users: dict[str, User]
    def __init__(self) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def can_handle(self, message: object) -> bool: ...
    def validate_command(self, command: object) -> FlextResult[None]: ...
    def handle(self, command: object) -> FlextResult[object]: ...

class UpdateUserHandler(FlextBaseHandler):
    users: Incomplete
    def __init__(self, user_storage: dict[str, User]) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def can_handle(self, message: object) -> bool: ...
    def validate_command(self, command: object) -> FlextResult[None]: ...
    def handle(self, command: object) -> FlextResult[object]: ...

class GetUserHandler(FlextBaseHandler):
    users: Incomplete
    def __init__(self, user_storage: dict[str, User]) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def can_handle(self, message: object) -> bool: ...
    def validate_command(self, query: object) -> FlextResult[None]: ...
    def authorize_query(self, query: object) -> FlextResult[None]: ...
    def handle(self, query: object) -> FlextResult[object]: ...

class ListUsersHandler(FlextBaseHandler):
    users: Incomplete
    def __init__(self, user_storage: dict[str, User]) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def handle(self, query: object) -> FlextResult[object]: ...

class UserCreatedEventHandler(FlextEventHandler):
    def __init__(self) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def process_event(self, event: object) -> FlextResult[None]: ...

class UserUpdatedEventHandler(FlextEventHandler):
    def __init__(self) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def process_event(self, event: object) -> FlextResult[None]: ...

class OrderCreatedEventHandler(FlextEventHandler):
    def __init__(self) -> None: ...
    @property
    def logger(self) -> FlextLogger: ...
    def process_event(self, event: object) -> FlextResult[None]: ...

def demonstrate_command_handlers() -> None: ...
def demonstrate_query_handlers() -> None: ...
def demonstrate_event_handlers() -> None: ...
def demonstrate_handler_registry() -> None: ...
def demonstrate_handler_chain() -> None: ...
def demonstrate_function_handlers() -> None: ...
def main() -> None: ...
