from collections.abc import Callable as Callable, Mapping
from dataclasses import dataclass

from _typeshed import Incomplete
from structlog.stdlib import BoundLogger as BoundLogger

from flext_core import (
    FlextDomainEvent as FlextDomainEvent,
    FlextEventPublisher,
    FlextEventSubscriber,
    FlextHandlers,
    FlextLoggerProtocol,
    FlextMessageHandler as FlextMessageHandler,
    FlextMiddleware,
    FlextPlugin,
    FlextPluginContext,
    FlextRepository,
    FlextResult,
    FlextService,
    FlextUnitOfWork,
    FlextValidationRule,
    TAnyDict as TAnyDict,
)

MAX_TCP_PORT: int

@dataclass
class User:
    id: str
    name: str
    email: str
    age: int | None = ...
    is_active: bool = ...

@dataclass
class Product:
    id: str
    name: str
    price: float
    category: str
    stock: int = ...

@dataclass
class Order:
    id: str
    user_id: str
    products: list[str]
    total: float
    status: str = ...

@dataclass
class UserCreatedEvent:
    event_id: str
    event_type: str
    aggregate_id: str
    event_version: int
    timestamp: str
    user_id: str
    name: str
    email: str
    def to_dict(self) -> dict[str, object]: ...
    @classmethod
    def from_dict(cls, data: dict[str, object]) -> UserCreatedEvent: ...

@dataclass
class OrderPlacedEvent:
    event_id: str
    event_type: str
    aggregate_id: str
    event_version: int
    timestamp: str
    order_id: str
    user_id: str
    total: float
    def to_dict(self) -> dict[str, object]: ...
    @classmethod
    def from_dict(cls, data: dict[str, object]) -> OrderPlacedEvent: ...

class EmailValidator:
    def validate(self, value: object) -> FlextResult[object]: ...

class AgeRangeRule(FlextValidationRule):
    min_age: Incomplete
    max_age: Incomplete
    def __init__(self, min_age: int = 18, max_age: int = 120) -> None: ...
    def apply(self, value: object, field_name: str) -> FlextResult[object]: ...
    def get_error_message(self, field_name: str, _value: object) -> str: ...

class NonEmptyStringRule(FlextValidationRule):
    def apply(self, value: object, field_name: str) -> FlextResult[object]: ...
    def get_error_message(self, field_name: str, _value: object) -> str: ...

class PositiveNumberRule(FlextValidationRule):
    def apply(self, value: object, field_name: str) -> FlextResult[object]: ...
    def get_error_message(self, field_name: str, _value: object) -> str: ...

class UserService(FlextService):
    def __init__(self) -> None: ...
    def start(self) -> FlextResult[None]: ...
    def stop(self) -> FlextResult[None]: ...
    def health_check(self) -> FlextResult[TAnyDict]: ...
    def create_user(
        self, name: str, email: str, age: int | None = None
    ) -> FlextResult[User]: ...
    def get_user(self, user_id: str) -> FlextResult[User]: ...

class ConfigurableEmailService:
    def __init__(self) -> None: ...
    def configure(self, settings: Mapping[str, object]) -> FlextResult[None]: ...
    def send_email(self, _to: str, _subject: str, _body: str) -> FlextResult[None]: ...

class UserCommandHandler(FlextHandlers.CommandHandler):
    def __init__(self, user_service: UserService) -> None: ...
    def can_handle(self, message: object) -> bool: ...
    def handle(self, message: object) -> FlextResult[object]: ...

class LoggingMiddleware(FlextMiddleware):
    def process(
        self, message: object, next_handler: Callable[[object], FlextResult[object]]
    ) -> FlextResult[object]: ...

class ValidationMiddleware(FlextMiddleware):
    def __init__(self) -> None: ...
    def process(
        self, message: object, next_handler: Callable[[object], FlextResult[object]]
    ) -> FlextResult[object]: ...

class UserRepository(FlextRepository[User]):
    def __init__(self) -> None: ...
    def find_by_id(self, entity_id: str) -> FlextResult[User]: ...
    def save(self, entity: User) -> FlextResult[User]: ...
    def get_by_id(self, entity_id: str) -> FlextResult[User | None]: ...
    def find_all(self) -> FlextResult[list[User]]: ...
    def delete(self, entity_id: str) -> FlextResult[None]: ...

class DatabaseUnitOfWork(FlextUnitOfWork):
    def __init__(self, user_repo: UserRepository) -> None: ...
    def add_change(self, operation: str, data: object) -> None: ...
    def commit(self) -> FlextResult[None]: ...
    def rollback(self) -> FlextResult[None]: ...
    def begin(self) -> FlextResult[None]: ...
    def __enter__(self) -> FlextUnitOfWork: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...

class MockLogger:
    def info(self, message: str, *args: object, **kwargs: object) -> None: ...
    def error(self, message: str, *args: object, **kwargs: object) -> None: ...
    def debug(self, message: str, *args: object, **kwargs: object) -> None: ...
    def warning(self, message: str, *args: object, **kwargs: object) -> None: ...
    def critical(self, message: str, *args: object, **kwargs: object) -> None: ...
    def bind(self, **_kwargs: object) -> BoundLogger: ...
    def unbind(self, *_keys: str) -> BoundLogger: ...

class SimplePluginContext:
    def __init__(self, config: dict[str, object] | None = None) -> None: ...
    def get_logger(self) -> FlextLoggerProtocol: ...
    def get_config(self) -> dict[str, object]: ...
    def get_service(self, service_name: str) -> FlextResult[object]: ...
    def register_service(self, service_name: str, service: object) -> None: ...

class EmailNotificationPlugin(FlextPlugin):
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    def initialize(self, context: FlextPluginContext) -> FlextResult[None]: ...
    def get_info(self) -> dict[str, object]: ...
    def shutdown(self) -> FlextResult[None]: ...
    def send_welcome_email(self, user: User) -> FlextResult[None]: ...

class AuditLogPlugin(FlextPlugin):
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    def initialize(self, context: FlextPluginContext) -> FlextResult[None]: ...
    def get_info(self) -> dict[str, object]: ...
    def shutdown(self) -> FlextResult[None]: ...
    def log_event(
        self, event_type: str, details: dict[str, object]
    ) -> FlextResult[None]: ...

class SimpleEventPublisher(FlextEventPublisher):
    def __init__(self) -> None: ...
    def publish(self, event: FlextDomainEvent) -> FlextResult[None]: ...
    def publish_batch(self, events: list[FlextDomainEvent]) -> FlextResult[None]: ...
    def add_subscriber(
        self, event_type: type[object], handler: FlextMessageHandler
    ) -> None: ...

class SimpleEventSubscriber(FlextEventSubscriber):
    def __init__(self, publisher: SimpleEventPublisher) -> None: ...
    def subscribe(
        self, event_type: type[object], handler: FlextMessageHandler
    ) -> FlextResult[None]: ...
    def unsubscribe(
        self, event_type: type[object], handler: FlextMessageHandler
    ) -> FlextResult[None]: ...
    def handle_event(self, event: FlextDomainEvent) -> FlextResult[None]: ...
    def can_handle(self, event_type: str) -> bool: ...

class UserEventHandler(FlextHandlers.EventHandler):
    def __init__(self, audit_plugin: AuditLogPlugin) -> None: ...
    def can_handle(self, message: object) -> bool: ...
    def handle(self, message: object) -> FlextResult[object]: ...

def demonstrate_validation_interfaces() -> None: ...
def demonstrate_service_interfaces() -> None: ...
def demonstrate_handler_interfaces() -> None: ...
def demonstrate_repository_interfaces() -> None: ...
def demonstrate_plugin_interfaces() -> None: ...
def demonstrate_event_interfaces() -> None: ...
def main() -> None: ...
