from _typeshed import Incomplete

from flext_core import FlextResult

MIN_USER_AGE: int
MAX_USER_AGE: int
MAX_RETRY_ATTEMPTS: int

class User:
    user_id: Incomplete
    name: Incomplete
    email: Incomplete
    age: Incomplete
    is_active: bool
    def __init__(
        self, user_id: str, name: str, email: str, age: int | None = None
    ) -> None: ...

class DatabaseConnection:
    host: Incomplete
    port: Incomplete
    database: Incomplete
    connected: bool
    def __init__(self, host: str, port: int, database: str) -> None: ...
    def connect(self) -> FlextResult[None]: ...
    def authenticate(self, username: str, password: str) -> FlextResult[None]: ...

class UserValidationService:
    def validate_user_data(self, data: dict[str, object]) -> FlextResult[User]: ...

class UserManagementService:
    def __init__(self) -> None: ...
    def create_user(self, user_data: dict[str, object]) -> FlextResult[User]: ...
    def get_user(self, user_id: str) -> FlextResult[User]: ...
    def delete_user(self, user_id: str, requester_id: str) -> FlextResult[None]: ...

class ConfigurationService:
    def __init__(self) -> None: ...
    def load_configuration(
        self, config_data: dict[str, object]
    ) -> FlextResult[None]: ...

class ExternalAPIService:
    api_url: Incomplete
    timeout_seconds: Incomplete
    def __init__(self, api_url: str, timeout_seconds: int = 30) -> None: ...
    def fetch_user_profile(self, user_id: str) -> FlextResult[dict[str, object]]: ...

def demonstrate_base_exceptions() -> None: ...
def demonstrate_validation_exceptions() -> None: ...
def demonstrate_operational_exceptions() -> None: ...
def demonstrate_configuration_exceptions() -> None: ...
def demonstrate_connection_exceptions() -> None: ...
def demonstrate_exception_patterns() -> None: ...
def main() -> None: ...
