# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Shared model modules for examples."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

if TYPE_CHECKING:
    from examples._models import (
        ex00 as ex00,
        ex01 as ex01,
        ex02 as ex02,
        ex03 as ex03,
        ex04 as ex04,
        ex05 as ex05,
        ex07 as ex07,
        ex08 as ex08,
        ex10 as ex10,
        ex11 as ex11,
        ex12 as ex12,
        ex14 as ex14,
        exconfig as exconfig,
        shared as shared,
    )
    from examples._models.ex00 import (
        Ex00UserInput as Ex00UserInput,
        Ex00UserProfile as Ex00UserProfile,
    )
    from examples._models.ex01 import (
        Ex01DemonstrationResult as Ex01DemonstrationResult,
        Ex01InvalidPersonPayload as Ex01InvalidPersonPayload,
        Ex01RunDemonstrationCommand as Ex01RunDemonstrationCommand,
        Ex01User as Ex01User,
        Ex01ValidPersonPayload as Ex01ValidPersonPayload,
    )
    from examples._models.ex02 import (
        Ex02CacheService as Ex02CacheService,
        Ex02DatabaseService as Ex02DatabaseService,
        Ex02EmailService as Ex02EmailService,
        Ex02TestConfig as Ex02TestConfig,
    )
    from examples._models.ex03 import (
        Ex03Email as Ex03Email,
        Ex03Money as Ex03Money,
        Ex03Order as Ex03Order,
        Ex03OrderItem as Ex03OrderItem,
        Ex03User as Ex03User,
    )
    from examples._models.ex04 import (
        Ex04AutoCommand as Ex04AutoCommand,
        Ex04CreateUser as Ex04CreateUser,
        Ex04DeleteUser as Ex04DeleteUser,
        Ex04FailingDelete as Ex04FailingDelete,
        Ex04GetUser as Ex04GetUser,
        Ex04NoSubscriberEvent as Ex04NoSubscriberEvent,
        Ex04Ping as Ex04Ping,
        Ex04UnknownQuery as Ex04UnknownQuery,
        Ex04UserCreated as Ex04UserCreated,
    )
    from examples._models.ex05 import (
        Ex05BadProcessor as Ex05BadProcessor,
        Ex05GoodProcessor as Ex05GoodProcessor,
        Ex05HandlerBad as Ex05HandlerBad,
        Ex05HandlerLike as Ex05HandlerLike,
        Ex05StatusEnum as Ex05StatusEnum,
        Ex05UserModel as Ex05UserModel,
    )
    from examples._models.ex07 import (
        Ex07CreateUserCommand as Ex07CreateUserCommand,
        Ex07DemoPlugin as Ex07DemoPlugin,
        Ex07GetUserQuery as Ex07GetUserQuery,
        Ex07UserCreatedEvent as Ex07UserCreatedEvent,
    )
    from examples._models.ex08 import Ex08Order as Ex08Order, Ex08User as Ex08User
    from examples._models.ex10 import (
        Ex10CommandBusStub as Ex10CommandBusStub,
        Ex10ContextPayload as Ex10ContextPayload,
        Ex10DerivedMessage as Ex10DerivedMessage,
        Ex10Entity as Ex10Entity,
        Ex10Message as Ex10Message,
        Ex10ProcessorBad as Ex10ProcessorBad,
        Ex10ProcessorGood as Ex10ProcessorGood,
        Ex10ProtocolHandler as Ex10ProtocolHandler,
        Ex10ServiceStub as Ex10ServiceStub,
    )
    from examples._models.ex11 import (
        Ex11CommandBusStub as Ex11CommandBusStub,
        Ex11EntityStub as Ex11EntityStub,
        Ex11HandlerLike as Ex11HandlerLike,
        Ex11HandlerLikeService as Ex11HandlerLikeService,
        Ex11Payload as Ex11Payload,
        Ex11ProcessorProtocolBad as Ex11ProcessorProtocolBad,
        Ex11ProcessorProtocolGood as Ex11ProcessorProtocolGood,
    )
    from examples._models.ex12 import (
        Ex12CommandA as Ex12CommandA,
        Ex12CommandB as Ex12CommandB,
    )
    from examples._models.ex14 import (
        Ex14CreateUserCommand as Ex14CreateUserCommand,
        Ex14GetUserQuery as Ex14GetUserQuery,
        Ex14UserDTO as Ex14UserDTO,
    )
    from examples._models.exconfig import ExConfigAppConfig as ExConfigAppConfig
    from examples._models.shared import (
        SharedHandle as SharedHandle,
        SharedPerson as SharedPerson,
    )

_LAZY_IMPORTS: Mapping[str, Sequence[str]] = {
    "Ex00UserInput": ["examples._models.ex00", "Ex00UserInput"],
    "Ex00UserProfile": ["examples._models.ex00", "Ex00UserProfile"],
    "Ex01DemonstrationResult": ["examples._models.ex01", "Ex01DemonstrationResult"],
    "Ex01InvalidPersonPayload": ["examples._models.ex01", "Ex01InvalidPersonPayload"],
    "Ex01RunDemonstrationCommand": [
        "examples._models.ex01",
        "Ex01RunDemonstrationCommand",
    ],
    "Ex01User": ["examples._models.ex01", "Ex01User"],
    "Ex01ValidPersonPayload": ["examples._models.ex01", "Ex01ValidPersonPayload"],
    "Ex02CacheService": ["examples._models.ex02", "Ex02CacheService"],
    "Ex02DatabaseService": ["examples._models.ex02", "Ex02DatabaseService"],
    "Ex02EmailService": ["examples._models.ex02", "Ex02EmailService"],
    "Ex02TestConfig": ["examples._models.ex02", "Ex02TestConfig"],
    "Ex03Email": ["examples._models.ex03", "Ex03Email"],
    "Ex03Money": ["examples._models.ex03", "Ex03Money"],
    "Ex03Order": ["examples._models.ex03", "Ex03Order"],
    "Ex03OrderItem": ["examples._models.ex03", "Ex03OrderItem"],
    "Ex03User": ["examples._models.ex03", "Ex03User"],
    "Ex04AutoCommand": ["examples._models.ex04", "Ex04AutoCommand"],
    "Ex04CreateUser": ["examples._models.ex04", "Ex04CreateUser"],
    "Ex04DeleteUser": ["examples._models.ex04", "Ex04DeleteUser"],
    "Ex04FailingDelete": ["examples._models.ex04", "Ex04FailingDelete"],
    "Ex04GetUser": ["examples._models.ex04", "Ex04GetUser"],
    "Ex04NoSubscriberEvent": ["examples._models.ex04", "Ex04NoSubscriberEvent"],
    "Ex04Ping": ["examples._models.ex04", "Ex04Ping"],
    "Ex04UnknownQuery": ["examples._models.ex04", "Ex04UnknownQuery"],
    "Ex04UserCreated": ["examples._models.ex04", "Ex04UserCreated"],
    "Ex05BadProcessor": ["examples._models.ex05", "Ex05BadProcessor"],
    "Ex05GoodProcessor": ["examples._models.ex05", "Ex05GoodProcessor"],
    "Ex05HandlerBad": ["examples._models.ex05", "Ex05HandlerBad"],
    "Ex05HandlerLike": ["examples._models.ex05", "Ex05HandlerLike"],
    "Ex05StatusEnum": ["examples._models.ex05", "Ex05StatusEnum"],
    "Ex05UserModel": ["examples._models.ex05", "Ex05UserModel"],
    "Ex07CreateUserCommand": ["examples._models.ex07", "Ex07CreateUserCommand"],
    "Ex07DemoPlugin": ["examples._models.ex07", "Ex07DemoPlugin"],
    "Ex07GetUserQuery": ["examples._models.ex07", "Ex07GetUserQuery"],
    "Ex07UserCreatedEvent": ["examples._models.ex07", "Ex07UserCreatedEvent"],
    "Ex08Order": ["examples._models.ex08", "Ex08Order"],
    "Ex08User": ["examples._models.ex08", "Ex08User"],
    "Ex10CommandBusStub": ["examples._models.ex10", "Ex10CommandBusStub"],
    "Ex10ContextPayload": ["examples._models.ex10", "Ex10ContextPayload"],
    "Ex10DerivedMessage": ["examples._models.ex10", "Ex10DerivedMessage"],
    "Ex10Entity": ["examples._models.ex10", "Ex10Entity"],
    "Ex10Message": ["examples._models.ex10", "Ex10Message"],
    "Ex10ProcessorBad": ["examples._models.ex10", "Ex10ProcessorBad"],
    "Ex10ProcessorGood": ["examples._models.ex10", "Ex10ProcessorGood"],
    "Ex10ProtocolHandler": ["examples._models.ex10", "Ex10ProtocolHandler"],
    "Ex10ServiceStub": ["examples._models.ex10", "Ex10ServiceStub"],
    "Ex11CommandBusStub": ["examples._models.ex11", "Ex11CommandBusStub"],
    "Ex11EntityStub": ["examples._models.ex11", "Ex11EntityStub"],
    "Ex11HandlerLike": ["examples._models.ex11", "Ex11HandlerLike"],
    "Ex11HandlerLikeService": ["examples._models.ex11", "Ex11HandlerLikeService"],
    "Ex11Payload": ["examples._models.ex11", "Ex11Payload"],
    "Ex11ProcessorProtocolBad": ["examples._models.ex11", "Ex11ProcessorProtocolBad"],
    "Ex11ProcessorProtocolGood": ["examples._models.ex11", "Ex11ProcessorProtocolGood"],
    "Ex12CommandA": ["examples._models.ex12", "Ex12CommandA"],
    "Ex12CommandB": ["examples._models.ex12", "Ex12CommandB"],
    "Ex14CreateUserCommand": ["examples._models.ex14", "Ex14CreateUserCommand"],
    "Ex14GetUserQuery": ["examples._models.ex14", "Ex14GetUserQuery"],
    "Ex14UserDTO": ["examples._models.ex14", "Ex14UserDTO"],
    "ExConfigAppConfig": ["examples._models.exconfig", "ExConfigAppConfig"],
    "SharedHandle": ["examples._models.shared", "SharedHandle"],
    "SharedPerson": ["examples._models.shared", "SharedPerson"],
    "ex00": ["examples._models.ex00", ""],
    "ex01": ["examples._models.ex01", ""],
    "ex02": ["examples._models.ex02", ""],
    "ex03": ["examples._models.ex03", ""],
    "ex04": ["examples._models.ex04", ""],
    "ex05": ["examples._models.ex05", ""],
    "ex07": ["examples._models.ex07", ""],
    "ex08": ["examples._models.ex08", ""],
    "ex10": ["examples._models.ex10", ""],
    "ex11": ["examples._models.ex11", ""],
    "ex12": ["examples._models.ex12", ""],
    "ex14": ["examples._models.ex14", ""],
    "exconfig": ["examples._models.exconfig", ""],
    "shared": ["examples._models.shared", ""],
}

_EXPORTS: Sequence[str] = [
    "Ex00UserInput",
    "Ex00UserProfile",
    "Ex01DemonstrationResult",
    "Ex01InvalidPersonPayload",
    "Ex01RunDemonstrationCommand",
    "Ex01User",
    "Ex01ValidPersonPayload",
    "Ex02CacheService",
    "Ex02DatabaseService",
    "Ex02EmailService",
    "Ex02TestConfig",
    "Ex03Email",
    "Ex03Money",
    "Ex03Order",
    "Ex03OrderItem",
    "Ex03User",
    "Ex04AutoCommand",
    "Ex04CreateUser",
    "Ex04DeleteUser",
    "Ex04FailingDelete",
    "Ex04GetUser",
    "Ex04NoSubscriberEvent",
    "Ex04Ping",
    "Ex04UnknownQuery",
    "Ex04UserCreated",
    "Ex05BadProcessor",
    "Ex05GoodProcessor",
    "Ex05HandlerBad",
    "Ex05HandlerLike",
    "Ex05StatusEnum",
    "Ex05UserModel",
    "Ex07CreateUserCommand",
    "Ex07DemoPlugin",
    "Ex07GetUserQuery",
    "Ex07UserCreatedEvent",
    "Ex08Order",
    "Ex08User",
    "Ex10CommandBusStub",
    "Ex10ContextPayload",
    "Ex10DerivedMessage",
    "Ex10Entity",
    "Ex10Message",
    "Ex10ProcessorBad",
    "Ex10ProcessorGood",
    "Ex10ProtocolHandler",
    "Ex10ServiceStub",
    "Ex11CommandBusStub",
    "Ex11EntityStub",
    "Ex11HandlerLike",
    "Ex11HandlerLikeService",
    "Ex11Payload",
    "Ex11ProcessorProtocolBad",
    "Ex11ProcessorProtocolGood",
    "Ex12CommandA",
    "Ex12CommandB",
    "Ex14CreateUserCommand",
    "Ex14GetUserQuery",
    "Ex14UserDTO",
    "ExConfigAppConfig",
    "SharedHandle",
    "SharedPerson",
    "ex00",
    "ex01",
    "ex02",
    "ex03",
    "ex04",
    "ex05",
    "ex07",
    "ex08",
    "ex10",
    "ex11",
    "ex12",
    "ex14",
    "exconfig",
    "shared",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, _EXPORTS)
