# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Models package."""

from __future__ import annotations

from flext_core.lazy import install_lazy_exports

_LAZY_IMPORTS = {
    "Ex00UserInput": ("examples._models.ex00", "Ex00UserInput"),
    "Ex00UserProfile": ("examples._models.ex00", "Ex00UserProfile"),
    "Ex01DemonstrationResult": ("examples._models.ex01", "Ex01DemonstrationResult"),
    "Ex01InvalidPersonPayload": ("examples._models.ex01", "Ex01InvalidPersonPayload"),
    "Ex01RunDemonstrationCommand": (
        "examples._models.ex01",
        "Ex01RunDemonstrationCommand",
    ),
    "Ex01User": ("examples._models.ex01", "Ex01User"),
    "Ex01ValidPersonPayload": ("examples._models.ex01", "Ex01ValidPersonPayload"),
    "Ex02CacheService": ("examples._models.ex02", "Ex02CacheService"),
    "Ex02DatabaseService": ("examples._models.ex02", "Ex02DatabaseService"),
    "Ex02EmailService": ("examples._models.ex02", "Ex02EmailService"),
    "Ex02TestConfig": ("examples._models.ex02", "Ex02TestConfig"),
    "Ex03Email": ("examples._models.ex03", "Ex03Email"),
    "Ex03Money": ("examples._models.ex03", "Ex03Money"),
    "Ex03Order": ("examples._models.ex03", "Ex03Order"),
    "Ex03OrderItem": ("examples._models.ex03", "Ex03OrderItem"),
    "Ex03User": ("examples._models.ex03", "Ex03User"),
    "Ex04AutoCommand": ("examples._models.ex04", "Ex04AutoCommand"),
    "Ex04CreateUser": ("examples._models.ex04", "Ex04CreateUser"),
    "Ex04DeleteUser": ("examples._models.ex04", "Ex04DeleteUser"),
    "Ex04FailingDelete": ("examples._models.ex04", "Ex04FailingDelete"),
    "Ex04GetUser": ("examples._models.ex04", "Ex04GetUser"),
    "Ex04NoSubscriberEvent": ("examples._models.ex04", "Ex04NoSubscriberEvent"),
    "Ex04Ping": ("examples._models.ex04", "Ex04Ping"),
    "Ex04UnknownQuery": ("examples._models.ex04", "Ex04UnknownQuery"),
    "Ex04UserCreated": ("examples._models.ex04", "Ex04UserCreated"),
    "Ex05BadProcessor": ("examples._models.ex05", "Ex05BadProcessor"),
    "Ex05GoodProcessor": ("examples._models.ex05", "Ex05GoodProcessor"),
    "Ex05HandlerBad": ("examples._models.ex05", "Ex05HandlerBad"),
    "Ex05HandlerLike": ("examples._models.ex05", "Ex05HandlerLike"),
    "Ex05StatusEnum": ("examples._models.ex05", "Ex05StatusEnum"),
    "Ex05UserModel": ("examples._models.ex05", "Ex05UserModel"),
    "Ex07CreateUserCommand": ("examples._models.ex07", "Ex07CreateUserCommand"),
    "Ex07DemoPlugin": ("examples._models.ex07", "Ex07DemoPlugin"),
    "Ex07GetUserQuery": ("examples._models.ex07", "Ex07GetUserQuery"),
    "Ex07UserCreatedEvent": ("examples._models.ex07", "Ex07UserCreatedEvent"),
    "Ex08Order": ("examples._models.ex08", "Ex08Order"),
    "Ex08User": ("examples._models.ex08", "Ex08User"),
    "Ex10CommandBusStub": ("examples._models.ex10", "Ex10CommandBusStub"),
    "Ex10ContextPayload": ("examples._models.ex10", "Ex10ContextPayload"),
    "Ex10DerivedMessage": ("examples._models.ex10", "Ex10DerivedMessage"),
    "Ex10Entity": ("examples._models.ex10", "Ex10Entity"),
    "Ex10Message": ("examples._models.ex10", "Ex10Message"),
    "Ex10ProcessorBad": ("examples._models.ex10", "Ex10ProcessorBad"),
    "Ex10ProcessorGood": ("examples._models.ex10", "Ex10ProcessorGood"),
    "Ex10ProtocolHandler": ("examples._models.ex10", "Ex10ProtocolHandler"),
    "Ex10ServiceStub": ("examples._models.ex10", "Ex10ServiceStub"),
    "Ex11CommandBusStub": ("examples._models.ex11", "Ex11CommandBusStub"),
    "Ex11EntityStub": ("examples._models.ex11", "Ex11EntityStub"),
    "Ex11HandlerLike": ("examples._models.ex11", "Ex11HandlerLike"),
    "Ex11HandlerLikeService": ("examples._models.ex11", "Ex11HandlerLikeService"),
    "Ex11Payload": ("examples._models.ex11", "Ex11Payload"),
    "Ex11ProcessorProtocolBad": ("examples._models.ex11", "Ex11ProcessorProtocolBad"),
    "Ex11ProcessorProtocolGood": ("examples._models.ex11", "Ex11ProcessorProtocolGood"),
    "Ex12CommandA": ("examples._models.ex12", "Ex12CommandA"),
    "Ex12CommandB": ("examples._models.ex12", "Ex12CommandB"),
    "Ex14CreateUserCommand": ("examples._models.ex14", "Ex14CreateUserCommand"),
    "Ex14GetUserQuery": ("examples._models.ex14", "Ex14GetUserQuery"),
    "Ex14UserDTO": ("examples._models.ex14", "Ex14UserDTO"),
    "ExConfigAppConfig": ("examples._models.exconfig", "ExConfigAppConfig"),
    "SharedHandle": ("examples._models.shared", "SharedHandle"),
    "SharedPerson": ("examples._models.shared", "SharedPerson"),
    "ex00": "examples._models.ex00",
    "ex01": "examples._models.ex01",
    "ex02": "examples._models.ex02",
    "ex03": "examples._models.ex03",
    "ex04": "examples._models.ex04",
    "ex05": "examples._models.ex05",
    "ex07": "examples._models.ex07",
    "ex08": "examples._models.ex08",
    "ex10": "examples._models.ex10",
    "ex11": "examples._models.ex11",
    "ex12": "examples._models.ex12",
    "ex14": "examples._models.ex14",
    "exconfig": "examples._models.exconfig",
    "shared": "examples._models.shared",
}


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
