from abc import ABC, abstractmethod as _abstractmethod

from _typeshed import Incomplete

from flext_core import interfaces as interfaces
from flext_core.__version__ import (
    FlextCompatibilityResult as FlextCompatibilityResult,
    FlextVersionInfo as FlextVersionInfo,
    __version__ as __version__,
)
from flext_core.aggregate_root import FlextAggregateRoot as FlextAggregateRoot
from flext_core.commands import FlextCommands as FlextCommands
from flext_core.config import (
    CONFIG_VALIDATION_MESSAGES as CONFIG_VALIDATION_MESSAGES,
    DEFAULT_ENVIRONMENT as DEFAULT_ENVIRONMENT,
    DEFAULT_LOG_LEVEL as DEFAULT_LOG_LEVEL,
    DEFAULT_PAGE_SIZE as DEFAULT_PAGE_SIZE,
    DEFAULT_RETRIES as DEFAULT_RETRIES,
    DEFAULT_TIMEOUT as DEFAULT_TIMEOUT,
    FlextAbstractConfig as FlextAbstractConfig,
    FlextBaseConfigModel as FlextBaseConfigModel,
    FlextConfig as FlextConfig,
    FlextConfigDefaults as FlextConfigDefaults,
    FlextConfigFactory as FlextConfigFactory,
    FlextConfigOps as FlextConfigOps,
    FlextConfigValidation as FlextConfigValidation,
    FlextDatabaseConfig as FlextDatabaseConfig,
    FlextJWTConfig as FlextJWTConfig,
    FlextLDAPConfig as FlextLDAPConfig,
    FlextObservabilityConfig as FlextObservabilityConfig,
    FlextOracleConfig as FlextOracleConfig,
    FlextRedisConfig as FlextRedisConfig,
    FlextSettings as FlextSettings,
    FlextSingerConfig as FlextSingerConfig,
    create_config as create_config,
    load_config_from_env as load_config_from_env,
    load_config_from_file as load_config_from_file,
    merge_configs as merge_configs,
    safe_get_env_var as safe_get_env_var,
    safe_load_json_file as safe_load_json_file,
    validate_config as validate_config,
)
from flext_core.constants import (
    ERROR_CODES as ERROR_CODES,
    MESSAGES as MESSAGES,
    SERVICE_NAME_EMPTY as SERVICE_NAME_EMPTY,
    FlextConnectionType as FlextConnectionType,
    FlextConstants as FlextConstants,
    FlextDataFormat as FlextDataFormat,
    FlextEntityStatus as FlextEntityStatus,
    FlextEnvironment as FlextEnvironment,
    FlextFieldType as FlextFieldType,
    FlextLogLevel as FlextLogLevel,
    FlextOperationStatus as FlextOperationStatus,
)
from flext_core.container import (
    FlextContainer as FlextContainer,
    FlextContainerUtils as FlextContainerUtils,
    FlextGlobalContainerManager as FlextGlobalContainerManager,
    FlextServiceKey as FlextServiceKey,
    FlextServiceRegistrar as FlextServiceRegistrar,
    FlextServiceRetriever as FlextServiceRetriever,
    configure_flext_container as configure_flext_container,
    create_module_container_utilities as create_module_container_utilities,
    get_flext_container as get_flext_container,
    get_typed as get_typed,
    register_typed as register_typed,
)
from flext_core.context import FlextContext as FlextContext
from flext_core.core import FlextCore as FlextCore, flext_core as flext_core
from flext_core.decorators import (
    FlextAbstractDecorator as FlextAbstractDecorator,
    FlextAbstractDecoratorFactory as FlextAbstractDecoratorFactory,
    FlextAbstractErrorHandlingDecorator as FlextAbstractErrorHandlingDecorator,
    FlextAbstractLoggingDecorator as FlextAbstractLoggingDecorator,
    FlextAbstractPerformanceDecorator as FlextAbstractPerformanceDecorator,
    FlextAbstractValidationDecorator as FlextAbstractValidationDecorator,
    FlextDecoratorFactory as FlextDecoratorFactory,
    FlextDecorators as FlextDecorators,
    FlextDecoratorUtils as FlextDecoratorUtils,
    FlextErrorHandlingDecorators as FlextErrorHandlingDecorators,
    FlextFunctionalDecorators as FlextFunctionalDecorators,
    FlextImmutabilityDecorators as FlextImmutabilityDecorators,
    FlextLoggingDecorators as FlextLoggingDecorators,
    FlextPerformanceDecorators as FlextPerformanceDecorators,
    FlextValidationDecorators as FlextValidationDecorators,
    _flext_cache_decorator as _flext_cache_decorator,
    _flext_safe_call_decorator as _flext_safe_call_decorator,
    _flext_timing_decorator as _flext_timing_decorator,
    _flext_validate_input_decorator as _flext_validate_input_decorator,
)
from flext_core.delegation_system import (
    FlextDelegatedProperty as FlextDelegatedProperty,
    FlextMixinDelegator as FlextMixinDelegator,
    create_mixin_delegator as create_mixin_delegator,
    validate_delegation_system as validate_delegation_system,
)
from flext_core.domain_services import (
    FlextDomainService as FlextDomainService,
    OperationType as OperationType,
    TDomainResult as TDomainResult,
)
from flext_core.exceptions import (
    FlextAbstractBusinessError as FlextAbstractBusinessError,
    FlextAbstractConfigurationError as FlextAbstractConfigurationError,
    FlextAbstractError as FlextAbstractError,
    FlextAbstractErrorFactory as FlextAbstractErrorFactory,
    FlextAbstractInfrastructureError as FlextAbstractInfrastructureError,
    FlextAbstractValidationError as FlextAbstractValidationError,
    FlextAlreadyExistsError as FlextAlreadyExistsError,
    FlextAttributeError as FlextAttributeError,
    FlextAuthenticationError as FlextAuthenticationError,
    FlextConfigurationError as FlextConfigurationError,
    FlextConnectionError as FlextConnectionError,
    FlextCriticalError as FlextCriticalError,
    FlextError as FlextError,
    FlextExceptionMetrics as FlextExceptionMetrics,
    FlextExceptions as FlextExceptions,
    FlextNotFoundError as FlextNotFoundError,
    FlextOperationError as FlextOperationError,
    FlextPermissionError as FlextPermissionError,
    FlextProcessingError as FlextProcessingError,
    FlextTimeoutError as FlextTimeoutError,
    FlextTypeError as FlextTypeError,
    FlextValidationError as FlextValidationError,
    clear_exception_metrics as clear_exception_metrics,
    create_context_exception_factory as create_context_exception_factory,
    create_module_exception_classes as create_module_exception_classes,
    get_exception_metrics as get_exception_metrics,
)
from flext_core.fields import (
    FlextFieldCore as FlextFieldCore,
    FlextFieldCoreMetadata as FlextFieldCoreMetadata,
    FlextFieldId as FlextFieldId,
    FlextFieldMetadata as FlextFieldMetadata,
    FlextFieldName as FlextFieldName,
    FlextFieldRegistry as FlextFieldRegistry,
    FlextFields as FlextFields,
    FlextFieldTypeStr as FlextFieldTypeStr,
    FlextValidator as FlextValidator,
    flext_create_boolean_field as flext_create_boolean_field,
    flext_create_integer_field as flext_create_integer_field,
    flext_create_string_field as flext_create_string_field,
)
from flext_core.guards import (
    FlextGuards as FlextGuards,
    FlextValidatedModel as FlextValidatedModel,
    FlextValidationUtils as FlextValidationUtils,
    ValidatedModel as ValidatedModel,
    immutable as immutable,
    is_dict_of as is_dict_of,
    is_instance_of as is_instance_of,
    is_list_of as is_list_of,
    make_builder as make_builder,
    make_factory as make_factory,
    pure as pure,
    require_in_range as require_in_range,
    require_non_empty as require_non_empty,
    require_not_none as require_not_none,
    require_positive as require_positive,
    safe as safe,
    validated as validated,
)
from flext_core.handlers import (
    FlextAbstractHandler as FlextAbstractHandler,
    FlextAbstractHandlerChain as FlextAbstractHandlerChain,
    FlextAbstractHandlerRegistry as FlextAbstractHandlerRegistry,
    FlextAbstractMetricsHandler as FlextAbstractMetricsHandler,
    FlextAuthorizingHandler as FlextAuthorizingHandler,
    FlextBaseHandler as FlextBaseHandler,
    FlextEventHandler as FlextEventHandler,
    FlextHandlerChain as FlextHandlerChain,
    FlextHandlerRegistry as FlextHandlerRegistry,
    FlextHandlers as FlextHandlers,
    FlextMetricsHandler as FlextMetricsHandler,
    FlextValidatingHandler as FlextValidatingHandler,
    HandlersFacade as HandlersFacade,
)
from flext_core.legacy import (
    BaseConfigManager as BaseConfigManager,
    BaseEntry as BaseEntry,
    BaseFileWriter as BaseFileWriter,
    BaseProcessor as BaseProcessor,
    BaseSorter as BaseSorter,
    ConfigAttributeValidator as ConfigAttributeValidator,
    ConsoleLogger as ConsoleLogger,
    EntryType as EntryType,
    FlextValueObjectFactory as FlextValueObjectFactory,
    _BaseConfigDefaults as _BaseConfigDefaults,
)
from flext_core.loggings import (
    FlextLogContext as FlextLogContext,
    FlextLogContextManager as FlextLogContextManager,
    FlextLogger as FlextLogger,
    FlextLoggerFactory as FlextLoggerFactory,
    create_log_context as create_log_context,
    flext_get_logger as flext_get_logger,
    get_logger as get_logger,
)
from flext_core.mixins import (
    FlextAbstractEntityMixin as FlextAbstractEntityMixin,
    FlextAbstractIdentifiableMixin as FlextAbstractIdentifiableMixin,
    FlextAbstractLoggableMixin as FlextAbstractLoggableMixin,
    FlextAbstractMixin as FlextAbstractMixin,
    FlextAbstractSerializableMixin as FlextAbstractSerializableMixin,
    FlextAbstractServiceMixin as FlextAbstractServiceMixin,
    FlextAbstractTimestampMixin as FlextAbstractTimestampMixin,
    FlextAbstractValidatableMixin as FlextAbstractValidatableMixin,
    FlextCacheableMixin as FlextCacheableMixin,
    FlextCommandMixin as FlextCommandMixin,
    FlextComparableMixin as FlextComparableMixin,
    FlextIdentifiableMixin as FlextIdentifiableMixin,
    FlextLoggableMixin as FlextLoggableMixin,
    FlextSerializableMixin as FlextSerializableMixin,
    FlextTimestampMixin as FlextTimestampMixin,
    FlextTimingMixin as FlextTimingMixin,
    FlextValidatableMixin as FlextValidatableMixin,
    LegacyCompatibleCacheableMixin as LegacyCompatibleCacheableMixin,
    LegacyCompatibleCommandMixin as LegacyCompatibleCommandMixin,
    LegacyCompatibleComparableMixin as LegacyCompatibleComparableMixin,
    LegacyCompatibleDataMixin as LegacyCompatibleDataMixin,
    LegacyCompatibleEntityMixin as LegacyCompatibleEntityMixin,
    LegacyCompatibleFullMixin as LegacyCompatibleFullMixin,
    LegacyCompatibleIdentifiableMixin as LegacyCompatibleIdentifiableMixin,
    LegacyCompatibleLoggableMixin as LegacyCompatibleLoggableMixin,
    LegacyCompatibleSerializableMixin as LegacyCompatibleSerializableMixin,
    LegacyCompatibleServiceMixin as LegacyCompatibleServiceMixin,
    LegacyCompatibleTimestampMixin as LegacyCompatibleTimestampMixin,
    LegacyCompatibleTimingMixin as LegacyCompatibleTimingMixin,
    LegacyCompatibleValidatableMixin as LegacyCompatibleValidatableMixin,
)
from flext_core.models import (
    DomainEventDict as DomainEventDict,
    FlextAuth as FlextAuth,
    FlextConnectionDict as FlextConnectionDict,
    FlextData as FlextData,
    FlextDatabaseModel as FlextDatabaseModel,
    FlextEntity as FlextEntity,
    FlextEntityDict as FlextEntityDict,
    FlextFactory as FlextFactory,
    FlextFieldValidationInfo as FlextFieldValidationInfo,
    FlextLegacyConfig as FlextLegacyConfig,
    FlextModel as FlextModel,
    FlextModelDict as FlextModelDict,
    FlextObs as FlextObs,
    FlextOperationDict as FlextOperationDict,
    FlextOperationModel as FlextOperationModel,
    FlextOracleModel as FlextOracleModel,
    FlextServiceModel as FlextServiceModel,
    FlextSingerStreamModel as FlextSingerStreamModel,
    FlextValidationContext as FlextValidationContext,
    FlextValue as FlextValue,
    FlextValueObjectDict as FlextValueObjectDict,
    JsonSchemaDefinition as JsonSchemaDefinition,
    JsonSchemaFieldInfo as JsonSchemaFieldInfo,
    JsonSchemaValue as JsonSchemaValue,
    create_database_model as create_database_model,
    create_operation_model as create_operation_model,
    create_oracle_model as create_oracle_model,
    create_service_model as create_service_model,
    model_to_dict_safe as model_to_dict_safe,
    validate_all_models as validate_all_models,
)
from flext_core.observability import (
    FlextConsoleLogger as FlextConsoleLogger,
    FlextInMemoryMetrics as FlextInMemoryMetrics,
    FlextMinimalObservability as FlextMinimalObservability,
    FlextNoOpSpan as FlextNoOpSpan,
    FlextNoOpTracer as FlextNoOpTracer,
    FlextSimpleAlerts as FlextSimpleAlerts,
    FlextSimpleObservability as FlextSimpleObservability,
    InMemoryMetrics as InMemoryMetrics,
    MinimalObservability as MinimalObservability,
    NoOpTracer as NoOpTracer,
    SimpleAlerts as SimpleAlerts,
    get_console_logger as get_console_logger,
    get_global_observability as get_global_observability,
    get_memory_metrics as get_memory_metrics,
    get_noop_tracer as get_noop_tracer,
    get_observability as get_observability,
    get_simple_observability as get_simple_observability,
    reset_global_observability as reset_global_observability,
)
from flext_core.payload import (
    FlextEvent as FlextEvent,
    FlextMessage as FlextMessage,
    FlextPayload as FlextPayload,
    create_cross_service_event as create_cross_service_event,
    create_cross_service_message as create_cross_service_message,
    get_serialization_metrics as get_serialization_metrics,
    validate_cross_service_protocol as validate_cross_service_protocol,
)
from flext_core.protocols import (
    FlextAlertsProtocol as FlextAlertsProtocol,
    FlextConfigurable as FlextConfigurableProtocol,
    FlextLoggerProtocol as FlextLoggerProtocol,
    FlextMetricsProtocol as FlextMetricsProtocol,
    FlextObservabilityProtocol as FlextObservabilityProtocol,
    FlextPlugin as FlextPlugin,
    FlextPluginContext as FlextPluginContext,
    FlextPluginLoader as FlextPluginLoader,
    FlextPluginRegistry as FlextPluginRegistry,
    FlextRepository as FlextRepository,
    FlextTracerProtocol as FlextTracerProtocol,
    FlextValidator as FlextValidatorProtocol,
)
from flext_core.result import FlextResult as FlextResult
from flext_core.root_models import (
    FlextConnectionString as FlextConnectionString,
    FlextEmailAddress as FlextEmailAddress,
    FlextEntityId as FlextEntityId,
    FlextErrorCode as FlextErrorCode,
    FlextErrorMessage as FlextErrorMessage,
    FlextEventList as FlextEventList,
    FlextHost as FlextHost,
    FlextMetadata as FlextMetadata,
    FlextPercentage as FlextPercentage,
    FlextPort as FlextPort,
    FlextServiceName as FlextServiceName,
    FlextTimestamp as FlextTimestamp,
    FlextVersion as FlextVersion,
    create_email as create_email,
    create_entity_id as create_entity_id,
    create_host_port as create_host_port,
    create_service_name as create_service_name,
    create_version as create_version,
    from_legacy_dict as from_legacy_dict,
    to_legacy_dict as to_legacy_dict,
)
from flext_core.schema_processing import (
    FlextBaseConfigManager as FlextBaseConfigManager,
    FlextBaseEntry as FlextBaseEntry,
    FlextBaseFileWriter as FlextBaseFileWriter,
    FlextBaseProcessor as FlextBaseProcessor,
    FlextBaseSorter as FlextBaseSorter,
    FlextConfigAttributeValidator as FlextConfigAttributeValidator,
    FlextEntryType as FlextEntryType,
    FlextEntryValidator as FlextEntryValidator,
    FlextProcessingPipeline as FlextProcessingPipeline,
    FlextRegexProcessor as FlextRegexProcessor,
    ProcessingPipeline as ProcessingPipeline,
)
from flext_core.semantic import (
    FlextSemantic as FlextSemantic,
    FlextSemanticError as FlextSemanticError,
    FlextSemanticModel as FlextSemanticModel,
    FlextSemanticObservability as FlextSemanticObservability,
)
from flext_core.testing_utilities import (
    FlextTestAssertion as FlextTestAssertion,
    FlextTestConfig as FlextTestConfig,
    FlextTestFactory as FlextTestFactory,
    FlextTestMocker as FlextTestMocker,
    FlextTestModel as FlextTestModel,
    FlextTestUtilities as FlextTestUtilities,
    ITestAssertion as ITestAssertion,
    ITestFactory as ITestFactory,
    ITestMocker as ITestMocker,
    TTestConfig as TTestConfig,
    TTestData as TTestData,
    create_api_test_response as create_api_test_response,
    create_ldap_test_config as create_ldap_test_config,
    create_oud_connection_config as create_oud_connection_config,
)
from flext_core.typings import (
    E as E,
    F as F,
    FlextTypes as FlextTypes,
    P as P,
    R as R,
    T as T,
    TAnyDict as TAnyDict,
    TAnyList as TAnyList,
    TAnyObject as TAnyObject,
    TCallable as TCallable,
    TCommand as TCommand,
    TCommandBusId as TCommandBusId,
    TCommandId as TCommandId,
    TCommandMetadata as TCommandMetadata,
    TCommandPayload as TCommandPayload,
    TCommandPriority as TCommandPriority,
    TCommandResult as TCommandResult,
    TCommandType as TCommandType,
    TComparable as TComparable,
    TConfig as TConfig,
    TConfigDict as TConfigDict,
    TConnection as TConnection,
    TConnectionString as TConnectionString,
    TCorrelationId as TCorrelationId,
    TCredentials as TCredentials,
    TData as TData,
    TDict as TDict,
    TEntity as TEntity,
    TEntityId as TEntityId,
    TErrorCode as TErrorCode,
    TErrorHandler as TErrorHandler,
    TErrorMessage as TErrorMessage,
    TEvent as TEvent,
    TFactory as TFactory,
    THandlerName as THandlerName,
    TList as TList,
    TLogMessage as TLogMessage,
    TMessage as TMessage,
    TMiddlewareName as TMiddlewareName,
    TOptional as TOptional,
    TPaginationToken as TPaginationToken,
    TPredicate as TPredicate,
    TQuery as TQuery,
    TQueryCriteria as TQueryCriteria,
    TQueryId as TQueryId,
    TQueryProjection as TQueryProjection,
    TQueryResult as TQueryResult,
    TQueryType as TQueryType,
    TRequest as TRequest,
    TResponse as TResponse,
    TResult as TResult,
    TSerializable as TSerializable,
    TService as TService,
    TServiceKey as TServiceKey,
    TServiceName as TServiceName,
    TStringDict as TStringDict,
    TToken as TToken,
    TTransformer as TTransformer,
    TUserData as TUserData,
    TUserId as TUserId,
    TValidatable as TValidatable,
    TValidationRule as TValidationRule,
    TValidator as TValidator,
    TValue as TValue,
    U as U,
    V as V,
)
from flext_core.utilities import (
    Console as Console,
    FlextBaseFactory as FlextBaseFactory,
    FlextConsole as FlextConsole,
    FlextConversions as FlextConversions,
    FlextDecoratedFunction as FlextDecoratedFunction,
    FlextFormatters as FlextFormatters,
    FlextGenerators as FlextGenerators,
    FlextGenericFactory as FlextGenericFactory,
    FlextIdGenerator as FlextIdGenerator,
    FlextPerformance as FlextPerformance,
    FlextTextProcessor as FlextTextProcessor,
    FlextTimeUtils as FlextTimeUtils,
    FlextTypeGuards as FlextTypeGuards,
    FlextUtilities as FlextUtilities,
    FlextUtilityFactory as FlextUtilityFactory,
    flext_clear_performance_metrics as flext_clear_performance_metrics,
    flext_get_performance_metrics as flext_get_performance_metrics,
    flext_record_performance as flext_record_performance,
    flext_safe_int_conversion as flext_safe_int_conversion,
    flext_track_performance as flext_track_performance,
    generate_correlation_id as generate_correlation_id,
    generate_id as generate_id,
    generate_iso_timestamp as generate_iso_timestamp,
    generate_uuid as generate_uuid,
    is_not_none as is_not_none,
    safe_call as safe_call,
    safe_int_conversion_with_default as safe_int_conversion_with_default,
    truncate as truncate,
)
from flext_core.validation import (
    FlextDomainValidator as FlextDomainValidator,
    FlextPredicates as FlextPredicates,
    FlextValidation as FlextValidation,
    FlextValidators as FlextValidators,
    flext_validate_email as flext_validate_email,
    flext_validate_non_empty_string as flext_validate_non_empty_string,
    flext_validate_numeric as flext_validate_numeric,
    flext_validate_required as flext_validate_required,
    flext_validate_service_name as flext_validate_service_name,
    flext_validate_string as flext_validate_string,
)
from flext_core.value_objects import FlextValueObject as FlextValueObject

__all__ = [
    "BYTES_PER_KB",
    "CONFIG_VALIDATION_MESSAGES",
    "CONFIG_VALIDATION_MESSAGES",
    "DEFAULT_ENVIRONMENT",
    "DEFAULT_ENVIRONMENT",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_RETRIES",
    "DEFAULT_RETRIES",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TIMEOUT",
    "ERROR_CODES",
    "MESSAGES",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_MINUTE",
    "SERVICE_NAME_EMPTY",
    "BaseConfigManager",
    "BaseEntry",
    "BaseFileWriter",
    "BaseProcessor",
    "BaseSorter",
    "ConfigAttributeValidator",
    "Console",
    "ConsoleLogger",
    "DomainEventDict",
    "E",
    "EntryType",
    "F",
    "FlextAbstractBusinessError",
    "FlextAbstractConfig",
    "FlextAbstractConfig",
    "FlextAbstractConfigurationError",
    "FlextAbstractDecorator",
    "FlextAbstractDecoratorFactory",
    "FlextAbstractEntityMixin",
    "FlextAbstractError",
    "FlextAbstractErrorFactory",
    "FlextAbstractErrorHandlingDecorator",
    "FlextAbstractHandler",
    "FlextAbstractHandlerChain",
    "FlextAbstractHandlerRegistry",
    "FlextAbstractIdentifiableMixin",
    "FlextAbstractInfrastructureError",
    "FlextAbstractLoggableMixin",
    "FlextAbstractLoggingDecorator",
    "FlextAbstractMetricsHandler",
    "FlextAbstractMixin",
    "FlextAbstractPerformanceDecorator",
    "FlextAbstractSerializableMixin",
    "FlextAbstractServiceMixin",
    "FlextAbstractSettings",
    "FlextAbstractTimestampMixin",
    "FlextAbstractValidatableMixin",
    "FlextAbstractValidationDecorator",
    "FlextAbstractValidationError",
    "FlextAggregateRoot",
    "FlextAlertsProtocol",
    "FlextAlreadyExistsError",
    "FlextApplicationConfig",
    "FlextAttributeError",
    "FlextAuth",
    "FlextAuthenticationError",
    "FlextAuthorizingHandler",
    "FlextBaseConfigManager",
    "FlextBaseConfigModel",
    "FlextBaseEntry",
    "FlextBaseFactory",
    "FlextBaseFileWriter",
    "FlextBaseHandler",
    "FlextBaseProcessor",
    "FlextBaseSorter",
    "FlextCacheableMixin",
    "FlextCommandHandler",
    "FlextCommandMixin",
    "FlextCommands",
    "FlextComparableMixin",
    "FlextCompatibilityResult",
    "FlextConfig",
    "FlextConfigAttributeValidator",
    "FlextConfigBuilder",
    "FlextConfigDefaults",
    "FlextConfigFactory",
    "FlextConfigLoaderProtocol",
    "FlextConfigManager",
    "FlextConfigMergerProtocol",
    "FlextConfigOperations",
    "FlextConfigOps",
    "FlextConfigSerializerProtocol",
    "FlextConfigValidation",
    "FlextConfigValidator",
    "FlextConfigValidatorProtocol",
    "FlextConfigurableProtocol",
    "FlextConfigurationError",
    "FlextConnectionDict",
    "FlextConnectionError",
    "FlextConnectionString",
    "FlextConnectionType",
    "FlextConsole",
    "FlextConsoleLogger",
    "FlextConstants",
    "FlextContainer",
    "FlextContainerUtils",
    "FlextContext",
    "FlextConversions",
    "FlextCore",
    "FlextCriticalError",
    "FlextData",
    "FlextDataFormat",
    "FlextDataIntegrationConfig",
    "FlextDatabaseConfig",
    "FlextDatabaseConfigDict",
    "FlextDatabaseModel",
    "FlextDecoratedFunction",
    "FlextDecoratorFactory",
    "FlextDecoratorUtils",
    "FlextDecorators",
    "FlextDelegatedProperty",
    "FlextDomainService",
    "FlextDomainValidator",
    "FlextEmailAddress",
    "FlextEntity",
    "FlextEntity",
    "FlextEntity",
    "FlextEntity",
    "FlextEntityDict",
    "FlextEntityId",
    "FlextEntityId",
    "FlextEntityStatus",
    "FlextEntryType",
    "FlextEntryValidator",
    "FlextEnvironment",
    "FlextError",
    "FlextErrorCode",
    "FlextErrorHandlingDecorators",
    "FlextErrorMessage",
    "FlextEvent",
    "FlextEventHandler",
    "FlextEventList",
    "FlextExceptionMetrics",
    "FlextExceptions",
    "FlextFactory",
    "FlextFactory",
    "FlextFieldCore",
    "FlextFieldCoreMetadata",
    "FlextFieldId",
    "FlextFieldMetadata",
    "FlextFieldName",
    "FlextFieldRegistry",
    "FlextFieldType",
    "FlextFieldTypeStr",
    "FlextFieldValidationInfo",
    "FlextFields",
    "FlextFormatters",
    "FlextFunctionalDecorators",
    "FlextGenerators",
    "FlextGenericFactory",
    "FlextGlobalContainerManager",
    "FlextGuards",
    "FlextHandlerChain",
    "FlextHandlerRegistry",
    "FlextHandlers",
    "FlextHost",
    "FlextIdGenerator",
    "FlextIdentifiableMixin",
    "FlextImmutabilityDecorators",
    "FlextInMemoryMetrics",
    "FlextJWTConfig",
    "FlextJWTConfigDict",
    "FlextLDAPConfig",
    "FlextLDAPConfigDict",
    "FlextLegacyConfig",
    "FlextLogContext",
    "FlextLogContextManager",
    "FlextLogLevel",
    "FlextLoggableMixin",
    "FlextLogger",
    "FlextLoggerFactory",
    "FlextLoggerProtocol",
    "FlextLoggingDecorators",
    "FlextMessage",
    "FlextMetadata",
    "FlextMetricsHandler",
    "FlextMetricsProtocol",
    "FlextMinimalObservability",
    "FlextMixinDelegator",
    "FlextModel",
    "FlextModel",
    "FlextModelDict",
    "FlextNoOpSpan",
    "FlextNoOpTracer",
    "FlextNotFoundError",
    "FlextObs",
    "FlextObservabilityConfig",
    "FlextObservabilityConfigDict",
    "FlextObservabilityProtocol",
    "FlextOperationDict",
    "FlextOperationError",
    "FlextOperationModel",
    "FlextOperationStatus",
    "FlextOracleConfig",
    "FlextOracleConfigDict",
    "FlextOracleModel",
    "FlextPayload",
    "FlextPercentage",
    "FlextPerformance",
    "FlextPerformanceConfig",
    "FlextPerformanceDecorators",
    "FlextPermissionError",
    "FlextPlugin",
    "FlextPluginContext",
    "FlextPluginLoader",
    "FlextPluginRegistry",
    "FlextPort",
    "FlextPredicates",
    "FlextProcessingError",
    "FlextProcessingPipeline",
    "FlextQueryHandler",
    "FlextRedisConfig",
    "FlextRedisConfigDict",
    "FlextRegexProcessor",
    "FlextRepository",
    "FlextResult",
    "FlextSemantic",
    "FlextSemanticError",
    "FlextSemanticModel",
    "FlextSemanticObservability",
    "FlextSerializableMixin",
    "FlextServiceKey",
    "FlextServiceModel",
    "FlextServiceName",
    "FlextServiceRegistrar",
    "FlextServiceRetriever",
    "FlextSettings",
    "FlextSimpleAlerts",
    "FlextSimpleObservability",
    "FlextSingerConfig",
    "FlextSingerConfigDict",
    "FlextSingerStreamModel",
    "FlextTestAssertion",
    "FlextTestConfig",
    "FlextTestFactory",
    "FlextTestMocker",
    "FlextTestModel",
    "FlextTestUtilities",
    "FlextTextProcessor",
    "FlextTimeUtils",
    "FlextTimeoutError",
    "FlextTimestamp",
    "FlextTimestampMixin",
    "FlextTimingMixin",
    "FlextTracerProtocol",
    "FlextTypeError",
    "FlextTypeGuards",
    "FlextTypes",
    "FlextUtilities",
    "FlextUtilityFactory",
    "FlextValidatableMixin",
    "FlextValidatedModel",
    "FlextValidatingHandler",
    "FlextValidation",
    "FlextValidationContext",
    "FlextValidationDecorators",
    "FlextValidationError",
    "FlextValidationUtils",
    "FlextValidator",
    "FlextValidatorProtocol",
    "FlextValidators",
    "FlextValue",
    "FlextValue",
    "FlextValue",
    "FlextValueObject",
    "FlextValueObjectDict",
    "FlextValueObjectFactory",
    "FlextVersion",
    "FlextVersionInfo",
    "HandlersFacade",
    "ITestAssertion",
    "ITestFactory",
    "ITestMocker",
    "InMemoryMetrics",
    "JsonSchemaDefinition",
    "JsonSchemaFieldInfo",
    "JsonSchemaValue",
    "LegacyCompatibleCacheableMixin",
    "LegacyCompatibleCommandMixin",
    "LegacyCompatibleComparableMixin",
    "LegacyCompatibleDataMixin",
    "LegacyCompatibleEntityMixin",
    "LegacyCompatibleFullMixin",
    "LegacyCompatibleIdentifiableMixin",
    "LegacyCompatibleLoggableMixin",
    "LegacyCompatibleSerializableMixin",
    "LegacyCompatibleServiceMixin",
    "LegacyCompatibleTimestampMixin",
    "LegacyCompatibleTimingMixin",
    "LegacyCompatibleValidatableMixin",
    "MinimalObservability",
    "NoOpTracer",
    "OperationType",
    "P",
    "ProcessingPipeline",
    "R",
    "SimpleAlerts",
    "T",
    "TAnyDict",
    "TAnyList",
    "TAnyObject",
    "TCallable",
    "TCommand",
    "TCommandBusId",
    "TCommandId",
    "TCommandMetadata",
    "TCommandPayload",
    "TCommandPriority",
    "TCommandResult",
    "TCommandType",
    "TComparable",
    "TConfig",
    "TConfigDict",
    "TConnection",
    "TConnectionString",
    "TCorrelationId",
    "TCredentials",
    "TData",
    "TDict",
    "TDomainResult",
    "TEntity",
    "TEntityId",
    "TErrorCode",
    "TErrorHandler",
    "TErrorMessage",
    "TEvent",
    "TFactory",
    "THandlerName",
    "TList",
    "TLogMessage",
    "TMessage",
    "TMiddlewareName",
    "TOptional",
    "TPaginationToken",
    "TPredicate",
    "TQuery",
    "TQueryCriteria",
    "TQueryId",
    "TQueryProjection",
    "TQueryResult",
    "TQueryType",
    "TRequest",
    "TResponse",
    "TResult",
    "TSerializable",
    "TService",
    "TServiceKey",
    "TServiceName",
    "TStringDict",
    "TTestConfig",
    "TTestData",
    "TToken",
    "TTransformer",
    "TUserData",
    "TUserId",
    "TValidatable",
    "TValidationRule",
    "TValidator",
    "TValue",
    "U",
    "V",
    "ValidatedModel",
    "_BaseConfigDefaults",
    "__version__",
    "__version_info__",
    "_flext_cache_decorator",
    "_flext_safe_call_decorator",
    "_flext_timing_decorator",
    "_flext_validate_input_decorator",
    "annotations",
    "clear_exception_metrics",
    "configure_flext_container",
    "create_api_test_response",
    "create_config",
    "create_context_exception_factory",
    "create_cross_service_event",
    "create_cross_service_message",
    "create_database_model",
    "create_email",
    "create_entity_id",
    "create_host_port",
    "create_ldap_test_config",
    "create_log_context",
    "create_mixin_delegator",
    "create_module_container_utilities",
    "create_module_exception_classes",
    "create_operation_model",
    "create_oracle_model",
    "create_oud_connection_config",
    "create_service_model",
    "create_service_name",
    "create_version",
    "flext_clear_performance_metrics",
    "flext_core",
    "flext_create_boolean_field",
    "flext_create_integer_field",
    "flext_create_string_field",
    "flext_get_logger",
    "flext_get_performance_metrics",
    "flext_record_performance",
    "flext_safe_int_conversion",
    "flext_track_performance",
    "flext_validate_email",
    "flext_validate_non_empty_string",
    "flext_validate_numeric",
    "flext_validate_required",
    "flext_validate_service_name",
    "flext_validate_string",
    "from_legacy_dict",
    "generate_correlation_id",
    "generate_id",
    "generate_iso_timestamp",
    "generate_uuid",
    "get_console_logger",
    "get_exception_metrics",
    "get_flext_container",
    "get_global_observability",
    "get_logger",
    "get_memory_metrics",
    "get_noop_tracer",
    "get_observability",
    "get_serialization_metrics",
    "get_simple_observability",
    "get_typed",
    "immutable",
    "interfaces",
    "is_dict_of",
    "is_instance_of",
    "is_list_of",
    "is_not_none",
    "is_not_none",
    "load_config_from_env",
    "load_config_from_file",
    "make_builder",
    "make_factory",
    "merge_configs",
    "model_to_dict_safe",
    "pure",
    "register_typed",
    "require_in_range",
    "require_non_empty",
    "require_not_none",
    "require_positive",
    "reset_global_observability",
    "safe",
    "safe_call",
    "safe_get_env_var",
    "safe_int_conversion_with_default",
    "safe_load_json_file",
    "to_legacy_dict",
    "truncate",
    "validate_all_models",
    "validate_config",
    "validate_cross_service_protocol",
    "validate_delegation_system",
    "validated",
]

__version_info__: Incomplete
BYTES_PER_KB: Incomplete
SECONDS_PER_MINUTE: Incomplete
SECONDS_PER_HOUR: Incomplete

class _config_base:
    @staticmethod
    def dict(*_args: object, **_kwargs: object) -> dict[str, object]: ...

class FlextCommandHandler(FlextAbstractHandler[T, U], ABC):
    @_abstractmethod
    def handle_command(self, command: T) -> FlextResult[U]: ...
    def handle(self, request: T) -> FlextResult[U]: ...

class FlextQueryHandler(FlextAbstractHandler[T, U], ABC):
    @_abstractmethod
    def handle_query(self, query: T) -> FlextResult[U]: ...
    def handle(self, request: T) -> FlextResult[U]: ...

# Names in __all__ with no definition:
#   FlextAbstractSettings
#   FlextApplicationConfig
#   FlextConfigBuilder
#   FlextConfigLoaderProtocol
#   FlextConfigManager
#   FlextConfigMergerProtocol
#   FlextConfigOperations
#   FlextConfigSerializerProtocol
#   FlextConfigValidator
#   FlextConfigValidatorProtocol
#   FlextDataIntegrationConfig
#   FlextDatabaseConfigDict
#   FlextJWTConfigDict
#   FlextLDAPConfigDict
#   FlextObservabilityConfigDict
#   FlextOracleConfigDict
#   FlextPerformanceConfig
#   FlextRedisConfigDict
#   FlextSingerConfigDict
#   annotations
