from _typeshed import Incomplete

from flext_core.models import FlextEntity
from flext_core.payload import FlextEvent
from flext_core.result import FlextResult
from flext_core.typings import TAnyDict

__all__ = ["FlextAggregateRoot"]

class FlextAggregateRoot(FlextEntity):
    model_config: Incomplete
    def __init__(
        self, entity_id: str | None = None, version: int = 1, **data: object
    ) -> None: ...
    def add_domain_event(self, *args: object) -> FlextResult[None]: ...
    def add_typed_domain_event(
        self, event_type: str, event_data: TAnyDict
    ) -> FlextResult[None]: ...
    def add_event_object(self, event: FlextEvent) -> None: ...
    def get_domain_events(self) -> list[FlextEvent]: ...
    def clear_domain_events(self) -> list[dict[str, object]]: ...
    def has_domain_events(self) -> bool: ...
