from collections import UserString
from collections.abc import Callable
from typing import Self

from flext_core.mixins import FlextLoggableMixin
from flext_core.result import FlextResult
from flext_core.typings import T

__all__ = [
    "FlextContainer",
    "FlextContainerUtils",
    "FlextServiceKey",
    "FlextServiceKey",
    "configure_flext_container",
    "create_module_container_utilities",
    "get_flext_container",
    "get_typed",
    "register_typed",
]

class FlextServiceKey[TService](UserString):
    def __new__(cls, name: str) -> Self: ...
    @property
    def name(self) -> str: ...
    @classmethod
    def __class_getitem__(cls, _item: object) -> type[FlextServiceKey]: ...

class FlextServiceRegistrar(FlextLoggableMixin):
    def __init__(self) -> None: ...
    def register_service(self, name: str, service: object) -> FlextResult[None]: ...
    def register_factory(self, name: str, factory: object) -> FlextResult[None]: ...
    def unregister_service(self, name: str) -> FlextResult[None]: ...
    def clear_all(self) -> FlextResult[None]: ...
    def get_service_names(self) -> list[str]: ...
    def get_service_count(self) -> int: ...
    def has_service(self, name: str) -> bool: ...
    def get_services_dict(self) -> dict[str, object]: ...
    def get_factories_dict(self) -> dict[str, Callable[[], object]]: ...

class FlextServiceRetriever(FlextLoggableMixin):
    def __init__(
        self, services: dict[str, object], factories: dict[str, Callable[[], object]]
    ) -> None: ...
    def get_service(self, name: str) -> FlextResult[object]: ...
    def get_service_info(self, name: str) -> FlextResult[dict[str, object]]: ...
    def list_services(self) -> dict[str, str]: ...

class FlextContainer(FlextLoggableMixin):
    def __init__(self) -> None: ...
    def register(self, name: str, service: object) -> FlextResult[None]: ...
    def register_factory(
        self, name: str, factory: Callable[[], object]
    ) -> FlextResult[None]: ...
    def unregister(self, name: str) -> FlextResult[None]: ...
    def get(self, name: str) -> FlextResult[object]: ...
    def clear(self) -> FlextResult[None]: ...
    def has(self, name: str) -> bool: ...
    def list_services(self) -> dict[str, str]: ...
    def get_service_names(self) -> list[str]: ...
    def get_service_count(self) -> int: ...
    def get_typed(self, name: str, expected_type: type[T]) -> FlextResult[T]: ...
    def get_info(self, name: str) -> FlextResult[dict[str, object]]: ...
    def get_or_create(
        self, name: str, factory: Callable[[], object]
    ) -> FlextResult[object]: ...
    def auto_wire(
        self, service_class: type[T], service_name: str | None = None
    ) -> FlextResult[T]: ...
    def batch_register(
        self, registrations: dict[str, object]
    ) -> FlextResult[list[str]]: ...

class FlextGlobalContainerManager(FlextLoggableMixin):
    def __init__(self) -> None: ...
    def get_container(self) -> FlextContainer: ...
    def set_container(self, container: FlextContainer) -> None: ...

class _SimpleGlobalManager:
    def __init__(self) -> None: ...
    def get_container(self) -> FlextContainer: ...
    def set_container(self, container: FlextContainer) -> None: ...

class FlextContainerUtils:
    @staticmethod
    def get_flext_container() -> FlextContainer: ...
    @staticmethod
    def configure_flext_container(
        container: FlextContainer | None,
    ) -> FlextContainer: ...

def get_flext_container() -> FlextContainer: ...
def configure_flext_container(container: FlextContainer | None) -> FlextContainer: ...
def get_typed[T](
    key: FlextServiceKey[T] | str, expected_type: type[T]
) -> FlextResult[T]: ...
def register_typed[T](
    key: FlextServiceKey[T] | str, service: T
) -> FlextResult[None]: ...
def create_module_container_utilities(module_name: str) -> dict[str, object]: ...
