from collections.abc import Generator, Mapping
from contextlib import contextmanager
from datetime import datetime

__all__ = ["FlextContext"]

class FlextContext:
    @staticmethod
    def get_correlation_id() -> str | None: ...
    @staticmethod
    def set_correlation_id(correlation_id: str) -> None: ...
    @staticmethod
    def generate_correlation_id() -> str: ...
    @staticmethod
    def get_parent_correlation_id() -> str | None: ...
    @staticmethod
    def set_parent_correlation_id(parent_id: str) -> None: ...
    @staticmethod
    @contextmanager
    def new_correlation(
        correlation_id: str | None = None, parent_id: str | None = None
    ) -> Generator[str]: ...
    @staticmethod
    @contextmanager
    def inherit_correlation() -> Generator[str | None]: ...
    @staticmethod
    def get_service_name() -> str | None: ...
    @staticmethod
    def set_service_name(service_name: str) -> None: ...
    @staticmethod
    def get_service_version() -> str | None: ...
    @staticmethod
    def set_service_version(version: str) -> None: ...
    @staticmethod
    @contextmanager
    def service_context(
        service_name: str, version: str | None = None
    ) -> Generator[None]: ...
    @staticmethod
    def get_user_id() -> str | None: ...
    @staticmethod
    def set_user_id(user_id: str) -> None: ...
    @staticmethod
    def get_operation_name() -> str | None: ...
    @staticmethod
    def set_operation_name(operation_name: str) -> None: ...
    @staticmethod
    def get_request_id() -> str | None: ...
    @staticmethod
    def set_request_id(request_id: str) -> None: ...
    @staticmethod
    @contextmanager
    def request_context(
        *,
        user_id: str | None = None,
        operation_name: str | None = None,
        request_id: str | None = None,
        metadata: dict[str, object] | None = None,
    ) -> Generator[None]: ...
    @staticmethod
    def get_operation_start_time() -> datetime | None: ...
    @staticmethod
    def set_operation_start_time(start_time: datetime | None = None) -> None: ...
    @staticmethod
    def get_operation_metadata() -> dict[str, object] | None: ...
    @staticmethod
    def set_operation_metadata(metadata: dict[str, object]) -> None: ...
    @staticmethod
    def add_operation_metadata(key: str, value: object) -> None: ...
    @staticmethod
    @contextmanager
    def timed_operation(
        operation_name: str | None = None,
    ) -> Generator[dict[str, object]]: ...
    @staticmethod
    def get_full_context() -> dict[str, object]: ...
    @staticmethod
    def get_correlation_context() -> dict[str, str]: ...
    @staticmethod
    def set_from_context(context: Mapping[str, object]) -> None: ...
    @staticmethod
    def clear_context() -> None: ...
    @staticmethod
    def ensure_correlation_id() -> str: ...
    @staticmethod
    def has_correlation_id() -> bool: ...
    @staticmethod
    def get_context_summary() -> str: ...
