from abc import ABC, abstractmethod
from typing import Generic, TypeVar

from _typeshed import Incomplete

from flext_core.commands import FlextCommands
from flext_core.result import FlextResult

__all__ = [
    "FlextAbstractHandler",
    "FlextAbstractHandlerChain",
    "FlextAbstractHandlerRegistry",
    "FlextAbstractMetricsHandler",
    "FlextAuthorizingHandler",
    "FlextBaseHandler",
    "FlextCommandHandler",
    "FlextEventHandler",
    "FlextHandlerChain",
    "FlextHandlerRegistry",
    "FlextHandlers",
    "FlextMetricsHandler",
    "FlextQueryHandler",
    "FlextValidatingHandler",
    "HandlersFacade",
]

TInput = TypeVar("TInput")
TOutput = TypeVar("TOutput")

class FlextAbstractHandler[TInput, TOutput](ABC):
    @property
    @abstractmethod
    def handler_name(self) -> str: ...
    @abstractmethod
    def handle(self, request: TInput) -> FlextResult[TOutput]: ...
    @abstractmethod
    def can_handle(self, message_type: object) -> bool: ...

class FlextAbstractHandlerChain[TInput, TOutput](ABC):
    @property
    def handler_name(self) -> str: ...
    @abstractmethod
    def handle(self, request: TInput) -> FlextResult[TOutput]: ...

class FlextAbstractHandlerRegistry[TInput](ABC):
    @abstractmethod
    def register(self, name: str, handler: TInput) -> FlextResult[TInput]: ...
    @abstractmethod
    def get_all_handlers(self) -> dict[str, TInput]: ...

class FlextAbstractMetricsHandler(FlextAbstractHandler[TInput, TOutput], ABC):
    @abstractmethod
    def collect_metrics(self) -> dict[str, object]: ...

class FlextAbstractValidatingHandler(FlextAbstractHandler[TInput, TOutput], ABC):
    @abstractmethod
    def validate_request(self, request: TInput) -> FlextResult[None]: ...

TQuery = TypeVar("TQuery")
TQueryResult = TypeVar("TQueryResult")

class FlextBaseHandler(FlextAbstractHandler[object, object]):
    def __init__(self, name: str | None = None) -> None: ...
    @property
    def handler_name(self) -> str: ...
    def handle(self, request: object) -> FlextResult[object]: ...
    def process_request(self, request: object) -> FlextResult[object]: ...
    def validate_request(self, request: object) -> FlextResult[None]: ...
    def can_handle(self, _message_type: object) -> bool: ...
    def pre_process(self, message: object) -> FlextResult[None]: ...
    def process_message(self, message: object) -> FlextResult[object]: ...
    @staticmethod
    def post_process(
        _message: object, _result: FlextResult[object]
    ) -> FlextResult[None]: ...
    def get_handler_metadata(self) -> dict[str, object]: ...

class FlextValidatingHandler(
    FlextBaseHandler, FlextAbstractValidatingHandler[object, object]
):
    def __init__(self, name: str | None = None) -> None: ...
    @property
    def handler_name(self) -> str: ...
    def handle(self, request: object) -> FlextResult[object]: ...
    def validate_request(self, request: object) -> FlextResult[None]: ...
    def can_handle(self, request: object) -> bool: ...
    def validate_input(self, request: object) -> FlextResult[None]: ...
    def validate_output(self, response: object) -> FlextResult[object]: ...
    def get_validation_rules(self) -> list[object]: ...
    @staticmethod
    def validate_message(message: object) -> FlextResult[None]: ...
    @staticmethod
    def process_message(message: object) -> FlextResult[object]: ...
    def validate(self, message: object) -> FlextResult[object]: ...
    @staticmethod
    def post_process(
        message: object, _result: FlextResult[object]
    ) -> FlextResult[None]: ...
    def get_handler_metadata(self) -> dict[str, object]: ...

class FlextAuthorizingHandler(FlextBaseHandler):
    required_permissions: Incomplete
    def __init__(
        self, name: str | None = None, required_permissions: list[str] | None = None
    ) -> None: ...
    def authorize(
        self, message: object, context: dict[str, object]
    ) -> FlextResult[bool]: ...
    def authorize_message(
        self, message: object, context: dict[str, object]
    ) -> FlextResult[bool]: ...
    def pre_process(self, message: object) -> FlextResult[None]: ...
    def get_handler_metadata(self) -> dict[str, object]: ...

class FlextEventHandler(FlextBaseHandler):
    def process_event(self, event: dict[str, object]) -> FlextResult[None]: ...
    @staticmethod
    def can_process(event_type: str | None = None) -> bool: ...
    @staticmethod
    def handle_event_type(
        event: dict[str, object], event_type: str | None = None
    ) -> FlextResult[None]: ...

class FlextMetricsHandler(
    FlextBaseHandler, FlextAbstractMetricsHandler[object, object]
):
    metrics: dict[str, object]
    def __init__(self, name: str | None = None) -> None: ...
    @property
    def handler_name(self) -> str: ...
    @property
    def name(self) -> str: ...
    def handle(self, request: object) -> FlextResult[object]: ...
    def validate_request(self, request: object) -> FlextResult[None]: ...
    def can_handle(self, request: object) -> bool: ...
    def start_metrics(self, request: object) -> None: ...
    def stop_metrics(self, request: object, response: object) -> None: ...
    def get_metrics(self) -> dict[str, object]: ...
    def clear_metrics(self) -> None: ...
    @staticmethod
    def process_message(message: object) -> FlextResult[object]: ...
    def collect_metrics(self) -> dict[str, object]: ...
    def collect_operation_metrics(
        self, operation: str, duration: float
    ) -> FlextResult[None]: ...
    def get_metrics_summary(self) -> dict[str, object]: ...
    @staticmethod
    def post_process(
        message: object, result: FlextResult[object]
    ) -> FlextResult[None]: ...
    def get_handler_metadata(self) -> dict[str, object]: ...

class FlextHandlerRegistry(
    FlextAbstractHandlerRegistry[FlextAbstractHandler[object, object]]
):
    registry: dict[str, FlextAbstractHandler[object, object]]
    def __init__(self) -> None: ...
    def register_handler(
        self, name: str, handler: FlextAbstractHandler[object, object]
    ) -> FlextResult[None]: ...
    def get_handler(
        self, name: str
    ) -> FlextResult[FlextAbstractHandler[object, object]]: ...
    def register(
        self,
        name_or_handler: str | FlextAbstractHandler[object, object],
        handler: FlextAbstractHandler[object, object] | None = None,
    ) -> FlextResult[FlextAbstractHandler[object, object]]: ...
    def get_handlers_for_type(
        self, message_type: type
    ) -> list[FlextAbstractHandler[object, object]]: ...
    def register_for_type(
        self,
        message_type: type,
        name: str,
        handler: FlextAbstractHandler[object, object],
    ) -> FlextResult[None]: ...
    def get_handler_for_type(
        self, message_type: type
    ) -> FlextResult[FlextAbstractHandler[object, object]]: ...
    def unregister_handler(self, name: str) -> bool: ...
    def get_all_handlers(self) -> dict[str, FlextAbstractHandler[object, object]]: ...
    def clear_handlers(self) -> None: ...
    def clear(self) -> None: ...
    def get_handlers(self) -> list[FlextAbstractHandler[object, object]]: ...

class FlextHandlerChain(FlextBaseHandler, FlextAbstractHandlerChain[object, object]):
    handlers: list[FlextAbstractHandler[object, object]]
    def __init__(
        self, handlers: list[FlextAbstractHandler[object, object]] | None = None
    ) -> None: ...
    @property
    def handler_name(self) -> str: ...
    def add_handler(self, handler: FlextAbstractHandler[object, object]) -> None: ...
    def remove_handler(self, handler: FlextAbstractHandler[object, object]) -> bool: ...
    def handle_request(self, request: object) -> FlextResult[object]: ...
    def get_handlers(self) -> list[FlextAbstractHandler[object, object]]: ...
    def process_chain(self, message: object) -> FlextResult[object]: ...
    def handle(self, message: object) -> FlextResult[object]: ...
    def can_handle(self, message_type: object) -> bool: ...
    def process(self, message: object) -> FlextResult[object]: ...
    def process_all(self, messages: list[object]) -> FlextResult[list[object]]: ...

class FlextCommandHandler(FlextCommands.Handler[TInput, TOutput], ABC):
    def __init__(
        self,
        handler_name: str | None = None,
        *,
        validator: object | None = None,
        authorizer: object | None = None,
        metrics_collector: object | None = None,
    ) -> None: ...
    def validate(self, message: object) -> FlextResult[object]: ...
    @abstractmethod
    def handle_command(self, command: TInput) -> FlextResult[TOutput]: ...
    def handle(self, command: TInput) -> FlextResult[TOutput]: ...
    def handle_with_hooks(self, command: TInput) -> FlextResult[TOutput]: ...
    def process_request(self, command: TInput) -> FlextResult[TOutput]: ...
    def validate_command(self, message: object) -> FlextResult[None]: ...
    def get_metrics(self) -> dict[str, object]: ...

class FlextQueryHandler(FlextCommands.QueryHandler[TInput, TOutput], ABC):
    def __init__(
        self, handler_name: str | None = None, authorizer: object | None = None
    ) -> None: ...
    @abstractmethod
    def handle_query(self, query: TInput) -> FlextResult[TOutput]: ...
    def handle(self, query: TInput) -> FlextResult[TOutput]: ...
    def authorize_query(self, query: object) -> FlextResult[None]: ...
    def pre_handle(self, query: object) -> FlextResult[None]: ...
    def process_request(self, query: TInput) -> FlextResult[TOutput]: ...
    @staticmethod
    def validate_message(message: object) -> FlextResult[None]: ...

class HandlersFacade:
    class CommandHandler(FlextCommandHandler[object, object], ABC): ...

    class QueryHandler(Generic[TQuery, TQueryResult]):
        def __init__(
            self, handler_name: str | None = None, authorizer: object | None = None
        ) -> None: ...
        def handle(self, query: TQuery) -> FlextResult[TQueryResult]: ...
        def authorize_query(self, query: object) -> FlextResult[None]: ...
        def pre_handle(self, query: object) -> FlextResult[None]: ...
        @staticmethod
        def validate_message(message: object) -> FlextResult[None]: ...

    class Handler(FlextCommands.Handler[object, object], ABC): ...
    class EventHandler(FlextEventHandler): ...

    @staticmethod
    def flext_create_chain(
        handlers: list[FlextAbstractHandler[object, object]] | None = None,
    ) -> FlextHandlerChain: ...
    @staticmethod
    def create_registry() -> FlextHandlerRegistry: ...
    @staticmethod
    def register_for_type(
        registry: FlextHandlerRegistry,
        message_type: type,
        name: str,
        handler: FlextAbstractHandler[object, object],
    ) -> FlextResult[None]: ...
    @staticmethod
    def get_handler_for_type(
        registry: FlextHandlerRegistry, message_type: type
    ) -> FlextResult[FlextAbstractHandler[object, object]]: ...
    @staticmethod
    def get_metrics(handler: object) -> dict[str, object]: ...
    class PipelineBehavior:
        next_behavior: object | None
        def __init__(self) -> None: ...
        @staticmethod
        def handle(message: object, next_handler: object) -> FlextResult[object]: ...
        def set_next(self, behavior: object) -> None: ...

    class CommandBus:
        def __init__(self) -> None: ...
        def register(
            self, command_type: type, handler: object
        ) -> FlextResult[None]: ...
        def send(self, command: object) -> FlextResult[object]: ...
        def get_metrics(self) -> dict[str, object]: ...

    class QueryBus:
        def __init__(self) -> None: ...
        def register(self, query_type: type, handler: object) -> FlextResult[None]: ...
        def send(self, query: object) -> FlextResult[object]: ...
        def get_metrics(self) -> dict[str, object]: ...

class _ConcreteCommandHandler(FlextCommandHandler[object, object]):
    def handle_command(self, command: object) -> FlextResult[object]: ...

class _ConcreteQueryHandler(FlextQueryHandler[TQuery, TQueryResult]):
    def handle_query(self, query: TQuery) -> FlextResult[TQueryResult]: ...

FlextHandlers = FlextBaseHandler
