from typing import TypedDict

from flext_core.constants import FlextConstants, FlextLogLevel as FlextLogLevel
from flext_core.typings import TAnyDict, TContextDict, TLogMessage

__all__ = [
    "FlextLogContext",
    "FlextLogContextManager",
    "FlextLogEntry",
    "FlextLogLevel",
    "FlextLogger",
    "FlextLoggerFactory",
    "create_log_context",
    "flext_get_logger",
    "get_logger",
    "setup_custom_trace_level",
]

Platform = FlextConstants.Platform

class FlextLogContext(TypedDict, total=False):
    user_id: str
    request_id: str
    session_id: str
    operation: str
    transaction_id: str
    tenant_id: str
    customer_id: str
    order_id: str
    duration_ms: float
    memory_mb: float
    cpu_percent: float
    error_code: str
    error_type: str
    stack_trace: str

class FlextLogEntry(TypedDict):
    timestamp: str
    level: str
    logger: str
    message: str
    method: str
    context: TAnyDict

def setup_custom_trace_level() -> None: ...

class FlextLogger:
    def __init__(self, name: str, level: str = "INFO") -> None: ...
    def set_level(self, level: str) -> None: ...
    def get_context(self) -> TContextDict: ...
    def set_context(self, context: TContextDict) -> None: ...
    def clear_context(self) -> None: ...
    def with_context(self, **context: object) -> FlextLogger: ...
    def trace(self, message: TLogMessage, *args: object, **context: object) -> None: ...
    def debug(self, message: TLogMessage, *args: object, **context: object) -> None: ...
    def info(self, message: TLogMessage, *args: object, **context: object) -> None: ...
    def warning(
        self, message: TLogMessage, *args: object, **context: object
    ) -> None: ...
    def error(self, message: TLogMessage, *args: object, **context: object) -> None: ...
    def critical(
        self, message: TLogMessage, *args: object, **context: object
    ) -> None: ...
    def exception(
        self, message: TLogMessage, *args: object, **context: object
    ) -> None: ...
    @classmethod
    def get_logger(cls, name: str, _level: str = "INFO") -> object: ...
    def bind(self, **context: object) -> FlextLogger: ...
    @classmethod
    def configure(
        cls,
        *,
        log_level: FlextLogLevel | None = None,
        _log_level: FlextLogLevel | None = None,
        json_output: bool = False,
        add_timestamp: bool = True,
        add_caller: bool = False,
    ) -> None: ...
    @classmethod
    def get_base_logger(cls, name: str, *, _level: str = "INFO") -> object: ...
    @classmethod
    def bind_context(cls, **context: object) -> object: ...
    @classmethod
    def with_performance_tracking(cls, name: str) -> object: ...
    @classmethod
    def flext_get_logger(cls, name: str) -> object: ...

class FlextLoggerFactory:
    @classmethod
    def get_logger(cls, name: str | None, level: str = "INFO") -> FlextLogger: ...
    @classmethod
    def set_global_level(cls, level: str) -> None: ...
    @classmethod
    def clear_loggers(cls) -> None: ...
    @staticmethod
    def get_log_store() -> list[FlextLogEntry]: ...
    @staticmethod
    def clear_log_store() -> None: ...
    @staticmethod
    def create_context(
        logger: FlextLogger, **context: object
    ) -> FlextLogContextManager: ...

class FlextLogContextManager:
    def __init__(self, logger: FlextLogger, **context: object) -> None: ...
    def __enter__(self) -> FlextLogger: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...

class _ContextManagerLogger:
    def __init__(self, logger: object) -> None: ...
    def __enter__(self) -> object: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...

def get_logger(name: str = "flext", level: str = "INFO") -> FlextLogger: ...
def create_log_context(
    logger: FlextLogger | str | None = None, **context: object
) -> FlextLogContextManager: ...
def flext_get_logger(name: str = "flext") -> FlextLogger: ...
