from abc import ABC, abstractmethod

from flext_core.protocols import FlextLoggerProtocol
from flext_core.result import FlextResult
from flext_core.typings import TEntityId

__all__ = [
    "FlextAbstractEntityMixin",
    "FlextAbstractIdentifiableMixin",
    "FlextAbstractLoggableMixin",
    "FlextAbstractMixin",
    "FlextAbstractSerializableMixin",
    "FlextAbstractServiceMixin",
    "FlextAbstractTimestampMixin",
    "FlextAbstractValidatableMixin",
    "FlextCacheableMixin",
    "FlextCommandMixin",
    "FlextComparableMixin",
    "FlextDataMixin",
    "FlextEntityMixin",
    "FlextFullMixin",
    "FlextIdentifiableMixin",
    "FlextLoggableMixin",
    "FlextSerializableMixin",
    "FlextServiceMixin",
    "FlextTimestampMixin",
    "FlextTimingMixin",
    "FlextValidatableMixin",
    "FlextValidators",
    "FlextValueObjectMixin",
    "LegacyCompatibleCacheableMixin",
    "LegacyCompatibleCommandMixin",
    "LegacyCompatibleComparableMixin",
    "LegacyCompatibleDataMixin",
    "LegacyCompatibleEntityMixin",
    "LegacyCompatibleFullMixin",
    "LegacyCompatibleIdentifiableMixin",
    "LegacyCompatibleLoggableMixin",
    "LegacyCompatibleSerializableMixin",
    "LegacyCompatibleServiceMixin",
    "LegacyCompatibleTimestampMixin",
    "LegacyCompatibleTimingMixin",
    "LegacyCompatibleValidatableMixin",
    "LegacyCompatibleValueObjectMixin",
]

class FlextAbstractMixin(ABC):
    @abstractmethod
    def mixin_setup(self) -> None: ...
    service_name: str | None
    @property
    def id(self) -> TEntityId | None: ...
    def __init__(self, *args: object, **kwargs: object) -> None: ...

class FlextAbstractTimestampMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def update_timestamp(self) -> None: ...
    @abstractmethod
    def get_timestamp(self) -> float: ...
    def mixin_setup(self) -> None: ...

class FlextAbstractIdentifiableMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def get_id(self) -> TEntityId: ...
    @abstractmethod
    def set_id(self, entity_id: TEntityId) -> None: ...
    def mixin_setup(self) -> None: ...

class FlextAbstractLoggableMixin(FlextAbstractMixin, ABC):
    @property
    @abstractmethod
    def logger(self) -> FlextLoggerProtocol: ...
    @abstractmethod
    def log_operation(self, operation: str, **kwargs: object) -> None: ...
    def mixin_setup(self) -> None: ...

class FlextAbstractValidatableMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def validate(self) -> FlextResult[None]: ...
    @property
    @abstractmethod
    def is_valid(self) -> bool: ...
    def mixin_setup(self) -> None: ...
    def clear_validation_errors(self) -> None: ...
    def add_validation_error(self, message: str) -> None: ...
    @property
    def validation_errors(self) -> list[str]: ...
    def mark_valid(self) -> None: ...

class FlextAbstractSerializableMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def to_dict(self) -> dict[str, object]: ...
    @abstractmethod
    def load_from_dict(self, data: dict[str, object]) -> None: ...
    def mixin_setup(self) -> None: ...

class FlextAbstractEntityMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def get_domain_events(self) -> list[object]: ...
    @abstractmethod
    def clear_domain_events(self) -> None: ...
    def mixin_setup(self) -> None: ...

class FlextAbstractServiceMixin(FlextAbstractMixin, ABC):
    @abstractmethod
    def get_service_name(self) -> str: ...
    @abstractmethod
    def initialize_service(self) -> FlextResult[None]: ...
    def mixin_setup(self) -> None: ...

class FlextValidators:
    @staticmethod
    def is_non_empty_string(value: object) -> bool: ...

class FlextTimestampMixin(FlextAbstractTimestampMixin):
    def mixin_setup(self) -> None: ...
    def update_timestamp(self) -> None: ...
    def get_timestamp(self) -> float: ...
    def get_age_seconds(self) -> float: ...
    @property
    def created_at(self) -> float: ...
    @property
    def updated_at(self) -> float: ...
    def get_age_in_seconds(self) -> float: ...

class FlextIdentifiableMixin(FlextAbstractIdentifiableMixin):
    def get_id(self) -> TEntityId: ...
    def get_identity(self) -> TEntityId: ...
    @property
    def id(self) -> TEntityId: ...
    @id.setter
    def id(self, value: TEntityId) -> None: ...
    def set_id(self, entity_id: TEntityId) -> None: ...
    def generate_id(self) -> None: ...
    @property
    def entity_id(self) -> TEntityId: ...
    def has_id(self) -> bool: ...

class FlextLoggableMixin(FlextAbstractLoggableMixin):
    @property
    def logger(self) -> FlextLoggerProtocol: ...
    def log_operation(self, operation: str, **kwargs: object) -> None: ...
    def mixin_setup(self) -> None: ...
    def log_info(self, message: str, **kwargs: object) -> None: ...
    def log_error(self, message: str, **kwargs: object) -> None: ...
    def log_debug(self, message: str, **kwargs: object) -> None: ...

class FlextTimingMixin:
    def __init__(self) -> None: ...
    def start_timing(self) -> None: ...
    def stop_timing(self) -> float: ...
    def get_last_elapsed_time(self) -> float: ...
    def get_average_elapsed_time(self) -> float: ...
    def clear_timing_history(self) -> None: ...

class FlextValidatableMixin(FlextAbstractValidatableMixin):
    def validate(self) -> FlextResult[None]: ...
    @property
    def is_valid(self) -> bool: ...
    def clear_validation_errors(self) -> None: ...
    def mixin_setup(self) -> None: ...
    def validate_and_set(self, **kwargs: object) -> None: ...
    def has_validation_errors(self) -> bool: ...

class FlextSerializableMixin(FlextAbstractSerializableMixin):
    def to_dict(self) -> dict[str, object]: ...
    def to_json(self) -> str: ...
    def to_dict_basic(self) -> dict[str, object]: ...
    def load_from_dict(self, data: dict[str, object]) -> None: ...
    def load_from_json(self, json_str: str) -> None: ...
    def mixin_setup(self) -> None: ...

class FlextComparableMixin:
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class FlextCacheableMixin:
    def get_cache_key(self) -> str: ...
    def get_cache_ttl(self) -> int: ...
    def cache_set(self, key: str, value: object) -> None: ...
    def cache_get(self, key: str) -> object | None: ...
    def cache_clear(self) -> None: ...

class FlextEntityMixin(
    FlextTimestampMixin,
    FlextIdentifiableMixin,
    FlextLoggableMixin,
    FlextValidatableMixin,
    FlextSerializableMixin,
):
    def mixin_setup(self) -> None: ...

class FlextValueObjectMixin(
    FlextValidatableMixin, FlextSerializableMixin, FlextComparableMixin
):
    def mixin_setup(self) -> None: ...

class FlextCommandMixin(
    FlextIdentifiableMixin,
    FlextTimestampMixin,
    FlextValidatableMixin,
    FlextSerializableMixin,
):
    def mixin_setup(self) -> None: ...

class FlextServiceMixin(FlextLoggableMixin, FlextValidatableMixin):
    @property
    def id(self) -> TEntityId | None: ...
    def mixin_setup(self) -> None: ...

class FlextDataMixin(
    FlextTimestampMixin, FlextSerializableMixin, FlextValidatableMixin
):
    validate_data: object | None
    def mixin_setup(self) -> None: ...

class FlextFullMixin(
    FlextTimestampMixin,
    FlextIdentifiableMixin,
    FlextLoggableMixin,
    FlextTimingMixin,
    FlextValidatableMixin,
    FlextSerializableMixin,
    FlextComparableMixin,
    FlextCacheableMixin,
):
    def mixin_setup(self) -> None: ...

CompatibleTimestampMixin = FlextTimestampMixin
CompatibleIdentifiableMixin = FlextIdentifiableMixin
CompatibleValidatableMixin = FlextValidatableMixin
CompatibleSerializableMixin = FlextSerializableMixin
CompatibleLoggableMixin = FlextLoggableMixin
CompatibleTimingMixin = FlextTimingMixin
CompatibleComparableMixin = FlextComparableMixin
CompatibleCacheableMixin = FlextCacheableMixin
CompatibleEntityMixin = FlextEntityMixin
CompatibleCommandMixin = FlextCommandMixin
CompatibleDataMixin = FlextDataMixin
CompatibleFullMixin = FlextFullMixin
CompatibleServiceMixin = FlextServiceMixin
CompatibleValueObjectMixin = FlextValueObjectMixin
LegacyCompatibleTimestampMixin = FlextTimestampMixin
LegacyCompatibleIdentifiableMixin = FlextIdentifiableMixin
LegacyCompatibleValidatableMixin = FlextValidatableMixin
LegacyCompatibleSerializableMixin = FlextSerializableMixin
LegacyCompatibleLoggableMixin = FlextLoggableMixin
LegacyCompatibleTimingMixin = FlextTimingMixin
LegacyCompatibleComparableMixin = FlextComparableMixin
LegacyCompatibleCacheableMixin = FlextCacheableMixin
LegacyCompatibleEntityMixin = FlextEntityMixin
LegacyCompatibleCommandMixin = FlextCommandMixin
LegacyCompatibleDataMixin = FlextDataMixin
LegacyCompatibleFullMixin = FlextFullMixin
LegacyCompatibleServiceMixin = FlextServiceMixin
LegacyCompatibleValueObjectMixin = FlextValueObjectMixin
