from collections.abc import Generator
from contextlib import contextmanager

from _typeshed import Incomplete

from flext_core.protocols import (
    FlextLoggerProtocol,
    FlextMetricsProtocol,
    FlextSpanProtocol,
    FlextTracerProtocol,
)
from flext_core.result import FlextResult

__all__ = [
    "ConsoleLogger",
    "FlextConsoleLogger",
    "FlextInMemoryMetrics",
    "FlextMinimalObservability",
    "FlextNoOpSpan",
    "FlextNoOpTracer",
    "FlextSimpleAlerts",
    "FlextSimpleObservability",
    "InMemoryMetrics",
    "MinimalObservability",
    "NoOpTracer",
    "SimpleAlerts",
    "get_console_logger",
    "get_global_observability",
    "get_memory_metrics",
    "get_noop_tracer",
    "get_observability",
    "get_simple_observability",
    "reset_global_observability",
]

GeneratorT = Generator

class FlextConsoleLogger:
    name: Incomplete
    def __init__(self, name: str = "flext-console") -> None: ...
    def trace(self, message: str, **kwargs: object) -> None: ...
    def debug(self, message: str, **kwargs: object) -> None: ...
    def info(self, message: str, **kwargs: object) -> None: ...
    def warning(self, message: str, **kwargs: object) -> None: ...
    def warn(self, message: str, **kwargs: object) -> None: ...
    def error(self, message: str, **kwargs: object) -> None: ...
    def critical(self, message: str, **kwargs: object) -> None: ...
    def fatal(self, message: str, **kwargs: object) -> None: ...
    def exception(
        self, message: str, *, exc_info: bool = True, **kwargs: object
    ) -> None: ...
    def audit(self, message: str, **kwargs: object) -> None: ...

class FlextNoOpSpan:
    def set_tag(self, key: str, value: str) -> None: ...
    def log_event(self, event_name: str, payload: dict[str, object]) -> None: ...
    def finish(self) -> None: ...
    def add_context(self, key: str, value: object) -> None: ...
    def add_error(self, error: Exception) -> None: ...

class FlextNoOpTracer:
    def start_span(self, operation_name: str) -> FlextSpanProtocol: ...
    def inject_context(self, headers: dict[str, str]) -> None: ...
    @contextmanager
    def trace_operation(self, operation_name: str) -> Generator[FlextSpanProtocol]: ...
    @contextmanager
    def business_span(self, operation: str, **kwargs: object) -> Generator[object]: ...
    @contextmanager
    def technical_span(self, operation: str, **kwargs: object) -> Generator[object]: ...
    @contextmanager
    def error_span(self, operation: str, **kwargs: object) -> Generator[object]: ...

class FlextInMemoryMetrics:
    def __init__(self) -> None: ...
    def increment_counter(
        self, name: str, tags: dict[str, str] | None = None
    ) -> None: ...
    def record_gauge(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> None: ...
    def record_histogram(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> None: ...
    def get_counter(self, name: str, tags: dict[str, str] | None = None) -> int: ...
    def get_gauge(
        self, name: str, tags: dict[str, str] | None = None
    ) -> float | None: ...
    def get_histogram(
        self, name: str, tags: dict[str, str] | None = None
    ) -> list[float]: ...
    def increment(
        self, name: str, value: int = 1, tags: dict[str, str] | None = None
    ) -> None: ...
    def gauge(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> None: ...
    def histogram(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> None: ...
    def get_metrics(self) -> dict[str, object]: ...
    def clear_metrics(self) -> None: ...

class FlextSimpleObservability:
    logger: Incomplete
    tracer: Incomplete
    metrics: Incomplete
    def __init__(
        self,
        logger: FlextLoggerProtocol | None = None,
        tracer: FlextTracerProtocol | None = None,
        metrics: FlextMetricsProtocol | None = None,
    ) -> None: ...
    def record_metric(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> FlextResult[None]: ...
    def start_trace(self, operation_name: str) -> FlextResult[str]: ...
    def health_check(self) -> FlextResult[dict[str, object]]: ...

class FlextSimpleAlerts:
    def info(self, message: str, **kwargs: object) -> None: ...
    def warning(self, message: str, **kwargs: object) -> None: ...
    @staticmethod
    def error(message: str, **kwargs: object) -> None: ...
    @staticmethod
    def critical(message: str, **kwargs: object) -> None: ...

class _SimpleHealth:
    @staticmethod
    def health_check() -> dict[str, object]: ...
    @staticmethod
    def ready_check() -> bool: ...
    @staticmethod
    def live_check() -> bool: ...

class FlextMinimalObservability:
    log: Incomplete
    trace: Incomplete
    metrics: Incomplete
    alerts: Incomplete
    health: Incomplete
    def __init__(self) -> None: ...
    def record_metric(
        self, name: str, value: float, tags: dict[str, str] | None = None
    ) -> FlextResult[None]: ...
    def start_trace(self, operation_name: str) -> FlextResult[str]: ...
    def health_check(self) -> FlextResult[dict[str, object]]: ...

def get_console_logger(name: str = "flext-console") -> FlextConsoleLogger: ...
def get_noop_tracer() -> FlextNoOpTracer: ...
def get_memory_metrics() -> FlextInMemoryMetrics: ...
def get_simple_observability(
    logger_name: str = "flext-console",
) -> FlextSimpleObservability: ...
def get_global_observability() -> FlextMinimalObservability: ...
def reset_global_observability() -> None: ...
def get_observability(
    *, log_level: str = "INFO", force_recreate: bool = False
) -> FlextMinimalObservability: ...

ConsoleLogger = FlextConsoleLogger
NoOpTracer = FlextNoOpTracer
InMemoryMetrics = FlextInMemoryMetrics
SimpleAlerts = FlextSimpleAlerts
MinimalObservability = FlextMinimalObservability
