from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Protocol, TypeGuard, TypeVar

from flext_core.result import FlextResult
from flext_core.typings import TAnyDict

__all__ = [
    "FlextBaseFactory",
    "FlextConversions",
    "FlextFormatters",
    "FlextGenerators",
    "FlextGenericFactory",
    "FlextIdGenerator",
    "FlextPerformance",
    "FlextTextProcessor",
    "FlextTimeUtils",
    "FlextTypeGuards",
    "FlextUtilities",
    "FlextUtilityFactory",
    "flext_clear_performance_metrics",
    "flext_get_performance_metrics",
    "flext_record_performance",
    "flext_safe_int_conversion",
    "flext_track_performance",
    "generate_correlation_id",
    "generate_id",
    "generate_iso_timestamp",
    "generate_uuid",
    "is_not_none",
    "safe_call",
    "safe_int_conversion_with_default",
    "truncate",
]

T = TypeVar("T")

class FlextConsole:
    def __init__(self) -> None: ...
    @staticmethod
    def print(*args: object, **kwargs: object) -> None: ...
    def log(self, *args: object, **kwargs: object) -> None: ...

Console = FlextConsole

class FlextDecoratedFunction(Protocol):
    def __call__(self, *args: object, **kwargs: object) -> object: ...

class FlextUtilities:
    SECONDS_PER_MINUTE: int
    SECONDS_PER_HOUR: int
    @classmethod
    def generate_uuid(cls) -> str: ...
    @classmethod
    def generate_id(cls) -> str: ...
    @classmethod
    def generate_timestamp(cls) -> float: ...
    @classmethod
    def generate_iso_timestamp(cls) -> str: ...
    @classmethod
    def generate_correlation_id(cls) -> str: ...
    @classmethod
    def generate_entity_id(cls) -> str: ...
    @classmethod
    def generate_session_id(cls) -> str: ...
    @classmethod
    def truncate(cls, text: str, max_length: int = 100, suffix: str = "...") -> str: ...
    @classmethod
    def handle_cli_main_errors(
        cls, cli_function: Callable[[], None], *, debug_mode: bool = False
    ) -> None: ...
    @classmethod
    def format_duration(cls, seconds: float) -> str: ...
    @classmethod
    def has_attribute(cls, obj: object, attr: str) -> bool: ...
    @classmethod
    def is_instance_of(cls, obj: object, target_type: type) -> bool: ...
    @classmethod
    def safe_call(
        cls, func: Callable[[], T] | Callable[[object], T]
    ) -> FlextResult[T]: ...
    @classmethod
    def is_not_none_guard(cls, value: T | None) -> TypeGuard[T]: ...
    @classmethod
    def safe_int_conversion(
        cls, value: object, default: int | None = None
    ) -> int | None: ...
    @classmethod
    def safe_int_conversion_with_default(cls, value: object, default: int) -> int: ...

class FlextPerformance:
    @staticmethod
    def track_performance(
        category: str,
    ) -> Callable[[FlextDecoratedFunction], FlextDecoratedFunction]: ...
    @staticmethod
    def get_performance_metrics() -> dict[str, TAnyDict]: ...
    @staticmethod
    def clear_performance_metrics() -> None: ...
    @staticmethod
    def record_performance(
        category: str, function_name: str, execution_time: float, *, _success: bool
    ) -> None: ...

class FlextConversions:
    @staticmethod
    def safe_call(func: Callable[[], T] | Callable[[object], T]) -> FlextResult[T]: ...
    @staticmethod
    def is_not_none(value: T | None) -> TypeGuard[T]: ...

class FlextTextProcessor:
    @staticmethod
    def truncate(text: str, max_length: int = 100, suffix: str = "...") -> str: ...
    @staticmethod
    def normalize_whitespace(text: str) -> str: ...
    @staticmethod
    def slugify(text: str) -> str: ...
    @staticmethod
    def mask_sensitive(
        text: str, *, mask_char: str = "*", show_first: int = 2, show_last: int = 2
    ) -> str: ...

class FlextTimeUtils:
    @staticmethod
    def format_duration(seconds: float) -> str: ...
    @staticmethod
    def generate_timestamp() -> float: ...

class FlextIdGenerator:
    @staticmethod
    def generate_id() -> str: ...
    @staticmethod
    def generate_correlation_id() -> str: ...
    @staticmethod
    def generate_entity_id() -> str: ...
    @staticmethod
    def generate_uuid() -> str: ...
    @staticmethod
    def safe_int_conversion(
        value: object, default: int | None = None
    ) -> int | None: ...
    @staticmethod
    def safe_int_conversion_with_default(value: object, default: int) -> int: ...
    @staticmethod
    def generate_timestamp() -> float: ...
    @staticmethod
    def safe_get(
        dictionary: dict[str, object], key: str, default: object = None
    ) -> object: ...
    @staticmethod
    def normalize_whitespace(text: str) -> str: ...
    @staticmethod
    def slugify(text: str) -> str: ...

class FlextTypeGuards:
    @staticmethod
    def has_attribute(obj: object, attr: str) -> bool: ...
    @staticmethod
    def is_instance_of(obj: object, target_type: type) -> bool: ...
    @staticmethod
    def is_list_of(obj: object, item_type: type) -> bool: ...
    @staticmethod
    def is_not_none_guard(value: object | None) -> bool: ...

class FlextGenerators:
    SECONDS_PER_MINUTE: int
    SECONDS_PER_HOUR: int
    @classmethod
    def generate_uuid(cls) -> str: ...
    @classmethod
    def generate_id(cls) -> str: ...
    @classmethod
    def generate_timestamp(cls) -> float: ...
    @classmethod
    def generate_iso_timestamp(cls) -> str: ...
    @classmethod
    def generate_correlation_id(cls) -> str: ...
    @classmethod
    def generate_entity_id(cls) -> str: ...
    @classmethod
    def generate_session_id(cls) -> str: ...
    @classmethod
    def format_duration(cls, seconds: float) -> str: ...

class FlextFormatters:
    @staticmethod
    def truncate(text: str, max_length: int = 100, suffix: str = "...") -> str: ...
    @staticmethod
    def format_duration(seconds: float) -> str: ...

class FlextBaseFactory[T](ABC):
    @abstractmethod
    def create(self, **kwargs: object) -> FlextResult[T]: ...

class FlextGenericFactory(FlextBaseFactory[object]):
    def __init__(self, target_type: type[object]) -> None: ...
    def create(self, **kwargs: object) -> FlextResult[object]: ...

class FlextUtilityFactory:
    def __init__(self) -> None: ...
    @staticmethod
    def create_generator() -> FlextGenerators: ...
    @staticmethod
    def create_formatter() -> FlextFormatters: ...
    @staticmethod
    def create_converter() -> FlextConversions: ...
    @staticmethod
    def create_performance_tracker() -> FlextPerformance: ...
    @staticmethod
    def create_text_processor() -> FlextTextProcessor: ...

def flext_safe_int_conversion(
    value: object, default: int | None = None
) -> int | None: ...
def generate_correlation_id() -> str: ...
def safe_int_conversion_with_default(value: object, default: int) -> int: ...
def flext_clear_performance_metrics() -> None: ...
def generate_id() -> str: ...
def generate_uuid() -> str: ...
def is_not_none(value: object) -> bool: ...
def safe_call(func: Callable[[], T] | Callable[[object], T]) -> FlextResult[T]: ...
def truncate(text: str, max_length: int = 100, suffix: str = "...") -> str: ...
def flext_get_performance_metrics() -> dict[str, TAnyDict]: ...
def flext_record_performance(
    category: str,
    function_name: str,
    execution_time: float,
    *,
    success: bool | None = None,
    _success: bool | None = None,
) -> None: ...
def flext_track_performance(
    category: str,
) -> Callable[[FlextDecoratedFunction], FlextDecoratedFunction]: ...
def generate_iso_timestamp() -> str: ...
