"""Template engine service for text rendering.

Consolidates shared text templates used by infrastructure scripts
into a service class with FlextResult error handling.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from flext_core.result import FlextResult, r


class TemplateEngine:
    """Infrastructure service for text template rendering.

    Centralizes template constants and provides safe rendering
    with FlextResult error handling.
    """

    TOC_START: str = "<!-- TOC START -->"
    """Markdown comment marking the start of a table of contents."""

    TOC_END: str = "<!-- TOC END -->"
    """Markdown comment marking the end of a table of contents."""

    GENERATED_HEADER: str = "<!-- Generated from {source} for {project}. -->"
    """Template for generated file header with source and project context."""

    GENERATED_SHELL_HEADER: str = "# Generated by {source} - DO NOT EDIT\n"
    """Template for shell/YAML generated file headers."""

    SSOT_HEADER: str = "<!-- Source of truth: workspace docs/guides/. -->"
    """Markdown comment indicating source of truth location."""

    STATUS_LINE: str = "PROJECT={project} PHASE={phase} RESULT={result} REASON={reason}"
    """Template for status line output."""

    def render(
        self,
        template: str,
        **kwargs: str,
    ) -> FlextResult[str]:
        """Render a template string with keyword arguments.

        Args:
            template: Template string with {key} placeholders.
            **kwargs: Values to substitute into the template.

        Returns:
            FlextResult[str] with the rendered string.

        """
        try:
            rendered = template.format(**kwargs)
            return r[str].ok(rendered)
        except KeyError as exc:
            return r[str].fail(f"missing template key: {exc}")
        except (IndexError, ValueError) as exc:
            return r[str].fail(f"template render error: {exc}")

    def render_generated_header(
        self,
        source: str,
        project: str,
    ) -> FlextResult[str]:
        """Render a generated file header.

        Args:
            source: Source script that generated the file.
            project: Project the file was generated for.

        Returns:
            FlextResult[str] with the rendered header.

        """
        return self.render(
            self.GENERATED_HEADER,
            source=source,
            project=project,
        )

    def render_status_line(
        self,
        project: str,
        phase: str,
        result: str,
        reason: str,
    ) -> FlextResult[str]:
        """Render a status line.

        Args:
            project: Project name.
            phase: Execution phase.
            result: Result status (PASS/FAIL).
            reason: Human-readable reason.

        Returns:
            FlextResult[str] with the rendered status line.

        """
        return self.render(
            self.STATUS_LINE,
            project=project,
            phase=phase,
            result=result,
            reason=reason,
        )


__all__ = ["TemplateEngine"]
