# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Unit package."""

from __future__ import annotations

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

_LAZY_IMPORTS = merge_lazy_imports(
    (
        "tests.unit._models",
        "tests.unit._utilities",
        "tests.unit.contracts",
        "tests.unit.flext_tests",
    ),
    {
        "TestsFlextUnitProtocols": ("tests.unit.protocols", "TestsFlextUnitProtocols"),
        "_models": "tests.unit._models",
        "_utilities": "tests.unit._utilities",
        "contracts": "tests.unit.contracts",
        "flext_tests": "tests.unit.flext_tests",
        "p": ("tests.unit.protocols", "p"),
        "protocols": "tests.unit.protocols",
        "test_args_coverage_100": "tests.unit.test_args_coverage_100",
        "test_beartype_engine": "tests.unit.test_beartype_engine",
        "test_collection_utilities_coverage_100": "tests.unit.test_collection_utilities_coverage_100",
        "test_collections_coverage_100": "tests.unit.test_collections_coverage_100",
        "test_config": "tests.unit.test_config",
        "test_constants_new": "tests.unit.test_constants_new",
        "test_container": "tests.unit.test_container",
        "test_container_full_coverage": "tests.unit.test_container_full_coverage",
        "test_context": "tests.unit.test_context",
        "test_context_coverage_100": "tests.unit.test_context_coverage_100",
        "test_context_full_coverage": "tests.unit.test_context_full_coverage",
        "test_coverage_context": "tests.unit.test_coverage_context",
        "test_coverage_exceptions": "tests.unit.test_coverage_exceptions",
        "test_coverage_loggings": "tests.unit.test_coverage_loggings",
        "test_coverage_models": "tests.unit.test_coverage_models",
        "test_coverage_utilities": "tests.unit.test_coverage_utilities",
        "test_decorators": "tests.unit.test_decorators",
        "test_decorators_discovery_full_coverage": "tests.unit.test_decorators_discovery_full_coverage",
        "test_decorators_full_coverage": "tests.unit.test_decorators_full_coverage",
        "test_deprecation_warnings": "tests.unit.test_deprecation_warnings",
        "test_di_incremental": "tests.unit.test_di_incremental",
        "test_di_services_access": "tests.unit.test_di_services_access",
        "test_dispatcher_di": "tests.unit.test_dispatcher_di",
        "test_dispatcher_full_coverage": "tests.unit.test_dispatcher_full_coverage",
        "test_dispatcher_minimal": "tests.unit.test_dispatcher_minimal",
        "test_dispatcher_reliability": "tests.unit.test_dispatcher_reliability",
        "test_dispatcher_timeout_coverage_100": "tests.unit.test_dispatcher_timeout_coverage_100",
        "test_enforcement": "tests.unit.test_enforcement",
        "test_entity_coverage": "tests.unit.test_entity_coverage",
        "test_enum_utilities_coverage_100": "tests.unit.test_enum_utilities_coverage_100",
        "test_exceptions": "tests.unit.test_exceptions",
        "test_handler_decorator_discovery": "tests.unit.test_handler_decorator_discovery",
        "test_handlers": "tests.unit.test_handlers",
        "test_handlers_full_coverage": "tests.unit.test_handlers_full_coverage",
        "test_lazy_exports": "tests.unit.test_lazy_exports",
        "test_loggings_error_paths_coverage": "tests.unit.test_loggings_error_paths_coverage",
        "test_loggings_full_coverage": "tests.unit.test_loggings_full_coverage",
        "test_loggings_strict_returns": "tests.unit.test_loggings_strict_returns",
        "test_mixins": "tests.unit.test_mixins",
        "test_mixins_full_coverage": "tests.unit.test_mixins_full_coverage",
        "test_models": "tests.unit.test_models",
        "test_models_base_full_coverage": "tests.unit.test_models_base_full_coverage",
        "test_models_container": "tests.unit.test_models_container",
        "test_models_context_full_coverage": "tests.unit.test_models_context_full_coverage",
        "test_models_cqrs_full_coverage": "tests.unit.test_models_cqrs_full_coverage",
        "test_models_entity_full_coverage": "tests.unit.test_models_entity_full_coverage",
        "test_models_generic_full_coverage": "tests.unit.test_models_generic_full_coverage",
        "test_protocols_new": "tests.unit.test_protocols_new",
        "test_registry": "tests.unit.test_registry",
        "test_registry_full_coverage": "tests.unit.test_registry_full_coverage",
        "test_result": "tests.unit.test_result",
        "test_result_additional": "tests.unit.test_result_additional",
        "test_result_coverage_100": "tests.unit.test_result_coverage_100",
        "test_result_exception_carrying": "tests.unit.test_result_exception_carrying",
        "test_result_full_coverage": "tests.unit.test_result_full_coverage",
        "test_runtime": "tests.unit.test_runtime",
        "test_runtime_coverage_100": "tests.unit.test_runtime_coverage_100",
        "test_runtime_full_coverage": "tests.unit.test_runtime_full_coverage",
        "test_service": "tests.unit.test_service",
        "test_service_additional": "tests.unit.test_service_additional",
        "test_service_bootstrap": "tests.unit.test_service_bootstrap",
        "test_service_coverage_100": "tests.unit.test_service_coverage_100",
        "test_settings_coverage": "tests.unit.test_settings_coverage",
        "test_typings_full_coverage": "tests.unit.test_typings_full_coverage",
        "test_typings_new": "tests.unit.test_typings_new",
        "test_utilities": "tests.unit.test_utilities",
        "test_utilities_cache_coverage_100": "tests.unit.test_utilities_cache_coverage_100",
        "test_utilities_collection_coverage_100": "tests.unit.test_utilities_collection_coverage_100",
        "test_utilities_collection_full_coverage": "tests.unit.test_utilities_collection_full_coverage",
        "test_utilities_configuration_coverage_100": "tests.unit.test_utilities_configuration_coverage_100",
        "test_utilities_configuration_full_coverage": "tests.unit.test_utilities_configuration_full_coverage",
        "test_utilities_context_full_coverage": "tests.unit.test_utilities_context_full_coverage",
        "test_utilities_coverage": "tests.unit.test_utilities_coverage",
        "test_utilities_data_mapper": "tests.unit.test_utilities_data_mapper",
        "test_utilities_domain": "tests.unit.test_utilities_domain",
        "test_utilities_domain_full_coverage": "tests.unit.test_utilities_domain_full_coverage",
        "test_utilities_enum_full_coverage": "tests.unit.test_utilities_enum_full_coverage",
        "test_utilities_generators_full_coverage": "tests.unit.test_utilities_generators_full_coverage",
        "test_utilities_guards_full_coverage": "tests.unit.test_utilities_guards_full_coverage",
        "test_utilities_mapper_coverage_100": "tests.unit.test_utilities_mapper_coverage_100",
        "test_utilities_mapper_full_coverage": "tests.unit.test_utilities_mapper_full_coverage",
        "test_utilities_parser_full_coverage": "tests.unit.test_utilities_parser_full_coverage",
        "test_utilities_reliability": "tests.unit.test_utilities_reliability",
        "test_utilities_text_full_coverage": "tests.unit.test_utilities_text_full_coverage",
        "test_utilities_type_checker_coverage_100": "tests.unit.test_utilities_type_checker_coverage_100",
        "test_utilities_type_guards_coverage_100": "tests.unit.test_utilities_type_guards_coverage_100",
        "test_version": "tests.unit.test_version",
        "typings": "tests.unit.typings",
    },
)
_ = _LAZY_IMPORTS.pop("cleanup_submodule_namespace", None)
_ = _LAZY_IMPORTS.pop("install_lazy_exports", None)
_ = _LAZY_IMPORTS.pop("lazy_getattr", None)
_ = _LAZY_IMPORTS.pop("logger", None)
_ = _LAZY_IMPORTS.pop("merge_lazy_imports", None)
_ = _LAZY_IMPORTS.pop("output", None)
_ = _LAZY_IMPORTS.pop("output_reporting", None)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
