# AUTO-GENERATED FILE — Regenerate with: make gen
"""Unit package."""

from __future__ import annotations

from flext_core.lazy import (
    build_lazy_import_map,
    install_lazy_exports,
    merge_lazy_imports,
)

_LAZY_IMPORTS = merge_lazy_imports(
    (
        "._enforcement_integration_fixtures",
        "._models",
        "._utilities",
    ),
    build_lazy_import_map(
        {
            "._enforcement_integration_fixtures.bad_module": (
                "TestsFlextCoreBadAccessors",
                "TestsFlextCoreBadAnyField",
                "TestsFlextCoreBadBareCollection",
                "TestsFlextCoreBadConstants",
                "TestsFlextCoreBadFrozen",
                "TestsFlextCoreBadInlineUnion",
                "TestsFlextCoreBadMissingDesc",
                "TestsFlextCoreBadMutableDefault",
                "TestsFlextCoreBadWorkerSettings",
            ),
            "._enforcement_integration_fixtures.clean_module": (
                "TestsFlextCoreCleanConstants",
                "TestsFlextCoreCleanModels",
                "TestsFlextCoreCleanProtocols",
            ),
            "._models.test_base": ("TestsFlextCoreModelsBase",),
            "._models.test_cqrs": ("TestsFlextCoreModelsCqrs",),
            "._models.test_entity": ("TestFlextModelsEntity",),
            "._models.test_exception_params": ("TestFlextModelsExceptionParams",),
            "._utilities.test_guards": ("TestFlextUtilitiesGuards",),
            "._utilities.test_mapper": ("TestsFlextCoreUtilitiesMapper",),
            ".base": ("TestsFlextCoreServiceBase",),
            ".test_beartype_engine": (
                "TestAliasContainsAny",
                "TestBeartypeClawCompatibility",
                "TestBeartypeConf",
                "TestContainsAny",
                "TestCountUnionMembers",
                "TestFacadeAccessibility",
                "TestForbiddenCollectionOrigin",
                "TestIsStrNoneUnion",
            ),
            ".test_collections_coverage_100": (
                "TestFlextModelsCollectionsCoverage100",
            ),
            ".test_constants_new": ("TestFlextConstants",),
            ".test_constants_project_metadata": (
                "TestAliasToSuffix",
                "TestManagedPyprojectKeys",
                "TestSpecialNameOverrides",
                "TestTierFacadePrefix",
                "TestUniversalAliasParentSources",
            ),
            ".test_container": ("TestFlextContainer",),
            ".test_container_full_coverage": ("TestContainerFullCoverage",),
            ".test_context": ("TestFlextContext",),
            ".test_context_coverage_100": ("TestContext100Coverage",),
            ".test_context_full_coverage": ("TestContextFullCoverage",),
            ".test_coverage_context": ("TestCoverageContext",),
            ".test_coverage_exceptions": ("TestCoverageExceptions",),
            ".test_coverage_loggings": ("TestCoverageLoggings",),
            ".test_coverage_models": ("TestCoverageModels",),
            ".test_coverage_utilities": ("Testu",),
            ".test_decorators": ("TestFlextDecorators",),
            ".test_decorators_discovery_full_coverage": (
                "TestDecoratorsDiscoveryFullCoverage",
            ),
            ".test_decorators_full_coverage": ("TestDecoratorsFullCoverage",),
            ".test_deprecation_warnings": ("TestDeprecationWarnings",),
            ".test_di_incremental": ("TestDIIncremental",),
            ".test_di_services_access": ("TestDiServicesAccess",),
            ".test_dispatcher_di": ("TestDispatcherDI",),
            ".test_dispatcher_full_coverage": ("TestDispatcherFullCoverage",),
            ".test_dispatcher_minimal": ("TestDispatcherMinimal",),
            ".test_dispatcher_reliability": ("TestDispatcherReliability",),
            ".test_dispatcher_timeout_coverage_100": (
                "TestDispatcherTimeoutCoverage100",
            ),
            ".test_enforcement": (
                "TestAccessorMethodBan",
                "TestBaseModelCoverage",
                "TestClassPrefixScope",
                "TestConstantsLayerRules",
                "TestDetailSubstitution",
                "TestEnforcementMode",
                "TestFalsePositiveSkips",
                "TestFieldRules",
                "TestHasNestedNamespaceViaMro",
                "TestModelClassRules",
                "TestNamespaceInheritance",
                "TestProjectDiscovery",
                "TestProjectPrefixOverrides",
                "TestProtocolsLayerRules",
                "TestReportApi",
                "TestSettingsInheritance",
                "TestTypesLayerRules",
                "TestUtilitiesLayerRules",
            ),
            ".test_enforcement_integration": (
                "TestBadModuleFiresExpectedRules",
                "TestCleanModuleEmitsNothing",
            ),
            ".test_entity_coverage": ("TestEntityCoverageEdgeCases",),
            ".test_enum_utilities_coverage_100": ("TestEnumUtilitiesCoverage",),
            ".test_exceptions": ("TestExceptions",),
            ".test_handler_decorator_discovery": ("TestHandlerDecoratorDiscovery",),
            ".test_handlers": ("TestFlextHandlers",),
            ".test_handlers_full_coverage": ("TestHandlersFullCoverage",),
            ".test_lazy_exports": (
                "TestBuildLazyImportMap",
                "TestInstallLazyExports",
                "TestLazyRuntimeState",
                "TestMergeLazyImports",
            ),
            ".test_loggings_error_paths_coverage": ("TestLoggingsErrorPaths",),
            ".test_loggings_full_coverage": ("TestModule",),
            ".test_loggings_strict_returns": ("TestLoggingsStrictReturns",),
            ".test_mixins": ("TestFlextMixinsNestedClasses",),
            ".test_mixins_full_coverage": ("TestMixinsFullCoverage",),
            ".test_models": ("TestModels",),
            ".test_models_base_full_coverage": ("TestModelsBaseFullCoverage",),
            ".test_models_container": ("TestFlextModelsContainer",),
            ".test_models_context_full_coverage": ("TestModelsContextFullCoverage",),
            ".test_models_cqrs_full_coverage": ("TestModelsCqrsFullCoverage",),
            ".test_models_entity_full_coverage": ("TestModelsEntityFullCoverage",),
            ".test_models_generic_full_coverage": ("TestModelsGenericFullCoverage",),
            ".test_models_project_metadata": (
                "TestNamespaceModel",
                "TestProjectModel",
                "TestToolFlextModel",
            ),
            ".test_protocols_new": ("TestFlextProtocols",),
            ".test_protocols_project_metadata": (
                "TestClassStemDeriverProtocol",
                "TestMetadataReaderProtocol",
                "TestTierFacadeNamerProtocol",
            ),
            ".test_registry": ("TestRegistryDsl",),
            ".test_registry_full_coverage": ("TestRegistryFullCoverage",),
            ".test_result": ("Testr",),
            ".test_result_additional": ("TestResultAdditional",),
            ".test_result_coverage_100": ("TestrCoverage",),
            ".test_result_exception_carrying": ("TestResultExceptionCarrying",),
            ".test_result_full_coverage": ("TestResultFullCoverage",),
            ".test_runtime": ("TestFlextRuntime",),
            ".test_runtime_coverage_100": ("TestRuntimeCoverage100",),
            ".test_runtime_full_coverage": ("TestRuntimeFullCoverage",),
            ".test_service": (
                "FailingService",
                "RaisingValidationService",
                "TestService",
                "UserData",
                "UserService",
                "ValidatingService",
            ),
            ".test_service_additional": ("TestServiceAdditional",),
            ".test_service_bootstrap": ("TestServiceBootstrap",),
            ".test_service_coverage_100": ("TestService100Coverage",),
            ".test_settings": ("TestFlextSettings",),
            ".test_settings_coverage": ("TestFlextSettingsCoverage",),
            ".test_typings_full_coverage": ("TestTypingsFullCoverage",),
            ".test_typings_new": ("TestFlextTypes",),
            ".test_typings_project_metadata": ("test_typings_project_metadata",),
            ".test_utilities_collection_coverage_100": (
                "TestUtilitiesCollectionCoverage",
            ),
            ".test_utilities_collection_full_coverage": (
                "TestUtilitiesCollectionFullCoverage",
            ),
            ".test_utilities_context_full_coverage": (
                "TestUtilitiesContextFullCoverage",
            ),
            ".test_utilities_coverage": ("TestUtilitiesCoverage",),
            ".test_utilities_data_mapper": ("TestUtilitiesDataMapper",),
            ".test_utilities_domain": ("TestuDomain",),
            ".test_utilities_domain_full_coverage": (
                "TestUtilitiesDomainFullCoverage",
            ),
            ".test_utilities_generators_full_coverage": (
                "TestUtilitiesGeneratorsFullCoverage",
            ),
            ".test_utilities_guards_full_coverage": (
                "TestUtilitiesGuardsFullCoverage",
            ),
            ".test_utilities_mapper_coverage_100": (
                "UtilitiesMapperCoverage100Namespace",
            ),
            ".test_utilities_mapper_full_coverage": (
                "BadBool",
                "BadMapping",
                "BadString",
                "ExplodingLenList",
                "TestUtilitiesMapperFullCoverage",
            ),
            ".test_utilities_parser_full_coverage": (
                "TestUtilitiesParserFullCoverage",
            ),
            ".test_utilities_project_metadata": (
                "TestComposeNamespaceConfig",
                "TestDeriveClassStem",
                "TestDerivePackageName",
                "TestDeriveTierFacadeName",
                "TestReadProjectMetadata",
                "TestReadToolFlextConfig",
            ),
            ".test_utilities_reliability": ("TestFlextUtilitiesReliability",),
            ".test_utilities_settings_coverage_100": ("TestFlextUtilitiesSettings",),
            ".test_utilities_settings_full_coverage": (
                "TestUtilitiesSettingsFullCoverage",
            ),
            ".test_utilities_text_full_coverage": ("TestUtilitiesTextFullCoverage",),
            ".test_utilities_type_checker_coverage_100": ("TestuTypeChecker",),
            ".test_utilities_type_guards_coverage_100": (
                "TestUtilitiesTypeGuardsCoverage100",
            ),
            ".test_version": ("TestFlextVersion",),
        },
    ),
    exclude_names=(
        "cleanup_submodule_namespace",
        "install_lazy_exports",
        "lazy_getattr",
        "logger",
        "merge_lazy_imports",
        "output",
        "output_reporting",
    ),
    module_name=__name__,
)


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, publish_all=False)
