"""Tests for FlextInfraWorkflowSyncer and SyncOperation.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import Mock, patch

from flext_core import r
from flext_infra.github.workflows import FlextInfraWorkflowSyncer, SyncOperation


class TestSyncOperation:
    """Test suite for SyncOperation data class."""

    def test_sync_operation_creation(self) -> None:
        """Test creating a SyncOperation instance."""
        op = SyncOperation(
            project="flext-core",
            path=".github/workflows/ci.yml",
            action="create",
            reason="New workflow file",
        )
        assert op.project == "flext-core"
        assert op.path == ".github/workflows/ci.yml"
        assert op.action == "create"
        assert op.reason == "New workflow file"

    def test_sync_operation_frozen(self) -> None:
        """Test that SyncOperation is immutable."""
        assert SyncOperation.model_config.get("frozen") is True


class TestFlextInfraWorkflowSyncer:
    """Test suite for FlextInfraWorkflowSyncer."""

    def test_resolve_source_workflow_absolute_path(self, tmp_path: Path) -> None:
        """Test resolving absolute source workflow path."""
        workflow_file = tmp_path / "source.yml"
        workflow_file.write_text("name: CI")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.resolve_source_workflow(tmp_path, workflow_file)
        assert result.is_success
        assert result.value == workflow_file

    def test_resolve_source_workflow_relative_path(self, tmp_path: Path) -> None:
        """Test resolving relative source workflow path."""
        workflow_file = tmp_path / "source.yml"
        workflow_file.write_text("name: CI")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.resolve_source_workflow(tmp_path, Path("source.yml"))
        assert result.is_success
        assert result.value == workflow_file

    def test_resolve_source_workflow_not_found(self, tmp_path: Path) -> None:
        """Test handling of missing source workflow file."""
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.resolve_source_workflow(tmp_path, Path("nonexistent.yml"))
        assert result.is_failure

    def test_default_initialization(self) -> None:
        """Test syncer initializes with default dependencies."""
        syncer = FlextInfraWorkflowSyncer()
        assert syncer._selector is not None
        assert syncer._json is not None
        assert syncer._templates is not None

    def test_resolve_default_source(self, tmp_path: Path) -> None:
        """Test resolving default source workflow."""
        workflows_dir = tmp_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("name: CI")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.resolve_source_workflow(tmp_path)
        assert result.is_success

    def test_resolve_default_source_missing(self, tmp_path: Path) -> None:
        """Test resolving default source when missing."""
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.resolve_source_workflow(tmp_path)
        assert result.is_failure


class TestRenderTemplate:
    """Test render_template method."""

    def test_adds_header(self, tmp_path: Path) -> None:
        """Test render adds generated header."""
        mock_templates = Mock()
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"
        template = tmp_path / "ci.yml"
        template.write_text("name: CI\n")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=mock_templates
        )
        result = syncer.render_template(template)
        assert result.is_success
        assert result.value.startswith("# GENERATED by")

    def test_already_has_header(self, tmp_path: Path) -> None:
        """Test render with template already having header."""
        mock_templates = Mock()
        header = "# GENERATED by flext_infra.github.workflows\n"
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"
        template = tmp_path / "ci.yml"
        template.write_text(header + "name: CI\n")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=mock_templates
        )
        result = syncer.render_template(template)
        assert result.is_success
        assert result.value.startswith(header)

    def test_read_failure(self, tmp_path: Path) -> None:
        """Test render when file read fails."""
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.render_template(tmp_path / "nonexistent.yml")
        assert result.is_failure


class TestSyncProject:
    """Test sync_project method."""

    def test_update_existing(self, tmp_path: Path) -> None:
        """Test updating existing workflow that differs."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("old content")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="new content",
            apply=True,
        )
        assert result.is_success
        ops = result.value
        assert len(ops) == 1
        assert ops[0].action == "update"
        assert (workflows_dir / "ci.yml").read_text() == "new content"

    def test_noop_same_content(self, tmp_path: Path) -> None:
        """Test noop when content matches."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("same content")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="same content",
        )
        assert result.is_success
        assert result.value[0].action == "noop"

    def test_create_missing(self, tmp_path: Path) -> None:
        """Test creating missing workflow."""
        project = tmp_path / "proj"
        project.mkdir()
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="new content",
            apply=True,
        )
        assert result.is_success
        assert result.value[0].action == "create"
        assert (project / ".github" / "workflows" / "ci.yml").exists()

    def test_create_dry_run(self, tmp_path: Path) -> None:
        """Test create in dry-run mode doesn't write."""
        project = tmp_path / "proj"
        project.mkdir()
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="new content",
            apply=False,
        )
        assert result.is_success
        assert result.value[0].action == "create"
        assert not (project / ".github" / "workflows" / "ci.yml").exists()

    def test_prune_extra_workflows(self, tmp_path: Path) -> None:
        """Test pruning non-canonical workflows."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("content")
        (workflows_dir / "extra.yml").write_text("old")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="content",
            apply=True,
            prune=True,
        )
        assert result.is_success
        actions = [op.action for op in result.value]
        assert "prune" in actions
        assert not (workflows_dir / "extra.yml").exists()

    def test_prune_skips_managed(self, tmp_path: Path) -> None:
        """Test pruning skips managed files."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("content")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="content",
            apply=True,
            prune=True,
        )
        assert result.is_success
        assert all(op.action != "prune" for op in result.value)

    def test_update_dry_run(self, tmp_path: Path) -> None:
        """Test update in dry-run mode doesn't write."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("old content")
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_project(
            project_name="proj",
            project_root=project,
            rendered_template="new content",
            apply=False,
        )
        assert result.is_success
        assert result.value[0].action == "update"
        assert (workflows_dir / "ci.yml").read_text() == "old content"

    def test_sync_project_oserror(self, tmp_path: Path) -> None:
        """Test sync_project handles OSError when writing fails."""
        project = tmp_path / "proj"
        workflows_dir = project / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        # Mock the write_text to raise OSError

        with patch.object(Path, "write_text", side_effect=OSError("Permission denied")):
            result = syncer.sync_project(
                project_name="proj",
                project_root=project,
                rendered_template="new content",
                apply=True,
            )
            assert result.is_failure
            assert "sync error" in result.error


class TestSyncWorkspace:
    """Test sync_workspace method."""

    def test_full_flow(self, tmp_path: Path) -> None:
        """Test full workspace sync flow."""
        mock_selector = Mock()
        mock_json = Mock()
        mock_templates = Mock()
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"

        # Create source workflow
        workflows_dir = tmp_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("name: CI\n")

        # Create project
        proj = Mock()
        proj.name = "my-proj"
        proj.path = tmp_path / "my-proj"
        proj.path.mkdir()
        mock_selector.resolve_projects.return_value = r[list].ok([proj])

        syncer = FlextInfraWorkflowSyncer(
            selector=mock_selector, json_io=mock_json, templates=mock_templates
        )
        result = syncer.sync_workspace(tmp_path, apply=True)
        assert result.is_success

    def test_source_resolution_failure(self, tmp_path: Path) -> None:
        """Test workspace sync with source resolution failure."""
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=Mock()
        )
        result = syncer.sync_workspace(tmp_path)
        assert result.is_failure

    def test_template_render_failure(self, tmp_path: Path) -> None:
        """Test workspace sync with template render failure."""
        workflows_dir = tmp_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        ci = workflows_dir / "ci.yml"
        ci.write_text("name: CI")

        mock_templates = Mock()
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"

        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=Mock(), templates=mock_templates
        )
        # Make the file unreadable after resolution
        # Instead, mock render_template to fail
        syncer.render_template = Mock(return_value=r[str].fail("render error"))
        syncer.resolve_source_workflow = Mock(return_value=r[Path].ok(ci))

        result = syncer.sync_workspace(tmp_path)
        assert result.is_failure

    def test_project_discovery_failure(self, tmp_path: Path) -> None:
        """Test workspace sync with project discovery failure."""
        workflows_dir = tmp_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("name: CI")

        mock_selector = Mock()
        mock_selector.resolve_projects.return_value = r[list].fail("no projects")
        mock_templates = Mock()
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"

        syncer = FlextInfraWorkflowSyncer(
            selector=mock_selector, json_io=Mock(), templates=mock_templates
        )
        result = syncer.sync_workspace(tmp_path)
        assert result.is_failure

    def test_with_report_path(self, tmp_path: Path) -> None:
        """Test workspace sync writes report."""
        mock_selector = Mock()
        mock_json = Mock()
        mock_templates = Mock()
        mock_templates.GENERATED_SHELL_HEADER = "# GENERATED by {source}\n"

        workflows_dir = tmp_path / ".github" / "workflows"
        workflows_dir.mkdir(parents=True)
        (workflows_dir / "ci.yml").write_text("name: CI\n")

        mock_selector.resolve_projects.return_value = r[list].ok([])

        syncer = FlextInfraWorkflowSyncer(
            selector=mock_selector, json_io=mock_json, templates=mock_templates
        )
        report = tmp_path / "report.json"
        result = syncer.sync_workspace(tmp_path, report_path=report)
        assert result.is_success
        mock_json.write.assert_called_once()


class TestWriteReport:
    """Test _write_report method."""

    def test_write_report(self, tmp_path: Path) -> None:
        """Test report writing with operations."""
        mock_json = Mock()
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=mock_json, templates=Mock()
        )
        ops = [
            SyncOperation(project="p1", path="ci.yml", action="create", reason="new"),
            SyncOperation(project="p2", path="ci.yml", action="noop", reason="synced"),
        ]
        report_path = tmp_path / "report.json"
        syncer._write_report(report_path, apply=True, operations=ops)
        mock_json.write.assert_called_once()
        call_args = mock_json.write.call_args
        payload = call_args[0][1]
        assert payload["mode"] == "apply"
        assert payload["summary"]["create"] == 1
        assert payload["summary"]["noop"] == 1

    def test_write_report_dry_run(self, tmp_path: Path) -> None:
        """Test report writing in dry-run mode."""
        mock_json = Mock()
        syncer = FlextInfraWorkflowSyncer(
            selector=Mock(), json_io=mock_json, templates=Mock()
        )
        report_path = tmp_path / "report.json"
        syncer._write_report(report_path, apply=False, operations=[])
        call_args = mock_json.write.call_args
        payload = call_args[0][1]
        assert payload["mode"] == "dry-run"
