from collections.abc import Generator
from pathlib import Path
from unittest.mock import MagicMock

import pytest
from _typeshed import Incomplete

from flext_core import TEntityId as TEntityId
from flext_core.config import FlextSettings

@pytest.fixture
def global_container_reset() -> Generator[None]: ...
@pytest.fixture
def sample_settings() -> FlextSettings: ...
@pytest.fixture
def temp_config_dir(tmp_path: Path) -> Path: ...
@pytest.fixture
def sample_entity_ids() -> list[TEntityId]: ...
@pytest.fixture
def mock_database() -> MagicMock: ...
@pytest.fixture
def mock_logger() -> MagicMock: ...
def entity_id_samples(request: pytest.FixtureRequest) -> TEntityId: ...
def environment_samples(request: pytest.FixtureRequest) -> str: ...
def log_level_samples(request: pytest.FixtureRequest) -> str: ...

class MockService:
    name: Incomplete
    database: Incomplete
    call_count: int
    def __init__(self, name: str, database: object = None) -> None: ...
    def process(self, data: str) -> str: ...

@pytest.fixture
def mock_service_factory() -> object: ...
def reset_singletons(monkeypatch: pytest.MonkeyPatch) -> None: ...
